- server/data/data-library/src/main/java/org/apache/james/domainlist/lib/AbstractDomainList.java
Fixes https://issues.apache.org/jira/browse/JAMES-1815
> Fix JAMES-1815: Copy potentially immutable list to allow modifications

- server/app/pom.xml
[This](https://issues.apache.org/jira/browse/JAMES-2911) is a dependency/packaging issue. Adding an exclusion for the Geronimo javamail implementation to the Spring app's `pom.xml` made it work out-of-the-box again.
Someone more involved in the project might want to re-visit [JAMES-2827 remove geronimo library](https://github.com/apache/james-project/commit/82e2bf9fb7cdee4088aac954a856216c160ea033), since it actually *removes* exclusions in `server/mailet/dkim/pom.xml`, which is how the Geronimo `.jar`s in question came in. Is the activation `.jar` also supposed be excluded? If so, it should probably added to the Spring app's exclusions as well.
That aside, there's quite a few of other Geronimo `.jar`s in the project that end up being packaged in the Spring app - for JTA and JMS, there's …
> JAMES-2911 Unable to send mail from James using an SMTP gateway

- docs/modules/development/pages/logging.adoc
- server/container/core/src/main/java/org/apache/james/server/core/JamesServerResourceLoader.java
- server/container/core/src/main/java/org/apache/james/server/core/configuration/Configuration.java
- server/container/guice/cassandra-guice/src/main/java/org/apache/james/CassandraJamesServerMain.java
- server/container/guice/cassandra-ldap-guice/src/main/java/org/apache/james/CassandraLdapJamesServerMain.java
- server/container/guice/cassandra-rabbitmq-guice/src/main/java/org/apache/james/CassandraRabbitMQJamesServerMain.java
- server/container/guice/cassandra-rabbitmq-ldap-guice/src/main/java/org/apache/james/CassandraRabbitMQLdapJamesServerMain.java
- server/container/guice/configuration/src/main/java/org/apache/james/utils/PropertiesProvider.java
- server/container/guice/guice-common/src/main/java/org/apache/james/JamesServerMain.java
- server/container/guice/jpa-guice/src/main/java/org/apache/james/JPAJamesServerMain.java
- server/container/guice/jpa-smtp-common/src/main/java/org/apache/james/JPAJamesServerMain.java
- server/container/guice/memory-guice/src/main/java/org/apache/james/MemoryJamesServerMain.java
* When loading a configuration file, print it's absolute path.
* Usefull for debugging production miss-configurations
https://issues.apache.org/jira/browse/JAMES-3221
> JAMES-3221 Simple implementation for logging configuration file paths

- server/container/guice/protocols/jmap/src/main/java/org/apache/james/jmap/rfc8621/RFC8621MethodsModule.java
- server/protocols/jmap/src/main/java/org/apache/james/jmap/JMAPRoutesHandler.java
- server/protocols/jmap/src/main/java/org/apache/james/jmap/http/Authenticator.java
This allow third party to reuse the existing Guice modules while adding
their own extra routes and authentication mechanism.
We are writing our first JMAP extensions in a third part project, this work is a prelude to an `extend JMAP` user guide :muscle:  :muscle:
> JAMES-3316 Modularize JMAP routes and authentication mechanism

- backends-common/elasticsearch-v7/src/main/java/org/apache/james/backends/es/v7/ClientProvider.java
- backends-common/elasticsearch-v7/src/main/java/org/apache/james/backends/es/v7/ElasticSearchConfiguration.java
Builders related to ElasticSearchConfiguration are using default access modifier, preventing users from creating their own configuration in their product.
> JAMES-3519: Allow ElasticSearchConfiguration customization

- mailbox/cassandra/pom.xml
- mpt/impl/imap-mailbox/cassandra/pom.xml
- server/data/data-cassandra/pom.xml
- server/protocols/webadmin-integration-test/webadmin-integration-test-common/src/main/java/org/apache/james/webadmin/integration/vault/DeletedMessageVaultIntegrationTest.java
- Fix an unstable test
- Make output of tests more readable by using Await.untilAsserted
- Decrease Cassandra fork count. 4 is maybe too gready...
> JAMES-3255 Try to improve build stability

- server/data/data-jmap/src/main/java/org/apache/james/jmap/api/filtering/FilteringManagement.java
- server/data/data-jmap/src/main/java/org/apache/james/jmap/api/filtering/Version.java
- server/data/data-jmap/src/main/java/org/apache/james/jmap/api/filtering/impl/DefineRulesCommand.java
- server/data/data-jmap/src/main/java/org/apache/james/jmap/api/filtering/impl/DefineRulesCommandHandler.java
- server/data/data-jmap/src/main/java/org/apache/james/jmap/api/filtering/impl/EventSourcingFilteringManagement.java
- server/data/data-jmap/src/main/java/org/apache/james/jmap/api/filtering/impl/FilteringAggregate.java
- server/data/data-jmap/src/test/java/org/apache/james/jmap/api/filtering/FilteringManagementContract.java
- server/data/data-jmap/src/test/java/org/apache/james/jmap/api/filtering/impl/DefineRulesCommandTest.java
- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/methods/SetFilterMethod.java
- server/protocols/jmap-draft/src/test/java/org/apache/james/jmap/mailet/filter/JMAPFilteringExtension.java
- server/protocols/jmap-draft/src/test/java/org/apache/james/jmap/mailet/filter/JMAPFilteringTest.java
As a client I do not want to override over people changes.
If I reset based on an outdated filter version, those changes should be rejected.
> JAMES-3529 Validate version when set Filter

- mpt/impl/imap-mailbox/external-james/src/test/java/org/apache/james/mpt/imapmailbox/external/james/DeploymentValidation.java
Otherwise it get rejected by the server as an unauthenticated
remote third part is claiming a local identity...
> JAMES-2754 Authenticate SMTP transaction in DeploymentValidation

- server/protocols/jmap-rfc-8621/doc/specs/spec/jmap/intro.mdown
- server/protocols/jmap-rfc-8621/doc/specs/spec/mail/intro.mdown
- server/protocols/jmap-rfc-8621/doc/specs/spec/mail/mailbox.mdown
- server/protocols/jmap-rfc-8621/doc/specs/spec/mail/message.mdown
While doing an inventory about the status of the JMAP implementation within the James server, I had the idea to review it in order to reference all JMAP related issues / partial implementation within the JIRA bugtracker. Which pointed out that I forgot many!
Of course, the doc turned out to be slightly outdated, here is my humble attempt to improve that matter of fact.
TODO: the annotated documentation should include links to the JIRA, in where we likely can better describe the issue. Who know, maybe even someone would be inspired and decide to help us fix stuff?
> JAMES-2884 Refresh the annotated JMAP documentation

- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EmailSubmissionSetMethodContract.scala
- server/protocols/jmap-rfc-8621/doc/specs/spec/mail/messagesubmission.mdown
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/EmailSubmissionSet.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailSubmissionSetMethod.scala
Re-reading https://jmap.io/spec-mail.html#emailsubmissionset
```
onSuccessUpdateEmail: Id[PatchObject]|null A map of EmailSubmission id
to an object containing properties to update on the Email object
referenced by the EmailSubmission if the create/update/destroy
succeeds. (For references to EmailSubmissions created in the same
“/set” invocation, this is equivalent to a creation-reference, so the
id will be the creation id prefixed with a #.)
```
We are currently using a message id, not an EmailSubmission id...
CF a bug report opened on the Linagora fork: https://github.com/linagora/james-project/issues/4310
> JAMES-3434 Fix EmailSubmission/set onSuccessUpdateEmail property

- backends-common/cassandra/src/main/java/org/apache/james/backends/cassandra/init/configuration/CassandraConfiguration.java
- backends-common/cassandra/src/main/java/org/apache/james/backends/cassandra/init/configuration/CassandraConsistenciesConfiguration.java
- docs/modules/servers/pages/distributed/configure/cassandra.adoc
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/CassandraMailboxSessionMapperFactory.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/DeleteMessageListener.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMailboxMapper.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMailboxPathV3DAO.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageIdMapper.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageIdToImapUidDAO.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageMapper.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/task/RecomputeMailboxCountersService.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/task/SolveMailboxInconsistenciesService.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/task/SolveMessageInconsistenciesService.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/CassandraMailboxManagerTest.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMailboxMapperGenericTest.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMailboxPathV3DAOTest.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMapperProvider.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageIdMapperRelaxedConsistencyTest.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageIdMapperTest.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageIdToImapUidDAOTest.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageMapperRelaxedConsistencyTest.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageMapperTest.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageMoveTest.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageWithAttachmentMapperTest.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/task/RecomputeMailboxCountersServiceTest.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/task/SolveMessageInconsistenciesServiceTest.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/MessageIdMapperTest.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/MessageMapperTest.java
- src/site/xdoc/server/config-cassandra.xml
```
| mailbox.read.strong.consistency
| Optional. Boolean, defaults to true. Disabling should be considered experimental.
If enabled, regular consistency level is used for read transactions for mailbox. Not doing so might result
in stale reads as the system.paxos table will not be checked for latest updates. Better performance are expected
by turning it off. Note that reads performed as part of write transactions are always performed with a strong
consistency.
| message.read.strong.consistency
| Optional. Boolean, defaults to true. Disabling should be considered experimental.
If enabled, regular consistency level is used for read transactions for message. Not doing so might result
in stale reads as the system.paxos table will not be checked for latest updates. Better performance are …
```
> JAMES-3435 Fine grain LWT configuration for the Cassandra mailbox

- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/http/UploadRoutes.java
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/UploadContract.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/UploadRoutes.scala
One time out of 25 the uploaded content was altered (Different SHA 256 in
the data store). Several Apache CI builds had been failing because of this.
Investigating this, I found that a piped input stream strategy was not
hitting this pitfall (RectorUtils::toInputStream). I thus incriminate
some weird data races on the Reactor side...
However, changing the reactor-netty logic (converting to byta array then to byte buffer again) also solve the test stability (I know! I do not
understand it either).
As the piped inputStream strategy (https://github.com/apache/james-project/pull/370) both mobilises significant resources
and cannot handle exception, then I think the dark magic trick is worth a try.
> JAMES-3432 Upload routes was unstable

- protocols/smtp/src/main/java/org/apache/james/protocols/smtp/core/AbstractSenderAuthIdentifyVerificationRcptHook.java
- server/mailet/integration-testing/src/test/java/org/apache/james/smtp/SmtpIdentityVerificationTest.java
- server/testing/src/main/java/org/apache/james/utils/SMTPMessageSender.java
Before this patch an unchecked error was specified. SMTP error code 430.
```
java.lang.IllegalArgumentException: null
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:127)
at org.apache.james.protocols.smtp.core.AbstractSenderAuthIdentifyVerificationRcptHook.belongsToLocalDomain(AbstractSenderAuthIdentifyVerificationRcptHook.java:89)
at org.apache.james.protocols.smtp.core.AbstractSenderAuthIdentifyVerificationRcptHook.doRcpt(AbstractSenderAuthIdentifyVerificationRcptHook.java:66)
at org.apache.james.smtpserver.SenderAuthIdentifyVerificationRcptHook.doRcpt(SenderAuthIdentifyVerificationRcptHook.java:59)
at org.apache.james.protocols.smtp.hook.RcptHook.doRcpt(RcptHook.java:77)
```
After this patch the sender address is explicitly rejected. Error code 503 & no …
> JAMES-3525 verifyIdentity should not fail on null sender

- server/blob/blob-api/src/main/java/org/apache/james/blob/api/BlobStore.java
- server/blob/blob-cassandra/src/main/java/org/apache/james/blob/cassandra/CassandraBlobStoreDAO.java
- server/blob/blob-storage-strategy/src/main/scala/org/apache/james/server/blob/deduplication/DeDuplicationBlobStore.scala
- server/blob/blob-storage-strategy/src/main/scala/org/apache/james/server/blob/deduplication/PassThroughBlobStore.scala
- server/container/guice/blob/memory/src/main/java/org/apache/james/modules/BlobMemoryModule.java
- server/container/guice/cassandra/src/main/java/org/apache/james/modules/mailbox/CassandraBucketModule.java
This avoids explicit dependencies on bucket strategy in modules which
need a bucket.
> JAME-3314 Extracts name of default BucketName to Blobstore

- backends-common/cassandra/src/test/java/org/apache/james/backends/cassandra/DockerCassandra.java
I find it annoying when reading through tests log to have logs from the
container adding extra empty lines.
this is really just cosmetic but hopefully still interesting enough.
> [Boyscout] trims DockerCassandra container logs

- backends-common/cassandra/src/main/java/org/apache/james/backends/cassandra/init/ClusterFactory.java
- backends-common/cassandra/src/main/java/org/apache/james/backends/cassandra/init/configuration/ClusterConfiguration.java
- backends-common/cassandra/src/test/java/org/apache/james/backends/cassandra/init/configuration/ClusterConfigurationTest.java
- docs/modules/servers/pages/distributed/configure/cassandra.adoc
- src/site/xdoc/server/config-cassandra.xml
This makes sense for Multi-DC Cassandra setups,
especially given the use of LOCAL_QUORUM
consistency level.
> JAMES-3573 Allow specifying DC in Cassandra configuration

- server/blob/blob-s3/pom.xml
- server/container/guice/cassandra-rabbitmq-guice/pom.xml
- server/container/guice/cassandra-rabbitmq-guice/src/main/java/org/apache/james/CassandraRabbitMQJamesServerMain.java
Not required, this brings in the JGroup dependency, vulnerable prior version 4.0.
This is a simple dependency cleanup.
> JAMES-3567 Distributed server should not depend on ActiveMQ

- server/container/core/src/main/java/org/apache/james/server/core/MimeMessageWrapper.java
- server/container/core/src/test/java/org/apache/james/server/core/MimeMessageWrapperTest.java
- Added the edge case tests
- If the header delimiter is missing, then the size would be negative, then the body is as a zero size.
> JAMES-3571 MimeMessageWrapper getSize was incorrect for empty messages

- CHANGELOG.md
- README.adoc
- dockerfiles/run/docker-compose.yml
- server/testing/src/main/java/org/apache/james/util/docker/Images.java
1.25 and before are subject to CVE-2021-28657
CVE-2021-27906 CVE-2021-27807
1.24 is subject to CVE-2020-9489
> [UPGRADE] Adopt Apache Tika 1.26

- README.adoc
Information on the readme file is not fully referenced (`Other Useful commands`), leading to some people lacking that.
> [DOCUMENTATION] Update document - Manage James via the Command Line

- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/change/JmapEventSerializer.scala
- server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/change/StateChangeEventSerializerTest.scala
This enables a rolling upgrade without any backward compatibility considerations to be
performed.
Answers my concerns regarding https://github.com/apache/james-project/pull/391#issuecomment-840252461
> JAMES-3581 Avoid breaking changes upon JMAP event deserialization

- mailbox/store/src/main/java/org/apache/james/mailbox/store/MessageResultImpl.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMailboxManager.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/model/FlagsFactory.java
- server/container/guice/guice-common/src/main/java/org/apache/james/PeriodicalHealthChecksConfiguration.java
- server/data/data-jmap/src/main/java/org/apache/james/jmap/api/model/Preview.java
- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/methods/JmapResponseWriterImpl.java
- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/model/message/view/MessageViewFactory.java
- server/protocols/jmap/src/main/java/org/apache/james/jmap/JMAPServer.java
- server/protocols/jmap/src/main/java/org/apache/james/jmap/VersionParser.java
Here we can see a call to `MessageResultImpl::getMessageId` responsible of `0.78%` of the total allocated memory... Rationals are that and intermediate (uneeded) on the fly messageMetadata is used, which includes an (innefficient) flag copy.
Here is a flame graph capture showing the costs of initializing JMAP routes for each requests.
> [PERFORMANCE] Various small enhancements detected thanks to flame graphs

- metrics/metrics-api/src/main/java/org/apache/james/metrics/api/MetricFactory.java
- metrics/metrics-api/src/main/java/org/apache/james/metrics/api/TimeMetric.java
- metrics/metrics-dropwizard/pom.xml
- metrics/metrics-dropwizard/src/main/java/org/apache/james/metrics/dropwizard/DropWizardMetricFactory.java
- metrics/metrics-dropwizard/src/main/java/org/apache/james/metrics/dropwizard/DropWizardTimeMetric.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/AbstractMailboxProcessor.java
- server/mailet/mailetcontainer-camel/src/main/java/org/apache/james/mailetcontainer/impl/JamesMailSpooler.java
- server/mailet/mailetcontainer-camel/src/main/java/org/apache/james/mailetcontainer/impl/camel/CamelProcessor.java
- server/mailet/mailetcontainer-camel/src/main/java/org/apache/james/mailetcontainer/impl/camel/MatcherSplitter.java
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/remote/delivery/DeliveryRunnable.java
- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/methods/GetFilterMethod.java
- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/methods/GetMailboxesMethod.java
- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/methods/GetMessageListMethod.java
- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/methods/GetMessagesMethod.java
- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/methods/GetVacationResponseMethod.java
- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/methods/SendMDNProcessor.java
- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/methods/SetFilterMethod.java
- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/methods/SetMailboxesMethod.java
- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/methods/SetMessagesDestructionProcessor.java
- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/methods/SetMessagesMethod.java
- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/methods/SetMessagesUpdateProcessor.java
- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/methods/SetVacationResponseMethod.java
- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/http/AuthenticationRoutes.java
- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/http/DefaultMailboxesProvisioner.java
- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/http/UserProvisioner.java
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/http/MailboxesProvisioner.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/http/UserProvisioning.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/Method.scala
Using metrics to capture p99 lead to over-snapshoting, and incurs a 33% throughtput penalty on JMAP draft.
Other SLOW logging implementations do rely on manual time
measurements (eg Datastax Cassandra driver).
As such, due to the low benefits and high costs I propose
to deprecate the logP99 API and migrate away from it.
Tools like Glowroot are able to capture slow traces at a
lighter cost and should rather be used.
I did run 2 benchmarks to evaluate the changes in terms of performance:
- a. Run 1000 users doing a representative JMAP polling request with a pause of 2-4 seconds in between. This represents the regular usage.
-b. Run 2000 users doing a representative JMAP polling request with a pause of 2-4 seconds in between. This adapts to system maximum throughtput (as high latencies would …
> JAMES-3107 Desactivate metrics p99 log

- server/blob/blob-cassandra/src/main/java/org/apache/james/blob/cassandra/CassandraBucketDAO.java
- server/blob/blob-cassandra/src/main/java/org/apache/james/blob/cassandra/CassandraDefaultBucketDAO.java
This makes this more viable in a multi-DC setup
while not affecting the single DC use case.
Cc https://github.com/apache/james-project/pull/436
Sorry for having been slow on the review...
> JAMES-3586 Use LOCAL_ONE for optimistic consistency downgrades

- docs/modules/servers/pages/distributed/configure/blobstore.adoc
- server/blob/blob-s3/src/main/java/org/apache/james/blob/objectstorage/aws/S3BlobStoreConfiguration.java
- server/blob/blob-s3/src/main/java/org/apache/james/blob/objectstorage/aws/S3BlobStoreDAO.java
- server/container/guice/blob/s3/src/main/java/org/apache/james/modules/objectstorage/S3BlobStoreConfigurationReader.java
- server/container/guice/blob/s3/src/main/java/org/apache/james/modules/objectstorage/S3BlobStoreModule.java
- src/site/xdoc/server/config-blobstore.xml
Running above 900 req/s on a 3 James setup I encounter the following
exception:
```
software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Channel was closed before it could be written to.
at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:98)
at software.amazon.awssdk.core.exception.SdkClientException.create(SdkClientException.java:43)
at software.amazon.awssdk.core.internal.http.pipeline.stages.utils.RetryableStageHelper.setLastException(RetryableStageHelper.java:198)
at software.amazon.awssdk.core.internal.http.pipeline.stages.utils.RetryableStageHelper.setLastException(RetryableStageHelper.java:194)
at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybe …
```
> JAMES-3028 S3Client should not be pooled 

- server/container/guice/cassandra-guice/src/main/java/org/apache/james/CassandraJamesServerMain.java
- server/container/guice/cassandra-rabbitmq-guice/src/main/java/org/apache/james/CassandraRabbitMQJamesServerMain.java
- server/container/guice/guice-common/src/main/java/org/apache/james/GuiceJamesServer.java
- server/container/guice/guice-common/src/test/java/org/apache/james/MailsShouldBeWellReceived.java
- server/container/guice/jpa-guice/src/main/java/org/apache/james/JPAJamesServerMain.java
- server/container/guice/jpa-smtp-common/src/main/java/org/apache/james/JPAJamesServerMain.java
- server/container/guice/memory-guice/src/main/java/org/apache/james/MemoryJamesServerMain.java
This enables those who want to adopt alternatives to the existing `CamelMailetContainer`, allowing to bypass existing bugs like `JAMES-3589`.
The issue is that Mailet container is pre-bundled in GuiceJamesServer thus do not allow overrides.
> JAMES-3589 Allow tailor-made servers to customize their mailet container

- server/protocols/jmap-draft-integration-testing/jmap-draft-integration-testing-common/src/test/java/org/apache/james/jmap/draft/methods/integration/SendMDNMethodTest.java
- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/methods/GetMessagesMethod.java
- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/methods/JmapResponse.java
- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/methods/JmapResponseWriterImpl.java
- server/protocols/jmap-draft/src/test/java/org/apache/james/jmap/draft/methods/GetMessagesMethodTest.java
Clients use a close ensemble of properties combination in JMAP responses.
This enable reuse of jackson assemblies and achieve significant speedup
of JMAP responses serialisation.
~20% of James applicative CPU time is spent doing JMAP response serialization. This is because each request needs a dedicated property filter, which is implemented by always initializing a new ObjectMapper, which takes time and is sub-optimal as it is not warm.
Here are the associated gatling run:
By caching common serialization patterns we decreased 6 time CPU utilization for JMAP Draft response serialization.
Here are the associated gatling run:
> [PERFORMANCE] Cache and reuse Object mappers for writing JMAP responses

- dockerfiles/run/spring/destination/conf/mailetcontainer.xml
- docs/modules/servers/pages/distributed/configure/mailetcontainer.adoc
- docs/modules/servers/pages/distributed/configure/smtp.adoc
- server/container/guice/cassandra-guice/sample-configuration/mailetcontainer.xml
- server/container/guice/cassandra-guice/src/test/resources/mailetcontainer.xml
- server/container/guice/cassandra-rabbitmq-guice/sample-configuration/mailetcontainer.xml
- server/container/guice/cassandra-rabbitmq-guice/src/test/resources/mailetcontainer.xml
- server/container/guice/jpa-guice/sample-configuration/mailetcontainer.xml
- server/container/guice/jpa-guice/src/test/resources/mailetcontainer.xml
- server/container/guice/jpa-smtp/sample-configuration/mailetcontainer.xml
- server/container/guice/jpa-smtp/src/test/resources/mailetcontainer.xml
- server/container/guice/memory-guice/sample-configuration/mailetcontainer.xml
- server/container/guice/memory-guice/src/test/java/org/apache/james/ErrorMailet.java
- server/container/guice/memory-guice/src/test/java/org/apache/james/LmtpIntegrationTest.java
- server/container/guice/memory-guice/src/test/resources/lmtpserver.xml
- server/container/guice/memory-guice/src/test/resources/mailetcontainer.xml
- server/mailet/integration-testing/src/test/java/org/apache/james/mailets/MailetErrorsTest.java
- server/mailet/integration-testing/src/test/java/org/apache/james/transport/mailets/OneRuntimeExceptionMailet.java
- server/mailet/integration-testing/src/test/java/org/apache/james/transport/mailets/OneRuntimeExceptionMatcher.java
- server/mailet/mailetcontainer-camel/src/main/java/org/apache/james/mailetcontainer/impl/JamesMailSpooler.java
- server/mailet/mailetcontainer-camel/src/main/java/org/apache/james/mailetcontainer/impl/camel/CamelProcessor.java
- server/mailet/mailetcontainer-camel/src/main/java/org/apache/james/mailetcontainer/impl/camel/MatcherSplitter.java
- server/protocols/protocols-lmtp/src/main/java/org/apache/james/lmtpserver/MailetContainerHandler.java
- server/testing/src/main/java/org/apache/james/utils/SMTPMessageSender.java
- src/site/xdoc/server/config-mailetcontainer.xml
- src/site/xdoc/server/config-smtp-lmtp.xml
Base use case: Executing the mailet container with LMTP I want to escalate some failures to the LMTP client
Nice bonus: It enables better error management eg by propagating exception upon mail processor we can trigger a nack and prevent message loss.
> JAMES-3588 MailetContainer error handling: allow error propagation

- server/container/guice/cassandra/src/main/java/org/apache/james/modules/mailbox/CassandraMailboxModule.java
- server/container/guice/elasticsearch/src/main/java/org/apache/james/modules/mailbox/ElasticSearchMailboxModule.java
- server/container/guice/jpa-guice/src/main/java/org/apache/james/modules/mailbox/LuceneSearchMailboxModule.java
- server/container/guice/protocols/jmap/src/main/java/org/apache/james/jmap/draft/JMAPModule.java
Not doing so prevents to benefit from there reactivity.
Proof:
> [PERFORMANCE] Bond Reactive listeners as Reactive

- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/model/MessageProperties.java
Read a Map instead of iterating values. This is done for each
getMessage requests hence is on the critical path.
With 27 properties to iterate for each 19 properties specified in the gatling tests, at a rate of 425 req/s makes this lookup noticeable...
(Note this pattern is repeated in ~3 places)
> [PERFORMANCE] Fasten MessageProperties lookup

- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageDAOV3.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/FlagsExtractor.java
There computing take up to 1,3% of CPU time, doing reflection
over and over again to build them.
See the following flame graphs:
> [PERFORMANCE] Use static TypeToken for complex CQL types

- mailbox/api/src/main/java/org/apache/james/mailbox/model/MessageResult.java
- mailbox/api/src/main/java/org/apache/james/mailbox/model/ThreadId.java
- mailbox/api/src/test/java/org/apache/james/mailbox/MailboxManagerTest.java
- mailbox/api/src/test/java/org/apache/james/mailbox/model/ThreadIdTest.java
- mailbox/jpa/src/main/java/org/apache/james/mailbox/jpa/mail/model/openjpa/AbstractJPAMailboxMessage.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/MessageResultImpl.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMessageResultIterator.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/model/DelegatingMailboxMessage.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/model/MailboxMessage.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/impl/SimpleMailboxMessageTest.java
We don't have threadId guessing algorithm yet, so now threadId property is naive implemented equals MessageId.
I think I should have put threadId property to some Implemented MailboxMessage constructor/ builder. However I not sure which Message model JMAP is using...
> JAMES-3516 Add threadId property to MessageResult POJO, MailboxMessage POJO

- docs/modules/servers/partials/HasMimeType.adoc
- docs/modules/servers/partials/HasMimeTypeAnySubPart.adoc
- mailet/standard/src/main/java/org/apache/james/transport/matchers/HasMimeType.java
- mailet/standard/src/main/java/org/apache/james/transport/matchers/HasMimeTypeAnySubPart.java
- mailet/standard/src/test/java/org/apache/james/transport/matchers/HasMimeTypeAnySubPartTest.java
- mailet/standard/src/test/java/org/apache/james/transport/matchers/HasMimeTypeTest.java
It do not try to go down the mime tree which makes it impractical for some use cases like `no subpart should have the content type application/zip`.
I understand that some use case do not need to walk down the entire mime tree (eg when categorizing MDN reports only top level content type is enough) however some over generic use cases implies checking the wall mime tree.
Thus I propose to add a `HasMimeTypeAnySubPart` mailet that complement HasMimeType and does just this.
> JAMES-2157 HasMimeType only look at the top level mime type

- docs/antora.yml
Trying to introduce a build for https://github.com/apache/james-site/pull/15 I have the following error:
```
Error: Duplicate nav in 3.6.0@james-project: modules/community/nav.adoc
```
> [DOCUMENTATION] Ship master branch Antora doc as 3.7.0-SNAPSHOT

- server/task/task-memory/src/main/java/org/apache/james/task/MemoryTaskManager.java
```
13:55:34.375 [ERROR] r.c.p.Operators - Operator called default onErrorDropped
java.lang.IllegalStateException: null
at org.apache.james.task.MemoryTaskManager$DetailsUpdater.updated(MemoryTaskManager.java:97)
at org.apache.james.task.SerialTaskManagerWorker.lambda$pollAdditionalInformation$5(SerialTaskManagerWorker.java:105)
at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:385)
at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:118)
at reactor.core.publisher.FluxRepeatPredicate$RepeatPredicateSubscriber.onNext(FluxRepeatPredicate.java:85)
at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1789)
at reactor.core.publisher.MonoDelayElement$DelayElementSubscriber.lambda$onNext$0(MonoDelayElement.java:125)
at …
```
> JAMES-2813 Long tasks on the MemoryTaskManager generates stactraces

- backends-common/cassandra/src/test/java/org/apache/james/backends/cassandra/DockerCassandra.java
- backends-common/elasticsearch-v7/src/test/java/org/apache/james/backends/es/v7/DockerElasticSearch.java
Well as I'm getting tired of having the RAM of my laptop burning to the ground half of the time I run integration tests on James, I decided to take a closer look.
Cassandra by default is deployed with 4Go RAM of heap. ES is deployed with 1Go (well I observed those when running locally)
Now the interesting thing is that some work has been done a while ago to limit the size of Cassandra to 650M for the tests, but the env variable setup was wrong. Thus we were still living with a 4Go memory eater Cassandra. 
I fixed that, and while I was at it, I'm taking a shot at ES too (half, from 1Go to 512M). The rational being, if it passes with Cassandra limited like this, might be as well with ES.
I would like to have a good bunch of CI runs though first to be sure it does not bring instability to …
> Limit the heap size of Cassandra and ES docker containers for tests

- server/container/guice/queue/rabbitmq/src/main/java/org/apache/james/modules/queue/rabbitmq/RabbitMQModule.java
Not doing so results in opening too many connections...
- Two connections were opened for the Health checks
- One connection for ReactorRabbitMQChannelPool
- One connection for ReceiverProvider
With the proposed fix we are down to one.
> JAMES-2683 SimpleConnectionPool should be a guice singleton

- server/mailet/integration-testing/src/test/java/org/apache/james/mailets/flow/AddRecipient.java
- server/mailet/integration-testing/src/test/java/org/apache/james/mailets/flow/ClearRecipientsMailet.java
- server/mailet/integration-testing/src/test/java/org/apache/james/mailets/flow/CollectMailAttributeMailet.java
- server/mailet/integration-testing/src/test/java/org/apache/james/mailets/flow/CollectingExecutionMailet.java
- server/mailet/integration-testing/src/test/java/org/apache/james/mailets/flow/CollectingExecutionMailetBis.java
- server/mailet/integration-testing/src/test/java/org/apache/james/mailets/flow/CountingExecutionMailet.java
- server/mailet/integration-testing/src/test/java/org/apache/james/mailets/flow/CountingExecutionMailetBis.java
- server/mailet/integration-testing/src/test/java/org/apache/james/mailets/flow/CountingExecutionTerminatingMailet.java
- server/mailet/integration-testing/src/test/java/org/apache/james/mailets/flow/EnsureNotDisposed.java
- server/mailet/integration-testing/src/test/java/org/apache/james/mailets/flow/ExecutionFlowTest.java
- server/mailet/integration-testing/src/test/java/org/apache/james/mailets/flow/FirstRecipientCountingExecutions.java
- server/mailet/integration-testing/src/test/java/org/apache/james/mailets/flow/None.java
- server/mailet/integration-testing/src/test/java/org/apache/james/mailets/flow/NoneWithNull.java
We expect:
- A mailet to be executed once for each recipients upon partial match and not several time
- A terminating mailet should not abort processing of previously split mails
- Mail modifications upon partial match should be retained
- After a partial match, downstream recipients should not be executed twice for a given recipient
The tests pass b replacing Camel logic by simple Java code:
```
public class CamelMailetProcessor extends AbstractStateMailetProcessor implements CamelContextAware {
private static final Logger LOGGER = LoggerFactory.getLogger(CamelMailetProcessor.class);
private final MetricFactory metricFactory;
private List<MatcherMailetPair> pairs;
public CamelMailetProcessor(MetricFactory metricFactory) {
this.metricFactory = metricFactory;
}
@override
public void …
```
> JAMES-3589 Reasonable tests regarding mailet container execution

- server/data/data-ldap/src/test/java/org/apache/james/user/ldap/DockerLdapSingleton.java
- server/data/data-ldap/src/test/java/org/apache/james/user/ldap/LdapGenericContainer.java
When I run the test `ReadOnlyUsersLDAPRepositoryTest,` I realized two containers about OpenLDAP had been started. 
One in it is unnecessary.
The reason is `ldapContainer.start()` was called twice. 
The use `static called` make docker container start whenever `DockerLdapSingleton` class be called. (Some of them don't even use it)
**Solution**
Remove the start called in static -> Let start manual.
> JAMES-2597  [FIX]  Remove the invoke LDAP testContainer when unnecessary

- CHANGELOG.md
- dockerfiles/run/docker-compose.yml
- docs/modules/servers/pages/distributed/run-docker.adoc
- docs/modules/servers/pages/distributed/run.adoc
- server/container/guice/cassandra-rabbitmq-guice/README.adoc
- server/testing/src/main/java/org/apache/james/util/docker/Images.java
- src/site/markdown/server/install/guice-cassandra-rabbitmq-s3.md
According to https://www.rabbitmq.com/changelog.html RabbitMQ prior this version is subject to several CVE:
- https://tanzu.vmware.com/security/cve-2020-5419
- https://tanzu.vmware.com/security/cve-2021-22117
- https://tanzu.vmware.com/security/cve-2021-22116
We currently run on `3.8.3`...
> JAMES-3593 Recommend upgrade of RabbitMQ to 3.8.16

- server/data/data-ldap/src/main/java/org/apache/james/user/ldap/ReadOnlyLDAPUser.java
Caught looking at Apache James master build.
Bob supplied a wrong password.
The following stacktrace sounds overkill:
```
09:02:11.041 [ERROR] o.a.j.u.l.ReadOnlyLDAPUser - Unexpected error upon authentication
com.unboundid.ldap.sdk.LDAPBindException: invalid credentials
at com.unboundid.ldap.sdk.LDAPConnection.bind(LDAPConnection.java:2401)
at com.unboundid.ldap.sdk.LDAPConnectionPool.bindAndRevertAuthentication(LDAPConnectionPool.java:1674)
at com.unboundid.ldap.sdk.LDAPConnectionPool.bindAndRevertAuthentication(LDAPConnectionPool.java:1637)
at org.apache.james.user.ldap.ReadOnlyLDAPUser.verifyPassword(ReadOnlyLDAPUser.java:131)
at org.apache.james.user.lib.UsersRepositoryImpl.lambda$test$0(UsersRepositoryImpl.java:128)
at java.base/java.util.Optional.map(Optional.java:265)
at …
```
> JAMES-3594 Decrease verbosity of bad credential auth failures

- mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMessageManager.java
This lead to many calls to FileInputStream::read that
triggers to much blocking calls.
Before:
After:
> [PERFORMANCE] Use buffer output stream upon MessageManager::append

- server/data/data-jmap/src/main/java/org/apache/james/jmap/api/model/Preview.java
Doing so is inefficient as bodies can be very large...
However we should truncate the preview after normalizing
spaces. So we try to estimate (being defensive) the
offset of the preview within the original string, to
only normalize spaces on the portion of the body that
interest us.
On some IMAP benchmarks, this space normalization occupied
2% of the CPU, as much as the mime parsing...
Proof:
> JAMES-2989 Preview should not normalize spaces of the entire body

- server/blob/blob-s3/src/main/java/org/apache/james/blob/objectstorage/aws/S3BlobStoreDAO.java
- server/protocols/webadmin/webadmin-mailbox/src/main/java/org/apache/james/webadmin/service/ExportService.java
```
{
"timestamp":"2021-06-08T08:45:03.535Z",
"level":"INFO",
"thread":"sdk-async-response-0-3",
"logger":"org.apache.james.mailbox.elasticsearch.events.ElasticSearchListeningMessageSearchIndex",
"message":"Indexing mailbox Outbox-CassandraId{id=9a091e40-32cf-11eb-995c-a3ae66e9f96a} of user firstname18.surname18@xxx.integration-open-paas.org on message MessageUid{uid=3397}",
"context":"default"
}
```
After this change set this gets executed on the parallel scheduler.
> JAMES-3028 Do not execute downstream requests on AWS driver pool

- mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/NaiveThreadIdGuessingAlgorithmImpl.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/ThreadIdGuessingAlgorithm.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/model/MimeMessageId.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/model/Subject.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/MimeMessageIdTest.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/SubjectTest.java
Just a few ideas want to show to you, not really some proper code yet.
My idea is enabling setThreadId in MailboxMessage (just like MoqSeq). 
Then in MessageStorer we can use message.setThreadId(with ThreadId from ThreadIdGuessingAlgorithm)
```
MailboxMessage message = messageFactory.createMessage(messageId, mailbox, internalDate, size, bodyStartOctet, content, flags, propertyBuilder, attachments);
threadId = ThreadIdManager.setThreadId(MailboxMessage message,...);
message.setThreadId(threadId);
return Mono.from(messageMapper.addReactive(mailbox, message))
.map(metadata -> Pair.of(metadata, Optional.of(attachments)));
```
> JAMES-3516 Implement naive ThreadIdGuessingAlgorithm

- backends-common/rabbitmq/src/main/java/org/apache/james/backends/rabbitmq/ReactorRabbitMQChannelPool.java
- event-bus/api/src/test/java/org/apache/james/events/GroupContract.java
- event-bus/distributed/src/main/java/org/apache/james/events/GroupRegistration.java
- event-bus/distributed/src/main/java/org/apache/james/events/GroupRegistrationHandler.java
- event-bus/distributed/src/main/java/org/apache/james/events/RabbitMQEventBus.java
- event-bus/distributed/src/test/java/org/apache/james/events/RabbitMQEventBusTest.java
- upgrade-instructions.md
Every groups deserializes the event, which uses CPU and puts pressure on RabbitMQ.
We can likely mutualize group executions to minimize deserialization, acks, and reduce pressure on RabbitMQ.
Note that we should try to preserve per-groups retries.
Single queue with consumer rate equals publish rate
And perf definitl improved!
> JAMES-3599 Group execution: execute listeners together

- server/data/data-jmap/src/main/java/org/apache/james/jmap/api/change/EmailChange.java
- server/data/data-jmap/src/main/java/org/apache/james/jmap/api/change/MailboxAndEmailChange.java
- server/data/data-jmap/src/main/java/org/apache/james/jmap/api/change/MailboxChange.java
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/WebSocketContract.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/change/MailboxChangeListener.scala
- server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/change/MailboxChangeListenerTest.scala
Before we were firing two events on the JMAP event bus:
- One for emails
- One for mailbox
The following work aggregates both into a single notification
and thus reduces of around 30% RabbitMQ publish rate.
> JAMES-3491 Do not send two JMAP events upon new messages

- pom.xml
2 CVEs for versions anterior to 2.0.24 regarding pdfbox dependency have been reported:
- https://nvd.nist.gov/vuln/detail/CVE-2021-31812
- https://nvd.nist.gov/vuln/detail/CVE-2021-31811
This upgrade should solve them.
> Upgrade pdfbox to 2.0.24

- server/container/util/src/main/java/org/apache/james/util/date/ImapDateTimeFormatter.java
0.28% of CPU is spent initializing it...
> [PERFORMANCE] ImapDateTimeFormatter can be static

- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageDAOV3.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageIdDAO.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageIdToImapUidDAO.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/FlagsExtractor.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/table/CassandraMessageIds.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/table/CassandraMessageV3Table.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/table/Flag.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/table/MessageIdToImapUid.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/task/SolveMessageInconsistenciesServiceTest.java
- server/data/data-jmap-cassandra/src/main/java/org/apache/james/jmap/cassandra/projections/CassandraEmailQueryView.java
- server/data/data-jmap-cassandra/src/main/java/org/apache/james/jmap/cassandra/projections/CassandraMessageFastViewProjection.java
- server/data/data-jmap-cassandra/src/main/java/org/apache/james/jmap/cassandra/projections/table/CassandraEmailQueryViewTable.java
- server/data/data-jmap-cassandra/src/main/java/org/apache/james/jmap/cassandra/projections/table/CassandraMessageFastViewProjectionTable.java
> [PERFORMANCE] Pre-convert Cassandra rows to lower case

- server/mailet/remote-delivery-integration-testing/src/test/java/org/apache/james/mailets/RemoteDeliveryForwardIntegrationTest.java
@tlle14 reported issues (https://github.com/linagora/james-project/issues/4338)  regarding forwards when forwarding to remote recipients with a local copy.
The following test proves James code works and we could review settings of the involved platform.
Cc @Arsnael
> JAMES-2366 Add missing tests for forwards to remote recipients

- mailbox/backup/src/test/java/org/apache/james/mailbox/backup/MailboxMessageFixture.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageMetadata.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/MessageRepresentation.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageDAOTest.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageDAOV3Test.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/migration/MessageV3MigrationTest.java
- mailbox/elasticsearch-v7/src/test/java/org/apache/james/mailbox/elasticsearch/v7/events/ElasticSearchListeningMessageSearchIndexTest.java
- mailbox/elasticsearch-v7/src/test/java/org/apache/james/mailbox/elasticsearch/v7/json/MessageToElasticSearchJsonTest.java
- mailbox/jpa/src/main/java/org/apache/james/mailbox/jpa/openjpa/OpenJPAMessageFactory.java
- mailbox/jpa/src/test/java/org/apache/james/mailbox/jpa/mail/MessageUtilsTest.java
- mailbox/plugin/spamassassin/src/test/java/org/apache/james/mailbox/spamassassin/SpamAssassinListenerTest.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/MessageFactory.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/MessageStorer.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/model/impl/SimpleMailboxMessage.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/MessageBuilder.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/MessageIdManagerTestSystem.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/StoreMailboxMessageResultIteratorTest.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/ListMessageAssertTest.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/MailboxMessageAssertTest.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/MessageIdMapperTest.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/MessageMapperTest.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/MessageMoveTest.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/MessageWithAttachmentMapperTest.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/MetadataMapAssertTest.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/impl/SimpleMailboxMessageTest.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/utils/ApplicableFlagCalculatorTest.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/search/ListeningMessageSearchIndexContract.java
- server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/routes/MailboxesRoutesTest.java
- server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/routes/UserMailboxesRoutesTest.java
After adding threadId property to SimpleMailboxMessage, we can enable setting threadId through MessageFactory::createMessage params
> JAMES-3516 Allow setting threadId through MessageFactory::createMessage params

- backends-common/rabbitmq/src/main/java/org/apache/james/backends/rabbitmq/ReactorRabbitMQChannelPool.java
- event-bus/distributed/src/main/java/org/apache/james/events/EventDispatcher.java
- server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/Enqueuer.java
- server/queue/queue-rabbitmq/src/test/java/org/apache/james/queue/rabbitmq/RabbitMQMailQueueTest.java
CPU utilisation related to RabbitMQ as expected increased (1.30 % -> 2.6%) however latencies went from 67ms to 90+ ms at ~800 req/s.
RPC related to `Channel::confirmSelect` done repeatedly are rather expensive, and I notice some active creation of channels.
As such, I feel unconfident with the publish / confirm part of the work and would split it to another pull request...
https://www.rabbitmq.com/tutorials/tutorial-seven-java.html
```
Confirms should be enabled just once, not for every message published.
```
Not the case given my implementation.
For now I see several solutions:
- rely on a sink to pass all messages as part of a single Flux. Thus init is done once. The done side is that the result is asynchronous to the caller (error handling would not be propagated)
- enable publish …
> JAMES-3604 Use publish confirm

- docs/modules/servers/pages/distributed/configure/healthcheck.adoc
- docs/modules/servers/pages/distributed/operate/webadmin.adoc
- pom.xml
- server/container/feature-checks/pom.xml
- server/container/feature-checks/src/main/java/org/apache/james/healthcheck/MailReceptionCheck.java
- server/container/guice/mailbox/pom.xml
- server/container/guice/mailbox/src/main/java/org/apache/james/modules/MailboxModule.java
- server/container/guice/mailbox/src/main/java/org/apache/james/modules/mailbox/MailReceptionHealthCheckModule.java
- server/pom.xml
- server/protocols/webadmin-integration-test/distributed-webadmin-integration-test/src/test/java/org/apache/james/webadmin/integration/rabbitmq/MailReceptionCheckIntegrationTest.java
- src/site/markdown/server/manage-webadmin.md
- src/site/xdoc/server/config-healthcheck.xml
As described in JAMES-3605, RabbitMQ consumers can end up being stuck.
In such a scenario we are not able to detect the failure and end up relying on cunsumer reports to restart James.
We would like to have a health-check, allowing automatic testing about mail reception. (Both periodical logs and also a HTTP endpoint for integration with a monitoring system)...
So a healthcheck no longer for a technical component but for a feature.
In `healthcheck.properties` on could configure a user to run reception checks:
```
reception.checks.user=test@domain.tld
```
If configured, the healthcheck would then send a mail to the user, await the email via the eventbus, then retrieve its content.
To be placed in a new `server/container/feature-checks` maven project.
- Given a paused RabbitMQ the check …
> JAMES-3607 Functional healthcheck exercising mail reception

- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/CassandraMailboxManager.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/CassandraMessageManager.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/CassandraMailboxManagerProvider.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/CassandraTestSystemFixture.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMailboxManagerAttachmentTest.java
- mailbox/jpa/src/main/java/org/apache/james/mailbox/jpa/openjpa/OpenJPAMailboxManager.java
- mailbox/jpa/src/main/java/org/apache/james/mailbox/jpa/openjpa/OpenJPAMessageManager.java
- mailbox/jpa/src/main/resources/META-INF/spring/mailbox-jpa.xml
- mailbox/jpa/src/test/java/org/apache/james/mailbox/jpa/JpaMailboxManagerProvider.java
- mailbox/maildir/src/main/resources/META-INF/spring/mailbox-maildir.xml
- mailbox/maildir/src/test/java/org/apache/james/mailbox/maildir/MaildirMailboxManagerProvider.java
- mailbox/memory/src/main/java/org/apache/james/mailbox/inmemory/InMemoryMailboxManager.java
- mailbox/memory/src/main/java/org/apache/james/mailbox/inmemory/InMemoryMessageManager.java
- mailbox/memory/src/main/resources/META-INF/spring/mailbox-memory.xml
- mailbox/memory/src/test/java/org/apache/james/mailbox/inmemory/manager/InMemoryIntegrationResources.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/MessageStorer.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMailboxManager.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMessageManager.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/NaiveThreadIdGuessingAlgorithmImpl.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/ThreadIdGuessingAlgorithm.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/utils/MimeMessageHeadersUtil.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/StoreMailboxManagerTest.java
- mpt/impl/imap-mailbox/cassandra/src/test/java/org/apache/james/mpt/imapmailbox/cassandra/host/CassandraHostSystem.java
- mpt/impl/imap-mailbox/jpa/src/test/java/org/apache/james/mpt/imapmailbox/jpa/host/JPAHostSystem.java
- mpt/impl/imap-mailbox/maildir/src/test/java/org/apache/james/mpt/imapmailbox/maildir/host/MaildirHostSystem.java
- server/container/guice/cassandra/src/main/java/org/apache/james/modules/mailbox/CassandraMailboxModule.java
- server/container/guice/mailbox-jpa/src/main/java/org/apache/james/modules/mailbox/JPAMailboxModule.java
- server/container/guice/memory/src/main/java/org/apache/james/modules/mailbox/MemoryMailboxModule.java
I have some questions:
- Am I supporting threadId for other protocols beside JMAP also? I am interacting with how James store threadId generally.
- Should we have CassandraThreadIdGuessingAlgorithm and InMemoryThreadIdGuessingAlgorithm... separately in the future?
> JAMES-3516 Plug threadIdGuessingAlgorithm to MessageManager

- backends-common/rabbitmq/src/main/java/org/apache/james/backends/rabbitmq/SimpleConnectionPool.java
- backends-common/rabbitmq/src/test/java/org/apache/james/backends/rabbitmq/RabbitMQExtension.java
- event-bus/distributed/src/main/java/org/apache/james/events/EventBusReconnectionHandler.java
- event-bus/distributed/src/main/java/org/apache/james/events/GroupRegistration.java
- event-bus/distributed/src/main/java/org/apache/james/events/GroupRegistrationHandler.java
- event-bus/distributed/src/main/java/org/apache/james/events/KeyRegistrationHandler.java
- event-bus/distributed/src/main/java/org/apache/james/events/RabbitMQEventBus.java
- mailet/amqp/src/main/java/org/apache/james/transport/mailets/AmqpForwardAttribute.java
- mpt/impl/imap-mailbox/rabbitmq/src/test/java/org/apache/james/mpt/imapmailbox/rabbitmq/host/RabbitMQEventBusHostSystem.java
- server/container/guice/distributed/src/main/java/org/apache/james/modules/event/JMAPEventBusModule.java
- server/container/guice/distributed/src/main/java/org/apache/james/modules/event/RabbitMQEventBusModule.java
- server/container/guice/queue/rabbitmq/pom.xml
- server/container/guice/queue/rabbitmq/src/main/java/org/apache/james/modules/queue/rabbitmq/RabbitMQModule.java
- server/container/guice/queue/rabbitmq/src/main/java/org/apache/james/modules/queue/rabbitmq/SpoolerReconnectionHandler.java
- server/mailet/mailetcontainer-impl/src/main/java/org/apache/james/mailetcontainer/impl/JamesMailSpooler.java
- server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/Dequeuer.java
- server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/RabbitMQMailQueue.java
- server/task/task-distributed/src/main/java/org/apache/james/task/eventsourcing/distributed/RabbitMQTerminationSubscriber.java
- server/task/task-distributed/src/main/java/org/apache/james/task/eventsourcing/distributed/RabbitMQWorkQueue.java
- server/task/task-distributed/src/main/java/org/apache/james/task/eventsourcing/distributed/RabbitMQWorkQueueReconnectionHandler.java
- server/task/task-distributed/src/main/java/org/apache/james/task/eventsourcing/distributed/TerminationReconnectionHandler.java
- server/task/task-memory/src/main/java/org/apache/james/task/WorkQueue.java
- server/task/task-memory/src/main/scala/org/apache/james/task/eventsourcing/EventSourcingTaskManager.scala
After upgrading RabbitMQ to 3.8.17 we noticed that, once in a while, messages were not consumed anymore. The consumers alocated to it died and were not replaced.
This results in emails / updates being delayed.
For any reason (GC, network failure) some timeout was exceeded and the connection deemed unusable.
Upon connection replacement, no attempt is made to resume the consumer.
Restart James.
We expect James, upon connection replacement, to happily restart its consumers.
Reconnection handler should also resume consummers.
> JAMES-3605 RabbitMQ reconnection handlers should restart consummers

- core/src/main/java/org/apache/james/core/Username.java
- core/src/test/java/org/apache/james/core/UsernameTest.java
- mailbox/elasticsearch-v7/src/main/java/org/apache/james/mailbox/elasticsearch/v7/json/MimePartParser.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/MimeDescriptorImpl.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMessageManager.java
- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/methods/MIMEMessageConverter.java
- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/methods/SetMessagesUpdateProcessor.java
- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/model/CreationMessage.java
- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/model/SetMessagesRequest.java
- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/send/PostDequeueDecorator.java
```
================================================================================
---- Global Information --------------------------------------------------------
> request count                                      29532 (OK=29532  KO=0     )
> min response time                                      6 (OK=6      KO=-     )
> max response time                                   5137 (OK=5137   KO=-     )
> mean response time                                   344 (OK=344    KO=-     )
> std deviation                                        325 (OK=325    KO=-     )
> response time 50th percentile                        241 (OK=241    KO=-     )
> response time 75th percentile                        370 (OK=370    KO=-     )
> response time 95th percentile                        848 (OK=848 …
```
> Various small performance enhancements when sending messages via JMAP

- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/CassandraMailboxManagerProvider.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/CassandraTestSystemFixture.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMailboxManagerAttachmentTest.java
- mailbox/jpa/src/main/resources/META-INF/spring/mailbox-jpa.xml
- mailbox/jpa/src/test/java/org/apache/james/mailbox/jpa/JpaMailboxManagerProvider.java
- mailbox/maildir/src/main/resources/META-INF/spring/mailbox-maildir.xml
- mailbox/maildir/src/test/java/org/apache/james/mailbox/maildir/MaildirMailboxManagerProvider.java
- mailbox/memory/src/main/resources/META-INF/spring/mailbox-memory.xml
- mailbox/memory/src/test/java/org/apache/james/mailbox/inmemory/manager/InMemoryIntegrationResources.java
- mailbox/scanning-search/src/test/java/org/apache/james/mailbox/store/search/SearchThreadIdGuessingAlgorithmTest.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/MessageStorer.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/NaiveThreadIdGuessingAlgorithm.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/SearchThreadIdGuessingAlgorithm.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/ThreadIdGuessingAlgorithm.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/ThreadIdGuessingAlgorithmContract.java
- mpt/impl/imap-mailbox/cassandra/src/test/java/org/apache/james/mpt/imapmailbox/cassandra/host/CassandraHostSystem.java
- mpt/impl/imap-mailbox/jpa/src/test/java/org/apache/james/mpt/imapmailbox/jpa/host/JPAHostSystem.java
- mpt/impl/imap-mailbox/maildir/src/test/java/org/apache/james/mpt/imapmailbox/maildir/host/MaildirHostSystem.java
- server/container/guice/cassandra/src/main/java/org/apache/james/modules/mailbox/CassandraMailboxModule.java
- server/container/guice/mailbox-jpa/src/main/java/org/apache/james/modules/mailbox/JPAMailboxModule.java
- server/container/guice/memory/src/main/java/org/apache/james/modules/mailbox/MemoryMailboxModule.java
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EmailImportContract.scala
Purpose: Experiment guessing threadId by doing search. Good to experiment but bad for production.
I changed a piece of code in buildSearchQuery. We did compare one to one corresponding field. We should compare many fields.
```
An identical message id [@!RFC5322] appears in both messages in any of the Message-Id, In-Reply-To, and References header fields.
```
> JAMES-3516 Implement SearchThreadIdGuessingAlgorithm

- metrics/metrics-dropwizard/src/main/java/org/apache/james/metrics/dropwizard/DropWizardMetricFactory.java
- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/methods/SendMDNProcessor.java
- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/methods/SetMessagesCreationProcessor.java
- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/methods/SetMessagesDestructionProcessor.java
- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/methods/SetMessagesMethod.java
A good part of applicative CPU is used calling cancels on fluxes to get back a mono.
Zoom:
Here is the associated gatling result:
Most of the cancels are gone (remains the ones of the authentication strategy)
Which translates with better gating perfs (~10% mean time and ~7% p99 decrease, ~0.5% throughput increase)
> [PERFORMANCE] DropWizardMetricFactory: optimize wrapping monos 

- src/site/xdoc/download.xml
I received the following notice:
```
Sorry, but the announce cannot be accepted.
There are some some errors on the download page.
Sources for releases must be downloaded from the ASF mirror system.
The links for the mailet 3.6.0 sources currently point to the Maven repo.
They must use the mirror system via closer.lua and the associated sigs and
hashes must be served from downloads.apache.org/james...
Please fix the download page, check, and submit a fresh announce.
Thanks!
Sebb
```
> Do not host download artifacts on maven central

- docs/modules/community/pages/release.adoc
- src/site/xdoc/download.xml
Some ASF bot complains about it: The links for the hupa artifacts are missing the /hupa/ subdirectory segment.
```
It looks like it needs extra registry with INFRA, which is likely not something
that would happen given the soon to come retirement of Apache HUPA.
```
Despite the files being on https://archive.apache.org/dist/james/hupa/0.0.2/
they are not exported through the Apache mirrors.
CF https://www.apache.org/dyn/closer.lua/james/0.0.2/hupa-parent-0.0.2-source-release.zip
```
The requested file or directory is not on the mirrors.
The object is in not in our archive https://archive.apache.org/dist/
```
> [RELEASE] Drop HUPA section from download page

- .scalafix.conf
- event-sourcing/event-sourcing-core/pom.xml
- event-sourcing/event-sourcing-pojo/pom.xml
- mailbox/event/json/pom.xml
- mdn/pom.xml
- pom.xml
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/pom.xml
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EmailChangesMethodContract.scala
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EmailGetMethodContract.scala
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EmailImportContract.scala
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EmailQueryMethodContract.scala
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EmailSetMethodContract.scala
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/MailboxChangesMethodContract.scala
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/MailboxQueryMethodContract.scala
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/MailboxSetMethodContract.scala
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/WebSocketContract.scala
- server/protocols/jmap-rfc-8621/pom.xml
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/http/UserProvisioning.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/json/EmailGetSerializer.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/json/EmailQuerySerializer.scala
In order to checkstyle for scala. Ref: https://github.com/linagora/james-project/issues/4348
- Tool: Scalafix (https://scalacenter.github.io/scalafix/)
- Maven plugin: scalafix-maven-plugin (https://github.com/evis/scalafix-maven-plugin)
**How to run:**
```bash
mvn -pl event-sourcing/event-sourcing-core,event-sourcing/event-sourcing-pojo,server/protocols/jmap-rfc-8621,server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common,mailbox/event/json,mdn clean compile test-compile scalafix:scalafix -Dscalafix.mode=AUTO_SUPPRESS_LINTER_ERRORS
```
Read more `scalafix.mode`: https://www.javadoc.io/doc/ch.epfl.scala/scalafix-interfaces/0.9.5/scalafix/interfaces/ScalafixMainMode.html
**Scope** 
The modules have scala code
```
- event-sourcing/event-sourcing-core,
- …
```
> [SCALA_CHECKSTYLE] Setup scalafix & Implement some rules

- server/data/data-cassandra/src/test/java/org/apache/james/user/cassandra/CassandraUsersRepositoryTest.java
- server/data/data-jpa/src/test/java/org/apache/james/user/jpa/JpaUsersRepositoryTest.java
- server/data/data-ldap/src/test/java/org/apache/james/user/ldap/ReadOnlyUsersLDAPRepositoryTest.java
- server/data/data-library/src/main/java/org/apache/james/user/lib/UsersRepositoryImpl.java
- server/data/data-library/src/test/java/org/apache/james/user/lib/UsersRepositoryContract.java
- server/data/data-memory/src/test/java/org/apache/james/user/memory/MemoryUsersRepositoryTest.java
The testee of UserRepositoryContract is UserRepositoryImpl. It is not flexible for reuse. 
Should we have separated the test case between UserRepository and UserRepositoryImpl
> [REFACTORING] UsersRepositoryContract

- src/site/markdown/server/manage-webadmin.md
- OLD: https://james.apache.org/server/manage-webadmin.html#Administrating_messages  (not jump to the target line)
- NEW: https://james.apache.org/server/manage-webadmin.html#Administrating_Messages  (working)
> JAMES-2993 WebAdmin markdown - Fix href Administrating messages

- server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/view/cassandra/CassandraMailQueueBrowser.java
This can cause issues for large bucket counts.
> JAMES-3601 Stop browsing buckets concurrently

- server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/view/cassandra/CassandraMailQueueBrowser.java
- server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/view/cassandra/CassandraMailQueueMailDelete.java
- server/queue/queue-rabbitmq/src/test/java/org/apache/james/queue/rabbitmq/view/cassandra/CassandraMailQueueViewTestFactory.java
A common mis-configuration of the Distributed mailqueue is to attempt to
update the browse start too often, which results in attempts to update the
browse start while we are already in the last slice.
Repeatedly trying to needlessly update the browse start can seriously undermine
application performance as browsing the mail queue is no cheap task.
Hopefully prior to attempt to update the browse start, we can ensure the browse start is not the current slice.
Thus mis-configurations are mitigated and will not result in hammering browse start update of the current slice
(mis-configuration however can result in suboptimal concurrently triggered browse start updates when switching
slices, operators should still ensure their "updateBrowseStartPace" are adequate, but failures to do so becomes …
> JAMES-3601 Do not update browse start when not needed

- server/blob/blob-api/src/main/java/org/apache/james/blob/api/HashBlobId.java
- server/blob/blob-api/src/test/java/org/apache/james/blob/api/DeduplicationBlobStoreContract.java
- server/blob/blob-api/src/test/java/org/apache/james/blob/api/HashBlobIdTest.java
SHA-256 generates 32 bytes long hash.
HEX encodes 1 byte with two characters so leads to 64 long
char strings.
Base64 have an overhead of 133% so leads to use 44
characters.
This simple change have the potential to significantly
decrease Cassandra storage space: each message storing 4
blobIds minimum (messageV3 header and body, header in
imapuidtable and messageidtable, not counting attachments)
thus we save 80 bytes per message pre-compression.
Note that deduplication is affected by this fix: similar
content before / after this fix will be affected different
blobIds so will be stored twice.
> JAMES-2287 Encode BlobId with base64

- mailbox/api/src/main/java/org/apache/james/mailbox/model/UpdatedFlags.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraApplicableFlagDAO.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageDAOV3.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageIdDAO.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageIdMapper.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageIdToImapUidDAO.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageMapper.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/task/SolveMessageInconsistenciesService.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageIdDAOTest.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageIdMapperTest.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageIdToImapUidDAOTest.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageMapperTest.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/base/SelectedMailboxImpl.java
- server/protocols/webadmin-integration-test/distributed-webadmin-integration-test/src/test/java/org/apache/james/webadmin/integration/rabbitmq/ConsistencyTasksIntegrationTest.java
- server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/view/cassandra/CassandraMailQueueViewModule.java
- upgrade-instructions.md
Taken from https://docs.datastax.com/en/landing_page/doc/landing_page/dataModel.html#dataModel__checkTableStructure
This includes:
- Avoid usage of non frozen collections if possible (and easily doable)
- Avoid insertion of tombstone when working with non frozen collections
- Preparing statements for Applicable flags thanks to refined Cassandra collection knowledge.
> JAMES-3626 Enforce more Cassandra schema best practices

- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/modules/CassandraQuotaModule.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/quota/CassandraGlobalMaxQuotaDao.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/quota/CassandraPerUserMaxQuotaManager.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/table/CassandraGlobalMaxQuota.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/quota/CassandraPerUserMaxQuotaManagerTest.java
- upgrade-instructions.md
This avoids reading the quota limits twice, for instance when receiving emails...
> JAMES-3630  Group quota limit reads

- server/protocols/webadmin/webadmin-mailbox/src/main/java/org/apache/james/webadmin/service/ClearMailboxContentTask.java
- server/protocols/webadmin/webadmin-mailbox/src/main/java/org/apache/james/webadmin/service/UserMailboxesService.java
- Avoid costly operation at pipeline evaluation,
integrate their reactive version to the reactive
pipeline.
- Remove no longer needed exceptions in method
signature
- Drop no longer needed logger
> JAMES-3621 Fix clear mailbox content reactive handling

- protocols/netty/src/main/java/org/apache/james/protocols/netty/BasicChannelUpstreamHandler.java
This stacktrace is especially annoying when behind a load balancer
doing port checks: connecting and disconnecting straight away, then the
banner can not be sent to the client.
These checks were encountered with for instance F5 Big Ip load
balancers.
> JAMES-2625 Remove stacktrace upon ClosedChannelException

- server/blob/blob-storage-strategy/pom.xml
- server/blob/blob-storage-strategy/src/main/java/org/apache/james/server/blob/deduplication/GenerationAwareBlobId.java
- server/blob/blob-storage-strategy/src/test/java/org/apache/james/server/blob/deduplication/GenerationAwareBlobIdTest.java
- `Generation` allows to avoid concurrency issues as GC won't be run on the active generation (the two lat one to allow a safe clock skew)
- `family` allows reconfiguration of the generation
Time is used to avoid synchronisation accross nodes.
> JAMES-3150 Implement a GenerationAwareBlobId

- mailbox/store/src/main/java/org/apache/james/mailbox/store/search/SearchUtil.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/search/SearchUtilTest.java
```
import java.util.Base64;
import org.apache.james.mailbox.store.search.SearchUtil;
import com.code_intelligence.jazzer.api.FuzzedDataProvider;
public class Fuzzed {
public static void fuzzerTestOneInput(FuzzedDataProvider fuzzedDataProvider) {
final byte[] bytes = fuzzedDataProvider.consumeString(128).getBytes();
final String b64 = new String(Base64.getEncoder().encode(bytes));
try {
SearchUtil.getBaseSubject(new String(bytes));
} catch (Exception e) {
throw new RuntimeException(b64, e);
}
}
}
```
Cc @quantranhong1999
> JAMES-3611 Use fuzzing to strengthen SearchUtil::getBaseSubject

- pom.xml
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-37714
jsoup is a Java library for working with HTML. Those using jsoup versions
prior to 1.14.2 to parse untrusted HTML or XML may be vulnerable to DOS
attacks. If the parser is run on user supplied input, an attacker may supply
content that causes the parser to get stuck (loop indefinitely until
cancelled), to complete more slowly than usual, or to throw an unexpected
exception. This effect may support a denial of service attack. The issue is
patched in version 1.14.2. There are a few available workarounds. Users may
rate limit input parsing, limit the size of inputs based on system resources,
and/or implement thread watchdogs to cap and timeout parse runtimes.
> [UPGRADE] JSOUP 1.14.1 -> 1.14.2 to address CVE-2021-37714

- protocols/imap/pom.xml
- protocols/imap/src/main/java/org/apache/james/imap/processor/AbstractMailboxProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/AbstractSelectionProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/fetch/FetchProcessor.java
- protocols/imap/src/test/java/org/apache/james/imap/processor/SelectProcessorTest.java
```
GIVEN Samsung Email mobile application
AND connected to an IMAP account located on an IMAP James server
AND load you emails (swap down if needed)
WHEN Refresh your emails (swap down a second time)
THEN the email account is rendered empty, only emails received since are displayed
```
Another refresh restores the original email list....
The second refresh uses QRESYNC SELECT command with the last known modification sequence modifier.
Thus James needs to compute the vanished responses (messages deletes since the last known modseq).
As James do not store expunges, we should interate the supplied range and identify the missing items, for which we will send vanished responses.
But James specifically filters out old messages from the liveness search, which results in all messages prior to …
> JAMES-3642 Fix Buggy behavior with Android Email mobile application

- server/container/core/src/main/java/org/apache/james/server/core/filesystem/FileSystemImpl.java
- server/container/core/src/main/java/org/apache/james/server/core/filesystem/ResourceFactory.java
- server/container/filesystem-api/src/main/java/org/apache/james/filesystem/api/FileSystem.java
- server/container/spring/src/main/java/org/apache/james/container/spring/context/JamesServerApplicationContext.java
- server/container/spring/src/main/java/org/apache/james/container/spring/context/web/JamesServerWebApplicationContext.java
- server/container/spring/src/main/java/org/apache/james/container/spring/filesystem/FileSystemImpl.java
- server/container/spring/src/main/java/org/apache/james/container/spring/filesystem/ResourceLoaderFileSystem.java
- server/container/spring/src/main/java/org/apache/james/container/spring/resource/DefaultJamesResourceLoader.java
- server/container/spring/src/main/java/org/apache/james/container/spring/resource/JamesResourceLoader.java
- server/data/data-file/src/test/java/org/apache/james/mailrepository/FileMailRepositoryTest.java
- server/data/data-library/src/main/java/org/apache/james/repository/file/AbstractFileRepository.java
An attacker could use webAdmin REST API to create folders in arbitrary
locations if it is not the case.
> JAMES-3646 FileMailRepository shoud reject URL outside of James root

- server/apps/cassandra-app/pom.xml
- server/apps/distributed-app/pom.xml
- server/apps/jpa-app/pom.xml
- server/apps/jpa-smtp-app/pom.xml
- server/apps/memory-app/pom.xml
DEPRECATION NOTICE of adoptopenjdk:
This image is officially deprecated in favor of the eclipse-temurin image,
and will receive no further updates after 2021-08-01 (Aug 01, 2021). Please
adjust your usage accordingly.
https://hub.docker.com/_/adoptopenjdk?tab=tags&page=1&ordering=last_updated&name=11
> JAMES-3647 Adopt eclipse-temurin:11-jre-focal docker image

- docs/modules/servers/partials/RemoteDelivery.adoc
- server/dns-service/dnsservice-library/src/main/java/org/apache/james/dnsservice/library/MXHostAddressIterator.java
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/RemoteDelivery.java
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/remote/delivery/MailDelivrerToHost.java
> JAMES-3645 Allow RemoteDelivery to use SMTPS and fallback to SMTP

- mailet/standard/src/main/java/org/apache/james/transport/mailets/PropagateError.java
- mailet/standard/src/test/java/org/apache/james/transport/mailets/PropagateErrorTest.java
Can be configured in the mailet container error processor to propagate errors to the calling context. Usefull for instance for error management with LMTP
EG:
```
<processor state="error" enableJmx="true">
<mailet match="All" class="MetricsMailet">
<metricName>mailetContainerErrors</metricName>
</mailet>
<mailet match="All" class="Bounce">
<onMailetException>ignore</onMailetException>
</mailet>
<mailet match="All" class="PropagateError">
<onMailetException>propagate</onMailetException>
</mailet>
</processor>
```
> JAMES-3588 Mailet to propagate encoutered error

- server/blob/blob-s3/pom.xml
Fixes:
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-37136 (DoS)
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-37137 (DoS)
> Upgrade S3 client and Netty

- server/protocols/protocols-smtp/src/main/java/org/apache/james/smtpserver/DataLineJamesMessageHookHandler.java
Before we pay the cost of building MDC for each line of the message, which is useless upon copying the content (won't log in the enclosing context).
Significant performance gains can be achieved by only wrapping the final operation in the MDC:
Run locally, to generate the load:
`time smtp-source -A -C100 -r 1 -l 500000 -m 5000 -s 20 -d -c -f any@other.com -M other.com -t bob@localhost localhost:25`
Which sends 5000 emails of 500KB each...
Before it takes 2 min 30, and the SMTP receival goes at the same speed than the dequeuing
After, it takes 1min40, ~1min to enqueue and 40 more seconds so complete the dequeue...
> JAMES-3196 Avoid MDC costs when not needed

- server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/SwitchableLineBasedFrameDecoder.java
- server/protocols/protocols-imap4/src/test/java/org/apache/james/imapserver/netty/IMAPServerTest.java
Thanks https://github.com/jtconsol for the report.
If data remains in the cumulation buffer after say a APPEND, we flush it, as it avoids
APPEND to wait indefinitly for data. However this did let the cumulation buffer in a
non usable state causing following commands to fail.
We should this set the cumulation buffer to null to no longer use it (and allocate a new one)
in order to prevent failures in follow up message processing.
> JAMES-1436 SwitchableLineBasedFrameDecoder: clean up cumulation buffer

- server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/SwitchableLineBasedFrameDecoder.java
- server/protocols/protocols-imap4/src/test/java/org/apache/james/imapserver/netty/IMAPServerTest.java
Thanks https://github.com/jtconsol for the report.
If data remains in the cumulation buffer after say a APPEND, we flush it, as it avoids
APPEND to wait indefinitly for data. However this did let the cumulation buffer in a
non usable state causing following commands to fail.
We should this set the cumulation buffer to null to no longer use it (and allocate a new one)
in order to prevent failures in follow up message processing.
> JAMES-1436 SwitchableLineBasedFrameDecoder: clean up cumulation buffer [BACKPORT]

- mailbox/plugin/quota-mailing/src/main/java/org/apache/james/mailbox/quota/mailing/subscribers/QuotaThresholdNotice.java
- mailbox/plugin/quota-mailing/src/test/java/org/apache/james/mailbox/quota/mailing/subscribers/QuotaThresholdNoticeTest.java
```
java.lang.IllegalStateException: null
at java.base/java.util.Optional.orElseThrow(Optional.java:408)
at org.apache.james.core.quota.QuotaSizeLimit.asLong(QuotaSizeLimit.java:52)
at org.apache.james.mailbox.quota.mailing.subscribers.QuotaThresholdNotice.computeScopes(QuotaThresholdNotice.java:202)
at org.apache.james.mailbox.quota.mailing.subscribers.QuotaThresholdNotice.renderTemplate(QuotaThresholdNotice.java:169)
at org.apache.james.mailbox.quota.mailing.subscribers.QuotaThresholdNotice.generateSubject(QuotaThresholdNotice.java:146)
at org.apache.james.mailbox.quota.mailing.subscribers.QuotaThresholdNotice.generateMimeMessage(QuotaThresholdNotice.java:140)
at org.apache.james.mailbox.quota.mailing.subscribers.QuotaThresholdMailer.sendNotice(QuotaThresholdMailer.java:78)
at …
```
> MAILBOX-333 Avoid overQuotaMailing failures when no size limit

- mpt/impl/smtp/cassandra-rabbitmq-object-storage/src/test/resources/mailetcontainer.xml
- mpt/impl/smtp/cassandra/src/test/resources/mailetcontainer.xml
- server/apps/cassandra-app/sample-configuration/mailetcontainer.xml
- server/apps/cassandra-app/src/test/resources/mailetcontainer.xml
- server/apps/distributed-app/sample-configuration/mailetcontainer.xml
- server/apps/distributed-app/src/test/resources/mailetcontainer.xml
- server/apps/memory-app/sample-configuration/mailetcontainer.xml
- server/apps/memory-app/src/test/resources/mailetcontainer.xml
- server/protocols/jmap-rfc-8621-integration-tests/distributed-jmap-rfc-8621-integration-tests/src/test/resources/mailetcontainer.xml
- server/protocols/jmap-rfc-8621-integration-tests/memory-jmap-rfc-8621-integration-tests/src/test/resources/mailetcontainer.xml
- server/protocols/webadmin-integration-test/distributed-webadmin-integration-test/src/test/resources/mailetcontainer.xml
- server/protocols/webadmin-integration-test/memory-webadmin-integration-test/src/test/resources/mailetcontainer.xml
https://ci-builds.apache.org/job/james/job/ApacheJames/job/master/281/testReport/junit/org.apache.james/WithCassandraPassThroughBlobStoreMutableTest/oneHundredMailsShouldBeWellReceived_GuiceJamesServer_/
This master build did fail because JMAP filtering failed for one of the emails.
This test sends 100 emails to a single recipient. Single recipients have their filters on a single Primary Key, and filters are managed by a Cassandra Lightweight transaction (refer to JAMES-3435 for background regarding LightWeight transactions in the project). Apparently this is enough to create contention!
```
05:02:05.113 [ERROR] o.a.j.m.i.ProcessorImpl - Exception calling org.apache.james.jmap.mailet.filter.JMAPFiltering: Cassandra timeout during read query at consistency SERIAL (1 responses were required …
```
> JAMES-3656 Ignore failures in non essential feature prior delivery

- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageIdMapper.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageMapper.java
- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/model/message/view/MessageFullViewFactory.java
- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/event/ComputeMessageFastViewProjectionListener.java
- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/http/JMAPApiRoutes.java
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/http/BasicAuthenticationStrategy.scala
Before: 10.22% of time is spent in Unsafe.park/unpark, after it is 9.12%.
We also have a little performance enhancement (not reaching system limit...)
Before
```
================================================================================
---- Global Information --------------------------------------------------------
> request count                                     126470 (OK=126470 KO=0     )
> min response time                                      6 (OK=6      KO=-     )
> max response time                                   6958 (OK=6958   KO=-     )
> mean response time                                    57 (OK=57     KO=-     )
> std deviation                                        139 (OK=139    KO=-     )
> response time 50th percentile                         28 (OK=28 …
```
> [PERFORMANCE] Limit context switches

- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/pushsubscription/PushListener.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/pushsubscription/PushRequest.scala
- server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/pushsubscription/PushListenerTest.scala
- server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/pushsubscription/PushRequestTest.scala
-> Urgency governs when the notification should be sent to the terminal
- State resynchronisation should occur only when on high battery / wifi
- we want to receive email notifications
-> Topic enables sending only the latest state, and ignores older ones. Newer messages replaces each other at the push gateway level.
> JAMES-3539 PushListener should set urgency and topic 

- server/mailet/mock-smtp-server/README.adoc
As per discussion on https://github.com/apache/james-project/pull/715, here are some example sessions for the mock smtp http endpoints, as documentation.
> documenting mock smtp server http endpoints

- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/PushServerExtension.scala
- server/protocols/jmap-rfc-8621-integration-tests/memory-jmap-rfc-8621-integration-tests/pom.xml
- server/protocols/jmap-rfc-8621-integration-tests/memory-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/memory/MemoryPushSubscriptionSetMethodTest.java
- server/protocols/jmap-rfc-8621-integration-tests/pom.xml
One of the weirdest things I have seen so far.
Solves https://ci-builds.apache.org/job/james/job/ApacheJames/job/master/332/
```
Error Message
Different value found in node "methodResponses[0][1].sent.k1546.textBody", expected: <string> but was: <missing>.
Stacktrace
java.lang.AssertionError: Different value found in node "methodResponses[0][1].sent.k1546.textBody", expected: <string> but was: <missing>.
```
Under the hood javax.mail was not able to handle `message/disposition-notification` content type.
I don't know why the build on https://github.com/apache/james-project/pull/724 was :green_apple: ...
> JAMES-3539 Fix a dependency conflict

- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/DSNBounce.java
- server/mailet/mailets/src/test/java/org/apache/james/transport/mailets/DSNBounceTest.java
When the DSNBounce mailet processes a mail without a Date header, it fails with the exception
`java.time.temporal.UnsupportedTemporalTypeException: Unsupported field: OffsetSeconds`
because the LocalDateTime used to construct the new date does not include timezone information required by the date formatter.
The fix is to construct the new date via ZonedDateTime instead.
There is actually a unit test for this, but the MimeMessageBuilder adds a Date header by default if not specified. The test fix is to explicitly remove the Date header after building.
> JAMES-3666 Fix DSNBounce exception when no Date header is present

- server/protocols/jmap-draft-integration-testing/jmap-draft-integration-testing-common/src/test/java/org/apache/james/jmap/ProvisioningTest.java
The test case `ProvisioningTest.provisionMailboxesShouldNotDuplicateMailboxByName` some times pass, some times fail.
Because the Content-Length is not a `2735` for all repeat tests. 
Example: 
- If the `id` in response is 9 => length =1
- If the `id` in response is 10 => length =2
I checked other JUnit tests that have validated content length in https://github.com/apache/james-project/pull/494.
But I don't think the risk from them. So, I just only fix this JUnit test
> JAMES-3600 Fix check Content-Length when ProvisioningTest

- server/data/data-jmap-cassandra/src/main/java/org/apache/james/jmap/cassandra/pushsubscription/CassandraPushSubscriptionRepository.java
- server/data/data-jmap/src/main/java/org/apache/james/jmap/api/pushsubscription/PushSubscriptionRepository.java
- server/data/data-jmap/src/main/java/org/apache/james/jmap/memory/pushsubscription/MemoryPushSubscriptionRepository.java
- server/data/data-jmap/src/main/scala/org/apache/james/jmap/api/model/PushSubscription.scala
- server/data/data-jmap/src/test/scala/org/apache/james/jmap/api/pushsubscription/PushSubscriptionRepositoryContract.scala
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/PushSubscriptionSetMethodContract.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/core/PushSubscriptionSet.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/json/PushSubscriptionSerializer.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/PushSubscriptionSetCreatePerformer.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/PushSubscriptionUpdatePerformer.scala
WIP: return server fixed expires in JMAP response
> JAMES-3539 PushSubscription/set update expires

- server/apps/distributed-app/docs/modules/ROOT/pages/configure/usersrepository.adoc
- server/data/data-library/src/main/java/org/apache/james/user/lib/UsersRepositoryImpl.java
- src/site/xdoc/server/config-users.xml
For standalone James installations, there should be some basic protection against people/bots abusing James as a password oracle for brute-force/dictionary attacks. This needs to be enforced in a central location, so it affects all of the various protocols supported by James.
This proposal adds an option verifyFailureDelay to usersrepository.xml, which delays the response if someone tries to authenticate with a non-existing user or wrong password. There is intentionally no distinction between these two cases, so it also covers username guessing attacks.
Introducing this feature should not affect existing James installations, so the default is 0 delay/disabled.
T-Shirt size S.
> JAMES-3669 Delay on authentication failure

- server/apps/cassandra-app/sample-configuration/jvm.properties
- server/apps/cassandra-app/src/main/java/org/apache/james/CassandraJamesServerMain.java
- server/apps/distributed-app/docs/modules/ROOT/pages/configure/index.adoc
- server/apps/distributed-app/docs/modules/ROOT/pages/configure/jvm.adoc
- server/apps/distributed-app/sample-configuration/jvm.properties
- server/apps/distributed-app/src/main/java/org/apache/james/CassandraRabbitMQJamesServerMain.java
- server/apps/distributed-pop3-app/sample-configuration/jvm.properties
- server/apps/distributed-pop3-app/src/main/java/org/apache/james/DistributedPOP3JamesServerMain.java
- server/apps/jpa-app/sample-configuration/jvm.properties
- server/apps/jpa-app/src/main/java/org/apache/james/JPAJamesServerMain.java
- server/apps/jpa-smtp-app/sample-configuration/jvm.properties
- server/apps/jpa-smtp-app/src/main/java/org/apache/james/JPAJamesServerMain.java
- server/apps/memory-app/sample-configuration/jvm.properties
- server/apps/memory-app/src/main/java/org/apache/james/MemoryJamesServerMain.java
- server/container/guice/common/src/main/java/org/apache/james/ExtraProperties.java
- src/site/xdoc/server/config-system.xml
Many aspects of JVM execution for James can be tweaked by system properties. However, a lot of them will clutter the command line and can become difficult to manage.
The solution is to read a properties file and set the contents as system properties. Since this can affect various class initializations, it should be done as soon as possible, e.g. immediately as first line of the server main() method.
This proposal adds a small utility class for this purpose. It will read a configuration file "conf/jvm.properties" if present, otherwise do nothing. The location of the file may be overridden by a system property "extra.props" for quick testing.
> JAMES-3668 Extra system properties from configuration file

- server/apps/distributed-app/docs/modules/ROOT/pages/operate/webadmin.adoc
- server/protocols/webadmin/webadmin-data/src/main/java/org/apache/james/webadmin/dto/VerifyUserRequest.java
- server/protocols/webadmin/webadmin-data/src/main/java/org/apache/james/webadmin/routes/UserRoutes.java
- server/protocols/webadmin/webadmin-data/src/main/java/org/apache/james/webadmin/service/UserService.java
- server/protocols/webadmin/webadmin-data/src/test/java/org/apache/james/webadmin/routes/UserRoutesTest.java
Extend the WebAdmin interface with a route to verify a username/password combination:
curl -XPOST http://ip:port/users/usernameToBeUsed \
-d '{"password":"passwordToBeVerified"}' \
-H "Content-Type: application/json"
The route reports 204 on success and 401 on failure. There is intentionally no distinction for non-existing users, to prevent a username oracle attack through this route.
Adding such a feature is useful for integrating James with 3rd party services, e.g. a web admin GUI.
T-Shirt size M.
> JAMES-3667 Add a WebAdmin route for verifying a user password.

- server/container/guice/cassandra/src/main/java/org/apache/james/modules/data/CassandraJmapModule.java
- server/data/data-jmap-cassandra/pom.xml
- server/data/data-jmap-cassandra/src/main/scala/org/apache/james/jmap/cassandra/identity/CassandraCustomIdentityDAO.scala
- server/data/data-jmap-cassandra/src/main/scala/org/apache/james/jmap/cassandra/identity/CassandraCustomIdentityModule.scala
- server/data/data-jmap-cassandra/src/main/scala/org/apache/james/jmap/cassandra/identity/tables/CassandraCustomIdentityTable.scala
- server/data/data-jmap-cassandra/src/main/scala/org/apache/james/jmap/cassandra/utils/EmailAddressTupleUtil.scala
- server/data/data-jmap-cassandra/src/test/java/org/apache/james/jmap/cassandra/identity/CassandraCustomIdentityTest.java
- server/data/data-jmap/src/main/scala/org/apache/james/jmap/api/identity/CustomIdentityDAO.scala
- server/data/data-jmap/src/main/scala/org/apache/james/jmap/api/model/Identity.scala
- server/data/data-jmap/src/test/scala/org/apache/james/jmap/api/identity/CustomIdentityDAOContract.scala
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/IdentityGetContract.scala
resolve https://github.com/linagora/james-project/issues/4424
> JAMES-3534 Cassandra implementation for CustomIdentityDAO

- mailbox/plugin/deleted-messages-vault/src/main/java/org/apache/james/vault/VaultConfiguration.java
- mailbox/plugin/deleted-messages-vault/src/main/java/org/apache/james/vault/blob/BlobStoreDeletedMessageVault.java
- mailbox/plugin/deleted-messages-vault/src/test/java/org/apache/james/vault/DeletedMessageVaultHookTest.java
- mailbox/plugin/deleted-messages-vault/src/test/java/org/apache/james/vault/VaultConfigurationTest.java
- mailbox/plugin/deleted-messages-vault/src/test/java/org/apache/james/vault/blob/BlobStoreDeletedMessageVaultTest.java
- server/apps/distributed-app/docs/modules/ROOT/pages/configure/vault.adoc
- server/apps/distributed-pop3-app/sample-configuration/deletedMessageVault.properties
- server/container/guice/mailbox-plugin-deleted-messages-vault/src/main/java/org/apache/james/modules/vault/DeletedMessageVaultConfigurationModule.java
- server/container/guice/mailbox-plugin-deleted-messages-vault/src/main/java/org/apache/james/modules/vault/DeletedMessageVaultModule.java
- server/protocols/webadmin/webadmin-mailbox-deleted-message-vault/src/main/java/org/apache/james/webadmin/vault/routes/RestoreService.java
- server/protocols/webadmin/webadmin-mailbox-deleted-message-vault/src/test/java/org/apache/james/webadmin/vault/routes/DeletedMessagesVaultRoutesTest.java
- src/site/xdoc/server/config-vault.xml
James should have an option to specify which mailbox receives any restored messages from the Deleted Messages Vault, i.e. something other than the default of 'Restored-Messages'.
This is necessary to use the Deleted Messages Vault in combination with POP3, since POP3 users cannot access any other mailboxes than 'INBOX'.
The solution is to add an extra configuration option 'restoreLocation' within deletedMessagesVault.properties, which can be injected into the RestoreService for this purpose.
T-Shirt size S.
> JAMES-3670 : Configurable restore location for deleted messages

- protocols/pop3/src/main/java/org/apache/james/protocols/pop3/core/AbstractPOP3CommandHandler.java
- protocols/pop3/src/main/java/org/apache/james/protocols/pop3/core/CapaCmdHandler.java
- protocols/pop3/src/main/java/org/apache/james/protocols/pop3/core/DeleCmdHandler.java
- protocols/pop3/src/main/java/org/apache/james/protocols/pop3/core/ListCmdHandler.java
- protocols/pop3/src/main/java/org/apache/james/protocols/pop3/core/NoopCmdHandler.java
- protocols/pop3/src/main/java/org/apache/james/protocols/pop3/core/QuitCmdHandler.java
- protocols/pop3/src/main/java/org/apache/james/protocols/pop3/core/RetrCmdHandler.java
- protocols/pop3/src/main/java/org/apache/james/protocols/pop3/core/RsetCmdHandler.java
- protocols/pop3/src/main/java/org/apache/james/protocols/pop3/core/StatCmdHandler.java
- protocols/pop3/src/main/java/org/apache/james/protocols/pop3/core/StlsCmdHandler.java
- protocols/pop3/src/main/java/org/apache/james/protocols/pop3/core/UidlCmdHandler.java
- protocols/pop3/src/main/java/org/apache/james/protocols/pop3/core/UserCmdHandler.java
- server/apps/cassandra-app/src/main/glowroot/plugins/pop3.json
- server/apps/distributed-app/src/main/glowroot/plugins/pop3.json
- server/apps/distributed-pop3-app/src/main/glowroot/plugins/pop3.json
- server/apps/jpa-app/src/main/glowroot/plugins/pop3.json
- server/apps/jpa-smtp-app/src/main/glowroot/plugins/pop3.json
- server/apps/memory-app/src/main/glowroot/plugins/pop3.json
For better analysis capability in POP3 related issues, James should have glowroot support for this protocol as well.
This is considerably easier with a minor refactoring, making all POP3 command handlers extend an AbstractPOP3CommandHandler which unifies their onCommand methods.
On this basis we can provide a simple glowroot plugin (pop3.json) for each James app variant.
T-Shirt size S.
> JAMES-3671 : Glowroot instrumentation for POP3 protocol

- server/apps/distributed-app/docs/modules/ROOT/pages/configure/blobstore.adoc
- server/apps/distributed-app/sample-configuration/blob.properties
- server/apps/distributed-pop3-app/sample-configuration/blob.properties
- server/blob/blob-s3/src/main/java/org/apache/james/blob/objectstorage/aws/AwsS3AuthConfiguration.java
- server/blob/blob-s3/src/main/java/org/apache/james/blob/objectstorage/aws/S3BlobStoreDAO.java
- server/blob/blob-s3/src/test/java/org/apache/james/blob/objectstorage/aws/AwsS3AuthConfigurationTest.java
- server/container/guice/blob/s3/src/main/java/org/apache/james/modules/objectstorage/aws/s3/AwsS3ConfigurationReader.java
- server/container/guice/blob/s3/src/test/java/org/apache/james/modules/objectstorage/aws/s3/AwsS3ConfigurationReaderTest.java
- src/site/xdoc/server/config-blobstore.xml
Since James supports S3 blob storage access via HTTPS, it should be possible to configure a specific trust store for validating the S3 server certificate. This lets users "pin" this certificate, and better separate the trust realms of infrastructure and public services (SMTP, IMAP etc.).
This can be achieved in blob.properties with the usual set of configuration options for such cases, such as:
```
objectstorage.s3.truststore.path=/conf/s3trust.p12
objectstorage.s3.truststore.type=PKCS12
objectstorage.s3.truststore.secret=yoursecret
objectstorage.s3.truststore.algorithm=SunX509 
```
T-Shirt size M.
> JAMES-3673 : Separate trust store for S3

- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/task/CassandraRecomputeCurrentQuotasServiceTest.java
- mpt/impl/managesieve/cassandra/src/test/java/org/apache/james/mpt/managesieve/cassandra/host/CassandraHostSystem.java
- server/apps/cassandra-app/sample-configuration/usersrepository.xml
- server/apps/distributed-app/docs/modules/ROOT/pages/configure/usersrepository.adoc
- server/apps/distributed-app/sample-configuration/usersrepository.xml
- server/apps/distributed-pop3-app/sample-configuration/usersrepository.xml
- server/apps/jpa-app/sample-configuration/usersrepository.xml
- server/apps/jpa-smtp-app/sample-configuration/usersrepository.xml
- server/apps/memory-app/sample-configuration/usersrepository.xml
- server/container/guice/data-cassandra/src/main/java/org/apache/james/modules/data/CassandraUsersRepositoryModule.java
- server/data/data-cassandra/src/main/java/org/apache/james/user/cassandra/CassandraRepositoryConfiguration.java
- server/data/data-cassandra/src/main/java/org/apache/james/user/cassandra/CassandraUsersDAO.java
- server/data/data-cassandra/src/test/java/org/apache/james/rrt/cassandra/CassandraRecipientRewriteTableTest.java
- server/data/data-cassandra/src/test/java/org/apache/james/rrt/cassandra/CassandraStepdefs.java
- server/data/data-cassandra/src/test/java/org/apache/james/user/cassandra/CassandraUsersRepositoryTest.java
- server/data/data-jpa/src/main/java/org/apache/james/user/jpa/model/JPAUser.java
- server/data/data-jpa/src/test/java/org/apache/james/user/jpa/model/JPAUserTest.java
- server/data/data-library/src/main/java/org/apache/james/user/lib/model/Algorithm.java
- server/data/data-library/src/main/java/org/apache/james/user/lib/model/DefaultUser.java
- server/data/data-library/src/main/java/org/apache/james/user/lib/util/DigestUtil.java
- server/data/data-library/src/test/java/org/apache/james/user/lib/UsersRepositoryContract.java
- server/data/data-library/src/test/java/org/apache/james/user/lib/model/AlgorithmTest.java
- server/data/data-library/src/test/java/org/apache/james/user/lib/model/DefaultUserTest.java
- server/data/data-library/src/test/java/org/apache/james/user/lib/util/DigestUtilTest.java
- server/data/data-memory/src/main/java/org/apache/james/user/memory/MemoryUsersDAO.java
- upgrade-instructions.md
See https://issues.apache.org/jira/browse/JAMES-3674 for a general description. This comes in two commits for clarification:
1. Extend `Algorithm.HashingMode` with new options `salted` and `legacy_salted`, and renaming `default` to `plain` now that there are multiple options. Remove the implicit factory mechanism in favor of an explicit second parameter, i.e.`Algorithm.of(algorithmName, hashingMode)`. Then have `DefaultUser` include the username when the selected algorithm requires salting.
2. Introduce a `CassandraUsersRepository` to pass configuration options to the user DAO. Extend the latter to remember the preferred algorithm and hashing mode from the configuration, and use them when hashing new passwords. But add an explicit `hashingmode` colum next to `algorithm` and `password` in …
> JAMES-3674 : Support password salting and hash scheme upgrading

- mailbox/api/src/main/java/org/apache/james/mailbox/MessageUid.java
This extra boxing was using 10% of CPU resources for IMAP.
> [PERFORMANCE] MessageUid::compareTo should not box values

- server/container/guice/common/src/main/java/org/apache/james/utils/DataProbeImpl.java
- server/data/data-api/src/main/java/org/apache/james/probe/DataProbe.java
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/IdentitySetContract.scala
After writing the test and having a look again at the delete API logic, I realize that we don't need to change any logic to the destroy case.
Still the test for sure.
> JAMES-3534 Identity/destroy should not fail for identities whose alias is deleted

- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/modules/CassandraMailboxRecentsModule.java
This prevents (most of) tombstones warnings when reading this
table and the underlying data model is resilient to
deletions not applied (as all entries are removed on SELECT).
> JAMES-3679 Set mailbox recent gc_grace_second to zero

- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/remote/delivery/MailDelivrerToHost.java
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/remote/delivery/RemoteDeliveryConfiguration.java
- server/mailet/mailets/src/test/java/org/apache/james/transport/mailets/remote/delivery/RemoteDeliveryConfigurationTest.java
Java Mail annoyingly wants its properties to use mail.smtp**s**.x prefix instead of mail.smtp.x when using an SMTPS session, and ignores the regular properties in this case.
> JAMES-3681 : RemoteDelivery must use correct properties for SMTPS

- server/apps/distributed-app/docs/modules/ROOT/partials/RemoteDelivery.adoc
- server/container/guice/common/src/main/java/org/apache/james/utils/MailRepositoryProbeImpl.java
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/RemoteDelivery.java
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/remote/delivery/DeliveryRunnable.java
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/remote/delivery/MailDelivrer.java
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/remote/delivery/RemoteDeliveryConfiguration.java
- server/mailet/mailets/src/test/java/org/apache/james/transport/mailets/remote/delivery/DeliveryRunnableTest.java
- server/mailet/mailets/src/test/java/org/apache/james/transport/mailets/remote/delivery/MailDelivrerTest.java
- server/mailet/remote-delivery-integration-testing/src/test/java/org/apache/james/mailets/RemoteDeliveryOnSuccessTest.java
Convenient to emit success DSNs and track
successful sends, eg via logging.
> JAMES-2912 RemoteDelivery: add a onSuccess processor

- server/protocols/jmap-draft/src/test/java/org/apache/james/jmap/http/XUserAuthenticationStrategyTest.java
- server/protocols/jmap/src/main/java/org/apache/james/jmap/http/XUserAuthenticationStrategy.java
This could be used by API gateways to be
responsible of authentication and propagate it
to the James server.
We plan on relying on such mechanism to
integrate James JMAP endpoints with OIDC.
> JAMES-3680 Provide a XUserAuthenticationStrategy

- src/site/xdoc/server/feature-security.xml
- Adds a Reporting vulnerabilities section
- CVE-2021-38542: Apache James vulnerable to STARTTLS command injection (IMAP and POP3)
- CVE-2021-40110: Apache James IMAP vulnerable to a ReDoS
- CVE-2021-40111: Apache James IMAP parsing Denial Of Service
- CVE-2021-40525: Apache James: Sieve file storage
vulnerable to path traversal attacks
- Add details for CVE-2017-12628
> [SITE] Fill the security page following recent CVE announces

- pom.xml
Solves https://security.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-2326698
Denial of Service (DoS)
Affected versions of this package are vulnerable to
Denial of Service (DoS) when using JDK serialization
to serialize and deserialize JsonNode values. It is
possible for the attacker to send a 4-byte length
payload, with a value of Integer.MAX_VALUE , that
will eventually cause large buffer allocation and
out of heap memory.
> [UPGRADE] Upgrade jackson 2.12.4 -> 2.13.1

- pom.xml
Solves CVE-2021-44832 (Score 6.6)
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-44832
Apache Log4j2 versions 2.0-beta7 through 2.17.0
(excluding security fix releases 2.3.2 and 2.12.4)
are vulnerable to a remote code execution (RCE)
attack when a configuration uses a JDBC Appender
with a JNDI LDAP data source URI when an attacker
has control of the target LDAP server. This issue
is fixed by limiting JNDI data source names to the
java protocol in Log4j2 versions 2.17.1, 2.12.4,
and 2.3.2.
> [UPGRADE] Upgrade log4j 2.17.0 -> 2.17.1

- src/adr/0052-pulsar-mailqueue.md
ADR for https://github.com/apache/james-project/pull/808
TODO:
- Message on the mailing list regarding this ADR, the future of pulsar in James, etc...
- Review and answer my tiny 3 technical questions over this work.
- Open JIRAs for follow up work. Create a pulsar `epic` and link all JIRAs to it.
> [ADR] 51. Pulsar MailQueue

- server/queue/queue-activemq/src/test/java/org/apache/james/queue/activemq/ActiveMQMailQueueBlobTest.java
- server/queue/queue-activemq/src/test/java/org/apache/james/queue/activemq/ActiveMQMailQueueTest.java
- server/queue/queue-api/src/test/java/org/apache/james/queue/api/DelayedManageableMailQueueContract.java
- server/queue/queue-jms/src/test/java/org/apache/james/queue/jms/JMSCacheableMailQueueTest.java
- server/queue/queue-pulsar/src/test/java/org/apache/james/queue/pulsar/PulsarMailQueueTest.java
- The Pulsar mail queue currently do not delete delayed emails
Explanation: the sequenceId of the mail is reset when
moved from the scheduled topic to the out topic, thus
bypassing deletes emitted while it was sitting in the
scheduled queue.
(this mechanism exist to prevent deletions to apply on
future emails)
We would likely need the sequence to be backed by some
applicative metadata - like a timestamp?
- Second problem: filter removal based on sequence number
Goal: Prevent uncontrolled growth by removing
meaningless deletion filters
Assumptions: emails are ordered
Pitfall: delayed messages are out of order.
Please note that the JMS mailqueue is buggy regarding
delayed messages being deleted, I used the memory implementation as a reference.
> JAMES-3687 Demonstrate issues with deletes of delayed mails

- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/remote/delivery/DeliveryRunnable.java
- server/protocols/protocols-smtp/src/main/java/org/apache/james/smtpserver/DataLineJamesMessageHookHandler.java
Adds mail specific MDC fields during initial hooks/spooling, as well as during remote delivery. (The latter runs in a different thread pool and thus looses the mailet container MDC).
> JAMES-3704 Improve mail diagnostics on system edge

- protocols/pop3/src/main/java/org/apache/james/protocols/pop3/core/RetrCmdHandler.java
- protocols/pop3/src/main/java/org/apache/james/protocols/pop3/core/TopCmdHandler.java
A minor refactoring to make the POP3 RETR/TOP handlers more easily extensible: Retrieve the message content via a separate protected method.
> JAMES-3705 Refactoring POP3 handlers to be more extensible

- server/container/core/src/main/java/org/apache/james/server/core/MailImpl.java
Before a streaming copy was done, taking ~28% of CPU
time for RecipientRewriteTable lookups.
> JAMES-343 Performance: Use ImmutableMap copy upon DSN parameters lookup

- server/protocols/webadmin-integration-test/distributed-webadmin-integration-test/src/test/java/org/apache/james/webadmin/integration/rabbitmq/RabbitMQWebAdminServerBlobGCIntegrationTest.java
An input stream was reused, thus empty on the second try. We
should fix this input mistake and correct the wrong assertions
based on it.
> JAMES-3150 Fix RabbitMQWebAdminServerBlobGCIntegrationTest

- protocols/imap/src/main/java/org/apache/james/imap/processor/fetch/FetchResponseBuilder.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/fetch/PartialFetchBodyElement.java
- protocols/imap/src/test/java/org/apache/james/imap/processor/fetch/PartialFetchBodyElementTest.java
- server/protocols/protocols-imap4/src/test/java/org/apache/james/imapserver/netty/IMAPServerTest.java
- server/testing/src/main/java/org/apache/james/utils/TestIMAPClient.java
1. Introduces unit tests for IMAP partial fetch. Those are not working properly after the Netty 4 migration cf https://github.com/apache/james-project/pull/886#issuecomment-1048862314
2. I discovered a bug where a ridicoulously high size is reproded for partial fetches with an offset and no limit (close to Long.MAX) that IMAP clients are not able to handle. This is due to the use of Long.MAX_VALUE to represent absence and causes mis-calculations down the line. Fixed with the use of Optionals...
> JAMES-3715 Tests and fix for IMAP partial Fetch

- pom.xml
When running maven (`mvn clean install`), The new version of scala maven plugin (v4.5.6) take more time than older version we used before (v.3.4.6) (https://github.com/apache/james-project/pull/826/commits/c2288511de79d1282081f39aba34e23213041317)
It comes from `incremental compilation` (https://davidb.github.io/scala-maven-plugin/example_incremental.html)
```
The incremental compilation is enabled by default after scala-maven-plugin v4.0.0, and the "recompileMode" configuration option is set to "incremental" by default.
```
=> Change suggestion: `<recompileMode>incremental</recompileMode>` -> `<recompileMode>all</recompileMode>`
- Command: `mvn clean install -Dmaven.javadoc.skip=true -DskipTests -T11`
- Env 1: My PC - CPU AMD 5600G - 6 core 12 threads
- Before: Total time:  05:26 min …
> [UPGRADE] scala maven plugin change recompileMode: incremental -> all

- server/protocols/protocols-imap4/pom.xml
- server/protocols/protocols-imap4/src/test/java/org/apache/james/imapserver/netty/IMAPServerTest.java
- server/protocols/protocols-imap4/src/test/resources/imapServerCompress.xml
Commons-net do not look like it supports compression thus I resorted
to use javax.mail
Compression is one of the untested features that broke during the
Netty 4 upgrade thus I take this opportunity to add more tests.
CF https://github.com/apache/james-project/pull/886#issuecomment-1050804710
> JAMES-3715 Add tests for IMAP COMPRESS transport layer

- backends-common/pulsar/src/main/scala/org/apache/james/backends/pulsar/PulsarReader.scala
- server/queue/queue-api/src/test/java/org/apache/james/queue/api/ManageableMailQueueContract.java
- server/queue/queue-pulsar/src/main/scala/org/apache/james/queue/pulsar/PulsarMailQueue.scala
- server/queue/queue-pulsar/src/test/java/org/apache/james/queue/pulsar/PulsarMailQueueTest.java
They can have been acknowledged and thus the underlying mime message removed from the store since we started browsing. We therefore ignore messages that can no longer be found in the mime message store.
> [JAMES-3721] Fixes ObjectNotFoundExceptions when browsing mails

- protocols/imap/src/main/java/org/apache/james/imap/api/process/SelectedMailbox.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/DefaultProcessorChain.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/IdleProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/base/SelectedMailboxImpl.java
- server/protocols/protocols-imap4/src/test/java/org/apache/james/imapserver/netty/IMAPServerTest.java
In the face of Netty4 migration, pipeline modifications (which IDLE does)
deserves to be seriously tested.
> JAMES-3715 Add TCP transport level tests for IMAP IDLE

- backends-common/elasticsearch-v7/src/main/java/org/apache/james/backends/es/v7/ClientProvider.java
- backends-common/rabbitmq/src/main/java/org/apache/james/backends/rabbitmq/RabbitMQConnectionFactory.java
- server/mailet/mailetcontainer-impl/src/main/java/org/apache/james/mailetcontainer/impl/JamesMailSpooler.java
Because audit of thread counts with tools like `jstack` reports a lot of unamed threads that we can hardly audit.
```
"pool-10-thread-1" #26 prio=5 os_prio=0 cpu=509.34ms elapsed=9834.34s tid=0x00007faaabf67000 nid=0x25 runnable  [0x00007faa221b6000]
java.lang.Thread.State: RUNNABLE
at sun.nio.ch.EPoll.wait(java.base@11.0.14.1/Native Method)
at sun.nio.ch.EPollSelectorImpl.doSelect(java.base@11.0.14.1/Unknown Source)
at sun.nio.ch.SelectorImpl.lockAndDoSelect(java.base@11.0.14.1/Unknown Source)
- locked <0x0000000741f969d8> (a sun.nio.ch.Util$2)
- locked <0x0000000741f96888> (a sun.nio.ch.EPollSelectorImpl)
at sun.nio.ch.SelectorImpl.select(java.base@11.0.14.1/Unknown Source)
at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:343)
at …
```
> [PERF] Better name James' threads

- mailbox/api/src/main/java/org/apache/james/mailbox/model/UidValidity.java
- mailbox/api/src/test/java/org/apache/james/mailbox/model/UidValidityTest.java
- protocols/imap/src/main/java/org/apache/james/imap/decode/ImapRequestLineReader.java
- protocols/imap/src/main/java/org/apache/james/imap/decode/parser/AbstractSelectionCommandParser.java
- protocols/imap/src/main/java/org/apache/james/imap/decode/parser/FetchCommandParser.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/AbstractMailboxProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/AbstractSelectionProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/fetch/FetchProcessor.java
- server/protocols/protocols-imap4/src/test/java/org/apache/james/imapserver/netty/IMAPServerTest.java
- James sends empty VANISHED response that don't comply with formal syntax
- We confused highest modseq and highest modseq for which deletion occured which caused under some circumpstances vanished response not to be returned
- Closed response was never sent upon implicit mailbox closure
- FETCH was not allowing to combine several modifiers
- SELECT was not strictly obeying QRESYNC formal syntax
- Math.abs related bug upon UIDVALIDITY generation
We need to test this changeset manually seriously with Evolution client with QRESYNC enabled to see if we solved our issues.
> JAMES-3722 Tests and fixes for IMAP QRESYNC

- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/EmailSet.scala
Failure to do so will cause invalid characters to be present,
preventing SMTP transmition.
```
host x.x.x.x[x.x.x.x] said: 554 5.6.0
Message contains NUL characters (in reply to end of DATA command)
```
> JAMES-3439 Email/set create should encode attachments in base64

- server/data/data-ldap/src/main/java/org/apache/james/user/ldap/ReadOnlyLDAPUser.java
Wrap the info and warn log into one:
- error is too high for something that can be caused by bad user input
- error log was missing critical information like username
- the info log is duplicated with the error log
> JAMES-3594 ReadOnlyLDAPUser adapt log message

- server/apps/distributed-app/sample-configuration/rabbitmq.properties
- server/apps/distributed-pop3-app/sample-configuration/rabbitmq.properties
The cluster hosts configuration should not be enabled by default, it creates an issue
in the dns resolution when starting James with a standalone rabbitmq.
> JAMES-3731 Fix default configuration for rabbitmq regarding distributed images

- protocols/netty/src/main/java/org/apache/james/protocols/netty/ProtocolMDCContextFactory.java
- server/apps/cassandra-app/sample-configuration/jvm.properties
- server/apps/distributed-app/docs/modules/ROOT/pages/configure/jvm.adoc
- server/apps/distributed-app/sample-configuration/jvm.properties
- server/apps/distributed-pop3-app/sample-configuration/jvm.properties
- server/apps/jpa-app/sample-configuration/jvm.properties
- server/apps/jpa-smtp-app/sample-configuration/jvm.properties
- server/apps/memory-app/sample-configuration/jvm.properties
- server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/IMAPMDCContext.java
- src/site/xdoc/server/config-system.xml
Resolving this takes up to 1% of IMAP compute time hence this information,
not necessarily useful, should be dis-activable.
> [PERF] Allow disabling host information in protocol MDC

- mpt/core/src/main/java/org/apache/james/mpt/session/ExternalSession.java
- protocols/api/src/main/java/org/apache/james/protocols/api/AbstractProtocolTransport.java
- protocols/netty/src/main/java/org/apache/james/protocols/netty/AllButStartTlsLineBasedChannelHandler.java
- server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/NettyImapSession.java
- server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/SwitchableLineBasedFrameDecoder.java
- server/protocols/protocols-imap4/src/test/java/org/apache/james/imapserver/netty/IMAPServerTest.java
- server/protocols/protocols-imap4/src/test/resources/imapServerStartTLS.xml
- server/protocols/protocols-managesieve/src/main/java/org/apache/james/managesieveserver/netty/ChannelManageSieveResponseWriter.java
- server/protocols/protocols-managesieve/src/main/java/org/apache/james/managesieveserver/netty/ManageSieveChannelUpstreamHandler.java
- Race condition between the framing handler and the processing handler allows to leverage concurrency based man in the middle attacks allowing command injection.
- Bad sanitizing of IMAP tags allow crafting an input that bypasses STARTTLS command detection
> JAMES-1862 Fix several issues with STARTTLS command injection detection

- protocols/imap/src/main/java/org/apache/james/imap/api/process/ImapSession.java
- protocols/imap/src/main/java/org/apache/james/imap/encode/FakeImapSession.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/IdleProcessor.java
- server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/NettyImapSession.java
IDLE event implementation in Netty uses a similar
pattern and this allows to get rid of a useless thread
pool... The less threads, the better!
> JAMES-3715 Schedule IMAP IDLE heartbits on the Netty Event loop

- server/protocols/jwt/src/main/java/org/apache/james/jwt/JwtTokenVerifier.java
- Provides an Immutable concurrent friendly JWT parser
- Avoids heavy instanciations that takes up to 0.70% of CPU
- Avoids deprecation warnings
> [PERF] Reuse JwtTokenVerifier parsers

- server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/ImapChannelUpstreamHandler.java
- server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/NettyConstants.java
From connection scoped to request scoped.
I started studying production heap dump in an effort to reduce the per user memory footprint. In conjunction with issues discussed in JAMES-3740 I found that in FastByteArrayOutputStream, upon writing a long line this buffer is sized up and never sized down.
We can end up with 60KB+ memory allocated per user... Forever.
While the impact is not as huge as the one described in JAMES-3740 yet for James deployment with a high connection density this could be non neglictible (100s MB of RAM).
Furthermore given the long lived lifecycle of this buffer (connection) it is very likely to be promoted to the old gen, which could build up to eventually get long GC pauses.
Suggestion: create a new IMAP composer for each request, 2 -> 64KB allocation is anyway …
> JAMES-3745 Use FastByteArrayOutputStream as a short lived object

- protocols/imap/src/main/java/org/apache/james/imap/api/process/SelectedMailbox.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/DefaultProcessorChain.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/IdleProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/base/SelectedMailboxImpl.java
- Avoid a data race resulting in some updates not to be sent
- Avoid the IDLE listener to never be unregistered and leak
- Finally prevent duplicated RabbitMQ registrations for IDLE and SELECT
All this is fixed by piggy backing IDLE notifications on SELECTED mailbox listener.
Please note that special care was put to avoid deadlocks.
> JAMES-3746 Backport behaviour changes for IMAP IDLE [3.7.x]

- protocols/imap/pom.xml
- protocols/imap/src/main/java/org/apache/james/imap/processor/base/UidMsnConverter.java
- protocols/imap/src/test/java/org/apache/james/imap/processor/base/UidMsnConverterTest.java
This reduces HEAP memory consumption of this use case by a factor 6.
In IMAP RFC-3501 there is two ways one addresses a message:
- By its UID (Unique ID) that is unique (until UID_VALIDITY changes...)
- By its MSN (Message Sequence  Number) which is the (mutable) position of a message in the mailbox.
We then need:
- Given a UID return its MSN which is for instance compulsory upon EXPUNGED notifications when QRESYNCH is not enabled.
- Given a MSN based request we need to convert it back to a UID (rare).
We do store the list of UIDs, sorted, in RAM and perform binarysearches to resolve those.
Each uid is wrapped in a MessageUID object. This object wrapping comes with an overhead of at least 12 bytes in addition to the 8 bytes payload (long). Quick benchmarks shows it's actually worse: 10 …
> JAMES-3740 Compact primitive collections for UID <-> MSN mapping

- mpt/impl/imap-mailbox/core/src/main/java/org/apache/james/mpt/imapmailbox/suite/Search.java
- mpt/impl/imap-mailbox/core/src/main/resources/org/apache/james/imap/scripts/SearchOptionAggregations.test
- mpt/impl/imap-mailbox/core/src/main/resources/org/apache/james/imap/scripts/SearchOptionSave.test
While documenting implemented RFCs for the distributed server, I realized we do not test the two following RFCs:
- https://datatracker.ietf.org/doc/html/rfc5182 Referencing the result of previous IMAP searches.
- https://datatracker.ietf.org/doc/html/rfc4731 Aggregations for IMAP search (min, max, count)
Write basic MPT tests for the following RFCs, because what is untested should not be advertised as supported.
While testing this I found a defect in IMAP CONDSTORE for the search commands that ignores only the first range for finding the highest modseq (with one range this is thus fully ignored) due to a bad stop condition in a for loop.
> JAMES-3751 MPT tests for IMAP SEARCH extentions

- mailet/base/src/main/java/org/apache/mailet/base/FlowedMessageUtils.java
- mailet/base/src/test/java/org/apache/mailet/base/FlowedMessageUtilsTest.java
Jira: https://issues.apache.org/jira/browse/JAMES-3753
I ended up rewriting almost all of `FlowedMessageUtils.flow()`. This implementation avoids creating temporary strings and fixes the bugs identified via fuzzing.
> JAMES-3753 Fix bugs in `FlowedMessageUtils.flow()`

- pom.xml
https://security.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-2421244
com.fasterxml.jackson.core:jackson-databind is a library which contains the general-purpose data-binding functionality and tree-model for Jackson Data Processor.
Affected versions of this package are vulnerable to Denial of Service (DoS) via a large depth of nested objects.
> [UPGRADE] jackson 2.13.1 -> 2.13.2.2 fixes CVE-2020-36518 [3.7.x]

- protocols/imap/src/main/java/org/apache/james/imap/decode/parser/SearchCommandParser.java
- protocols/imap/src/test/java/org/apache/james/imap/decode/parser/SearchCommandParserCharsetTest.java
- protocols/imap/src/test/java/org/apache/james/imap/decode/parser/SearchCommandParserNotTest.java
- protocols/imap/src/test/java/org/apache/james/imap/decode/parser/SearchCommandParserOrTest.java
- protocols/imap/src/test/java/org/apache/james/imap/decode/parser/SearchCommandParserQuotedCharsetTest.java
- protocols/imap/src/test/java/org/apache/james/imap/decode/parser/SearchCommandParserSearchKeySequenceSetTest.java
- protocols/imap/src/test/java/org/apache/james/imap/decode/parser/SearchCommandParserSearchKeyTest.java
- server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/ImapRequestFrameDecoder.java
- server/protocols/protocols-imap4/src/test/java/org/apache/james/imapserver/netty/IMAPServerTest.java
- Reader index was  not properly reset for
multiple subsequent continuations.
- Charset was not carried over for all the
terms of the search.
> JAMES-1489 Fix decoding for complex UTF-8 searches

- server/blob/blob-common/src/main/java/org/apache/james/blob/api/Store.java
- server/blob/mail-store/src/main/java/org/apache/james/blob/mail/MimeMessageStore.java
Co-Authored-By: Matthieu Baechler <matthieu@apache.org>
> JAMES-3761 Adds configurable bucketname to MimeMessageStore

- mailbox/api/src/main/java/org/apache/james/mailbox/extractor/TextExtractor.java
- mailbox/elasticsearch-v7/src/main/java/org/apache/james/mailbox/elasticsearch/v7/events/ElasticSearchListeningMessageSearchIndex.java
- mailbox/elasticsearch-v7/src/main/java/org/apache/james/mailbox/elasticsearch/v7/json/IndexableMessage.java
- mailbox/elasticsearch-v7/src/main/java/org/apache/james/mailbox/elasticsearch/v7/json/MessageToElasticSearchJson.java
- mailbox/elasticsearch-v7/src/main/java/org/apache/james/mailbox/elasticsearch/v7/json/MimePart.java
- mailbox/elasticsearch-v7/src/main/java/org/apache/james/mailbox/elasticsearch/v7/json/MimePartContainerBuilder.java
- mailbox/elasticsearch-v7/src/main/java/org/apache/james/mailbox/elasticsearch/v7/json/MimePartParser.java
- mailbox/elasticsearch-v7/src/main/java/org/apache/james/mailbox/elasticsearch/v7/json/RootMimePartContainerBuilder.java
- mailbox/elasticsearch-v7/src/test/java/org/apache/james/mailbox/elasticsearch/v7/json/IndexableMessageTest.java
- mailbox/elasticsearch-v7/src/test/java/org/apache/james/mailbox/elasticsearch/v7/json/MessageToElasticSearchJsonTest.java
- mailbox/elasticsearch-v7/src/test/java/org/apache/james/mailbox/elasticsearch/v7/json/MimePartTest.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/extractor/DefaultTextExtractor.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/extractor/JsoupTextExtractor.java
- mailbox/tika/pom.xml
- mailbox/tika/src/main/java/org/apache/james/mailbox/tika/CachingTextExtractor.java
- mailbox/tika/src/main/java/org/apache/james/mailbox/tika/ContentTypeFilteringTextExtractor.java
- mailbox/tika/src/main/java/org/apache/james/mailbox/tika/TikaHttpClient.java
- mailbox/tika/src/main/java/org/apache/james/mailbox/tika/TikaHttpClientImpl.java
- mailbox/tika/src/main/java/org/apache/james/mailbox/tika/TikaTextExtractor.java
- mailbox/tika/src/test/java/org/apache/james/mailbox/tika/CachingTextExtractorTest.java
- mailbox/tika/src/test/java/org/apache/james/mailbox/tika/TikaTextExtractorTest.java
- pom.xml
Tika was called from reactive code and was doing blocking HTTP calls from within
the MIME parsing code.
This generate:
- An unneeded thread consumption as we have some threads waiting for Tika
response
- Potentially dangerous blocking calls: for instance the InVM event bus was
doing such calls on the parallel thread pool (where it is critical NOT to
block)...
- Also the connection was opened on a per-call basis, not being reused.
We introduce the following changes:
- Reactification of the TextExtractor API
- We re-implement the HTTP calls done by TikaTextExtractor with reactor-netty
which allows us to pool HTTP connections and do this in a non-blocking
reactive fashion.
- We provide a reactive cache using the caffeine caching library - Guava
caches are blocking thus not an option...
- We …
> JAMES-3719 Reactive textual content extraction with Apache Tika

- server/container/util/src/test/java/org/apache/james/util/concurrency/ConcurrentTestRunnerTest.java
Locally 50ms was borderline with random failures, so
I expect the default value of 100 ms to be too low for
being reliable on a busy CI server where context switch
might be made expensive with expensive concurrent builds.
I hereby propose a safer, higher value of 2 seconds.
> [BUILD] Increase ConcurrentTestRunnerTest await time

- event-bus/distributed/src/main/java/org/apache/james/events/KeyRegistrationHandler.java
AMQP channel uses a lock to execute one RPC
Shitty driver design, iterating the channel pool to get a channel without RPC looks like a dead end.
At the very least we should not block the Netty event loop....
CF flame graph in the event loop:
CF AMQPChannel code:
```
private void doEnqueueRpc(Supplier<RpcWrapper> rpcWrapperSupplier) {
synchronized(this._channelMutex) {
boolean waitClearedInterruptStatus = false;
while(this._activeRpc != null) {
try {
this._channelMutex.wait();
} catch (InterruptedException var6) {
waitClearedInterruptStatus = true;
}
}
if (waitClearedInterruptStatus) {
Thread.currentThread().interrupt();
}
this._activeRpc = (RpcWrapper)rpcWrapperSupplier.get();
}
}
```
Getting tired of RabbitMQ driver and its fake reactive implementation.
> JAMES-3737 RabbitMQ unbinding is potentially blocking

- server/protocols/protocols-smtp/src/main/java/org/apache/james/smtpserver/SendMailHandler.java
Systems like postfix logs this information.
Today James logs only the transport envelope, which do not allow connecting James logs with external systems.
Such a log would also allows better identify messages concerned by an issue.
Proposal: add the messageId to SendMailHandler log.
> JAMES-3770 SendMailHandler should log MIME MessageID

- mailet/api/src/main/java/org/apache/mailet/DsnParameters.java
- mailet/api/src/test/java/org/apache/mailet/DsnParametersTest.java
- server/mailet/mailets/src/test/java/org/apache/james/transport/matchers/DSNDelayRequestedTest.java
Setting an invalid EndId leads to emails not being
transmissible to third party systems. Stricter validation
fixes this.
> JAMES-3431 Stricter validation for DSN ENVID

- mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMailboxManager.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/search/MessageSearches.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/search/SearchUtilsTest.java
- mailet/standard/src/main/java/org/apache/james/transport/mailets/Expires.java
- mailet/standard/src/test/java/org/apache/james/transport/mailets/ExpiresTest.java
- server/apps/distributed-app/docs/modules/ROOT/pages/configure/mailets.adoc
- server/apps/distributed-app/docs/modules/ROOT/pages/operate/webadmin.adoc
- server/apps/distributed-app/docs/modules/ROOT/partials/Expires.adoc
- server/container/guice/protocols/webadmin-mailbox/src/main/java/org/apache/james/modules/server/WebadminMailboxTaskSerializationModule.java
- server/protocols/webadmin/webadmin-mailbox/src/main/java/org/apache/james/webadmin/routes/MessagesRoutes.java
- server/protocols/webadmin/webadmin-mailbox/src/main/java/org/apache/james/webadmin/service/ExpireMailboxAdditionalInformationDTO.java
- server/protocols/webadmin/webadmin-mailbox/src/main/java/org/apache/james/webadmin/service/ExpireMailboxDTO.java
- server/protocols/webadmin/webadmin-mailbox/src/main/java/org/apache/james/webadmin/service/ExpireMailboxService.java
- server/protocols/webadmin/webadmin-mailbox/src/main/java/org/apache/james/webadmin/service/ExpireMailboxTask.java
- server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/routes/MessageRoutesExpireTest.java
- server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/routes/MessageRoutesTest.java
- server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/service/ExpireMailboxServiceTest.java
- server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/service/ExpireMailboxTaskAdditionalInformationDTOTest.java
- server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/service/ExpireMailboxTaskSerializationTest.java
- server/protocols/webadmin/webadmin-mailbox/src/test/resources/json/expireMailbox.additionalInformation.json
- server/protocols/webadmin/webadmin-mailbox/src/test/resources/json/expireMailbox.age.task.json
- server/protocols/webadmin/webadmin-mailbox/src/test/resources/json/expireMailbox.header.task.json
As discussed in the Jira ticket, this is my solution for deleting old emails form users INBOX. It can work in two ways:
1. Use Expires header in the stored mails:
POST http://ip:port/mailboxes?task=expireInboxes
2. Use age relative to time of invocation, e.g. all mails older than 30 days:
POST http://ip:port/mailboxes?task=expireInboxes&maxAge=30d
Optionally include &usersPerSecond=10 to control execution throttling.
To use variant 1, there is also a new "Expires" Mailet, which can add a default expires header, or enforce a min/max time bracket on an existing Expires header.
(Also includes a small fix to MessageSearches to respect the zone offset in a date-time value.)
> James 3758 Endpoint to delete old emails from INBOXes

- protocols/netty/src/main/java/org/apache/james/protocols/netty/BasicChannelInboundHandler.java
```
java.lang.NullPointerException: null
at org.apache.james.protocols.netty.BasicChannelInboundHandler.channelInactive(BasicChannelInboundHandler.java:137)
at org.apache.james.smtpserver.netty.SMTPChannelInboundHandler.channelInactive(SMTPChannelInboundHandler.java:64)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
at io.netty.channel.AbstractChannelHandlerContext.access$300(AbstractChannelHandlerContext.java:61)
at io.netty.channel.AbstractChannelHandlerContext$4.run(AbstractChannelHandlerContext.java:253)
at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
at …
```
> JAMES-3715 Prevent possible NPE upon inactive SMTP channel

- server/protocols/protocols-pop3-distributed/src/main/java/org/apache/james/pop3server/mailbox/task/MetaDataFixInconsistenciesService.java
-> Confirm inconsistencies before fixing them
Otherwise concurrent POP can be considered as inconsistencies.
-> Log errors
> JAMES-3623 MetaDataFixInconsistenciesService: account for concurrency

- backends-common/rabbitmq/src/main/java/org/apache/james/backends/rabbitmq/ReactorRabbitMQChannelPool.java
Fixes:
```
org.apache.james.backends.rabbitmq.ReactorRabbitMQChannelPoolTest.notUsedChannelShouldBeClosedWhenPoolIsClosed
Error Message
Expecting value to be false but was true
Stacktrace
org.opentest4j.AssertionFailedError: 
Expecting value to be false but was true
at org.apache.james.backends.rabbitmq.ReactorRabbitMQChannelPoolTest.notUsedChannelShouldBeClosedWhenPoolIsClosed(ReactorRabbitMQChannelPoolTest.java:117)
```
> JAMES-3772 Close ReactorRabbitMQChannelPool synchronously

- mailbox/store/src/main/java/org/apache/james/mailbox/store/ResultUtils.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/fetch/HeaderBodyElement.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/fetch/MimeBodyElement.java
- server/container/util/src/main/java/org/apache/james/util/io/BodyOffsetInputStream.java
- server/container/util/src/test/java/org/apache/james/util/BodyOffsetInputStreamTest.java
- server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/ChannelImapResponseWriter.java
Less time is spent reading data on input stream as we better leverage buffering.
Benefits storing messages (so also JMAP, SMTP)
(while still computing the input stream twice!)
> [PERF] More IMAP performance enhancement

- server/protocols/protocols-smtp/src/main/java/org/apache/james/smtpserver/SendMailHandler.java
As a tiny followup to [JAMES-3770](https://issues.apache.org/jira/browse/JAMES-3770), the MIME MessageID should also be in in the MDC at the time of spooling.
This makes it easier for people who use structured logging to search the correlation between MessageId and internal mail name for further diagnostics.
> JAMES-3776 SMTP should log MIME MessageId in MDC

- mailbox/store/src/main/java/org/apache/james/mailbox/store/JVMMailboxPathLocker.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/JVMMailboxPathLockerTest.java
Nowadays when working with lock, we use the same Bounded Elastic scheduler for two stuff:
- Acquiring the lock (a thread)
- Execution task and releasing the lock (another thread - when we subscribe the execution on Bounded elastic again).
This could cause the deadlock situation when the bounded elastic pool is exhausted then the execution and lock releasing never happened.
Deadlock illustrate: Let's say we have a thread pool size = 2
Thread 1: need the lock, have thread pool resource (itself) but won't release the thread pool until finished
Thread 2: holding the lock, need a new thread from the thread pool for execution and releasing the lock and won't release the lock until finished
=> Deadlock
Our thread log: https://pastebin.com/9iVxLYra
`boundedElastic-8 Acquired the lock …
> JAMES-3773: Acquiring the Mailbox path lock on another dedicated Scheduler

- server/protocols/webadmin/webadmin-mailbox/src/main/java/org/apache/james/webadmin/service/ExpireMailboxService.java
Current implementation produces
`
java.lang.IllegalStateException: Iterating over a toIterable() / toStream() is blocking, which is not supported in thread parallel-2
`
because the user list can be a BlockingIterable, e.g. in Cassandra.
The solution is to run user listing in the elastic scheduler which supports blocking.
> JAMES-3780 ExpireMailboxTask should support large number of users

- server/data/data-api/src/main/java/org/apache/james/rrt/api/CanSendFrom.java
- server/data/data-jmap/src/main/scala/org/apache/james/jmap/api/identity/CustomIdentityDAO.scala
- server/data/data-jmap/src/test/scala/org/apache/james/jmap/api/identity/IdentityRepositoryTest.scala
- server/data/data-library/src/main/java/org/apache/james/rrt/lib/CanSendFromImpl.java
- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/methods/SetMessagesCreationProcessor.java
- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/methods/SetMessagesUpdateProcessor.java
- server/protocols/jmap-draft/src/test/java/org/apache/james/jmap/draft/methods/SetMessagesUpdateProcessorTest.java
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailSubmissionSetMethod.scala
This change should improve the reactive chain where using CanSendFrom::userCanSendFrom (reactive).
One place left using this is `SenderAuthIdentifyVerificationRcptHook` (SMTP) which we could not migrate to reactive soon for now, therefore we need to keep CanSendFrom::userCanSendFrom (non-reactive).
> [REACTOR] Reactify CanSendFrom::userCanSendFrom

- backends-common/elasticsearch-v7/src/test/java/org/apache/james/backends/es/v7/DockerElasticSearch.java
- mailbox/tika/src/test/java/org/apache/james/mailbox/tika/TikaContainer.java
- server/data/data-ldap/src/test/java/org/apache/james/user/ldap/LdapGenericContainer.java
- server/mailet/integration-testing/src/test/java/org/apache/james/transport/mailets/SpamAssassinIntegrationTest.java
- server/mailet/mock-smtp-server/src/main/java/org/apache/james/mock/smtp/server/testing/MockSmtpServerExtension.java
- server/protocols/jmap-draft-integration-testing/jmap-draft-integration-testing-common/src/test/java/org/apache/james/jmap/ContainerTest.java
- server/testing/src/main/java/org/apache/james/util/docker/DockerContainer.java
- server/testing/src/main/java/org/apache/james/util/docker/Images.java
- server/testing/src/main/java/org/apache/james/utils/FakeSmtp.java
- By default, the testcontainer randomize the name for each container when start new.
The assign name of container will be easier to track on local when development
> Setting name for each container when run testcontainer 

- backends-common/rabbitmq/src/main/java/org/apache/james/backends/rabbitmq/RabbitMQConfiguration.java
- backends-common/rabbitmq/src/main/java/org/apache/james/backends/rabbitmq/RabbitMQManagementAPI.java
- backends-common/rabbitmq/src/test/java/org/apache/james/backends/rabbitmq/RabbitMQConfigurationTest.java
- server/apps/distributed-app/docs/modules/ROOT/pages/configure/rabbitmq.adoc
- server/apps/distributed-app/sample-configuration/rabbitmq.properties
- server/apps/distributed-pop3-app/sample-configuration/rabbitmq.properties
- server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/RabbitMQMailQueueManagement.java
- server/queue/queue-rabbitmq/src/test/java/org/apache/james/queue/rabbitmq/RabbitMqMailQueueFactoryTest.java
- src/site/xdoc/server/config-rabbitmq.xml
- upgrade-instructions.md
Some queues (the james work queues) don't get created if we use multiple virtual hosts and they have been created on an other one by an other James already, as we list all queues before creating if not existing.
Adding here a vhost option to just check the queues on that vhost, which should allow the creation of the missing queues on the targeted vhost if they got created somewhere else already.
> Add a vhost configuration option to RabbitMQ

- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/RemoteDelivery.java
- server/mailet/mailets/src/test/java/org/apache/james/transport/mailets/remote/delivery/RemoteDeliveryTest.java
Cherry-picked from master.
Loss of email is always bad, so this is an important fix and should be back ported to 3.7.x .
> JAMES-3787 RemoteDelivery: Error upon enqueue lead to email loss (3.7.x)

- pom.xml
- server/mailet/mailets/pom.xml
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/remote/delivery/MailDelivrerToHost.java
Remote Delivery now uses pools of SMTP and SMTPS sessions. This prevents a race condition in setting per-delivery properties.
The pools replace the former shared session objects. During tryDeliveryToHost(), the selectSession() method now borrows a session from the appropriate pool. Its properties can be changed as necessary for the current delivery. Once delivery is done, the new method releaseSession() finally returns this session to its pool. The pool resets any delivery specific properties to prevent information leaks.
The session pools are unbounded, so they can scale to whatever maximum thread concurrency is required. Otherwise, the default pool configuration should be fine.
> JAMES-3791 Remote Delivery uses a pool of SMTP sessions

- server/mailet/mailets/pom.xml
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/remote/delivery/MailDelivrerToHost.java
Straight cherry-pick from master. As a critical bug fix, this should be in 3.7.x too.
> JAMES-3791 Remote Delivery uses a pool of SMTP sessions (3.7.x)

- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/remote/delivery/MailDelivrerToHost.java
When developing the pooling solution, I missed this line affected by the change. The solution relies on property defaults now, but containsKey() does not fall back to defaults. Hence need to use getProperty() here, which does.
Only affects SMTPS transports. Without this, Java Mail will not see the enveloper sender we set, but tries to extract it from the From: header. And I have seen people put rather strange things into From: headers...
> JAMES-3791 Remote delivery pooling supports SMTPS

- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/delivery/SimpleMailStore.java
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/remote/delivery/MailDelivrerToHost.java
[JAMES-3770](https://issues.apache.org/jira/browse/JAMES-3770) added the MIME MessageId on spooling, making it easier to communicate with other mail server operators in diagnosing inbound delivery issues ("Did you receive this message from us?").
It seems useful to log the MessageId on remote delivery too, covering the outbound direction of relaying as well. Likewise, we should log it on local delivery for the local-to-local path.
Together, this lets us track all paths by which a mail can cross the boundaries of our realm of responsibility.
> JAMES-3792 Remote and Local delivery should log MIME MessageId

- server/apps/distributed-app/docs/modules/ROOT/pages/configure/extensions.adoc
- server/apps/distributed-app/docs/modules/ROOT/pages/extending/index.adoc
- server/container/guice/common/src/main/java/org/apache/james/modules/server/TaskSerializationModule.java
- server/container/guice/distributed/src/main/java/org/apache/james/modules/DistributedTaskSerializationModule.java
- server/container/guice/protocols/webadmin/src/main/java/org/apache/james/modules/server/TaskRoutesModule.java
- server/container/guice/protocols/webadmin/src/main/java/org/apache/james/modules/server/WebAdminServerModule.java
- server/container/guice/utils/src/main/java/org/apache/james/utils/ExtensionConfiguration.java
- server/task/task-json/src/main/java/org/apache/james/server/task/json/JsonTaskAdditionalInformationSerializer.java
- server/task/task-json/src/main/java/org/apache/james/server/task/json/JsonTaskSerializer.java
- server/task/task-json/src/main/java/org/apache/james/server/task/json/TaskExtensionModule.java
- server/task/task-json/src/main/java/org/apache/james/server/task/json/TaskModuleInjectionKeys.java
- James is supporting the custom web admin (https://james.apache.org/howTo/custom-webadmin-routes.html), but It does not yet support the `task-json` in the extension. 
We got an error when trying to guice bind more `AdditionalInformationDTOModule` to Set in the extension module. 
Eg:
```java
@Named(DTOModuleInjections.WEBADMIN_DTO)
@ProvidesIntoSet
public AdditionalInformationDTOModule<? extends TaskExecutionDetails.AdditionalInformation, ? extends AdditionalInformationDTO> webAdminFeedHamAdditionalInformation() {
return FeedHamToRSpamDTaskAdditionalInformationDTO.SERIALIZATION_MODULE;
}
```
-> It will be better if have a mechanism for support that 
- Add one more configure for `webadmin-dto` guice in `webadmin.properties`. Eg: `extensions.dtos=org.apache.james.modules.server.WebAdminDTOEx …
> JAMES-3796 Guice support the custom task in extension

- server/testing/src/main/java/org/apache/james/utils/FakeSmtp.java
GatewayRemoteDeliveryIntegrationTest::mailFromShouldBePreservedUponConcurrency
can take more than 15 secondes on the Apache CI.
> JAMES-3791 Increase FakeSmtp timeout

- server/mailet/rate-limiter/src/test/scala/org/apache/james/rate/limiter/api/RateLimiterContract.scala
Redis rate limiting window needs to be smaller than the
precision to have reliable assertions. This was not the
case for shouldFailWhenLowerLimitExceeded.
Fixes: https://ci-builds.apache.org/job/james/job/ApacheJames/job/PR-1111/7/testReport/junit/org.apache.james.rate.limiter/RedisRateLimiterTest/shouldFailWhenLowerLimitExceeded/
> JAMES-3693 Fix RateLimiterContract::shouldFailWhenLowerLimitExceeded

- mailbox/scanning-search/src/test/java/org/apache/james/mailbox/store/search/SimpleMessageSearchIndexTest.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/search/SimpleMessageSearchIndex.java
DRAFT: This adds a step to analyze the provided SearchQuery criteria and sort options to figure out the highest required mail fetch type.
Someone please check my classification in getFetchTypeForCriterion() and getFetchTypeForSort() - I have not worked with these before and am not sure I got them all right.
Unfortunately, I cannot really test this, as the InMemoryMessageMapper used by SimpleMessageSearchIndexTest seems to ignore the fetch type completely. Any suggestions? :(
> JAMES-3799 Optimize memory requirements of SimpleMessageSearchIndex

- third-party/rspamd/src/test/java/org/apache/james/rspamd/DockerRSpamDExtensionTest.java
- third-party/rspamd/src/test/java/org/apache/james/rspamd/RSpamDScannerTest.java
- third-party/rspamd/src/test/java/org/apache/james/rspamd/client/RSpamDHttpClientTest.java
- third-party/rspamd/src/test/java/org/apache/james/rspamd/route/FeedMessageRouteTest.java
- third-party/rspamd/src/test/java/org/apache/james/rspamd/task/FeedSpamToRSpamDTaskTest.java
RSpamD scoring delegates to many async modules and then aggregate the result. The implicit default `task_timeout` is 8 seconds which is sometime not long enough to return the full result.
Increasing timeout to a bigger value (say 20s) could let RSpamD enough time to fully score a mail.
> JAMES-3775 Increase RSpamD scoring stability

- server/queue/queue-pulsar/src/test/java/org/apache/james/queue/pulsar/PulsarMailQueueTest.java
https://ci-builds.apache.org/job/james/job/ApacheJames/job/PR-1099/16/testReport/junit/org.apache.james.queue.pulsar/PulsarMailQueueTest/dequeueShouldBeConcurrent/
```
Error Message
Too many concurrent offers. Specified maximum is 1. You have to wait for one previous future to be resolved to send another request
Stacktrace
java.lang.IllegalStateException: Too many concurrent offers. Specified maximum is 1. You have to wait for one previous future to be resolved to send another request
Standard Output
10:19:36.780 [ERROR] r.c.p.Operators - Operator called default onErrorDropped
java.lang.IllegalStateException: Too many concurrent offers. Specified maximum is 1. You have to wait for one previous future to be resolved to send another request
at …
```
> JAMES-3805 PulsarMailQueueTest.dequeueShouldBeConcurrent is unstable

- server/blob/blob-s3/src/main/java/org/apache/james/blob/objectstorage/aws/S3BlobStoreDAO.java
- server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/Dequeuer.java
Straight cherry-pick of https://github.com/apache/james-project/pull/1114
I think this is an important fix, and at the same time a trivial backport to 3.7.x. Everybody wins!
> JAMES-3800 / JAMES-3801 S3/RabbitMQ fix for 3.7.x

- mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMailboxManager.java
MailboxManagerTest::creatingConcurrentlyMailboxesWithSameParentShouldNotFail was hitting the limit of what the ASF CI can hold.
Reproduced locally with 64 concurrent processes, exponential
retries improved stability without reworking the test.
> [BUILD] Improve Mailbox creation stability

- third-party/rspamd/README.md
- third-party/rspamd/docker-compose-distributed.yml
- third-party/rspamd/docker-compose.yml
- third-party/rspamd/sample-configuration/antivirus.conf
- third-party/rspamd/sample-configuration/mailetcontainer_distributed.xml
- third-party/rspamd/sample-configuration/mailetcontainer_memory.xml
- third-party/rspamd/src/main/java/org/apache/james/rspamd/RSpamDScanner.java
- third-party/rspamd/src/main/java/org/apache/james/rspamd/client/RSpamDClientConfiguration.java
- third-party/rspamd/src/main/java/org/apache/james/rspamd/model/AnalysisResult.java
- third-party/rspamd/src/main/java/org/apache/james/rspamd/model/AnalysisResultDeserializer.java
- third-party/rspamd/src/test/java/org/apache/james/rspamd/DockerClamAV.java
- third-party/rspamd/src/test/java/org/apache/james/rspamd/DockerRSpamDExtensionTest.java
- third-party/rspamd/src/test/java/org/apache/james/rspamd/RSpamDScannerTest.java
- third-party/rspamd/src/test/java/org/apache/james/rspamd/client/RSpamDHttpClientTest.java
- third-party/rspamd/src/test/java/org/apache/james/rspamd/model/AnalysisResultDeserializationTest.java
- third-party/rspamd/src/test/resources/mail/attachment/inlineNonVirusTextAttachment.eml
- third-party/rspamd/src/test/resources/mail/attachment/inlineVirusTextAttachment.eml
- third-party/rspamd/src/test/resources/rspamd-config/antivirus.conf
As a user, I should NEVER receive an email containing a Virus.
RSpamDScanner mailet should push virus mail to `virusProcessor` for further processing (configurable).
E.g:
- Hard reject processing (store them in a mail repository and not deliver them):
```xml
<processor state="virus" enableJmx="false">
<mailet match="All" class="ToRepository">
<repositoryPath>file://var/mail/virus/</repositoryPath>
</mailet>
</processor>
```
- Soft reject processing (Remove attachment, modify the subject with [VIRUS] and add headers...):
```xml
<processor state="virus" enableJmx="false">
<mailet match="All" class="StripAttachment">
<remove>all</remove>
<pattern>.*</pattern>
</mailet>
<mailet match="All" class="AddSubjectPrefix">
<subjectPrefix>[VIRUS]</subjectPrefix>
</mailet>
</processor>
```
> JAMES-3775 ClamAV integration

- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/remote/delivery/DeliveryRunnable.java
This is necessary as else in high load a delivery-task can queue in the same thread as the never ending dequeuing-task and stay there forever
> JAMES-3803 RemoteDelivery uses different scheduler for dequeuing

- third-party/rspamd/src/test/java/org/apache/james/rspamd/DockerClamAV.java
- third-party/rspamd/src/test/java/org/apache/james/rspamd/DockerRSpamD.java
- third-party/rspamd/src/test/java/org/apache/james/rspamd/DockerRSpamDExtension.java
- third-party/rspamd/src/test/java/org/apache/james/rspamd/DockerRSpamDExtensionTest.java
- third-party/rspamd/src/test/java/org/apache/james/rspamd/task/FeedHamToRSpamDTaskTest.java
- Avoid restarting containers for each test class
- Start ClamAV and Redis in parallel
- Disable ClamFresh anti-virus database updates
- Tag tests as unstable as scoring is pretty much machine dependant
> JAMES-3775 Fasten Rspamd test suite

- server/protocols/protocols-imap4/src/test/resources/imapSSL.xml
Not doing so means port conflicts
CF https://ci-builds.apache.org/job/james/job/ApacheJames/job/PR-1142/1/
> [BUILD] SslConcurrentConnections should use a random port

- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/AttachmentLoader.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageDAO.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageDAOV3.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageDAOTest.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageDAOV3Test.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageIdMapperTest.java
- mailbox/scanning-search/src/test/java/org/apache/james/mailbox/store/search/SimpleMessageSearchIndexTest.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/BatchSizes.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/FetchGroupConverter.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/MessageMapper.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/BatchSizesTest.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/FetchGroupConverterTest.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/MailboxMessageAssertTest.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/MessageAssert.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/MessageIdMapperTest.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/MessageMapperTest.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/MessageWithAttachmentMapperTest.java
- server/container/guice/cassandra/src/main/java/org/apache/james/modules/mailbox/CassandraSessionModule.java
This value is unused and creates confusion. If body is accessed,
headers are accessed too, and accessing headers is cheap.
See https://github.com/apache/james-project/pull/1111
> JAMES-3799 Get rid of Body FetchType

- backends-common/cassandra/src/main/java/org/apache/james/backends/cassandra/init/ClusterFactory.java
- backends-common/cassandra/src/main/java/org/apache/james/backends/cassandra/init/KeyspaceFactory.java
- backends-common/cassandra/src/test/java/org/apache/james/backends/cassandra/CassandraWaitStrategy.java
- backends-common/cassandra/src/test/java/org/apache/james/backends/cassandra/DockerCassandra.java
- backends-common/cassandra/src/test/java/org/apache/james/backends/cassandra/init/SessionWithInitializedTablesFactoryTest.java
- server/container/guice/cassandra/src/main/java/org/apache/james/modules/mailbox/CassandraCacheSessionModule.java
- server/container/guice/cassandra/src/main/java/org/apache/james/modules/mailbox/CassandraSessionModule.java
20% speed up measured locally by:
- Using a single session for all resource creation
- Closing it async
- Creating keyspaces sequentially
- Avoid creating the user twice
- Using a faster check method than container exec
> [BUILD_TIME] Slightly faster Cassandra container startup

- backends-common/opensearch/src/main/java/org/apache/james/backends/opensearch/DeleteByQueryPerformer.java
- backends-common/opensearch/src/test/java/org/apache/james/backends/opensearch/DockerOpenSearch.java
- backends-common/opensearch/src/test/java/org/apache/james/backends/opensearch/DockerOpenSearchExtension.java
- backends-common/opensearch/src/test/java/org/apache/james/backends/opensearch/OpenSearchHealthCheckConnectionTest.java
- mailbox/opensearch/src/test/java/org/apache/james/mailbox/opensearch/OpenSearchIntegrationTest.java
- mailbox/opensearch/src/test/java/org/apache/james/mailbox/opensearch/search/OpenSearchSearcherTest.java
- mailbox/plugin/quota-search-opensearch/src/test/java/org/apache/james/quota/search/opensearch/events/OpenSearchQuotaMailboxListenerTest.java
- server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/routes/MailboxesRoutesTest.java
- server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/routes/UserMailboxesRoutesTest.java
- Mount tmpfs within the containers
- Use deleteByQuery where possible to cleanup data as it is faster
Gains :
- OpenSearchIntegrationTest 3 minutes -> 88 seconds locally
> [BUILD] Fasten OpenSearch tests

- server/blob/blob-s3/src/main/java/org/apache/james/blob/objectstorage/aws/S3BlobStoreDAO.java
The S3 driver guaranties not to mutate the byte[] which is
good enough given that james don't do it either. Preventing
needless copies of MBs of large mail definitely give a nice
performance boost as well as decrease the impact of handling
very large emails...
> JAMES-3793 Prevent needless defensive copies within S3BlobStoreDAO

- third-party/rspamd/README.md
- third-party/rspamd/src/main/java/org/apache/james/rspamd/RspamdScanner.java
- third-party/rspamd/src/test/java/org/apache/james/rspamd/RspamdScannerTest.java
Now positions headers on `add header` action (which would end up moving the email in user spam box) and distinguish reject action (email not delivered).
Scores threshold are configurable on RspamD side.
> JAMES-3775 Rspamd Scanner should distinguish reject from add_header

- protocols/imap/src/main/java/org/apache/james/imap/processor/base/SelectedMailboxImpl.java
This happens for instance when an error happens before the session is
fully selected eg upon IMAP error, or partial select completion.
```
java.lang.NullPointerException: Cannot invoke "org.apache.james.events.Registration.unregister()" because the return value of "java.util.concurrent.atomic.AtomicReference.get()" is null
at org.apache.james.imap.processor.base.SelectedMailboxImpl.deselect(SelectedMailboxImpl.java:196)
at org.apache.james.imapserver.netty.NettyImapSession.closeMailbox(NettyImapSession.java:153)
at org.apache.james.imapserver.netty.NettyImapSession.selected(NettyImapSession.java:127)
at org.apache.james.imap.processor.AbstractSelectionProcessor.selectMailbox(AbstractSelectionProcessor.java:409)
at org.apache.james.imap.processor.AbstractSelectionProcessor.lambda$selectMail …
```
> JAMES-3737 Upon IMAP deselect registration.get() can be null

- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/methods/GetMailboxesMethod.java
- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/model/MailboxFactory.java
- server/protocols/jmap-draft/src/test/java/org/apache/james/jmap/draft/model/MailboxFactoryTest.java
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/MailboxFactory.scala
Before we perform a O(n2) computation to retrieve parent mailboxes ids.
Now we use a map for faster lookups, eventually reducing the
complexity to O(n).
This is significant for user with many mailboxes.
> [PERF] Improve Mailbox/get algorithm

- server/mailet/remote-delivery-integration-testing/pom.xml
`[INFO] Apache James :: Server :: Mailet :: Integration Testing SUCCESS [02:39 min]`
Instead of
`[INFO] Apache James :: Server :: Remote Delivery :: Integration Testing SUCCESS [03:30 min]`
Small win...
> [BUILD] Reuse forks in RemoteDelivery integration testing

- server/apps/cassandra-app/docker-configuration/jvm.properties
- server/apps/cassandra-app/pom.xml
- server/apps/distributed-app/docker-configuration/jvm.properties
- server/apps/distributed-app/pom.xml
- server/apps/distributed-pop3-app/docker-configuration/jvm.properties
- server/apps/distributed-pop3-app/pom.xml
- server/container/guice/common/src/main/java/org/apache/james/ExtraProperties.java
We had issues with the relative path not working with Docker and James not being able to find the file.
Overriding to absolute path should ensure it finds it in this particular case.
> JAMES-3668 Add absolute paths for extra properties file in docker image

- third-party/rspamd/src/main/java/org/apache/james/rspamd/route/FeedMessageRoute.java
- third-party/rspamd/src/main/java/org/apache/james/rspamd/task/FeedHamToRspamdTask.java
- third-party/rspamd/src/main/java/org/apache/james/rspamd/task/FeedHamToRspamdTaskAdditionalInformationDTO.java
- third-party/rspamd/src/main/java/org/apache/james/rspamd/task/FeedHamToRspamdTaskDTO.java
- third-party/rspamd/src/main/java/org/apache/james/rspamd/task/FeedSpamToRspamdTask.java
- third-party/rspamd/src/main/java/org/apache/james/rspamd/task/FeedSpamToRspamdTaskAdditionalInformationDTO.java
- third-party/rspamd/src/main/java/org/apache/james/rspamd/task/FeedSpamToRspamdTaskDTO.java
- third-party/rspamd/src/main/java/org/apache/james/rspamd/task/RunningOptions.java
- third-party/rspamd/src/test/java/org/apache/james/rspamd/route/FeedMessageRouteTest.java
- third-party/rspamd/src/test/java/org/apache/james/rspamd/task/FeedHamToRspamdTaskAdditionalInformationDTOTest.java
- third-party/rspamd/src/test/java/org/apache/james/rspamd/task/FeedHamToRspamdTaskTest.java
- third-party/rspamd/src/test/java/org/apache/james/rspamd/task/FeedSpamToRspamdTaskAdditionalInformationDTOTest.java
- third-party/rspamd/src/test/java/org/apache/james/rspamd/task/FeedSpamToRspamdTaskTest.java
- Avoid intermediate flattening of RunningOptions within additionInformations (we
were doing RunningOptions (in the task) => flat (in the additionalInformation) =>
reconstruct the RunningOptions (in the DTOs); everything is simpler by just
keeping running options everywhere in that chain.
- Tasks context/snapshot capture what changes during the task execution, we do
not need to ship running options (which are immutable) within it.
- Extract RunningOptions to a common class as it is the same between Ham / Spam
Kills 228 lines of boiler plate.
> JAMES-3755 Refactor Rspamd ham/spam routes

- pom.xml
- server/protocols/protocols-imap4/pom.xml
- server/protocols/protocols-lmtp/pom.xml
- server/protocols/protocols-pop3/pom.xml
- server/protocols/protocols-smtp/pom.xml
Disable leak detector in tests as we do not achieve good resource management in
those tests. Enable it selectively in a few relevant projects.
> JAMES-3732 Fix a typo in poms regarding the leak detector

- server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/Dequeuer.java
- server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/view/cassandra/CassandraMailQueueBrowser.java
This is mostly a cherry pick of the respective commits from JAMES-3810. The only "backport" is the use of Schedulers.elastic() instead of ReaktorUtils.BLOCKING_CALL_WRAPPER since the latter does not exist yet in 3.7.x.
Note: Merging this should probably wait until the pending 3.7.1 release is decided.
> JAMES-3810: Backport of fixes to 3.7.x

- third-party/rspamd/src/main/java/org/apache/james/rspamd/RspamdScanner.java
- third-party/rspamd/src/test/java/org/apache/james/rspamd/RspamdScannerTest.java
It should advertise virus, rejected processor when specified.
(given that I introduced the requiredProcessingState validation with Rspamd in mind, it's well time to make Rspamd leverage it)
> JAMES-3755 RspamdScanner should specify requiredProcessingState

- core/src/main/java/org/apache/james/core/Username.java
- core/src/test/java/org/apache/james/core/UsernameTest.java
- mailbox/api/src/main/java/org/apache/james/mailbox/model/MailboxPath.java
- mailbox/api/src/test/java/org/apache/james/mailbox/model/MailboxPathTest.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMailboxManager.java
- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/methods/GetMailboxesMethod.java
Building maps to retrieve parentIds and know if a mailbox has children is expensive and can be further optimised. Also it is beneficial to switch such operations to a thread dedicated to computations.
Cc @Arsnael
> [PERF] Improve Mailbox/get performance when thousands of mailboxes

- server/apps/distributed-app/docs/modules/ROOT/pages/operate/webadmin.adoc
- src/site/markdown/server/manage-webadmin.md
`action` should be `reDeliver` instead of `redeliver`.
> [DOCUMENTATION] Correct Event Dead Letter webadmin routes documentation

- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageIdDAO.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageIdToImapUidDAO.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageIdDAOTest.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageIdToImapUidDAOTest.java
This NPE likely comes from badly applied [Rework message denormalization migration](https://github.com/apache/james-project/blob/master/upgrade-instructions.md#rework-message-denormalization) which creates in `imapUidTable` and `messageIdTable` a few rows with null `internalDate`, `bodyStartOctet`, `fullContentOctets` and `headerContent`. Now the Cassandra driver 4 code change just triggers that NPE (can not convert a null to Date).
Checked: `bodyStartOctet`, `size`, `headerContent` should be already good from NPE.
> JAMES-3815 Handle possible null values in imapUidTable and messageIdTable

- third-party/rspamd/README.md
- third-party/rspamd/src/main/java/org/apache/james/rspamd/route/FeedMessageRoute.java
- third-party/rspamd/src/main/java/org/apache/james/rspamd/task/FeedHamToRspamdTask.java
- third-party/rspamd/src/main/java/org/apache/james/rspamd/task/FeedHamToRspamdTaskDTO.java
- third-party/rspamd/src/main/java/org/apache/james/rspamd/task/FeedSpamToRspamdTask.java
- third-party/rspamd/src/main/java/org/apache/james/rspamd/task/FeedSpamToRspamdTaskDTO.java
- third-party/rspamd/src/main/java/org/apache/james/rspamd/task/GetMailboxMessagesService.java
- third-party/rspamd/src/main/java/org/apache/james/rspamd/task/RunningOptions.java
- third-party/rspamd/src/test/java/org/apache/james/rspamd/route/FeedMessageRouteTest.java
- third-party/rspamd/src/test/java/org/apache/james/rspamd/task/FeedHamToRspamdTaskAdditionalInformationDTOTest.java
- third-party/rspamd/src/test/java/org/apache/james/rspamd/task/FeedHamToRspamdTaskTest.java
- third-party/rspamd/src/test/java/org/apache/james/rspamd/task/FeedSpamToRspamdTaskAdditionalInformationDTOTest.java
- third-party/rspamd/src/test/java/org/apache/james/rspamd/task/FeedSpamToRspamdTaskTest.java
- third-party/rspamd/src/test/resources/json/feedHamClassifiedAsHam.additionalInformation.json
- third-party/rspamd/src/test/resources/json/feedSpamClassifiedAsHam.additionalInformation.json
This allows for instance reporting messages manually reported by the user to the
Spam mailbox with re-reporting messages already classified as Spam by Rspamd,
avoiding creating a positive retro-action loop, and only reporting relevant messages.
Similar for Ham reporting.
> JAMES-3755 Add a classifiedAsSpam parameter to Rspamd routes

- server/protocols/jwt/src/main/java/org/apache/james/jwt/OidcJwtTokenVerifier.java
- Avoid deprecated methods
- Remove needless method parameter, type inference is enough
> [REFACTORING] Cleanup OidcJwtTokenVerifier

- server/apps/jpa-app/src/main/resources/META-INF/persistence.xml
- server/apps/jpa-smtp-app/src/main/resources/META-INF/persistence.xml
- server/apps/jpa-smtp-app/src/test/java/org/apache/james/JPAJamesServerTest.java
- server/apps/spring-app/src/main/resources/META-INF/persistence.xml
- server/data/data-file/src/main/java/org/apache/james/mailrepository/file/FileMailRepository.java
- server/data/data-jdbc/src/main/java/org/apache/james/mailrepository/jdbc/JDBCMailRepository.java
- server/data/data-jpa/pom.xml
- server/data/data-jpa/src/main/java/org/apache/james/mailrepository/jpa/JPAMailRepository.java
- server/data/data-jpa/src/main/java/org/apache/james/mailrepository/jpa/JPAMailRepositoryUrlStore.java
- server/data/data-jpa/src/main/java/org/apache/james/mailrepository/jpa/MimeMessageJPASource.java
- server/data/data-jpa/src/main/java/org/apache/james/mailrepository/jpa/model/JPAMail.java
- server/data/data-jpa/src/main/java/org/apache/james/mailrepository/jpa/model/JPAUrl.java
- server/data/data-jpa/src/main/resources/META-INF/persistence.xml
- server/data/data-jpa/src/test/java/org/apache/james/jpa/healthcheck/JPAHealthCheckTest.java
- server/data/data-jpa/src/test/java/org/apache/james/mailrepository/jpa/JPAMailRepositoryTest.java
- server/data/data-jpa/src/test/java/org/apache/james/mailrepository/jpa/JPAMailRepositoryUrlStoreExtension.java
- server/mailrepository/mailrepository-api/src/test/java/org/apache/james/mailrepository/MailRepositoryContract.java
Here is an initial implementation of a JPAMailStore, which will hopefully suffice to make the JPA app work fully with a database, a big relief for everyone that migrated from 2.3.x and was shocked to discover they are forced to use file repositories ;-)
This is an initial implementation that is hopefully good enough to be useful, but still has room for improvement. After merging others can help incrementally improve on it as necessary. Specifically:
- It passes MailRepositoryContract as suggested in JAMES-2656, except for two disabled tests (which are both also disabled in JDBCMailRepository, so it's no worse than that):
- mailRepositoriesShouldBeURLIsolated seems to fail only because the mock Mail has no lastUpdated and state fields set - I'm not sure if these fields are supposed to be …
> JAMES-2656 - Add initial JPAMailRepository implementation

- mailbox/tools/quota-recompute/src/main/java/org/apache/james/mailbox/quota/task/RecomputeCurrentQuotasService.java
- server/data/data-api/src/main/java/org/apache/james/user/api/UsersRepository.java
- server/data/data-cassandra/src/main/java/org/apache/james/user/cassandra/CassandraUsersDAO.java
- server/data/data-library/src/main/java/org/apache/james/user/lib/UsersDAO.java
- server/data/data-library/src/main/java/org/apache/james/user/lib/UsersRepositoryImpl.java
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/RandomStoring.java
- server/protocols/webadmin/webadmin-jmap/src/main/java/org/apache/james/webadmin/data/jmap/EmailQueryViewPopulator.java
- server/protocols/webadmin/webadmin-jmap/src/main/java/org/apache/james/webadmin/data/jmap/MessageFastViewProjectionCorrector.java
- server/protocols/webadmin/webadmin-mailbox/src/main/java/org/apache/james/webadmin/service/ExpireMailboxService.java
- server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/service/ExpireMailboxServiceTest.java
- third-party/rspamd/src/main/java/org/apache/james/rspamd/task/FeedHamToRspamdTask.java
- third-party/rspamd/src/main/java/org/apache/james/rspamd/task/FeedSpamToRspamdTask.java
- third-party/rspamd/src/main/java/org/apache/james/rspamd/task/GetMailboxMessagesService.java
It is very error prone to plug blocking components into a reactive pipeline. Allowing implementations to pass a reactive version reduces this risk.
> [REFACTORING] List users the reactive way

- server/queue/queue-pulsar/src/main/scala/org/apache/james/queue/pulsar/FilterStage.scala
- server/queue/queue-pulsar/src/main/scala/org/apache/james/queue/pulsar/PulsarMailQueue.scala
- server/queue/queue-pulsar/src/test/java/org/apache/james/queue/pulsar/PulsarMailQueueTest.java
Previously to this patch, filter registration was going through a pulsar delivery even for non-distributed James. This meant tests that verify the filtering behavior had to wait for the message to be consumed back from the queue.
This lead us to introduce an artificial wait to ensure that the filter was correctly registered. Unfortunately, the delay was not always enough, especially on the CI which lead to flaky tests.
I propose to add a small optmization which registers the filter with the receiving instance synchronously before publishing it to pulsar.
This way, the wait time to filter  registration can be much smaller.
Because the filter stage uses a set, adding the same filter multiple times should have a negligible impact on performances.
There was already a test in place that …
> [JAMES-3696] makes PulsarMailQueue tests more stable

- backends-common/rabbitmq/src/main/java/org/apache/james/backends/rabbitmq/RabbitMQConfiguration.java
- event-bus/distributed/src/main/java/org/apache/james/events/GroupRegistration.java
- event-bus/distributed/src/main/java/org/apache/james/events/GroupRegistrationHandler.java
- event-bus/distributed/src/main/java/org/apache/james/events/KeyReconnectionHandler.java
- event-bus/distributed/src/main/java/org/apache/james/events/KeyRegistrationHandler.java
- server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/RabbitMQMailQueueFactory.java
We can't create a quorum queue and mark it as auto-delete, RabbitMQ does not allow it. So we keep the jmap event bus notification queues as classic for now.
Just did something quick to test... Probably can do something cleaner?
> JAMES-3604 Fix issue when creating quorum rabbitmq queues

- server/task/task-distributed/src/main/java/org/apache/james/task/eventsourcing/distributed/RabbitMQWorkQueue.java
- server/task/task-memory/src/main/java/org/apache/james/task/SerialTaskManagerWorker.java
Today when I shut down James, the associated tasks runs forever.
With this change James attempts to cancel currently running task upon shutdown.
> JAMES-3825 Cancel tasks upon graceful shutdown

- mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/MailboxMappingFactory.java
- mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/json/EMailer.java
- mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/json/HeaderCollection.java
- mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/json/JsonMessageConstants.java
- mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/query/CriterionConverter.java
- mailbox/opensearch/src/test/java/org/apache/james/mailbox/opensearch/OpenSearchIntegrationTest.java
- mailbox/opensearch/src/test/java/org/apache/james/mailbox/opensearch/json/EMailersTest.java
- mailbox/opensearch/src/test/java/org/apache/james/mailbox/opensearch/json/HeaderCollectionTest.java
- mailbox/opensearch/src/test/resources/eml/inlined-mixed.json
- mailbox/store/src/test/resources/eml/emailWithNonIndexableAttachmentWithoutAttachment.json
- mailbox/store/src/test/resources/eml/htmlMail.json
- mailbox/store/src/test/resources/eml/invalidCharset.json
- mailbox/store/src/test/resources/eml/mail.json
- mailbox/store/src/test/resources/eml/nonTextual.json
- mailbox/store/src/test/resources/eml/pgpSignedMail.json
- mailbox/store/src/test/resources/eml/recursiveMail.json
- mailbox/store/src/test/resources/eml/recursiveMailWithoutAttachments.json
- mailbox/store/src/test/resources/eml/spamMail.json
Given an email with `bob@domain.tld`
-> `bob@domain.tld` matches
-> `bob` (localpart) matches
-> `domain.tld` (domain) matches
-> `domain` (part of the domain) do not match. (and it should).
I think we could easily propose a better 'search experience' by improving indexing and searches for domains.
Traps to avoid:
Given `bob@domain.tld` search we should not return results of other addresses of `domain.tld` domain.
Given `domain.tld` search we should not return unrelated search results from the `tld` top-domain.
migration strategy will be aturaly covered upon the OpenSearch migration.
> JAMES-3827 Improve indexing of email address domains

- mailet/amqp/src/main/java/org/apache/james/transport/mailets/AmqpForwardAttribute.java
- mailet/amqp/src/test/java/org/apache/james/transport/mailets/AmqpForwardAttributeTest.java
- mailet/api/src/main/java/org/apache/mailet/AttributeValue.java
- mailet/api/src/main/java/org/apache/mailet/Serializer.java
- mailet/api/src/test/java/org/apache/mailet/AttributeValueTest.java
- mailet/crypto/src/main/java/org/apache/james/transport/mailets/SMIMECheckSignature.java
- mailet/crypto/src/main/java/org/apache/james/transport/mailets/SMIMEDecrypt.java
- mailet/icalendar/src/main/java/org/apache/james/transport/mailets/ICALToHeader.java
- mailet/icalendar/src/main/java/org/apache/james/transport/mailets/ICALToJsonAttribute.java
- mailet/icalendar/src/main/java/org/apache/james/transport/mailets/ICalendarParser.java
- mailet/icalendar/src/test/java/org/apache/james/transport/mailets/ICALToHeadersTest.java
- mailet/icalendar/src/test/java/org/apache/james/transport/mailets/ICALToJsonAttributeTest.java
- mailet/icalendar/src/test/java/org/apache/james/transport/mailets/ICalendarParserTest.java
- mailet/standard/src/main/java/org/apache/james/transport/mailets/MailAttributesListToMimeHeaders.java
- mailet/standard/src/main/java/org/apache/james/transport/mailets/MimeDecodingMailet.java
- mailet/standard/src/main/java/org/apache/james/transport/mailets/RecoverAttachment.java
- mailet/standard/src/main/java/org/apache/james/transport/mailets/StripAttachment.java
- mailet/standard/src/test/java/org/apache/james/transport/mailets/MailAttributesListToMimeHeadersTest.java
- mailet/standard/src/test/java/org/apache/james/transport/mailets/MimeDecodingMailetTest.java
- mailet/standard/src/test/java/org/apache/james/transport/mailets/StripAttachmentTest.java
Prevent:
```
exception	java.lang.ClassCastException: class [B cannot be cast to class org.apache.mailet.AttributeValue ([B is in module java.base of loader 'bootstrap'; org.apache.mailet.AttributeValue is in unnamed module of loader 'app')
at org.apache.mailet.Serializer$MapSerializer.lambda$serialize$0(Serializer.java:507)
at com.google.common.collect.CollectCollectors.lambda$toImmutableMap$6(CollectCollectors.java:185)
at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(Unknown Source)
at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
at …
```
> JAMES-3828 Rework AttibuteValue duplication; reject invalid values early

- backends-common/rabbitmq/src/main/java/org/apache/james/backends/rabbitmq/Constants.java
- backends-common/rabbitmq/src/main/java/org/apache/james/backends/rabbitmq/RabbitMQConfiguration.java
- event-bus/distributed/src/main/java/org/apache/james/events/GroupRegistration.java
- event-bus/distributed/src/main/java/org/apache/james/events/GroupRegistrationHandler.java
- event-bus/distributed/src/main/java/org/apache/james/events/KeyReconnectionHandler.java
- event-bus/distributed/src/main/java/org/apache/james/events/KeyRegistrationHandler.java
- server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/RabbitMQMailQueueFactory.java
Performance tests showed that there was some serious performance issues when having quorum queues for event notifications as well with IMAP.
> JAMES-3604 Allow quorum queues only on mail queues

- mpt/impl/smtp/cassandra-pulsar/src/test/java/org/apache/james/mpt/smtp/CassandraPulsarForwardSmtpTest.java
- mpt/impl/smtp/cassandra-pulsar/src/test/java/org/apache/james/mpt/smtp/CassandraPulsarSmtpStarttlsCommandTest.java
- server/queue/queue-pulsar/src/test/java/org/apache/james/queue/pulsar/PulsarMailQueueFactoryTest.java
- server/queue/queue-pulsar/src/test/java/org/apache/james/queue/pulsar/PulsarMailQueueTest.java
Failed in 4 builds out of 7.
```
com.github.fge.lambdas.ThrownByLambdaException: org.apache.pulsar.client.admin.PulsarAdminException$NotFoundException: Tenant does not exist
Caused by: org.apache.pulsar.client.admin.PulsarAdminException$NotFoundException: Tenant does not exist
Caused by: org.apache.pulsar.shade.javax.ws.rs.NotFoundException: HTTP 404 Tenant does not exist
```
> [BUILD] Tag Pulsar related work as unstable

- server/data/data-jdbc/pom.xml
- server/data/data-jdbc/src/main/java/org/apache/james/mailrepository/jdbc/JDBCMailRepository.java
- server/data/data-jdbc/src/main/java/org/apache/james/mailrepository/jdbc/MessageInputStream.java
- server/data/data-jdbc/src/main/java/org/apache/james/mailrepository/jdbc/MimeMessageJDBCSource.java
- server/data/data-jdbc/src/test/java/org/apache/james/mailrepository/jdbc/JDBCMailRepositoryTest.java
Will be dropped in 3.9.0.
See https://www.mail-archive.com/server-dev@james.apache.org/msg72460.html
> [DEPRECATION] Deprecate JDBCMailRepository

- server/apps/distributed-app/docs/modules/ROOT/partials/RemoteDelivery.adoc
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/RemoteDelivery.java
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/remote/delivery/MailDelivrerToHost.java
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/remote/delivery/RemoteDeliveryConfiguration.java
- server/mailet/mailets/src/test/java/org/apache/james/transport/mailets/remote/delivery/RemoteDeliveryConfigurationTest.java
- upgrade-instructions.md
Using host names instead of IP addresses for RemoteDelivery allows enabling of TLS host name verification in security sensitive deployments, via Java Mail property mail.smtp(s).ssl.checkserveridentity in the mailet configuration.
I do not see any disadvantages with this change, but the intricacies of server lookup are complex, and I may not see the full picture. Any reasons why this would be a problem?
> JAMES-3832  Support TLS host name verification

- server/apps/distributed-app/docs/modules/ROOT/partials/RemoteDelivery.adoc
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/RemoteDelivery.java
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/remote/delivery/MailDelivrerToHost.java
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/remote/delivery/RemoteDeliveryConfiguration.java
- server/mailet/mailets/src/test/java/org/apache/james/transport/mailets/remote/delivery/RemoteDeliveryConfigurationTest.java
- upgrade-instructions.md
RemoteDelivery will do TLS host name verification when contacting remote mail servers.
The RemoteDelivery mailet configuration gets a new property verifyServerIdentity for this, enabled by default.
This is mostly a cherry-pick from master, I just had to adjust the upgrade-instructions.md.
> JAMES-3832 Enable TLS host name verification (3.7.x)

- metrics/metrics-dropwizard/src/main/java/org/apache/james/metrics/dropwizard/DropWizardGaugeRegistry.java
Otherwise measurements are still performed despite underlying components being stopped.
> [FIX] Unregister gauge upon shutdown [3.7.x]

- metrics/metrics-dropwizard/src/main/java/org/apache/james/metrics/dropwizard/DropWizardGaugeRegistry.java
Otherwise measurements are still performed despite underlying components being stopped.
> [FIX] Unregister gauge upon shutdown

- third-party/rspamd/README.md
- third-party/rspamd/sample-configuration/mailetcontainer_distributed.xml
- third-party/rspamd/sample-configuration/mailetcontainer_memory.xml
`RspamdScanner` mailet depends on third-party service which could fail when they are unavailable. We should ignore errors of the `RspamdScanner`.
> JAMES-3775 Ensure ignoring error of the RspamdScanner mailet

- backends-common/pulsar/src/test/java/org/apache/james/backends/pulsar/DockerPulsarExtension.java
- server/apps/scaling-pulsar-smtp/src/test/java/org/apache/james/PulsarExtension.java
supercedes https://github.com/apache/james-project/pull/1236
without this patch repeat run of pulsar mailqueue sometimes fails within a dozen runs with a missing `public` tenant. With the patch I couldn't make the run fail on my laptop (stopped a bit over 40 runs)
> [JAMES-3805] fixes more flaky pulsar tests

- mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/json/EMailer.java
- mailbox/opensearch/src/test/java/org/apache/james/mailbox/opensearch/json/EMailerTest.java
```
java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because "s" is nul
at org.apache.james.mailbox.elasticsearch.json.EMailer.removeTopDomain(EMailer.java:42)
at org.apache.james.mailbox.elasticsearch.json.EMailer.<init>(EMailer.java:38)
at org.apache.james.mailbox.elasticsearch.json.HeaderCollection$Builder.lambda$manageAddressField$0(HeaderCollection.java:145)
```
> JAMES-3827 Support From fields without domain parts in the email address

- server/apps/distributed-app/docs/modules/ROOT/pages/configure/spam.adoc
- server/mailet/rate-limiter-redis/src/test/java/org/apache/james/rate/limiter/DockerRedis.java
- third-party/rspamd/README.md
- third-party/rspamd/docker-compose-distributed.yml
- third-party/rspamd/docker-compose.yml
- third-party/rspamd/pom.xml
- third-party/rspamd/sample-configuration/rspamd.properties
- third-party/rspamd/sample-configuration/statistic.conf
- third-party/rspamd/src/main/java/org/apache/james/rspamd/RspamdListener.java
- third-party/rspamd/src/main/java/org/apache/james/rspamd/RspamdScanner.java
- third-party/rspamd/src/main/java/org/apache/james/rspamd/client/RspamdClientConfiguration.java
- third-party/rspamd/src/main/java/org/apache/james/rspamd/client/RspamdHttpClient.java
- third-party/rspamd/src/main/java/org/apache/james/rspamd/module/RspamdTaskExtensionModule.java
- third-party/rspamd/src/main/java/org/apache/james/rspamd/route/FeedMessageRoute.java
- third-party/rspamd/src/main/java/org/apache/james/rspamd/task/FeedHamToRspamdTask.java
- third-party/rspamd/src/main/java/org/apache/james/rspamd/task/FeedHamToRspamdTaskDTO.java
- third-party/rspamd/src/main/java/org/apache/james/rspamd/task/FeedSpamToRspamdTask.java
- third-party/rspamd/src/main/java/org/apache/james/rspamd/task/FeedSpamToRspamdTaskDTO.java
- third-party/rspamd/src/main/java/org/apache/james/rspamd/task/GetMailboxMessagesService.java
- third-party/rspamd/src/test/java/org/apache/james/rspamd/DockerClamAV.java
- third-party/rspamd/src/test/java/org/apache/james/rspamd/DockerRspamd.java
- third-party/rspamd/src/test/java/org/apache/james/rspamd/RspamdListenerTest.java
- third-party/rspamd/src/test/java/org/apache/james/rspamd/RspamdScannerTest.java
- third-party/rspamd/src/test/java/org/apache/james/rspamd/client/RspamdHttpClientTest.java
- third-party/rspamd/src/test/java/org/apache/james/rspamd/route/FeedMessageRouteTest.java
- third-party/rspamd/src/test/java/org/apache/james/rspamd/task/FeedHamToRspamdTaskTest.java
- third-party/rspamd/src/test/java/org/apache/james/rspamd/task/FeedSpamToRspamdTaskTest.java
- third-party/rspamd/src/test/resources/rspamd-config/statistic.conf
Rebase on master, contribute my work on fixup commits.
Not a code or Rspamd issue, just a Bayes configuration issue.
Result:
```java
Bob spam score before: 20.825
Alice spam score before: 20.825
Bob spam score after: 25.925
Alice spam score after: 20.825
Bob ham score before: 0.99
Alice ham score before: 0.99
Bob ham score after: 0.374475
Alice ham score after: 0.99
```
We have the option to enable per-user in Rspamd mailet but not for listener and tasks (always call use per-user bayes). Maybe we should have a configuration option for them?
> JAMES-3775 Rspamd per user reporting

- src/site/xdoc/server/release-notes.xml
For 3.7.0 it should read "Released March 202**2**" rather than "Released March 2021".
> Fix release year for 3.7.0

- server/task/task-distributed/src/test/java/org/apache/james/task/eventsourcing/distributed/DistributedTaskManagerTest.java
- server/task/task-memory/pom.xml
- server/task/task-memory/src/main/java/org/apache/james/task/SerialTaskManagerWorker.java
- server/task/task-memory/src/test/java/org/apache/james/task/SerialTaskManagerWorkerTest.java
Fix: The task has not been canceled before the shutdown of the server.
Related:
- https://github.com/apache/james-project/pull/1214
> JAMES-3825 Cancel tasks upon graceful shutdown - waiting to the cancelled listener is completed

- protocols/api/src/main/java/org/apache/james/protocols/api/ProtocolSession.java
- protocols/api/src/main/java/org/apache/james/protocols/api/ProtocolSessionImpl.java
- protocols/api/src/main/java/org/apache/james/protocols/api/ProtocolTransport.java
- protocols/api/src/test/java/org/apache/james/protocols/api/AbstractProtocolTransportTest.java
- protocols/imap/src/main/java/org/apache/james/imap/api/process/ImapSession.java
- protocols/imap/src/main/java/org/apache/james/imap/encode/FakeImapSession.java
- protocols/netty/src/main/java/org/apache/james/protocols/netty/NettyProtocolTransport.java
- protocols/smtp/src/test/java/org/apache/james/protocols/smtp/utils/BaseFakeSMTPSession.java
- server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/NettyImapSession.java
James supports SMTPS and StartTLS, but currently has no way to programmatically access the resulting SSLSession from SMTP Hooks, POP3 Command Handlers etc. I propose to make the SSLSession accessible through the ProtocolSession.
This way, hooks/handlers can examine the SSL/TLS parameters negotiated with the currently connected client. They can check e.g. TLS version and selected cipher suite to evaluate the security level of the connection. With certificate based client authentication enabled, they can get the provided client certificate, e.g. to check against a permission list. Or a JamesMessageHook could attach it to the Mail object, so this information becomes even available to Mailets after spooling.
> JAMES-3842 Access SSLSession from Hooks and Handlers

- server/mailet/mailets/src/main/java/org/apache/james/transport/util/MimeMessageBodyGenerator.java
- server/mailet/mailets/src/test/java/org/apache/james/transport/util/MimeMessageBodyGeneratorTest.java
I noticed that vacation notices generated by James look somewhat strange in Thunderbird, and probably other mail clients as well: It shows both the HTML and plain text variant of the message (see attached screenshot). This is likely caused by the Content-Type of multipart/mixed.
I suggest we change this to multipart/alternative instead, so a HTML capable client will only show the HTML part, while a text-only client will show the text part instead.
I also noticed that, after setting an HTML message and an empty text message by accident, the generated text part is naturally empty. This is OK for HTML-capable clients, but in the worst case a text-only client would show just an empty mail, even though there is content in the HTML part.
I suggest we make the vacation notice generation more …
> JAMES-3846 Improve vacation notice appearance

- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/VacationMailet.java
- server/mailet/mailets/src/test/java/org/apache/james/transport/mailets/VacationMailetTest.java
- server/mailet/mock-smtp-server/pom.xml
- server/mailet/mock-smtp-server/src/main/java/org/apache/james/mock/smtp/server/MockMessageHandler.java
- server/mailet/mock-smtp-server/src/main/java/org/apache/james/mock/smtp/server/model/Mail.java
- server/mailet/mock-smtp-server/src/test/java/org/apache/james/mock/smtp/server/ConfigurationClientTest.java
- server/protocols/jmap-draft-integration-testing/jmap-draft-integration-testing-common/pom.xml
- server/protocols/jmap-draft-integration-testing/jmap-draft-integration-testing-common/src/test/java/org/apache/james/jmap/MockSmtpTestRule.java
- server/protocols/jmap-draft-integration-testing/jmap-draft-integration-testing-common/src/test/java/org/apache/james/jmap/VacationRelayIntegrationTest.java
- server/testing/src/main/java/org/apache/james/util/docker/Images.java
https://github.com/apache/james-project/pull/1278 without the custom config hack to turn off the nullSender, and without turning off the integration tests.
CC @ottoka
> JAMES-3843 VacationMailet should use null sender

- protocols/imap/src/main/java/org/apache/james/imap/decode/FetchPartPathDecoder.java
- protocols/imap/src/test/java/org/apache/james/imap/decode/FetchPartPathDecoderTest.java
Kill recursion when dealing with header names.
> [FIX] Prevent stack overflow in FETCH command

- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EmailSetMethodContract.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/EmailSet.scala
To quote the spec:
https://jmap.io/spec-mail.html#emailset
```
The server MAY also choose to set additional headers. If not included, the server MUST generate and set a Message-ID header
field in conformance with [@!RFC5322], Section 3.6.4, and a Date header field in conformance with Section 3.6.1.
```
> [JMAP] Email/set create should add missing mimeMessageId and sentAt

- examples/proxy-smtp/README.md
- examples/proxy-smtp/docker-compose.yml
- examples/proxy-smtp/haproxy.cfg
- examples/proxy-smtp/imapserver.xml
- examples/proxy-smtp/smtpserver.xml
- protocols/netty/src/main/java/org/apache/james/protocols/netty/AbstractSSLAwareChannelPipelineFactory.java
- server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/IMAPServer.java
Given James is responsible of TLS termination, PROXY protocol should be handled first, before SSL.
Add examples for TLS + PROXY support.
Cc @ouvtam
> JAMES-3788 Fix PROXY protocol support with TLS

- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/remote/delivery/MailDelivrerToHost.java
I noticed that sometimes RemoteDelivery opens a connection using a fully qualified hostname that ends with a trailing dot, like "mail.example.org." I believe James may get that from MX resolving, since afaik DNS servers may do this to indicate an absolute FQDN vs. a relative one. This is not an issue when establishing a connection, but will break TLS hostname verification, since the CN and SubjectAltNames in server certificates never use trailing dots.
Consequently, RemoteDelivery should strip a trailing dot from the hostname before connecting.
Note that this is the minimal fix for the verification issue; log messages related to remote delivery will still show the hostname with a trailing dot. I am not sure if this is intended behavior, i.e. to see exactly what James got from DNS …
> JAMES-3851 TLS host name verification should handle trailing dot

- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/remote/delivery/MailDelivrerToHost.java
Straight cherry-pick from master to fix the issue in 3.7.x as well.
> JAMES-3851 TLS host name verification should handle trailing dot (3.7.x)

- mpt/impl/imap-mailbox/core/src/main/java/org/apache/james/mpt/imapmailbox/suite/QuotaTest.java
- mpt/impl/imap-mailbox/core/src/main/resources/org/apache/james/imap/scripts/Quota.test
- mpt/impl/imap-mailbox/core/src/main/resources/org/apache/james/imap/scripts/Status.test
- protocols/imap/src/main/java/org/apache/james/imap/api/ImapConstants.java
- protocols/imap/src/main/java/org/apache/james/imap/api/display/HumanReadableText.java
- protocols/imap/src/main/java/org/apache/james/imap/api/message/StatusDataItems.java
- protocols/imap/src/main/java/org/apache/james/imap/api/message/response/StatusResponse.java
- protocols/imap/src/main/java/org/apache/james/imap/decode/parser/StatusCommandParser.java
- protocols/imap/src/main/java/org/apache/james/imap/encode/MailboxStatusResponseEncoder.java
- protocols/imap/src/main/java/org/apache/james/imap/message/response/MailboxStatusResponse.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/AppendProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/GetQuotaRootProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/StatusProcessor.java
- protocols/imap/src/test/java/org/apache/james/imap/encode/MailboxStatusResponseEncoderTest.java
- server/apps/distributed-app/docs/modules/ROOT/pages/architecture/implemented-standards.adoc
- src/site/xdoc/protocols/imap4.xml
- Adds QUOTA=RES-MESSAGE and QUOTA=RES-STORAGE capabilities
- Adds support for DELETED status item (also mandated by RFC-9051 IMAP4Rev2)
- Adds support for DELETED_STORAGE status item
- Adds the optional OVERQUOTA response code for append commands
- Document support for this specification
> JAMES-3856 RFC-9208 Implement IMAP QUOTA revision

- server/blob/blob-s3/src/main/java/org/apache/james/blob/objectstorage/aws/S3BlobStoreDAO.java
- Retrieve the size without needing to recompute it
- Reduce the chunking from 1MB to 100KB
- No need to allocate more that the stream size
> [PERF] Reduce memory allocation upon S3BlobStoreDAO::save(InputStream)

- mailbox/api/src/main/java/org/apache/james/mailbox/MessageManager.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMessageManager.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/AbstractSelectionProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/ExpungeProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/GetACLProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/SearchProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/StatusProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/StoreProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/fetch/FetchProcessor.java
- protocols/imap/src/test/java/org/apache/james/imap/processor/GetACLProcessorTest.java
- protocols/imap/src/test/java/org/apache/james/imap/processor/ListRightsProcessorTest.java
- Simpler code
- Allows saving on some uneeded Cassandra queries, especially for STATUS
> [REFACTORING] More flexible fetch groups for Mailbox metadata

- backends-common/rabbitmq/src/main/java/org/apache/james/backends/rabbitmq/RabbitMQConfiguration.java
- backends-common/rabbitmq/src/test/java/org/apache/james/backends/rabbitmq/RabbitMQConfigurationTest.java
- server/apps/distributed-app/docs/modules/ROOT/pages/configure/rabbitmq.adoc
- server/apps/distributed-app/sample-configuration/rabbitmq.properties
- server/apps/distributed-pop3-app/sample-configuration/rabbitmq.properties
- src/site/xdoc/server/config-rabbitmq.xml
vhost parameter should only be used in special cases with bad formatted URIs (like with '_' characters) as a workaround. For most of the time, adding the vhost in the uri is enough!
> JAMES-3864 Refactor vhost management

- server/apps/memory-app/src/test/java/org/apache/james/StartSequenceTest.java
- server/container/guice/common/src/main/java/org/apache/james/modules/StartablesModule.java
- server/container/guice/common/src/main/java/org/apache/james/utils/InitializationOperations.java
- server/container/guice/common/src/main/java/org/apache/james/utils/Startables.java
- server/container/guice/common/src/test/java/org/apache/james/modules/InitializationOperationsTest.java
- server/container/guice/configuration/src/main/java/org/apache/james/utils/InitializationOperation.java
- server/container/guice/configuration/src/main/java/org/apache/james/utils/InitilizationOperationBuilder.java
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/ToSenderFolder.java
- ToSenderFolder should call `.block`
- Correct the start sequence for provisionned guice resources.
> Backport a few more bugs [3.7.x]

- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageIdMapperRelaxedConsistencyTest.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageIdMapperTest.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageMapperRelaxedConsistencyTest.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageMapperTest.java
Recently, sometime we observed `java.lang.IllegalStateException: Session is closed` for Cassandra mapper tests in CI failed builds.
Git bisect issued commit: https://github.com/apache/james-project/commit/746ca874aecfb5ea77679a081a32999471bbbce7
Currently, for each test, `mapperProvider` is created before BeforeEachCallBack and BeforeEach lead to it sometime points to a closed CqlSession (when max tests e.g 500 played then Cassandra container restart -> close the old session and opens a new session). 
Current flow for each mapper test: 
create new final `mapperProvider` (refer to to-be-closed session) -> BeforeEachCallback (restarting Cassandra leads to closing the old session and creating a new session) -> BeforeEach (return the `mapperProvider`refers to closed session).
We need to let …
> [BUILD] Fix unstable cassandra mapper tests

- mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/query/CriterionConverter.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/search/AbstractMessageSearchIndexTest.java
We did not align the specs for BEFORE, ON, SINCE ... commands for a few edge cases.
https://www.rfc-editor.org/rfc/rfc9051.html#name-search-command
With this change, this is how our internal API for date searching should work (Opensearch/Elasticsearch):
e.g User searches `SINCE <date>`, we union ON and AFTER parts at IMAP layer => align the spec `Messages whose internal date (disregarding time and timezone) is within or later than the specified date.`
The same alignment is for other search date commands.
> JAMES-3754 Date searching should align IMAP4rev2 specifications

- upgrade-instructions.md
"Note how all text within the single quotes is preserved. No interpolation is done, but this means we also can’t, under any circumstances, have a single quote directly within the single quote."
We need to interpolate the single quote in the JSON message.
> JAMES-3754 Fix saveDate OpenSearch upgrade-instructions.md

- backends-common/cassandra/src/main/java/org/apache/james/backends/cassandra/init/CassandraTableManager.java
- backends-common/cassandra/src/test/java/org/apache/james/backends/cassandra/CassandraCluster.java
- backends-common/cassandra/src/test/java/org/apache/james/backends/cassandra/TestingSessionTest.java
- backends-common/cassandra/src/test/java/org/apache/james/backends/cassandra/init/SessionWithInitializedTablesFactoryTest.java
- backends-common/cassandra/src/test/java/org/apache/james/backends/cassandra/versions/CassandraSchemaVersionDAOTest.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/CassandraMessageIdManagerSideEffectTest.java
- server/container/guice/cassandra/src/main/java/org/apache/james/server/CassandraTruncateTableTask.java
- server/protocols/webadmin-integration-test/distributed-webadmin-integration-test/src/test/java/org/apache/james/webadmin/integration/rabbitmq/RabbitMQWebAdminServerIntegrationTest.java
Apart from the first test that did create the table, follow up tests have no way to know the actual version ad thus choose the lowest. Avoiding clearing this table avoids this.
> [FIX] Avoid clearing the schemaVersion

- protocols/imap/src/main/java/org/apache/james/imap/api/process/ImapSession.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/IdleProcessor.java
- server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/ChannelImapResponseWriter.java
- server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/ImapChannelUpstreamHandler.java
- server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/ImapLineHandlerAdapter.java
- server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/NettyImapSession.java
Today each Imap response line is transmitted in a
distinct TCP packet.
This causes a lot of network overhead as
=> TCP headers are added for each response line.
To give an idea a LIST response line is 35 bytes
long but result in a 101 bytes TCP frame so a 188%
overcost....
=> TCP ack are conducted for each line independently.
An ACK is 66 bytes
This is especially problematic for LIST, FETCH commands that actually result in many (100, 1000, maybe millions) response lines.
We should try to limit the calls to "flush" with Netty, and force the flush only once per IMAP command (at the end of processing). Netty is free to transmit some data earlier if it's buffer states requires it.
The entire mailbox list take 1 packet to transmit (1420 bytes total for 41 mailboxes so ~35 bytes per mailbox) …
> JAMES-3870 Group IMAP response line within TCP packets

- mailbox/api/src/main/java/org/apache/james/mailbox/model/FetchGroup.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/AttachmentLoader.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageDAO.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageDAOV3.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageMapperTest.java
- mailbox/scanning-search/src/test/java/org/apache/james/mailbox/store/search/SimpleMessageSearchIndexTest.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/BatchSizes.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/ResultUtils.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/FetchGroupConverter.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/MessageMapper.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/FetchGroupConverterTest.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/MessageMapperTest.java
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/resources/eml/inlined-single-attachment.eml
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EmailGetMethodContract.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/json/EmailGetSerializer.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/Email.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/EmailBodyPart.scala
The idea is to allow fastly retrieve preview of a mail with attachment metadata with JMAP. e.g with GMAIL:
Nowadays, to fetch the `attachments` property, we use the FULL_CONTENT fetch type means fetching the body content while we don't need that in this case.
We should introduce a JMAP read level that retrieves the `attachments` property without fetching the body of the mail.
> JAMES-3872 Add another read level to get attachment metadata without reading the email body

- server/apps/jpa-app/sample-configuration/james-database-mariadb.properties
- server/apps/jpa-app/sample-configuration/james-database.properties
- server/apps/jpa-smtp-app/sample-configuration/james-database-mariadb.properties
- server/apps/jpa-smtp-app/sample-configuration/james-database.properties
- server/container/guice/jpa-common/src/main/java/org/apache/james/modules/data/JPAConfiguration.java
- server/container/guice/jpa-common/src/main/java/org/apache/james/modules/data/JPAEntityManagerModule.java
- server/container/guice/jpa-common/src/test/java/org/apache/james/modules/data/JPAConfigurationTest.java
- src/site/xdoc/server/config-system.xml
It all in the comment and the jira issue, not all the dbcp data source properties are exposed through james-database.properties. I need to add one to configure maxTotal connection
> [JAMES-3877] enables configuration of jdbc pool max connections

- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/DelegateGetMethodContract.scala
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/DelegatedAccountGetMethodContract.scala
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/probe/DelegationProbe.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/delegation/DelegateGet.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/delegation/DelegatedAccountGet.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/DelegateGetMethod.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/DelegatedAccountGetMethod.scala
Currently, the get method returns AccountId as an id of delegation in response.
=> 
Update: use DelegationId, which is already (Same id as Delegate/Set method)
> JAMES-3756 - Update Delegate/get, DelegatedAccount/get - return DelegationId in response

- server/protocols/webadmin/webadmin-core/src/main/java/org/apache/james/webadmin/WebAdminServer.java
Logging bound port at startup helps make sure the ops setup is correct. The idea was lifted from `AbstractConfigurableAsyncServer` which is used for the SMTP server.
> [boyscout] logs bound port when webmin server starts

- server/data/data-jdbc/src/main/java/org/apache/james/mailrepository/jdbc/JDBCMailRepository.java
This fixes the JAMES-3875, cur of to long error messages who lead to exception, and replacing setObject(null) with type to avoid type missmatch
> JAMES-3875 JPAMailRepository fix

- server/apps/distributed-app/docs/modules/ROOT/partials/RemoteDelivery.adoc
- server/apps/spring-app/src/main/resources/mailetcontainer.xml
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/remote/delivery/DnsHelper.java
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/remote/delivery/RemoteDeliveryConfiguration.java
Implement round robin loadbalancing if multiple gateways are defined 
Add new Remote Delivery property loadBalancing.
> JAMES-3876 Load-balancing flag for Remote Delivery Gateways

- server/apps/scaling-pulsar-smtp/src/main/java/org/apache/james/Main.java
- server/protocols/protocols-library/src/main/java/org/apache/james/protocols/lib/LegacyJavaEncryptionFactory.java
- server/protocols/protocols-library/src/main/java/org/apache/james/protocols/lib/SslConfig.java
While doing the setup of our james instance, we had a hard time making sure that the right keystore and corresponding parameters were applied, and ti diagnose some invalid configuration leading to guice context configuration error.
These two commits helped us debug it.
> Improves logs for guice context and ssl contexts initialization errors

- backends-common/rabbitmq/src/main/java/org/apache/james/backends/rabbitmq/RabbitMQConfiguration.java
- event-bus/distributed/src/main/java/org/apache/james/events/KeyReconnectionHandler.java
- event-bus/distributed/src/main/java/org/apache/james/events/KeyRegistrationHandler.java
- server/task/task-api/src/test/java/org/apache/james/task/TaskManagerContract.java
- server/task/task-distributed/src/main/java/org/apache/james/task/eventsourcing/distributed/RabbitMQTerminationSubscriber.java
- server/task/task-distributed/src/main/java/org/apache/james/task/eventsourcing/distributed/RabbitMQWorkQueue.java
- server/task/task-distributed/src/main/java/org/apache/james/task/eventsourcing/distributed/RabbitMQWorkQueueReconnectionHandler.java
- server/task/task-distributed/src/main/java/org/apache/james/task/eventsourcing/distributed/TerminationReconnectionHandler.java
- server/task/task-distributed/src/main/scala/org/apache/james/task/eventsourcing/distributed/RabbitMQWorkQueueSupplier.scala
- server/task/task-distributed/src/test/java/org/apache/james/task/eventsourcing/distributed/DistributedTaskManagerTest.java
- server/task/task-distributed/src/test/java/org/apache/james/task/eventsourcing/distributed/RabbitMQTerminationSubscriberTest.java
- server/task/task-distributed/src/test/java/org/apache/james/task/eventsourcing/distributed/RabbitMQWorkQueuePersistenceTest.java
- server/task/task-distributed/src/test/java/org/apache/james/task/eventsourcing/distributed/RabbitMQWorkQueueTest.java
- server/task/task-memory/src/test/java/org/apache/james/task/eventsourcing/TerminationSubscriberContract.java
- Apply queue expiracy only for per-node queues
Those are temporary RPC-like response queues tied to a
specific James instance, needing cleanup. Other,
permanent queues should not be deleted.
- Apply queue expiracy for the task manager
Safer than auto-deletes
> JAMES-3694 Refine RabbitMQ usage of x-expires queue feature

- protocols/imap/src/main/java/org/apache/james/imap/processor/base/UidMsnConverter.java
- protocols/imap/src/test/java/org/apache/james/imap/processor/base/UidMsnConverterTest.java
- contains calls can rely on binary search
- remove duplicated collection.sort call
- and fix a bug for adding longs in the structure.
- fix long removal
- deallocate int structure when switching to long
- complete test coverage
> JAMES-3740 Small improvments for UidMSNConverter

- mailbox/api/src/main/java/org/apache/james/mailbox/extractor/TextExtractor.java
- mailbox/api/src/test/java/org/apache/james/mailbox/extractor/TextExtractorContract.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/extractor/DefaultTextExtractor.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/extractor/DefaultTextExtractorTest.java
- mailbox/tika/src/main/java/org/apache/james/mailbox/tika/CachingTextExtractor.java
I propose a new contract to make sure `TextExtractor` implementations close the provided input streams.
I only made it to work with Default implementation but I'm sure it can be extended to other implementations.
> Fix a leak in TextExtractor

- mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMessageManager.java
- mailet/crypto/src/main/java/org/apache/james/transport/KeyStoreHolder.java
- mailet/crypto/src/main/java/org/apache/james/transport/SMIMEKeyHolder.java
- mailet/standard/src/main/java/org/apache/james/transport/mailets/RecoverAttachment.java
- server/container/core/src/main/java/org/apache/james/server/core/MimeMessageInputStreamSource.java
- server/container/util/src/main/java/org/apache/james/util/DataChunker.java
- server/container/util/src/main/java/org/apache/james/util/io/UnsynchronizedBufferedInputStream.java
Synchronized methods becomes ore expensive with higher JRE versions (loom) making calling
`BufferedInputStream::read()` method for each byte prohibitive.
See https://issues.apache.org/jira/projects/IO/issues/IO-786
> [PERF] Use UnsynchronizedBufferedInputStream

- mailbox/store/src/main/java/org/apache/james/mailbox/store/MimeDescriptorImpl.java
- protocols/imap/src/main/java/org/apache/james/imap/api/message/UidRange.java
This allows buffering parts reads, which is used to discover its size.
Local benchmark showed
- A good 10x speed enhancement on 650KB email (2.9ms to 0.25 ms)
- A decent 2x speed enhancement on 5KB email (40 us to 20 us)
Context: Line length is only needed for textual parts...
> [PERF] MimeDescriptorImpl: avoid counting lines for non text parts

- backends-common/pulsar/pom.xml
- backends-common/pulsar/src/main/scala/org/apache/james/backends/pulsar/PulsarClients.scala
- backends-common/pulsar/src/main/scala/org/apache/james/backends/pulsar/PulsarConfiguration.scala
- backends-common/pulsar/src/test/java/org/apache/james/backends/pulsar/DockerPulsarExtension.java
- backends-common/pulsar/src/test/java/org/apache/james/backends/pulsar/PulsarConfigurationTest.java
- server/container/guice/queue/pulsar/src/main/java/org/apache/james/queue/pulsar/module/PulsarQueueModule.java
- server/queue/queue-pulsar/src/main/scala/org/apache/james/queue/pulsar/PulsarMailQueue.scala
- server/queue/queue-pulsar/src/main/scala/org/apache/james/queue/pulsar/PulsarMailQueueFactory.scala
- server/queue/queue-pulsar/src/test/java/org/apache/james/queue/pulsar/PulsarMailQueueFactoryTest.java
- server/queue/queue-pulsar/src/test/java/org/apache/james/queue/pulsar/PulsarMailQueueTest.java
The initial implementation only supported no auth, which doesn't work well in a prod environment. 
This PR adds support for 
- explicit no auth
- basic user/password auth
- token auth
> Adds minimal pulsar authentication support to pulsar configuration

- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EmailGetMethodContract.scala
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EmailSetMethodContract.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/json/EmailGetSerializer.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/json/EmailSetSerializer.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/EmailGet.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/EmailHeader.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/EmailSet.scala
Also supports typing header:Name:asType:all syntax
See related issue: https://github.com/iNPUTmice/jmap/issues/77
See long unhandled issue tracking this on the Linagora backlog: https://github.com/linagora/james-project/issues/3739
That's a quick evening contribution eventually solving some enduser related issues.
> JAMES-3379 Support header:Name:all syntax

- mailbox/spring/src/test/README.md
It took me a while (and matthieu's help) to figure out how to run testsuites that depend on openjpa.  
So I wanted to document somewhere for other developpers the steps to run the tests outside of maven. 
I must say, I am not sure how the tests work in maven as I couldn't find where the agent is configured yet the build still works without additional config. 
Since it is not easily discoverable from the point of failure, I think it is nice to document it. I am open to suggestions of a better approach :)
> [doc] adds quick help on how to run openjpa basesd tests

- server/apps/distributed-app/sample-configuration/rabbitmq.properties
- server/apps/distributed-pop3-app/sample-configuration/rabbitmq.properties
The default rabbitmq container in docker-compose sample file is not ready `vhost`
-> when we run docker-compose.yml file, James will start failing
```
07:03:22.705 [1;31m[ERROR][0;39m o.a.j.GuiceJamesServer - Fatal error while starting James
java.lang.RuntimeException: Non recoverable exception status: 404
at org.apache.james.backends.rabbitmq.RabbitMQManagementAPI.lambda$static$3(RabbitMQManagementAPI.java:447)
at feign.AsyncResponseHandler.handleResponse(AsyncResponseHandler.java:98)
at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:141)
at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:91)
at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100)
at com.sun.proxy.$Proxy68.listVhostQueues(Unknown Source)
at …
```
> JAMES-3864 Update sample AMQP vhost configuration in rabbitmq.properties

- examples/custom-listeners/pom.xml
- mailbox/cassandra/pom.xml
- mailbox/jpa/pom.xml
- mailbox/lucene/pom.xml
- mailbox/memory/pom.xml
- mailbox/plugin/quota-search-scanning/pom.xml
- mailbox/plugin/quota-search/pom.xml
- mailbox/scanning-search/pom.xml
- mailbox/spring/pom.xml
- mailbox/store/pom.xml
- mailbox/tools/copier/pom.xml
- mailbox/tools/indexer/pom.xml
- mpt/impl/imap-mailbox/cassandra/pom.xml
- mpt/impl/imap-mailbox/inmemory/pom.xml
- mpt/impl/imap-mailbox/jpa/pom.xml
- mpt/impl/imap-mailbox/lucenesearch/pom.xml
- pom.xml
- protocols/imap/pom.xml
- server/blob/blob-export-file/pom.xml
- server/container/guice/configuration/pom.xml
- server/container/mailbox-jmx/pom.xml
- server/protocols/jmap-draft/pom.xml
- server/protocols/jmap-rfc-8621/pom.xml
- server/protocols/protocols-pop3-distributed/pom.xml
- server/protocols/protocols-pop3/pom.xml
- server/protocols/webadmin/webadmin-mail-over-web/pom.xml
- server/protocols/webadmin/webadmin-mailqueue/pom.xml
CF https://github.com/frohoff/ysoserial
This was possible through the commons-logging 1.2 transitive dependency.
> JAMES-3881 Prevent CommonsBeanutils1 deserialization exploit

- server/apps/cassandra-app/sample-configuration/jvm.properties
- server/apps/distributed-app/docs/modules/ROOT/pages/operate/security.adoc
- server/apps/distributed-app/sample-configuration/jvm.properties
- server/apps/distributed-pop3-app/sample-configuration/jvm.properties
- server/apps/jpa-app/sample-configuration/jvm.properties
- server/apps/jpa-smtp-app/sample-configuration/jvm.properties
- server/apps/memory-app/sample-configuration/jvm.properties
- server/apps/spring-app/pom.xml
This prevents the use of MLets for remote code executions and make life of attackers harder.
> JAMES-3881 -Djmx.remote.x.mlet.allow.getMBeansFromURL=false

- server/container/guice/data-ldap/src/main/java/org/apache/james/data/LdapUsersRepositoryModule.java
- server/data/data-ldap/src/main/java/org/apache/james/user/ldap/LdapHealthCheck.java
- server/data/data-ldap/src/test/java/org/apache/james/user/ldap/LdapHealthCheckTest.java
As the title says, added a new health checker to check LDAP server's health and tested it.
Note: checkShouldReturnHealthyIfLdapIsRunning failed when I ran it locally. Apparently, there is an exception thrown by the ldap user repository that says "Unable check user existence from ldap".
I'm sure that the test container has started because I can view it from Docker Desktop, but for some reason, the exception is still thrown.
> JAMES-2601 Implement a LDAP healthCheck

- server/apps/cassandra-app/sample-configuration/jvm.properties
- server/apps/distributed-app/docs/modules/ROOT/pages/operate/security.adoc
- server/apps/distributed-app/sample-configuration/jvm.properties
- server/apps/distributed-pop3-app/sample-configuration/jvm.properties
- server/apps/jpa-app/sample-configuration/jvm.properties
- server/apps/jpa-smtp-app/sample-configuration/jvm.properties
- server/apps/memory-app/sample-configuration/jvm.properties
- server/apps/spring-app/pom.xml
This prevents the use of MLets for remote code executions and make life of attackers harder.
> JAMES-3881 -Djmx.remote.x.mlet.allow.getMBeansFromURL=false [BACKPORT]

- server/protocols/webadmin/webadmin-mailbox/src/main/java/org/apache/james/webadmin/service/ExpireMailboxTask.java
- server/task/task-api/pom.xml
- server/task/task-api/src/main/java/org/apache/james/task/AsyncSafeTask.java
- server/task/task-api/src/main/java/org/apache/james/task/Task.java
- server/task/task-memory/src/main/java/org/apache/james/task/SerialTaskManagerWorker.java
- server/task/task-memory/src/test/java/org/apache/james/task/SerialTaskManagerWorkerTest.java
See JAMES-3890 for rationale. TL;DR: Long running tasks should not delay regular tasks.
I introduce the AsyncSafeTask for long running tasks that are allowed to execute in parallel with other tasks, converting ExpireMailboxTask as an example.
I patched the respective functionality into SerialTaskManagerWorker (name does not quite fit anymore). It gets a separate asyncTaskExceutor for such tasks, and uses a map instead of a reference to keep track of everything, e.g. to cancel running tasks. The "pollingMono" wrapper takes care of cleaning up the map once it finishes.
While this achieves the goal, I am not quite sure this is the best possible solution. I also may have missed some crucial edge cases. Any suggestions?
> JAMES-3890 Allow parallel execution of safe tasks

- server/task/task-api/pom.xml
- server/task/task-api/src/main/java/org/apache/james/task/AsyncSafeTask.java
- server/task/task-api/src/main/java/org/apache/james/task/Task.java
- server/task/task-memory/src/main/java/org/apache/james/task/SerialTaskManagerWorker.java
- server/task/task-memory/src/test/java/org/apache/james/task/SerialTaskManagerWorkerTest.java
This is a backport of  #1452 to the 3.7.x branch. In order to keep it minimal, there are some notable changes compared to the master version:
- Task.runAsync() uses Schedulers.elastic() since ReactorUtils.BLOCKING_CALL_WRAPPER has not been introduced yet.
- SerialTaskManagerWorker.close() does not cancel and wait for tasks to finish. Seems that was introduced later an never backported. While I could add this as a potential stability improvement, I am not sure what the impact would be.
- There is no ExpireMailboxTask yet to use as a showcase, though I did a smoke test with a private extension that was its spiritual predecessor.
> JAMES-3890 Allow parallel execution of safe tasks (3.7.x backport)

- server/apps/cassandra-app/sample-configuration/jvm.properties
- server/apps/cli-integration-tests/src/test/java/org/apache/james/cli/JmxSecurityServerIntegrationTest.java
- server/apps/cli/src/main/java/org/apache/james/cli/ServerCmd.java
- server/apps/cli/src/main/java/org/apache/james/cli/probe/impl/JmxConnection.java
- server/apps/cli/src/test/java/org/apache/james/cli/ServerCmdTest.java
- server/apps/distributed-app/docs/modules/ROOT/pages/configure/jmx.adoc
- server/apps/distributed-app/sample-configuration/jvm.properties
- server/apps/distributed-pop3-app/sample-configuration/jvm.properties
- server/apps/jpa-app/pom.xml
- server/apps/jpa-app/sample-configuration/jvm.properties
- server/apps/jpa-smtp-app/pom.xml
- server/apps/jpa-smtp-app/sample-configuration/jvm.properties
- server/apps/memory-app/pom.xml
- server/apps/memory-app/sample-configuration/jvm.properties
- server/apps/spring-app/src/main/java/org/apache/james/app/spring/JamesAppSpringMain.java
- server/container/guice/common/src/main/java/org/apache/james/TemporaryJamesServer.java
- server/container/guice/jmx/src/main/java/org/apache/james/modules/server/JMXServer.java
- server/container/guice/jmx/src/main/java/org/apache/james/modules/server/JmxConfiguration.java
- src/site/xdoc/server/config-system.xml
This is a quick cherry pick of the remaining JAMES-3881 commits to  the 3.7.x branch. Some of them were already in place:
JAMES-3881 -Djmx.remote.x.mlet.allow.getMBeansFromURL=false (#1460)
JAMES-3881 Prevent CommonsBeanutils1 deserialization exploit [BACKPORT] (#1455)
JAMES-3881 Unregister LOG4J MBeans (#1459)
DISCLAIMER: I was not involved in the original work. Someone more knowledgeable with JMX please review it.
I did a quick test on distributed-pop3-app: James creates the jmxremote files, and the CLI requires authentication. Given authentication it works. Apart from this I cannot really tell if there is anything missing.
> JAMES-3881 Set a JMX password (3.7.x)

- server/mailet/integration-testing/src/test/java/org/apache/james/mailets/flow/PauseThenCountingExecutionMailet.java
- server/mailet/integration-testing/src/test/java/org/apache/james/mailets/flow/ShutDownIntegrationTest.java
- server/mailet/mailetcontainer-impl/pom.xml
- server/mailet/mailetcontainer-impl/src/main/java/org/apache/james/mailetcontainer/impl/JamesMailSpooler.java
- server/mailet/mailets/pom.xml
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/RemoteDelivery.java
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/remote/delivery/DeliveryRunnable.java
Graceful shutdown for scheduler is a late addition to the reactor framework, hence I propose an alternative to it.
CF https://github.com/reactor/reactor-core/pull/3089
> JAMES-3891 Graceful shutdown for queue consumers [3.7.x]

- mailbox/api/src/main/java/org/apache/james/mailbox/DefaultMailboxes.java
- mpt/impl/imap-mailbox/core/src/main/java/org/apache/james/mpt/host/JamesImapHostSystem.java
- mpt/impl/imap-mailbox/core/src/main/java/org/apache/james/mpt/imapmailbox/suite/Condstore.java
- protocols/imap/src/main/java/org/apache/james/imap/api/ImapConfiguration.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/AbstractAuthProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/CapabilityProcessor.java
- protocols/imap/src/test/java/org/apache/james/imap/api/ImapConfigurationTest.java
- protocols/imap/src/test/java/org/apache/james/imap/processor/CapabilityProcessorTest.java
- server/protocols/jmap-draft-integration-testing/jmap-draft-integration-testing-common/src/test/java/org/apache/james/jmap/ProvisioningTest.java
- server/protocols/jmap-draft-integration-testing/jmap-draft-integration-testing-common/src/test/java/org/apache/james/jmap/draft/methods/integration/GetMailboxesMethodTest.java
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/BackReferenceContract.scala
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/MailboxGetMethodContract.scala
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/ProvisioningContract.scala
- server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/IMAPServer.java
- server/protocols/protocols-imap4/src/test/java/org/apache/james/imapserver/netty/IMAPServerConfigurationTest.java
I opted to create default mailboxes when `INBOX` is created without explicitly checking if they exist to lower the impact on the repositories as the check is made on each logging in.
> JAMES-3895 Automatically provision default (IMAP) mailboxes

- server/container/mailbox-adapter/src/main/java/org/apache/james/adapter/mailbox/MailboxUsernameChangeTaskStep.java
- server/container/mailbox-adapter/src/test/java/org/apache/james/adapter/mailbox/MailboxUsernameChangeTaskStepTest.java
Script:
- Bob already has an inbox mailbox (no messages)
- Alice change her username to Bob by webadmin
- Get task status, the result is ABORTED
Keep all old BOB mailbox data (messages, subscriptions...)
- Rename Bob X mailbox -> Bob X-migrating mailbox
- Rename Alice mailbox X -> Bob mailbox X
- Copy messages in Bob X-migrating mailbox to Bob mailbox X, and then delete Bob X-migrating mailbox
> JAMES-3885 - Change username - should migrate succeed when mailboxes from old user already exist on the new user

- pom.xml
- protocols/netty/pom.xml
- server/blob/blob-s3/pom.xml
- server/mailet/rate-limiter-redis/pom.xml
To avoid having possible netty lib mismatches depending of the flavors and other third party libs.
> [FIX] Declare all netty libs on master pom

- mailbox/api/src/main/java/org/apache/james/mailbox/model/SearchQuery.java
- mailbox/lucene/src/main/java/org/apache/james/mailbox/lucene/search/LuceneMessageSearchIndex.java
- mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/query/CriterionConverter.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/SearchThreadIdGuessingAlgorithm.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/search/MessageSearches.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/search/SimpleMessageSearchIndex.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/SearchProcessor.java
- protocols/imap/src/test/java/org/apache/james/imap/processor/SearchProcessorTest.java
- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/utils/FilterToCriteria.java
- server/protocols/jmap-draft/src/test/java/org/apache/james/jmap/draft/utils/FilterToCriteriaTest.java
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/utils/search/MailboxFilter.scala
This enable hitting the subject field whose indexing can be separately tuned (language?)
This also avoids relying on nested entities for subject search.
https://github.com/apache/james-project/pull/988
> JAMES-2080 Add a dedicated Subject search criterion

- third-party/clamav/src/test/java/org/apache/james/clamav/DockerClamAV.java
The CI sometimes fails because cannot start to succeed the docker ClamAV
```
Stable Tests
[ERROR] o.a.j.c.ClamAVScan - Exception thrown
java.net.ConnectException: maxPings exceeded: 2. Giving up. The clamd daemon seems not to be running
```
> JAMES-3775 DockerClamAV - update waiting strategy

- mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/IndexHeaders.java
- mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/OpenSearchMailboxConfiguration.java
- mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/json/IndexableMessage.java
- mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/json/MessageToOpenSearchJson.java
- mailbox/opensearch/src/test/java/org/apache/james/mailbox/opensearch/OpenSearchIntegrationTest.java
- mailbox/opensearch/src/test/java/org/apache/james/mailbox/opensearch/events/OpenSearchListeningMessageSearchIndexTest.java
- mailbox/opensearch/src/test/java/org/apache/james/mailbox/opensearch/json/IndexableMessageTest.java
- mailbox/opensearch/src/test/java/org/apache/james/mailbox/opensearch/json/MessageToOpenSearchJsonTest.java
- mailbox/opensearch/src/test/java/org/apache/james/mailbox/opensearch/search/OpenSearchSearcherTest.java
- mailbox/store/src/test/resources/eml/spamMailNoHeaders.json
- mpt/impl/imap-mailbox/opensearch/src/test/java/org/apache/james/mpt/imapmailbox/elasticsearch/host/OpenSearchHostSystem.java
- server/apps/distributed-app/docs/modules/ROOT/pages/configure/opensearch.adoc
- server/container/guice/opensearch/src/main/java/org/apache/james/modules/mailbox/OpenSearchMailboxModule.java
- server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/routes/MailboxesRoutesTest.java
- server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/routes/UserMailboxesRoutesTest.java
- src/site/xdoc/server/config-opensearch.xml
Indicates if you wish to index headers or not (default: true). Note that specific headers (From, To, Cc, Bcc, Subject, Message-Id, Date, Content-Type) are still indexed in their dedicated type. Header indexing is expensive as each header currently need to be stored as a nested document but turning off headers indexing result in non-strict compliance with the IMAP / JMAP standards.
Indexing 5.000 mails takes ~1 minute and occupies 26MB of index (5KB perf mail) which is consistant with our production mertics. The commit log is more bulky and with index occupies 185 MB.
Indexing 10.000 takes ~ 76s and occupies 6.9 MB of index (690 B / mails). The commit log is more bulky and with index occupies 62 MB.
This change allows a dramatic space reduction on OpenSearch (cost saving!) of ~ x8 for the …
> JAMES-2080 Allow turning off header indexing in OpenSearch

- server/apps/cassandra-app/sample-configuration/jvm.properties
- server/apps/distributed-app/sample-configuration/jvm.properties
- server/container/guice/cassandra/src/main/java/org/apache/james/modules/data/CassandraJmapModule.java
- server/data/data-jmap-cassandra/src/main/java/org/apache/james/jmap/cassandra/filtering/FilteringIncrementalRuleChangeDTO.java
- server/data/data-jmap-cassandra/src/main/java/org/apache/james/jmap/cassandra/filtering/FilteringRuleSetDefineDTOModules.java
- server/data/data-jmap-cassandra/src/test/java/org/apache/james/jmap/cassandra/filtering/CassandraEventSourcingFilteringManagementTest.java
- server/data/data-jmap-cassandra/src/test/java/org/apache/james/jmap/cassandra/filtering/DTOTest.java
- server/data/data-jmap-cassandra/src/test/resources/json/increment.json
- server/data/data-jmap/src/main/java/org/apache/james/jmap/api/filtering/impl/FilteringAggregate.java
- server/data/data-jmap/src/main/java/org/apache/james/jmap/api/filtering/impl/IncrementalRuleChange.java
- server/data/data-jmap/src/test/java/org/apache/james/jmap/api/filtering/RuleFixture.java
- server/data/data-jmap/src/test/java/org/apache/james/jmap/api/filtering/impl/IncrementalRuleChangeTest.java
- upgrade-instructions.md
Goals: capture most changes of the filtering aggregate to reduce the complexity of this aggregate.
This work (in progress) proposes an incremental update that covers:
- Rules addition at the beginning of the rule set or at the end
- Rules deletion
- Rules modification
Actions falling outside of this scope cannot be captured in an incremental fashion and would lead to a full reset (todays behaviour). This is the case when:
- Rules are being reordered.
- Rules are added in the middle of existing rules.
I suspect no UI allows this. Hence this is more that likely enough.
> JAMES-3777 Incremental events for Filters

- server/task/task-memory/src/main/scala/org/apache/james/task/eventsourcing/DecisionProjection.scala
- server/task/task-memory/src/main/scala/org/apache/james/task/eventsourcing/Events.scala
- server/task/task-memory/src/main/scala/org/apache/james/task/eventsourcing/TaskAggregate.scala
They fully capture the state of the aggregate.
This prevents loading the full history for looong
running tasks and prevents timeouts upon polling updates.
Before the aggregate was containing a lot of events, that were periodically loaded:
```
Widest Partitions:
[Task/2d534232-fade-47aa-8c6f-1ec2d0f238f9] 1855
[Task/d8499ec7-a62a-4541-970a-7339fccf23e8] 779
```
Eventually resulting in timeouts as the full partition was loaded...
```
reactor.core.Exceptions$ErrorCallbackNotImplemented: com.datastax.oss.driver.api.core.DriverTimeoutException: Query timed out after PT5S
Caused by: com.datastax.oss.driver.api.core.DriverTimeoutException: Query timed out after PT5S
at com.datastax.oss.driver.internal.core.cql.CqlRequestHandler.lambda$scheduleTimeout$1(CqlRequestHandler.java:207)
at …
```
> JAMES-3900 Snapshots for polled updates

- server/apps/distributed-app/docs/modules/ROOT/pages/configure/jmap.adoc
- server/apps/distributed-app/docs/modules/ROOT/pages/operate/webadmin.adoc
- server/container/guice/cassandra/src/main/java/org/apache/james/modules/data/CassandraJmapModule.java
- server/container/guice/memory/src/main/java/org/apache/james/modules/data/MemoryDataJmapModule.java
- server/container/guice/protocols/webadmin-jmap/src/main/java/org/apache/james/modules/server/JmapTaskSerializationModule.java
- server/container/guice/protocols/webadmin-jmap/src/main/java/org/apache/james/modules/server/JmapTasksModule.java
- server/data/data-jmap-cassandra/src/main/java/org/apache/james/jmap/cassandra/filtering/CassandraFilteringProjection.java
- server/data/data-jmap-cassandra/src/main/java/org/apache/james/jmap/cassandra/filtering/CassandraFilteringProjectionModule.java
- server/data/data-jmap-cassandra/src/test/java/org/apache/james/jmap/cassandra/filtering/CassandraEventSourcingFilteringManagementNoProjectionTest.java
- server/data/data-jmap-cassandra/src/test/java/org/apache/james/jmap/cassandra/filtering/CassandraEventSourcingFilteringManagementTest.java
- server/data/data-jmap/src/main/java/org/apache/james/jmap/api/filtering/Version.java
- server/data/data-jmap/src/main/java/org/apache/james/jmap/api/filtering/impl/EventSourcingFilteringManagement.java
- server/data/data-jmap/src/main/java/org/apache/james/jmap/api/filtering/impl/FilteringAggregateId.java
- server/data/data-jmap/src/test/java/org/apache/james/jmap/api/filtering/FilteringManagementContract.java
- server/protocols/webadmin-integration-test/webadmin-integration-test-common/src/main/java/org/apache/james/webadmin/integration/WebAdminServerIntegrationImmutableTest.java
- server/protocols/webadmin/webadmin-jmap/src/main/java/org/apache/james/webadmin/data/jmap/Constants.java
- server/protocols/webadmin/webadmin-jmap/src/main/java/org/apache/james/webadmin/data/jmap/PopulateFilteringProjectionRequestToTask.java
- server/protocols/webadmin/webadmin-jmap/src/main/java/org/apache/james/webadmin/data/jmap/PopulateFilteringProjectionTask.java
- server/protocols/webadmin/webadmin-jmap/src/main/java/org/apache/james/webadmin/data/jmap/PopulateFilteringProjectionTaskAdditionalInformationDTO.java
- server/protocols/webadmin/webadmin-jmap/src/test/java/org/apache/james/webadmin/data/jmap/PopulateFilteringProjectionItemsTaskAdditionalInformationDTOTest.java
- server/protocols/webadmin/webadmin-jmap/src/test/java/org/apache/james/webadmin/data/jmap/PopulateFilteringProjectionRequestToTaskTest.java
- server/protocols/webadmin/webadmin-jmap/src/test/java/org/apache/james/webadmin/data/jmap/PopulateFilteringProjectionTaskSerializationTest.java
- server/protocols/webadmin/webadmin-jmap/src/test/resources/json/populateFilters.additionalInformation.json
- server/protocols/webadmin/webadmin-jmap/src/test/resources/json/populateFilters.task.json
- src/site/markdown/server/manage-webadmin.md
- src/site/xdoc/server/config-jmap.xml
Uses a read projection (optional)
This prevents loading the full aggregate history (O(n2)) and doing LWTs upon receiving emails.
A route allows resetting the projection.
Possible enhancement:
- Allow individual filter addition, removal (history in O(N) )
- (Snapshots for the event sourcing system in James ?)
> JAMES-3777 Mitigate performance problems with JMAP filters

- backends-common/opensearch/src/main/java/org/apache/james/backends/opensearch/ReactorOpenSearchClient.java
My bet: it was not handling cancelation! What the driver likely did upon 429 `Too much requests`...
> [REFACTORING] ReactorOpenSearchClient: Use Mono::fromFuture

- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/remote/delivery/RemoteDeliveryConfiguration.java
If there is an empty `<gateway/>` element in configuration then RemoteDelivery adds empty values to collection resulting in entry `[:]` which then fails to deliver. I'd argue that in that case James should skip such configuration and use `serviceNoGateway()` method.
Example configuration:
```xml
<processor state="relay" enableJmx="true">
<mailet match="All" class="RemoteDelivery">
<outgoingQueue>outgoing</outgoingQueue>
<delayTime>5000, 100000, 500000</delayTime>
<maxRetries>3</maxRetries>
<maxDnsProblemRetries>0</maxDnsProblemRetries>
<deliveryThreads>10</deliveryThreads>
<sendpartial>true</sendpartial>
<bounceProcessor>bounces</bounceProcessor>
<debug>true</debug>
<gateway></gateway>
<gatewayPort></gatewayPort>
<gatewayUsername></gatewayUsername>
<gatewayPassword></gatewayPassword> …
```
> Don't add gateway if no gateway is configured (empty value)

- server/apps/distributed-app/docs/modules/ROOT/pages/run/run-docker.adoc
- server/apps/distributed-app/docs/modules/ROOT/pages/run/run-java.adoc
This ease the installation process
> [DOC] Antora documentation should rely on --generate-keystore

- server/apps/cassandra-app/src/main/java/org/apache/james/CassandraJamesServerConfiguration.java
- server/apps/distributed-app/src/main/java/org/apache/james/CassandraRabbitMQJamesConfiguration.java
- server/apps/distributed-pop3-app/src/main/java/org/apache/james/DistributedPOP3JamesConfiguration.java
- server/container/guice/common/src/main/java/org/apache/james/modules/CommonServicesModule.java
- server/container/guice/configuration/src/main/java/org/apache/james/utils/PropertiesProvider.java
When I started James, I saw several logs `Load configuration file` from the same file. 
First I think has an error somewhere. But no, we re-IO load file for separate configuration. 
-> 
I make the `PropertiesProvider` singleton and add the guava cache (in 10 minutes) for file configuration
Before:
```
9:08:33.126 [INFO ] o.a.j.CONFIGURATION - Load configuration file /root/conf/extensions.properties
2023-05-05T09:08:33.143397454Z 09:08:33.143 [INFO ] o.a.j.CONFIGURATION - Load configuration file /root/conf/jmap.properties
2023-05-05T09:08:33.146069684Z 09:08:33.145 [INFO ] o.a.j.CONFIGURATION - Load configuration file /root/conf/jmap.properties
2023-05-05T09:08:33.307942017Z 09:08:33.307 [INFO ] o.a.j.CONFIGURATION - Load configuration file /root/conf/jmap.properties …
```
> [REFACTORING] Make PropertiesProvider singleton & avoid load multi times from FileSystem

- backends-common/opensearch/src/main/java/org/apache/james/backends/opensearch/ClientProvider.java
Before, we were using Non-Preemptive authentication for OpenSearch that makes 1 normal OpenSearch request to be 2 round trips (1 authenticated 401 request and 1 normal request).
This likely negatively affected our search performance. We should avoid that.
rf: https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/master/_basic_authentication.html
> [PERF] Avoid using Non-Preemptive authentication for OpenSearch

- pom.xml
For fitting with base scala version: 2.13.10
Maven warning:
```
[WARNING]  Expected all dependencies to require Scala version: 2.13.10
[WARNING]  org.apache.james:blob-storage-strategy:3.9.0-SNAPSHOT requires scala version: 2.13.10
[WARNING]  eu.timepit:refined_2.13:0.10.1 requires scala version: 2.13.8
[WARNING] Multiple versions of scala libraries detected!
```
> [UPGRADE] - Maven eu.timepit:refined_2.13:0.10.1 -> 0.10.3

- mailbox/jpa/pom.xml
- mailbox/jpa/src/main/java/org/apache/james/mailbox/jpa/mail/JPAMailboxMapper.java
- mailbox/jpa/src/main/java/org/apache/james/mailbox/jpa/mail/JPAMessageMapper.java
- mailbox/jpa/src/main/java/org/apache/james/mailbox/jpa/openjpa/OpenJPAMessageManager.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMailboxManager.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMessageManager.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/AnnotationMapper.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/MessageMapper.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/ModSeqProvider.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/UidProvider.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/user/SubscriptionMapper.java
- mpt/impl/imap-mailbox/jpa/pom.xml
- server/apps/jpa-app/pom.xml
- server/apps/jpa-app/sample-configuration/jvm.properties
- server/apps/jpa-smtp-app/pom.xml
- server/apps/jpa-smtp-app/sample-configuration/jvm.properties
- server/apps/spring-app/pom.xml
openjpa (blocking) calls on the IMAP event loop
No openjpa (blocking) calls on the IMAP event loop
> [FIX] JPA blocking calls should be moved to bounded elastic

- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/jsieve/ActionDispatcher.java
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/jsieve/ActionUtils.java
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/jsieve/FileIntoAction.java
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/jsieve/RedirectAction.java
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/jsieve/RejectAction.java
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/jsieve/VacationReply.java
- server/mailet/mailets/src/test/java/org/apache/james/transport/mailets/delivery/SieveIntegrationTest.java
- server/mailet/mailets/src/test/resources/org/apache/james/transport/mailets/delivery/reject.script
https://issues.apache.org/jira/browse/JAMES-3913 Sieve REJECT action still deliveres the mail
https://issues.apache.org/jira/browse/JAMES-3914 When processing an email with several recipients the following SIEVE actions fails:
- FileInto
- Vacation
- Redirect
- Reject
> JAMES-3913 + JAMES-3914 Fix Sieve mailet (big) bugs

- protocols/netty/src/main/java/org/apache/james/protocols/netty/AbstractSSLAwareChannelPipelineFactory.java
CF https://github.com/apache/james-project/tree/master/examples/proxy-smtp on port 465
```
james      | 03:01:57.543 [WARN ] i.n.c.ChannelInitializer - Failed to initialize a channel. Closing: [id: 0xab45804e, L:/172.18.0.2:465 - R:/172.18.0.3:35036]
james      | java.util.NoSuchElementException: proxyInformationHandler
james      |    at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073)
james      |    at io.netty.channel.DefaultChannelPipeline.addAfter(DefaultChannelPipeline.java:302)
james      |    at io.netty.channel.DefaultChannelPipeline.addAfter(DefaultChannelPipeline.java:290)
james      |    at org.apache.james.protocols.netty.AbstractSSLAwareChannelPipelineFactory.initChannel(AbstractSSLAwareChannelPipelineFactory.java:58)
james      | …
```
> FIX Proxy for SMTPS

- mailet/standard/src/main/java/org/apache/james/transport/matchers/IsFromMailingList.java
- mailet/standard/src/main/java/org/apache/james/transport/matchers/IsSingleRecipient.java
- mailet/standard/src/test/java/org/apache/james/transport/matchers/IsFromMailingListTest.java
- mailet/standard/src/test/java/org/apache/james/transport/matchers/IsSingleRecipientTest.java
* Implemented IsFromMailingList matcher with using AutomaticallySentMailDetector::isMailingList utility. This matcher returns recipients of the mail if the mail is from a mailing list.
* Fixed IsSingleRecipient matcher - for methods that return an array, prefer returning an empty array over a null value.
> JAMES-2434 IsFromMailingList matcher

- mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/model/Property.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/model/impl/PropertyBuilder.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/impl/PropertyBuilderTest.java
`org.apache.james.mailbox.store.mail.model.Property#Property()` already had contract (in it's javadoc) specifying that all parameters must be non-null - I added explicit check for it.
Moreover, checking possible call places, one of `PropertyBuilder#setProperty()` already had null-check, so I added same check to remaining to methods responsible for setting properties (one taking `List` and one taking `Map`).
@chibenwa suggested filtering properties with null value before persisting, but IMHO this approach is better and should prevent any other similar issues.
(ref: https://issues.apache.org/jira/browse/JAMES-3922)
> JAMES-3922: Enforce non-null Property contract and add missing null-check in Prope

- server/apps/distributed-app/docs/modules/ROOT/pages/configure/jmap.adoc
- server/apps/memory-app/sample-configuration/jmap.properties
- src/site/xdoc/server/config-jmap.xml
In order to config future release extension for jmap. we need a new properties `delay.sends.enabled` in `jmap.properties`
- `delay.sends.enabled = true` => support for future release 
- `delay.sends.enabled = false` => no support for future release 
IMO, we need add doc for this properties in https://james.apache.org/server/config-jmap.html
> JAMES-3822: New properties for future release jmap in jmap.properties

- backends-common/rabbitmq/src/main/java/org/apache/james/backends/rabbitmq/RabbitMQConfiguration.java
- event-bus/distributed/src/main/java/org/apache/james/events/GroupRegistration.java
- event-bus/distributed/src/main/java/org/apache/james/events/GroupRegistrationHandler.java
- event-bus/distributed/src/main/java/org/apache/james/events/KeyReconnectionHandler.java
- event-bus/distributed/src/main/java/org/apache/james/events/KeyRegistrationHandler.java
- server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/RabbitMQMailQueueFactory.java
- server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/view/api/FakeMailQueueView.java
We can't create a quorum queue and mark it as auto-delete, RabbitMQ does not allow it. So we keep the jmap event bus notification queues as classic for now.
> [BACKPORT] JAMES-3604 Fix issue when creating quorum rabbitmq queues

- server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/routes/SessionRoutesTest.scala
- server/protocols/jmap/src/main/java/org/apache/james/jmap/JMAPRoutes.java
Permanent redirects causes Safari to drop
Authorization headers
> [FIX] JMAP Session should use temporary redirects

- backends-common/rabbitmq/src/main/java/org/apache/james/backends/rabbitmq/ReactorRabbitMQChannelPool.java
This prevents the call from blocking the reactive pipeline.
JDC Flight Control performance (CPU and latency) results before fix:
**CPU and latency after fix:**
> Move rabbitMQ channel close operation to boundedElastic thread

- upgrade-instructions.md
TLS Host name verification was added in 3.7.3 and not in 3.8.0.
Pull-Request: https://github.com/apache/james-project/pull/1247
> TLS Host name verification was added in 3.7.3

- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailSubmissionSetMethod.scala
- server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/RabbitMQMailQueue.java
- The invoke `SMono(queue.enqueueReactive(mail, delay))` when delay is zero/negative is unnecessary
- `RabbitMQMailQueue.java` does not exist override the delay method, so the invoke to default `enQueue(mail, delay)` makes blocking
> JAMES-3822 Only invoke enqueue delay method when delay input is positive

- Jenkinsfile
- examples/custom-james-assembly/README.md
- examples/custom-james-assembly/pom.xml
- examples/pom.xml
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageMapperRelaxedConsistencyTest.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageMapperTest.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/MessageMapperTest.java
- pom.xml
- server/mailet/mock-smtp-server/pom.xml
- server/protocols/jmap-draft-integration-testing/rabbitmq-jmap-draft-integration-testing/pom.xml
- server/protocols/jmap-rfc-8621-integration-tests/distributed-jmap-rfc-8621-integration-tests/pom.xml
- server/protocols/webadmin-integration-test/distributed-webadmin-integration-test/pom.xml
- server/testing/src/main/java/org/apache/james/jmap/HttpJmapAuthentication.java
The pr https://github.com/apache/james-project/pull/1647 has a lot of files changed.
The ci can't green after several re-runs, So this pr is a split part of 1674 for easier
> Upgrade dependencies - maven plugin

- backends-common/cassandra/src/test/java/org/apache/james/backends/cassandra/DockerCassandra.java
- server/blob/blob-api/src/test/java/org/apache/james/blob/api/DeleteBlobStoreDAOContract.java
- server/blob/blob-s3/src/test/java/org/apache/james/blob/objectstorage/aws/S3MinioTest.java
- server/mailet/mailets/src/test/java/org/apache/james/transport/mailets/RequeueTest.java
Same as https://github.com/apache/james-project/pull/1672 but without the timeout increase of Cassandra waiting strategy, as I ain't sure about what exactly is creating those timeouts in webadmin-cli (which I'm surprised as none of those commits should have a change on that)
> [DUPLICATED] Better stability with Cassandra docker containers and integration tests

- backends-common/jpa/pom.xml
Exclude old JMS spec from dependencies to fix NoSuchMethodError when sending a message via SMTP
> Exclude old JMS spec from dependencies

- code-coverage-report/pom.xml
- examples/pom.xml
The HTML result files of code coverage make searching in IDE noisy locally. Explicitly running code coverage on Jenkins is enough IMO.
resolve https://github.com/linagora/james-project/issues/4838
> JAMES-3903 Do not run code coverage plugin locally

- protocols/smtp/pom.xml
- protocols/smtp/src/main/java/org/apache/james/protocols/smtp/core/fastfail/SpamTrapHandler.java
- protocols/smtp/src/test/java/org/apache/james/protocols/smtp/core/fastfail/SpamTrapHandlerTest.java
- server/protocols/protocols-smtp/src/main/java/org/apache/james/smtpserver/fastfail/SpamTrapHandler.java
resolve https://github.com/linagora/james-project/issues/4844
Rely on UpdatableTickingClock to avoid CPU resource race condition on the CI that leads to test unstable.
> [BUILD] Fix unstable SpamTrapHandlerTest.testSpamTrap test

- server/mailet/integration-testing/src/test/java/org/apache/james/transport/mailets/ToRepositoryIntegrationTest.java
- server/protocols/webadmin-integration-test/distributed-webadmin-integration-test/src/test/java/org/apache/james/webadmin/integration/rabbitmq/RabbitMQWebAdminServerTaskSerializationIntegrationImmutableTest.java
- server/protocols/webadmin-integration-test/distributed-webadmin-integration-test/src/test/java/org/apache/james/webadmin/integration/rabbitmq/RabbitMQWebAdminServerTaskSerializationIntegrationTest.java
- server/protocols/webadmin/webadmin-core/src/test/java/org/apache/james/webadmin/WebAdminUtils.java
- server/protocols/webadmin/webadmin-data/src/main/java/org/apache/james/webadmin/routes/DomainsRoutes.java
- server/protocols/webadmin/webadmin-data/src/main/java/org/apache/james/webadmin/routes/MailAddressParser.java
- server/protocols/webadmin/webadmin-data/src/main/java/org/apache/james/webadmin/routes/RegexMappingRoutes.java
- server/protocols/webadmin/webadmin-data/src/test/java/org/apache/james/webadmin/routes/AddressMappingRoutesTest.java
- server/protocols/webadmin/webadmin-data/src/test/java/org/apache/james/webadmin/routes/AliasRoutesTest.java
- server/protocols/webadmin/webadmin-data/src/test/java/org/apache/james/webadmin/routes/DomainsRoutesTest.java
- server/protocols/webadmin/webadmin-data/src/test/java/org/apache/james/webadmin/routes/ForwardRoutesTest.java
- server/protocols/webadmin/webadmin-data/src/test/java/org/apache/james/webadmin/routes/GroupsRoutesTest.java
- server/protocols/webadmin/webadmin-data/src/test/java/org/apache/james/webadmin/routes/RegexMappingRoutesTest.java
- server/protocols/webadmin/webadmin-data/src/test/java/org/apache/james/webadmin/routes/SieveScriptRoutesTest.java
- server/protocols/webadmin/webadmin-data/src/test/java/org/apache/james/webadmin/routes/UserRoutesTest.java
- server/protocols/webadmin/webadmin-mailbox/src/main/java/org/apache/james/webadmin/routes/UserQuotaRoutes.java
- server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/routes/UserMailboxesRoutesTest.java
- server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/routes/UserQuotaRoutesTest.java
- server/protocols/webadmin/webadmin-mailrepository/src/main/java/org/apache/james/webadmin/routes/MailRepositoriesRoutes.java
Currently, we are doing 2 times URL decoding for request param: 1 by Spark and 1 by our own.
That leads to in some cases we need to encode 2 times which is not expected.
E.g we have a bug while creating forward with just 1-time encoding:
```
Original forward address: `bob+tag@b.com`
-> One-time encoded: `bob%2Btag%40b.com`
```
James today decodes the address 2 times:
```
1st decoding result: `bob+tag@b.com`
2nd decoding result: `bob tag@b.com` => invalid Mail Address => Can not create the valid forward...
```
> JAMES-3936 Webadmin: Avoid double decoding request param

- server/apps/distributed-app/docs/modules/ROOT/pages/configure/jmap.adoc
- server/container/guice/protocols/jmap/src/main/java/org/apache/james/jmap/draft/JMAPModule.java
- server/data/data-jmap-cassandra/src/main/java/org/apache/james/jmap/cassandra/upload/CassandraUploadRepository.java
- server/data/data-jmap-cassandra/src/test/java/org/apache/james/jmap/cassandra/upload/CassandraUploadServiceTest.java
- server/data/data-jmap/src/main/java/org/apache/james/jmap/api/upload/JmapUploadQuotaConfiguration.java
- server/data/data-jmap/src/main/java/org/apache/james/jmap/api/upload/UploadServiceDefaultImpl.java
- server/data/data-jmap/src/test/java/org/apache/james/jmap/api/upload/UploadRepositoryContract.scala
- server/data/data-jmap/src/test/java/org/apache/james/jmap/memory/upload/InMemoryUploadServiceTest.java
- server/data/data-jmap/src/test/scala/org/apache/james/jmap/api/upload/UploadServiceContract.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/core/Capability.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/core/JmapRfc8621Configuration.scala
- src/site/xdoc/server/config-jmap.xml
resolve https://github.com/linagora/james-project/issues/4848
TODO:
- Try to use `Flux.window` for batch sorting to avoid OOM upon large upload lists
- Documentation
- ...
> JAMES-3925 Enforce quota for JMAP uploads

- server/apps/distributed-app/docs/modules/ROOT/pages/configure/blobstore.adoc
- server/apps/distributed-app/docs/modules/ROOT/pages/configure/index.adoc
- server/apps/distributed-app/docs/modules/ROOT/pages/configure/redis.adoc
- server/apps/distributed-app/docs/modules/ROOT/pages/operate/guide.adoc
- server/apps/distributed-app/docs/modules/ROOT/pages/operate/metrics.adoc
- server/apps/jpa-smtp-app/README.adoc
- server/grafana-reporting/prometheus-datasource/README.md
- src/homepage/_posts/2016-02-09-jmap.markdown
- src/homepage/howTo/custom-listeners.html
- src/homepage/howTo/custom-smtp-commands.html
- src/homepage/howTo/custom-webadmin-routes.html
- src/homepage/howTo/deleted-messages-vault.html
- src/homepage/howTo/mail-processing.html
- src/site/markdown/server/install/guice-jpa-smtp.md
- src/site/markdown/server/manage-guice-distributed-james.md
- src/site/site.xml
- src/site/xdoc/server/config-blob-export.xml
- src/site/xdoc/server/config-guice.xml
- src/site/xdoc/server/config-redis.xml
- src/site/xdoc/server/config.xml
- src/site/xdoc/server/dev-extend-matcher.xml
- src/site/xdoc/server/dev-extend.xml
- src/site/xdoc/server/feature-performance.xml
- src/site/xdoc/server/feature-security.xml
- src/site/xdoc/server/metrics.xml
- src/site/xdoc/server/monitor-logging.xml
- src/site/xdoc/server/packaging.xml
When I use [siteinspector](https://github.com/siteinspector/siteinspector) to scan dead links of https://james.apache.org/, I get a lot of results. A lot of them were published a long time ago (since 2009...)
In this PR, I just updated the link that I found a new
Here is a full not-found link list
[notFound.csv](https://github.com/apache/james-project/files/12557244/notFound.csv)
> [DOCUMENTATION] Update outdated link, not found link

- server/blob/blob-cassandra/src/main/java/org/apache/james/blob/cassandra/cache/CassandraBlobCacheModule.java
- upgrade-instructions.md
- The use of TWCS creates MANY small SSTABLE and puts a lot of pressure on the Cassandra server.
> JAMES-3135 blob_cache table needs to use STCS

- protocols/smtp/src/main/java/org/apache/james/protocols/smtp/SMTPSessionImpl.java
The address can be null, EG behind an AWS load balancer.
> JAMES-3941 Null check in SMTPSessionImpl

- server/queue/queue-api/src/main/java/org/apache/james/queue/api/MailQueue.java
`enQueue` executed a `.block` on the Cassandra thread.
RabbitMQ was not effected thanks to its own reactive implementation. While other implementations e.g. Pulsar were blocked.
> JAMES-3822 MailQueue::enqueueReactive is blocking and should be executed on the boundedElastic scheduler

- protocols/imap/src/main/java/org/apache/james/imap/processor/AbstractAuthProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/AuthenticateProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/ExpungeProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/fetch/FetchProcessor.java
- protocols/smtp/src/main/java/org/apache/james/protocols/smtp/core/esmtp/AuthCmdHandler.java
- server/container/util/src/main/java/org/apache/james/util/AuditTrail.java
- server/container/util/src/test/java/org/apache/james/util/AuditTrailTest.java
- server/data/data-file/src/main/java/org/apache/james/mailrepository/file/FileMailRepository.java
- server/data/data-jpa/src/main/java/org/apache/james/mailrepository/jpa/JPAMailRepository.java
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/LocalDelivery.java
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/RecipientRewriteTableProcessor.java
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/RemoteDelivery.java
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/delivery/MailDispatcher.java
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/remote/delivery/DeliveryRunnable.java
- server/mailrepository/mailrepository-blob/src/main/scala/org/apache/james/mailrepository/blob/BlobMailRepository.scala
- server/mailrepository/mailrepository-cassandra/src/main/java/org/apache/james/mailrepository/cassandra/CassandraMailRepository.java
- server/mailrepository/mailrepository-memory/src/main/java/org/apache/james/mailrepository/memory/MemoryMailRepository.java
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/Email.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/DelegateSetCreatePerformer.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/DelegateSetDeletePerformer.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/DelegatedAccountDeletePerformer.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailSetDeletePerformer.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailSubmissionSetMethod.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/MailboxSetUpdatePerformer.scala
- server/protocols/protocols-lmtp/src/main/java/org/apache/james/lmtpserver/DataLineLMTPHandler.java
- server/protocols/protocols-lmtp/src/main/java/org/apache/james/lmtpserver/hook/MailboxDeliverToRecipientHandler.java
- server/protocols/protocols-smtp/src/main/java/org/apache/james/smtpserver/SendMailHandler.java
resolve https://github.com/linagora/james-project/issues/4866
> JAMES-3942 Audit user trail

- server/apps/scaling-pulsar-smtp/pom.xml
docker-configuration folder does not exists, was making the docker build with Jib failing for pulsar smtp module.
cc @jeantil :)
> [JAMES-3943] fix package pulsar smtp docker image with jib

- server/container/guice/data-cassandra/src/main/java/org/apache/james/modules/data/CassandraDelegationStoreModule.java
- server/data/data-cassandra/src/main/java/org/apache/james/user/cassandra/CassandraDelegationStore.java
- server/data/data-cassandra/src/main/java/org/apache/james/user/cassandra/CassandraUsersDAO.java
- server/data/data-cassandra/src/test/java/org/apache/james/user/cassandra/CassandraDelegationStoreTest.java
Those are only authorizedAccesses,
authenticated through other means (OIDC,
certificates) that do not correspond to an
actual user (no mails of their own). They
only access mails of others.
Cassandra partial row for keeping track
which users we have access to causes James
to mistakenly list those entries into local
users.
> JAMES-3948 FIX virtual users should not be listed

- server/apps/cassandra-app/sample-configuration/jvm.properties
- server/apps/distributed-app/sample-configuration/jvm.properties
- server/apps/distributed-pop3-app/sample-configuration/jvm.properties
- server/apps/jpa-app/sample-configuration/jvm.properties
- server/apps/jpa-smtp-app/sample-configuration/jvm.properties
- server/apps/memory-app/sample-configuration/jvm.properties
- server/container/guice/jmx/src/main/java/org/apache/james/modules/server/JMXServer.java
- server/container/guice/jmx/src/main/java/org/apache/james/modules/server/JmxConfiguration.java
Non POSIX compliant systems can't manage permissions the right way.
> JAMES-3949 Prevent usage of JMX file auto configuration on Windows

- mailet/api/pom.xml
- mailet/api/src/main/java/org/apache/mailet/LoopPrevention.java
- mailet/api/src/test/java/org/apache/mailet/LoopPreventionTest.java
- server/container/guice/common/src/main/java/org/apache/james/utils/FilteringManagementProbeImpl.java
- server/container/guice/common/src/main/java/org/apache/james/utils/MailRepositoryProbeImpl.java
- server/data/data-jmap-cassandra/src/main/java/org/apache/james/jmap/cassandra/filtering/RuleDTO.java
- server/data/data-jmap/src/main/java/org/apache/james/jmap/api/filtering/Rule.java
- server/data/data-jmap/src/test/java/org/apache/james/jmap/api/filtering/RuleFixture.java
- server/mailet/integration-testing/src/test/java/org/apache/james/mailets/FilterForwardIntegrationTest.java
- server/mailet/integration-testing/src/test/java/org/apache/james/mailets/ForwardIntegrationTest.java
- server/mailet/integration-testing/src/test/java/org/apache/james/mailets/ForwardLoopIntegrationTest.java
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/RecipientRewriteTableProcessor.java
- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/mailet/filter/ActionApplier.java
Prevents infinite email loop with forwards by tracking for which users the forwards where applied.
Tracks both regular forwards and JMAP filters forwards.
CF https://github.com/apache/james-project/pull/1758
> JAMES-3944 FILTER: forward loop issue

- backends-common/postgres/src/main/java/org/apache/james/backends/postgres/PostgresTable.java
- backends-common/postgres/src/main/java/org/apache/james/backends/postgres/PostgresTableManager.java
- backends-common/postgres/src/main/java/org/apache/james/backends/postgres/quota/PostgresQuotaModule.java
- backends-common/postgres/src/test/java/org/apache/james/backends/postgres/PostgresExtensionTest.java
- backends-common/postgres/src/test/java/org/apache/james/backends/postgres/PostgresTableManagerTest.java
- mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/PostgresMailboxAnnotationModule.java
- mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/mail/PostgresMailboxModule.java
- mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/mail/PostgresMessageModule.java
- mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/user/PostgresSubscriptionModule.java
- server/data/data-postgres/src/main/java/org/apache/james/domainlist/postgres/PostgresDomainModule.java
- server/data/data-postgres/src/main/java/org/apache/james/mailrepository/postgres/PostgresMailRepositoryModule.java
- server/data/data-postgres/src/main/java/org/apache/james/rrt/postgres/PostgresRecipientRewriteTableModule.java
- server/data/data-postgres/src/main/java/org/apache/james/user/postgres/PostgresUserModule.java
Would be useful in case jOOQ DSL does not provide support for some queries e.g. create an EXCLUDE constraint.
> JAMES-2586 Add an `addAdditionalAlterQueries` option when declaring Postgres table

- server/apps/postgres-app/sample-configuration/mailetcontainer.xml
It caused the postgres-app docker can not start.
Again, an issue because of merging PRs in parallel.
> JAMES-2586 Fix repositoryPath in postgres-app mailetcontainer.xml

- backends-common/postgres/src/main/java/org/apache/james/backends/postgres/PostgresCommons.java
- mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/mail/PostgresMessageMapper.java
- mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/mail/PostgresMessageModule.java
- mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/mail/dao/PostgresMailboxMessageDAO.java
- mailbox/postgres/src/test/java/org/apache/james/mailbox/postgres/mail/PostgresMapperProvider.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/FlagsUpdateCalculator.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/MessageMapperTest.java
- James will fetch current flags from the database -> evaluate the new updatedFlag based on request -> update the new flags to the database 
- Based on the update flags mode (append, remove, replace) then will directly update to flags in the database (without fetching before)
> JAMES-2586 Fix [PGSQL] Concurrency control for flags updates

- mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/mail/dao/PostgresMailboxMessageDAO.java
- mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/search/AllSearchOverride.java
- mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/search/DeletedSearchOverride.java
- mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/search/DeletedWithRangeSearchOverride.java
- mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/search/NotDeletedWithRangeSearchOverride.java
- mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/search/UidSearchOverride.java
- mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/search/UnseenSearchOverride.java
- mailbox/postgres/src/test/java/org/apache/james/mailbox/postgres/search/AllSearchOverrideTest.java
- mailbox/postgres/src/test/java/org/apache/james/mailbox/postgres/search/DeletedSearchOverrideTest.java
- mailbox/postgres/src/test/java/org/apache/james/mailbox/postgres/search/DeletedWithRangeSearchOverrideTest.java
- mailbox/postgres/src/test/java/org/apache/james/mailbox/postgres/search/NotDeletedWithRangeSearchOverrideTest.java
- mailbox/postgres/src/test/java/org/apache/james/mailbox/postgres/search/SearchOverrideFixture.java
- mailbox/postgres/src/test/java/org/apache/james/mailbox/postgres/search/UidSearchOverrideTest.java
- mailbox/postgres/src/test/java/org/apache/james/mailbox/postgres/search/UnseenSearchOverrideTest.java
- server/apps/postgres-app/sample-configuration-distributed/opensearch.properties
Todo:
Technically, if I'm not wrong, with the searchModuleChooser integrated, the conf is already there, and there is no need to care about bindings?
> JAMES-2586 Implement Postgresql search overrides

- backends-common/postgres/pom.xml
jooq 3.16 (latest version for JDK 11 support) is in the end-of-life stage. We may need to consider pushing James to JDK 17 soon...
> [UPDATE] jooq and r2dbc-postgresql version

- backends-common/postgres/src/main/java/org/apache/james/backends/postgres/PostgresTableManager.java
- server/container/guice/common/src/main/java/org/apache/james/utils/InitializationOperations.java
- server/container/guice/configuration/src/main/java/org/apache/james/utils/InitializationOperation.java
- server/container/guice/configuration/src/main/java/org/apache/james/utils/InitilizationOperationBuilder.java
- server/container/guice/postgres-common/src/main/java/org/apache/james/modules/data/PostgresCommonModule.java
- Because using `InitializationOperation` for init postgres does not ensure the sort order. 
Hence James will throw an exception at DomainList init when starting. 
More detail: https://github.com/apache/james-project/pull/1807#issuecomment-1835691054
- Currently, we bypass it by moving `initPostgres()` inside the constructor of `PostgresTableManager` => when Guice loads inject constructor, it will also run `initPostgres()`
It works, but we can refactor it by adding the "priority" in `InitializationOperation`, then we can sort the list before running the init method. 
In this way, not only `PostgresTableManger`, we can get the benefit in the future when similar cases
> JAMES-2586 Refactor the way initPostgres of PostgresTableManager

- server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/Enqueuer.java
One-liner to correctly propagate the exception up the chain. 3.7.x backport.
> JAMES-3968 Fix mail loss due to RabbitMQ ack failure (3.7.x)

- mailbox/api/src/main/java/org/apache/james/mailbox/model/UpdatedFlags.java
- server/data/data-jmap/src/main/java/org/apache/james/jmap/api/change/EmailChange.java
- server/data/data-jmap/src/main/java/org/apache/james/jmap/api/change/JmapChange.java
- server/data/data-jmap/src/main/java/org/apache/james/jmap/api/change/MailboxAndEmailChange.java
- server/data/data-jmap/src/main/java/org/apache/james/jmap/api/change/MailboxChange.java
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EmailChangesMethodContract.scala
- server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/change/MailboxChangeListenerTest.scala
- Need to consider setFlags(\Deleted) as deleted
- Handle COPY/MOVE as message updates
- Need to handle unset deleted flags
- Need to ignore RECENT changes
- Need to handle clear deleted flags as a create
- Need to noop when deleting a flag marked as deleted
- More resilient when faced with Noop flags updates
- Per message management is now required
> [FIX] Several improvments for /changes and notifications

- server/protocols/protocols-smtp/src/main/java/org/apache/james/smtpserver/fastfail/SPFHandler.java
The original code assumes that there's always a value present, which in my case, it isn't. As a rule of thumb you should always check an Optional<> for presence of the value, instead of directing calling .get() since you'll never know if the value is truly present.
That said, I don't know the implications of not having a SPF Attribute Value present later up in the chain. Maybe some other logic should be implemented when no SPF Attribute Value is present.
> Fix for NoSuchElement in SPFHandler

- protocols/smtp/src/main/java/org/apache/james/protocols/smtp/SMTPSessionImpl.java
- server/protocols/protocols-smtp/src/test/java/org/apache/james/smtpserver/SMTPProxyProtocolTest.java
- server/protocols/protocols-smtp/src/test/resources/smtpserver-proxy.xml
Otherwise, the relaying information is taken from the proxy and not from the source.
> [FIX] SMTP stack should recompute relaying rights upon PROXY message

- server/container/guice/protocols/smtp/src/main/java/org/apache/james/modules/protocols/JSPFModule.java
… DNSService isn't properly registered resulting in an error when wiring up the SPFHandler.
This one-liner solves the issue.
> Fix for GUICE configuration and wiring the SPFHandler (DNSService)

- server/data/data-ldap/src/main/java/org/apache/james/user/ldap/LdapRepositoryConfiguration.java
- server/data/data-ldap/src/main/java/org/apache/james/user/ldap/ReadOnlyLDAPUsersDAO.java
I want a user to authenticate with a login old by one attribute eg `uid` and then use another attribute as a end username eg `mail`.
That way we can set up complex login architecture, eg:
```
uid: device1_bob
mail: bob@linagora.com
password: abc
uid: device2_bob
mail: bob@linagora.com
password: def
```
> [FIX] Enable dynamic translation of LDAP entries

- README.adoc
The project does not seem to build correctly without git presence (as when downloading the files instead of cloning).
This change adds the clone command to the README.
Attempts to close issue [3688](https://issues.apache.org/jira/browse/JAMES-3688).
> JAMES-3688 [DOC] Add git clone command to documentation

- server/apps/postgres-app/sample-configuration/postgres.properties
- Fix the startup docker-compose not work
> JAMES-2586 Disable row-level security by default in postgres.properties

- server/blob/blob-s3/src/test/java/org/apache/james/blob/objectstorage/aws/S3MinioTest.java
I saw lots of builds failing on Minio today. decided to investigate and yeah locally it was very unstable on latest minio image.
Not the first time it happens, so I went back on the latest stable tag that I could get when testing locally and pushed this PR. IDK if the image is buggy or if something slightly changed in minio behavior, but not the issue here.
> [Build][Fix] Fix tag for Minio testing image

- protocols/smtp/src/main/java/org/apache/james/protocols/smtp/core/ReceivedDataLineFilter.java
- server/protocols/protocols-smtp/src/test/java/org/apache/james/smtpserver/SMTPSTest.java
- server/protocols/protocols-smtp/src/test/resources/smtpserver-tls.xml
Follow the following syntax:
```
Received: from localhost (EHLO localhost) ([127.0.0.1])
(using TLSv1.3 with cipher TLS_AES_256_GCM_SHA384)
by hp-HP-ProBook-440-G5 (JAMES SMTP Server ) with ESMTPA ID f3184f40
for <rcpt@localhost>;
Mon, 05 Feb 2024 10:14:49 +0100 (CET)
```
This is useful for instance for Spam detection where we can relay the SSL information to RSpamD.
> [ENHANCEMENT] Add SSL information into SMTP header

- mailbox/api/src/main/java/org/apache/james/mailbox/model/MailboxPath.java
- mailbox/api/src/test/java/org/apache/james/mailbox/model/MailboxPathTest.java
- server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/routes/UserMailboxesRoutesTest.java
Multiline mailbox names could be created through JMAP.
As '*' character is forbidden in mailbox name so
injection of IMAP untagged commands was not possible but this could still be used to inject lines onto
unspecting IMAO clients eg with an hypothetic team mailbox.
Better disactivate.
> [FIX] Prevent creation of multiline mailbox names

- .gitignore
- .mvn/extensions.xml
- .mvn/gradle-enterprise.xml
- pom.xml
As per https://issues.apache.org/jira/browse/JAMES-3978 this PR configure the basics dor develocity integration. 
This brings : 
- build scans at https://ge.apache.org
- automatic build scan upload for CI 
- manual build scan upload for local dev
- build metrics from the accumulated build scans 
- automatic local caching for maven goals that are known by the extension 
- can bring speed up gains for both local and ci builds as long as you remember to include the clean goal 
https://issues.apache.org/jira/browse/JAMES-3978?focusedCommentId=17813731&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17813731
> [JAMES-3978] initial setup of develocity for james build

- mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/user/PostgresSubscriptionModule.java
- server/data/data-jmap-postgres/src/main/java/org/apache/james/jmap/postgres/change/PostgresEmailChangeModule.java
- server/data/data-jmap-postgres/src/main/java/org/apache/james/jmap/postgres/change/PostgresMailboxChangeModule.java
- server/data/data-postgres/src/main/java/org/apache/james/mailrepository/postgres/PostgresMailRepositoryUrlStore.java
- server/data/data-postgres/src/main/java/org/apache/james/rrt/postgres/PostgresRecipientRewriteTableModule.java
Fix error log from postgres when james startup
```
2024-02-06 09:07:22.373 UTC [41] ERROR:  relation "subscription_user_index" already exists
2024-02-06T09:07:22.373765269Z 2024-02-06 09:07:22.373 UTC [41] STATEMENT:  create index "subscription_user_index" on subscription(user_name)
2024-02-06T09:07:22.381077149Z 2024-02-06 09:07:22.381 UTC [41] ERROR:  relation "idx_rrt_target_address" already exists
2024-02-06T09:07:22.381086477Z 2024-02-06 09:07:22.381 UTC [41] STATEMENT:  create index "idx_rrt_target_address" on rrt(target_address)
2024-02-06T09:07:22.385200689Z 2024-02-06 09:07:22.385 UTC [41] ERROR:  relation "idx_email_change_date" already exists
2024-02-06T09:07:22.385207101Z 2024-02-06 09:07:22.385 UTC [41] STATEMENT:  create index "idx_email_change_date" on email_change(date) …
```
> JAMES-2586 Handle case when Postgres index/constraint already exists

- backends-common/postgres/src/main/java/org/apache/james/backends/postgres/quota/PostgresQuotaCurrentValueDAO.java
- mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/mail/PostgresMailboxModule.java
1. [JAMES-2586 Optimize query increase/decrease for Quota Current Value](https://github.com/apache/james-project/commit/721f9c0bfc80974a798b0c45df1498fe0bd0fb95)
The query to increase the current value of the quota is frequently executed. The current SQL query is as follows:
```sql
insert into quota_current_value (
identifier,
component,
type,
"current_value"
)
values (
'$1',
'$2',
'$3',
'$4'
)
on conflict on constraint "quota_current_value_primary_key"
do update
set
"current_value" = ("quota_current_value"."current_value" + $5);
```
This query is verbose and incurs overhead due to constraint checking.
=> The reality is the INSERT statement should be executed only once during initialization, and subsequent operations should use the UPDATE statement.
=> James can handle the INSERT and …
> JAMES-2586 Optimize some postgres query

- pom.xml
Patch updated activemq version from 5.18.2 to 5.18.3 to address CVE-2023-46604
> upgraded activemq to address CVE-2023-46604

- .mvn/gradle-enterprise.xml
- examples/pom.xml
- mpt/core/pom.xml
- pom.xml
- server/apps/scaling-pulsar-smtp/pom.xml
After enabling the build scans  quickly noticed that each full clean install generates extra build scans for mpt-core and testing
I tracked it to a behavior of the javadoc plugin which forks maven goals for dependencies
symptoms are 
```
[INFO] --- javadoc:3.1.1:javadoc (create-javadocs) @ apache-james-mpt-app ---
[INFO] The goal 'org.apache.maven.plugins:maven-javadoc-plugin:3.1.1:javadoc' has not been previously called for the module: 'org.apache.james:testing-base:jar:3.9.0-SNAPSHOT'. Trying to invoke it...
[INFO] The goal 'org.apache.maven.plugins:maven-javadoc-plugin:3.1.1:javadoc' has not been previously called for the module: 'org.apache.james:apache-james-mpt-core:jar:3.9.0-SNAPSHOT'. Trying to invoke it...
[INFO]
```
and 
```
[INFO] --- javadoc:3.1.1:jar (create-javadocs) @ …
```
> [JAMES-3978] avoid forked javadoc goals and associated build scans

- pom.xml
Flaky test detection in develocity requires allowing test retry at least once. While this will probably make our test suite even longer than it already is, it could help prioritize the tests to be fixed to enabled test result remote caching
> [JAMES-3978] activate flaky tests detection

- protocols/netty/src/main/java/org/apache/james/protocols/netty/NettyServer.java
- protocols/smtp/src/main/java/org/apache/james/protocols/smtp/core/HeloCmdHandler.java
- protocols/smtp/src/main/java/org/apache/james/protocols/smtp/core/esmtp/EhloCmdHandler.java
- server/apps/memory-app/src/test/java/org/apache/james/LmtpIntegrationTest.java
- server/protocols/protocols-lmtp/src/test/java/org/apache/james/lmtpserver/LmtpServerTest.java
- server/protocols/protocols-smtp/src/test/java/org/apache/james/smtpserver/SMTPProxyProtocolTest.java
- server/protocols/protocols-smtp/src/test/java/org/apache/james/smtpserver/SMTPServerTest.java
- server/protocols/protocols-smtp/src/test/java/org/apache/james/smtpserver/SMTPTestConfiguration.java
https://datatracker.ietf.org/doc/html/rfc5321#section-4.1.1.1
Syntax:
ehlo           = "EHLO" SP ( Domain / address-literal ) CRLF
helo           = "HELO" SP Domain CRLF
Failing to do so could lead to vulnerabilities eg value injection
in received headers that could lead to arbitrary Received header
crafting and might allow eg to bypass some anti-virus checks.
This is a simple exploit that the non security-expert I am could put together in
2 minutes but other scenarii could leverage this as well.
Tests demanded substancial adaptations to be syntax compliant.
> [FIX] Apply RFC-5321 syntax validation for EHLO

- third-party/crowdsec/README.md
- third-party/crowdsec/src/main/java/org/apache/james/crowdsec/CrowdsecEhloHook.java
- third-party/crowdsec/src/main/java/org/apache/james/crowdsec/CrowdsecSMTPConnectHandler.java
- third-party/crowdsec/src/main/java/org/apache/james/crowdsec/CrowdsecService.java
- third-party/crowdsec/src/test/java/org/apache/james/crowdsec/CrowdsecEhloHookTest.java
- third-party/crowdsec/src/test/java/org/apache/james/crowdsec/CrowdsecExtension.java
- third-party/crowdsec/src/test/java/org/apache/james/crowdsec/CrowdsecSMTPConnectHandlerTest.java
- third-party/crowdsec/src/test/java/org/apache/james/crowdsec/CrowdsecServiceTest.java
EHLO is not required before sending AUTH, therefore blocking on EHLO does't work very well against bruteforce attempts.
This PR introduces a hard connection close when a banned ip attempts to connect again to james even before the IP can send any SMTP command.
> [JAMES-3897] Crowdsec SMTP connect hook

- protocols/netty/src/main/java/org/apache/james/protocols/netty/BasicChannelInboundHandler.java
- server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/ImapChannelUpstreamHandler.java
Client requested protocol TLSv1.1 is not enabled or supported in server context
This benign event should likely not lead to an error log.
> [FIX] Lower log level of SSL handshake exceptions

- server/data/data-api/src/main/java/org/apache/james/vacation/api/AccountId.java
- server/data/data-api/src/test/java/org/apache/james/vacation/api/NotificationRegistryContract.java
- server/data/data-api/src/test/java/org/apache/james/vacation/api/VacationRepositoryContract.java
Easiest way to achieve this goal is to always use lower case in the AccountId wrapper. That should fix the issue everywhere.
Also extended the DAO contracts with tests for case insensitive access.
> JAMES-3991 Vacation handling should be case insensitive

- server/data/data-api/src/main/java/org/apache/james/vacation/api/AccountId.java
- server/data/data-api/src/test/java/org/apache/james/vacation/api/NotificationRegistryContract.java
- server/data/data-api/src/test/java/org/apache/james/vacation/api/VacationRepositoryContract.java
Cherry-Pick from master.
While this is not strictly a bugfix, it solves an inconsistent behavior, so IMO makes sense to have it on the stable branch as well.
> JAMES-3991 Vacation handling should be case insensitive (3.8.x)

- pom.xml
* git-commit-id => upgrade, use config property to inject computed git properties to all projects in the reactor. this avoids querying git for every single projects by reusing the properties found for the first project executed
* remote-resources => disable plugin by default except for the places where it is actually needed and configured (mailet)
> [BUILD PERF] refine plugin settings for faster builds

- pom.xml
sslcontext-kickstart-for-pem updated to latest version 8.3.1 to match BouncyCastle version 1.77 updated in #1975 (sslcontext-kickstart-for-pem 8.1.2 was still using bcpkix-jdk15on 1.70).
>  [UPDATE] sslcontext-kickstart-for-pem to match BC version in #1975

- backends-common/postgres/src/main/java/org/apache/james/backends/postgres/utils/PostgresExecutor.java
- event-bus/postgres/src/main/java/org/apache/james/events/PostgresEventDeadLetters.java
- mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/DeleteMessageListener.java
- mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/mail/dao/PostgresMailboxDAO.java
- mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/mail/dao/PostgresMailboxMessageDAO.java
- server/data/data-jmap-postgres/src/main/java/org/apache/james/jmap/postgres/pushsubscription/PostgresPushSubscriptionDAO.java
- server/data/data-postgres/src/main/java/org/apache/james/sieve/postgres/PostgresSieveScriptDAO.java
- server/data/data-postgres/src/main/java/org/apache/james/user/postgres/PostgresUsersDAO.java
- server/data/data-postgres/src/main/java/org/apache/james/vacation/postgres/PostgresNotificationRegistryDAO.java
Using `EXISTS()` has better performance
Ref:
https://blog.jooq.org/avoid-using-count-in-sql-when-you-could-use-exists/
https://www.jooq.org/doc/3.19/manual/reference/dont-do-this/dont-do-this-count-instead-of-exists/
> JAMES-2586 Avoid Using COUNT() in SQL When You Could Use EXISTS()

- server/container/guice/jpa-common/src/main/java/org/apache/james/modules/data/JPAEntityManagerModule.java
Due to changes introduced with "JAMES-2156 Add configuration option to enable attachment storage for JPA", values for keys `openjpa.Multithreaded` and `attachmentStorage.enabled` set in properties passed to `Persistence.createEntityManagerFactory()` method have incorrect values.
Due to usage of `toString()` method on `Optional<Boolean>` instead of calling it directly on `Boolean`, values are set as `Optional[true]` if they had value `true` causing it to evaluate inside persistence to `false`.
This change fixes this regression restoring ability to set  `openjpa.Multithreaded` and `attachmentStorage.enabled` to values other than `false`.
> Fixed issue with incorrect JPA properties values

- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageIdMapper.java
Default value 32 might be too much
> [FIX] Apply batch size to prefetch

- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/remote/delivery/Bouncer.java
- server/mailet/mailets/src/test/java/org/apache/james/transport/mailets/remote/delivery/BouncerTest.java
See https://issues.apache.org/jira/browse/JAMES-4006
Just moved the "if (!mail.hasSender())" condition to the bounceWithMailetContext() method where it is actually needed.
Adjusted the respective test to expect the null sender mail being passed to the bounce processor.
> JAMES-4006 Bouncer should pass DSN to bounce processor

- protocols/imap/src/main/java/org/apache/james/imap/api/process/ImapSession.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/fetch/FetchProcessor.java
- server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/ImapChannelUpstreamHandler.java
- server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/NettyConstants.java
- server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/NettyImapSession.java
Channel writability is the netty trick for backpressure: as a server you shall avoid writing to a channel that is not writable.
In order to apply this Netty best practice to Apache James we relied on:
- The ImapSession as a mean to communicate between the processor and the channel.
- A sink to bridge the gap from a push oriented architecture (our IMAP stack) to a pull one (netty writability).
In order for it to be merged I would like:
(Cowboy style -> avoid unecessary administrative friction in the validation of that patch that would definitively make me sleep better!)
> JAMES-3997 Netty backpressure for IMAP FETCH

- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EmailSetMethodContract.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/json/EmailGetSerializer.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/json/EmailSetSerializer.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/Email.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/EmailSet.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailSetCreatePerformer.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailSubmissionSetMethod.scala
- server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/json/EmailSetSerializerTest.scala
jira https://issues.apache.org/jira/browse/JAMES-4008
> JAMES-4008 JMAP - Email/set - Should be able to save a draft with invalid email address

- mailbox/store/src/test/resources/eml/james-3901.json
- pom.xml
- server/protocols/jmap-draft/src/test/java/org/apache/james/jmap/draft/methods/MIMEMessageConverterTest.java
Solves https://github.com/linagora/james-project/issues/5080
```
java.lang.IllegalArgumentException: URLDecoder: Incomplete trailing escape (%) pattern
at java.base/java.net.URLDecoder.decode(Unknown Source)
at java.base/java.net.URLDecoder.decode(Unknown Source)
at org.apache.james.mime4j.util.MimeParameterMapping.decodeParameterValue(MimeParameterMapping.java:55)
at org.apache.james.mime4j.util.MimeParameterMapping.addParameter(MimeParameterMapping.java:39)
at org.apache.james.mime4j.field.ContentDispositionFieldLenientImpl.parse(ContentDispositionFieldLenientImpl.java:165)
at org.apache.james.mime4j.field.ContentDispositionFieldLenientImpl.getDispositionType(ContentDispositionFieldLenientImpl.java:72)
at org.apache.james.mime4j.message.MaximalBodyDescriptor.getContentDispositionType(Max …
```
> [UPGRADE] MIME4J 0.8.9 -> 0.8.10

- server/mailet/remote-delivery-integration-testing/src/test/java/org/apache/james/mailets/RemoteDeliveryErrorHandlingTest.java
As we did not await task execution the seond mail repository reprocessing could be triggered while the first one was not even started which would go undetected.
Strictier awaits does the trick
> [BUILD] RemoteDeliveryErrorHandlingTest was unstable

- server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/ImapRequestFrameDecoder.java
Instead, we replace the framer in-place
> [FIX] java.util.NoSuchElementException: requestDecoder

- server/apps/distributed-app/docs/modules/ROOT/partials/RecipientRewriteTable.adoc
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/RecipientRewriteTable.java
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/RecipientRewriteTableProcessor.java
**Why** Destination service might consider Header from do not match sender envelop and reject with a bounce.
This creates an infinite loop.
=> This is **DIRTY FIXING**
Real fix: do like outlook...
- For local domains: like today.
- For remote domains: Wrap the forwarded message ina nested mime part, set subject to the value of the mail.
> JAMES-4003 [FIX] Avoid forwarding bounces as it might create infinite loops

- mailet/icalendar/src/main/java/org/apache/james/transport/mailets/ICalendarParser.java
- Avoid logging the whole ICS in INFO mode
- Reduce the log level to info
This avoids super verbose logs for things that anyway we cannot process...
> [FIX] Calendar parsing: be less verbose

- pom.xml
The issue with submodules has been fixed. What was bothering some of us on other projects using James as a submodule has been fixed and released in this new version, among other things, cf: https://github.com/git-commit-id/git-commit-id-maven-plugin/releases/tag/v8.0.0
I think that should content everybody :)
cc @chibenwa , @jeantil
> Upgrade git-commit-id-maven-plugin to 8.0.0

- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EmailGetMethodContract.scala
Fix test cases `bodyStructureShouldSupportSpecificHeaders`
it fails when run with Distributed test
How to fix:
Replace `"blobId": "1_1"` -> `"blobId": "${messageId.serialize}_1"`
Reference: https://github.com/apache/james-project/blob/aee6550277db4e31099867e1d29c7598f9a4dad9/server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/EmailBodyPart.scala#L136
> JAMES-3419 JMAP EmailBodyPart individual headers - Fix test cases

- backends-common/cassandra/src/main/java/org/apache/james/backends/cassandra/init/ResilientClusterProvider.java
- server/container/guice/cassandra/src/main/java/org/apache/james/modules/mailbox/CassandraCacheSessionModule.java
This was broken, likely upon the cassandra driver upgrade
> [FIX] Enforce a separate keyspace for blob store cache

- server/data/data-jmap-postgres/src/main/java/org/apache/james/jmap/postgres/pushsubscription/PostgresPushSubscriptionDAO.java
- server/data/data-jmap-postgres/src/main/java/org/apache/james/jmap/postgres/pushsubscription/PostgresPushSubscriptionModule.java
- server/data/data-jmap-postgres/src/main/java/org/apache/james/jmap/postgres/pushsubscription/PostgresPushSubscriptionRepository.java
Avoid 2 round trips (checking duplicate deviceClientId + INSERT subscription) when saving a subscription.
> JAMES 2586 PostgresPushSubscriptionRepository: rely on Postgres unique constraint for deviceClientId

- third-party/rspamd/src/main/java/org/apache/james/rspamd/client/RspamdHttpClient.java
- third-party/rspamd/src/test/java/org/apache/james/rspamd/client/RspamdHttpClientTest.java
Technicly this can be caused by buggy IMAP clients
When that happens then this causes a cascade of failures with dead letter as this gets retried.
Better ignore...
> [FIX] RSpamD should not fail when reporting empty body

- backends-common/cassandra/pom.xml
- event-bus/cassandra/pom.xml
- event-sourcing/event-store-cassandra/pom.xml
- mailbox/cassandra/pom.xml
- mailbox/plugin/deleted-messages-vault-cassandra/pom.xml
- mailbox/plugin/quota-mailing-cassandra/pom.xml
- mpt/impl/imap-mailbox/cassandra/pom.xml
- mpt/impl/managesieve/cassandra/pom.xml
- mpt/impl/smtp/cassandra-rabbitmq-object-storage/pom.xml
- mpt/impl/smtp/cassandra/pom.xml
- pom.xml
- server/apps/cassandra-app/pom.xml
- server/apps/distributed-app/pom.xml
- server/apps/distributed-pop3-app/pom.xml
- server/blob/blob-cassandra/pom.xml
- server/data/data-cassandra/pom.xml
- server/data/data-jmap-cassandra/pom.xml
- server/mailrepository/mailrepository-cassandra/pom.xml
- server/protocols/jmap-rfc-8621-integration-tests/distributed-jmap-rfc-8621-integration-tests/pom.xml
- server/queue/queue-rabbitmq/pom.xml
- server/task/task-distributed/pom.xml
Fixes:
- CVE-2024-25710: Denial of service caused by an infinite loop for a corrupted DUMP file
- CVE-2024-26308: OutOfMemoryError unpacking broken Pack200 file
> [UPDATE] commons-compress 1.24.0 -> 1.26.0

- mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/mail/dao/PostgresMailboxMessageDAO.java
- mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/mail/dao/PostgresThreadDAO.java
- server/blob/blob-postgres/src/main/java/org/apache/james/blob/postgres/PostgresBlobStoreDAO.java
- server/data/data-jmap-postgres/src/main/java/org/apache/james/jmap/postgres/identity/PostgresCustomIdentityDAO.java
- server/data/data-jmap-postgres/src/main/java/org/apache/james/jmap/postgres/pushsubscription/PostgresPushSubscriptionDAO.java
When debugging why CI failed at https://github.com/apache/james-project/pull/2048#issuecomment-1987593874
I realized that Jooq will hang when the input to `IN` clause is empty.
=> 
We should check the collection size before the query
> JAMES-2586 [Postgres] FIXUP when query with IN - should pre-check collection size

- protocols/netty/src/main/java/org/apache/james/protocols/netty/BasicChannelInboundHandler.java
- server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/ImapChannelUpstreamHandler.java
This pollutes the logs.
ERROR logs are for really bad thing needing immediate admin attention, ideally triggering an alarm.
Those are not to be triggered when a guy try telnet on a SMTPS endpoint.
Reducing the log level to info would help making james easier to monitor
> [ENHANCEMENT] Decrease log level for "NotSslRecordException"

- server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/ReactiveThrottler.java
- server/protocols/protocols-imap4/src/test/java/org/apache/james/imapserver/netty/ReactiveThrottlerTest.java
POD restart did solve the situation.
Concext: many APPEND request and I suspect our object store to be slow...
> JAMES-4019 ReactiveThrottler should handle better cancellation

- backends-common/postgres/src/main/java/org/apache/james/backends/postgres/PostgresConfiguration.java
- backends-common/postgres/src/test/java/org/apache/james/backends/postgres/PostgresConfigurationTest.java
- server/apps/postgres-app/sample-configuration/postgres.properties
- server/container/guice/postgres-common/src/main/java/org/apache/james/modules/data/PostgresCommonModule.java
Default is disabled in rd2bc conf, which is an issue when trying to connect to a postgresql db using ssl.
Yes it's dirty, it was to be able to test quickly if I could connect to a postgresql db backed up by ovh service or not. 
Result is yes it works :) 
Will work on making the sslMode configurable at least.
Would probably be beneficial to make the all ssl configurable in case James is backed by a postgres db hosted internally with specific ssl certs, but we can probably do that later/have a ticket for it.
> Add sslMode to require in PostgresqlConnectionConfiguration

- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/MailboxSetMethodContract.scala
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/UploadContract.scala
These are the tests that took a lot of time to fully repeat. 
cf: https://ge.apache.org/s/dqudut5akzxr6/tests/goal/org.apache.james:postgres-jmap-rfc-8621-integration-tests:surefire:test@default-test/details/org.apache.james.jmap.rfc8621.postgres.PostgresUploadTest?top-execution=1 
cf: https://ge.apache.org/s/dqudut5akzxr6/tests/goal/org.apache.james:postgres-jmap-rfc-8621-integration-tests:surefire:test@default-test/details/org.apache.james.jmap.rfc8621.postgres.PostgresMailboxSetMethodTest?top-execution=1
Likely overkill to repeat that much, we can reduce the repeat count to save some test runtime...
> JAMES-2586 Reduce repeat count for some JMAP integration tests

- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/core/ProblemDetails.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/MailboxSetCreatePerformer.scala
ERROR level logs:
```
reactor.netty.channel.AbortedException: Connection has been closed
at reactor.netty.http.server.HttpServerOperations.onInboundClose(HttpServerOperations.java:699)
at reactor.netty.channel.ChannelOperationsHandler.channelInactive(ChannelOperationsHandler.java:73)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:305)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274)
at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive(CombinedChannelDuplexHandler.java:418)
at …
```
> [LOGGING] Aborting JMAP upload is too verbose

- mailbox/store/src/main/java/org/apache/james/mailbox/store/ResultUtils.java
- mpt/impl/imap-mailbox/core/src/main/resources/org/apache/james/imap/scripts/FetchRFC822Header.test
Every message has at least one part number.  Non-[MIME-IMB] messages, and non-multipart [MIME-IMB] messages with no encapsulated message, only have a part 1.
> JAMES-4020 Fully comply with RFC-3501 Section 6.4.5

- server/testing/src/main/java/org/apache/james/util/docker/Images.java
cf: https://docs.docker.com/engine/deprecated/#pushing-and-pulling-with-image-manifest-v2-schema-1
Solution: https://hub.docker.com/r/quanth99/rest-smtp-sink
> [FIX] Solve weave/rest-smtp-sink: Docker image manifest v2 schema 1 deprecation issue

- mailbox/api/src/main/java/org/apache/james/mailbox/model/ByteContent.java
- mailbox/api/src/main/java/org/apache/james/mailbox/model/Content.java
- mailbox/api/src/main/java/org/apache/james/mailbox/model/HeaderAndBodyByteContent.java
- mailbox/jpa/src/main/java/org/apache/james/mailbox/jpa/mail/model/openjpa/JPAMailboxMessage.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/MessageResultImpl.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/model/DelegatingMailboxMessage.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/model/Message.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/model/impl/SimpleMessage.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/streaming/InputStreamContent.java
- protocols/imap/src/main/java/org/apache/james/imap/message/BytesBackedLiteral.java
- protocols/imap/src/main/java/org/apache/james/imap/message/Literal.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/fetch/ContentBodyElement.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/fetch/FetchProcessor.java
- server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/ChannelImapResponseWriter.java
Backpressure results.
Set up:
```
channel.config().setWriteBufferWaterMark(new WriteBufferWaterMark(100 * 1024, 500 * 1014));
```
(100 KB low level watermark, 500 KB high level watermark) higher than the defaults to fasten overall streaming.
Results:
Message size (bytes) | Count at which backpressure trigger | Total memory loaded |
---------------------|-------------------------------------|---------------------|
4532                 | NEVER                               |         2.3 MB      |
9032                 | 349                                 |         3.2 MB      |
18032                | 176                                 |         3.2 MB      | 
36032                | 86                                  |         3.1 MB      | 
72032                | 44 …
> JAMES-3977 Accurate backpressure for IMAP FETCH

- server/data/data-file/src/test/java/org/apache/james/rrt/file/RewriteTablesTest.java
Somehow I missed that in https://github.com/apache/james-project/pull/1963/commits/c6f2462a8d8cf7b90c1509ca9c13ae16ecc74ba5 
This commit is to add it back.
> JAMES-3961 data-file RRT test should not fail unstable test phase

- protocols/smtp/src/main/java/org/apache/james/protocols/smtp/core/esmtp/MailSizeEsmtpExtension.java
- server/container/core/src/main/java/org/apache/james/server/core/MimeMessageWrapper.java
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/EmailBodyPart.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/MinimalEmailBodyPart.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/DownloadRoutes.scala
- Avoid needlessly computing part sizes with JMAP message part downloads
- Avoid using synchronized imput stream
- Avoid calling session::getAttachment on each SMTP line
> [PERF] Collection of profiling improvments

- src/site/xdoc/server/dev-build.xml
Otherwise, the old layout would fail checkstyle against the `jakarta` imports.
> [DOC] Update import layout suggestion

- server/mailet/integration-testing/src/test/java/org/apache/james/mailets/MailetErrorsTest.java
- server/mailet/integration-testing/src/test/java/org/apache/james/mailets/NoSuchMethodErrorMailet.java
- server/mailet/mailetcontainer-impl/src/main/java/org/apache/james/mailetcontainer/impl/JamesMailSpooler.java
- server/mailet/mailetcontainer-impl/src/main/java/org/apache/james/mailetcontainer/impl/ProcessorImpl.java
Upon JVM Error, the error would not be caught to be retried. Therefore, the message would not be acked -> RabbitMQ would disconnect the MailQueue consumer after the [Delivery Acknowledgement Timeout](https://www.rabbitmq.com/docs/consumers#acknowledgement-timeout).
For example, a custom mailet that depends on the old `javax` APIs caused `java.lang.NoSuchMethodError: 'javax.mail.internet.MimeMessage org.apache.mailet.Mail.getMessage()` that caused the RabbitMQ consumer being disconnected.
And `NoSuchMethodError` is a subclass of `Throwable`, not `Exception`.
```json
{
"timestamp": "2024-03-26T11:34:42.677Z",
"level": "WARN",
"thread": "spooler-39",
"logger": "reactor.core.Exceptions",
"message": "throwIfFatal detected a jvm fatal exception, which is thrown and logged below:",
"context": …
```
> [FIX] JamesMailSpooler should be more resilient on JVM Error

- backends-common/postgres/src/main/java/org/apache/james/backends/postgres/quota/PostgresQuotaCurrentValueDAO.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/quota/ListeningCurrentQuotaUpdater.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/quota/ListeningCurrentQuotaUpdaterTest.java
It starts from pr: 
- https://github.com/apache/james-project/pull/1984
When I tried to optimize the query, after that it did not ensure the concurrent insert (eg: when provisioning mailbox messages)
To avoid that: I created a pr: 
- https://github.com/apache/james-project/pull/2118
But the fact is it does not work. The Mockito test case did lack cases. 
(The method `getCurrentQuotas` always returns a value even when no record in the database (it returns ZERO value, not empty).
=> Revert before has another better idea
> JAMES-2586 - [Revert] Optimize query increase/decrease for Quota current value 

- server/blob/blob-common/src/main/java/org/apache/james/blob/api/Store.java
- server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/AbstractNettyImapRequestLineReader.java
- server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/NettyStreamImapRequestLineReader.java
I noticed some file descriptors for deleted files:
```
java      1 root  DEL       REG              0,144                   7 /tmp/libnetty_transport_native_epoll_x86_645311867425088058321.so
java      1 root  DEL       REG              0,144                   6 /tmp/jffi8865510689510247619.so
java      1 root  mem-W     REG              0,144     32768         5 /tmp/hsperfdata_root/1
java      1 root  774u     unix 0x0000000000000000       0t0 621499767 /tmp/.java_pid1.tmp type=STREAM
java      1 root  787w      REG              0,144   3022948        16 /tmp/imap-literal11264261390326828628.tmp
java      1 root  934r      REG              0,144    280223         9 /tmp/DelegateCloseableByteSource1691427123218830736.tmp (deleted)
java      1 root  936r      REG              0,144 …
```
> [ENHANCEMENT] Explicitly close FileInputStream

- server/apps/distributed-app/docs/modules/ROOT/pages/run/run-kubernetes.adoc
Very simple typo fix for helm-secrets link in Run with Kubernetes guide.
Updated line 37.
Unclear why line 184,
link:https://helm.sh/docs/chart_template_guide/getting_started/[Helm templates]
is displayed as an deletion and addition by Github.
> Fix simple typo in run-kubernetes.adoc

- server/data/data-postgres/src/main/java/org/apache/james/user/postgres/PostgresUsersDAO.java
- server/data/data-postgres/src/test/java/org/apache/james/user/postgres/PostgresUsersRepositoryTest.java
- server/protocols/webadmin-integration-test/postgres-webadmin-integration-test/src/test/java/org/apache/james/webadmin/integration/postgres/PostgresPopulateEmailQueryViewTaskIntegrationTest.java
Root cause: likely a jooq reactive bug. Likely the query that lists a big amount of users somehow blocks the jooq thread.
Mitigate fix: `collectList` to await the list users query to finish before executing other queries...
A similar fix: https://github.com/apache/james-project/commit/03e4b363409adf197ae3af667996b537a69e934f
> JAMES-2586 PopulateEmailQueryViewTask should not hang for postgres-app

- backends-common/postgres/src/main/java/org/apache/james/backends/postgres/PostgresConfiguration.java
- backends-common/postgres/src/main/java/org/apache/james/backends/postgres/utils/PostgresExecutor.java
- backends-common/postgres/src/test/java/org/apache/james/backends/postgres/PostgresExtension.java
- mailbox/postgres/src/test/java/org/apache/james/mailbox/postgres/mail/PostgresAnnotationMapperRowLevelSecurityTest.java
- mailbox/postgres/src/test/java/org/apache/james/mailbox/postgres/mail/PostgresMailboxMapperRowLevelSecurityTest.java
- mailbox/postgres/src/test/java/org/apache/james/mailbox/postgres/mail/PostgresMessageMapperRowLevelSecurityTest.java
- mailbox/postgres/src/test/java/org/apache/james/mailbox/postgres/user/PostgresSubscriptionMapperRowLevelSecurityTest.java
- server/apps/postgres-app/sample-configuration/postgres.properties
- server/container/guice/postgres-common/src/main/java/org/apache/james/modules/data/PostgresCommonModule.java
Allow James to recover upon jOOQ reactive hanging bug. Also log error so we can monitor and fix the potential issues.
> JAMES-2586 Apply reactor timeout for jOOQ

- server/apps/distributed-app/sample-configuration/mailetcontainer.xml
At commit: https://github.com/apache/james-project/pull/2139/files#diff-cff23544a088a4764e404fea6ba9c132649cbcbdcab611c71d3e9affcedf126f  
It should be "Bounce", not "MetricsMailet"
The MetricsMailet without `metricName` make NullPointerException  (when startup james docker compose)
```
10:22:37.356 [ERROR] o.a.j.m.l.AbstractStateMailetProcessor - Unable to init mailet MetricsMailet
2024-04-05T10:22:37.357306362Z java.lang.NullPointerException: null
2024-04-05T10:22:37.357309458Z 	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:903)
2024-04-05T10:22:37.357312423Z 	at org.apache.james.transport.mailets.MetricsMailet.init(MetricsMailet.java:63)
2024-04-05T10:22:37.357315339Z 	at org.apache.james.transport.mailets.MetricsMailet.init(MetricsMailet.java:59) …
```
> [FIX] Avoid sending bounce when reprocessing - fix mailet class

- server/apps/distributed-app/docs/modules/ROOT/pages/run/k8s-values.adoc
- server/apps/distributed-app/helm-chart/james/templates/james-admin-ingress.yaml
- server/apps/distributed-app/helm-chart/james/templates/jmap-ingress.yaml
- server/apps/distributed-app/helm-chart/james/values.yaml
For James Helm Chart, the current version uses kubernetes.io/ingress.class annotation that has been deprecated. It is encouraged to use ingressClassName instead for Kubernetes v1.18+.
> Added ingressClassName support and adminIngress for k8s

- pom.xml
- server/apps/cassandra-app/sample-configuration/jvm.properties
- server/apps/distributed-pop3-app/sample-configuration/jvm.properties
- server/apps/jpa-app/sample-configuration/jvm.properties
- server/apps/jpa-smtp-app/sample-configuration/jvm.properties
- server/apps/memory-app/sample-configuration/jvm.properties
- server/apps/scaling-pulsar-smtp/sample-configuration/jvm.properties
- server/protocols/jwt/pom.xml
- server/protocols/jwt/src/main/java/org/apache/james/jwt/JwtTokenVerifier.java
- server/protocols/jwt/src/test/java/org/apache/james/jwt/OidcJwtTokenVerifierTest.java
- server/protocols/jwt/src/test/java/org/apache/james/jwt/OidcTokenFixture.java
jjwt support zip by default yet uncompression of untrusted data can result in excessive memory/cpu usage for special crafted malicious payload.
> [FIX] JWT should not attempt to unzip data by default

- server/mailrepository/mailrepository-cassandra/src/main/java/org/apache/james/mailrepository/cassandra/CassandraMailRepository.java
Have the repository URL and the error for sure is nice. 
I miss those on a mail loop investigation, getting the history of errors, that I cannot otherwise find in logs, would be handy.
> [ENHANCEMENT] More information in mailrepository audit log

- backends-common/redis/src/main/java/org/apache/james/backends/redis/RedisConfiguration.scala
- backends-common/redis/src/test/java/org/apache/james/backends/redis/RedisConfigurationTest.scala
- Before: Ex: redisURL=redis://redis1:6379,redis://redis2:6379 Then RedisUris has size = 1
When runtime, the `Configuration` is `org.apache.james.utils.DelegatedPropertiesConfiguration` with `delimiter` is `,` 
=> `config.getString("redisURL")` return only the first element of an array
RedisUris has size = 2 with example above
> JAMES-3693 Fixup parsing `redisURL` when cluster with multi url endpoint

- protocols/imap/src/main/java/org/apache/james/imap/processor/fetch/FetchProcessor.java
The log mistakenly lead to think backpressure was restored multiple time
> [FIX] FetchProcessor: only log Resuming IMAP FETCH once

- protocols/netty/src/main/java/org/apache/james/protocols/netty/BasicChannelInboundHandler.java
- protocols/netty/src/main/java/org/apache/james/protocols/netty/LineHandlerUpstreamHandler.java
- server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/HAProxyMessageHandler.java
In production logs:
```
java.lang.IllegalArgumentException: username local part should not be empty
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143)
at org.apache.james.core.Username.<init>(Username.java:81)
at org.apache.james.core.Username.fromLocalPartWithDomain(Username.java:58)
at org.apache.james.core.Username.fromLocalPartWithDomain(Username.java:52)
at org.apache.james.core.Username.of(Username.java:46)
at org.apache.james.protocols.smtp.core.esmtp.AuthCmdHandler.doLoginAuthPass(AuthCmdHandler.java:327)
at org.apache.james.protocols.smtp.core.esmtp.AuthCmdHandler$2.onCommand(AuthCmdHandler.java:190)
at org.apache.james.protocols.smtp.core.esmtp.AuthCmdHandler$AbstractSMTPLineHandler.handleCommand(AuthCmdHandler.java:109)
at …
```
> [FIX] Leak upon unmanaged SMTP error

- protocols/imap/src/main/java/org/apache/james/imap/api/process/ImapLineHandler.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/AuthenticateProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/IdleProcessor.java
- server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/ImapLineHandlerAdapter.java
Line handlers overrides are run directly on the event loop and thus should be non-blocking. We thus redefine them as a reactive construct in order to handle them asynchronously might it need be.
This finding was done by doing wall clock profiling.
Command used:
```
./profiler.sh -e wall -d 600 -t -i 1ms -I '*james*' -X '*JamesMailSpooler*' -X '*smtp*' -f /root/wall7.html 1
```
(this command assume that blocking calls will be done in apache james and narrow the traces, exclude known blocking patterns handled safely)
> [FIX] Remove some blocking calls in IMAP event loop

- server/blob/blob-aes/src/main/java/org/apache/james/blob/aes/AESBlobStoreDAO.java
- server/blob/blob-aes/src/main/java/org/apache/james/blob/aes/PBKDF2StreamingAeadFactory.java
Prevent needless copies / reallocations
> [ENHANCEMENT] Use the correct AES segment size

- server/container/util/src/main/java/org/apache/james/util/StreamUtils.java
- server/container/util/src/test/java/org/apache/james/util/StreamUtilsTest.java
- server/data/data-api/src/main/java/org/apache/james/rrt/api/AliasReverseResolver.java
- server/data/data-api/src/main/java/org/apache/james/rrt/api/CanSendFrom.java
- server/data/data-api/src/main/java/org/apache/james/rrt/api/RecipientRewriteTable.java
- server/data/data-api/src/test/java/org/apache/james/rrt/lib/AliasReverseResolverContract.java
- server/data/data-api/src/test/java/org/apache/james/rrt/lib/CanSendFromContract.java
- server/data/data-cassandra/src/main/java/org/apache/james/rrt/cassandra/CassandraRecipientRewriteTable.java
- server/data/data-jmap/src/main/scala/org/apache/james/jmap/api/identity/CustomIdentityDAO.scala
- server/data/data-jmap/src/test/scala/org/apache/james/jmap/api/identity/IdentityRepositoryTest.scala
- server/data/data-library/src/main/java/org/apache/james/rrt/lib/AliasReverseResolverImpl.java
- server/data/data-library/src/main/java/org/apache/james/rrt/lib/CanSendFromImpl.java
- server/data/data-memory/src/test/java/org/apache/james/rrt/lib/CanSendFromImplTest.java
- server/protocols/protocols-lmtp/src/test/java/org/apache/james/lmtpserver/LmtpServerTest.java
- server/protocols/protocols-smtp/src/test/java/org/apache/james/smtpserver/SMTPServerTestSystem.java
- server/protocols/webadmin/webadmin-data/src/main/java/org/apache/james/webadmin/routes/UserRoutes.java
- server/protocols/webadmin/webadmin-data/src/test/java/org/apache/james/webadmin/routes/UserRoutesTest.java
- server/protocols/webadmin/webadmin-jmap/src/test/java/org/apache/james/webadmin/data/jmap/UserIdentitiesRoutesTest.java
The underlying RRT exposes iterables which are inherantly blocking.
`recipientRewriteTable.listSources(...)` actually is just a mere wrapper around a cassandra table and would be easy to reactify.
Then the overall algorithm could be reactified CF https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html#expand-java.util.function.Function-
This is called upon sending email (likely to be blocking anyway) but also listing identities which is not an uncommon request.
> [ENHANCEMENT] Better reactify Identity methods

- server/protocols/jmap-rfc-8621-integration-tests/distributed-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/distributed/DistributedPushSubscriptionSetMethodTest.java
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/PushSubscriptionSetMethodContract.scala
- server/protocols/jmap-rfc-8621-integration-tests/memory-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/memory/MemoryPushSubscriptionSetMethodTest.java
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/PushSubscriptionGetMethod.scala
Clients may not destroy the expired subscription well -> dangling Push subscriptions.
We should better clean expired Push subscriptions. It is aligned with the JMAP specs: `It MAY automatically destroy the push subscription at or after this time.`
> JAMES-3539 Backend should clean expired Push subscriptions

- backends-common/redis/src/main/java/org/apache/james/backends/redis/RedisHealthCheck.scala
- backends-common/redis/src/test/java/org/apache/james/backends/redis/DockerRedis.java
- backends-common/redis/src/test/java/org/apache/james/backends/redis/RedisClusterExtension.java
- backends-common/redis/src/test/java/org/apache/james/backends/redis/RedisClusterHealthCheckTest.scala
- backends-common/redis/src/test/java/org/apache/james/backends/redis/RedisStandaloneHealthCheckTest.scala
- backends-common/redis/src/test/resources/redis_cluster.conf
The healthcheck: `org.apache.james.backends.redis.RedisHealthCheck` always log can not connect to Redis.
even when Redis cluster work up normal
- Before invoking method `redisClusterClient.connectAsync` we need to initial partition first by invoking method `redisClusterClient.getPartitions
- The method `redisClusterClient.connectAsync(StringCodec.UTF8)` always success when the cluster fail (eg: 1 /3 node down) => We need one more step for checking. 
- call `.getPartitions` first, then `.connectAsync` -> `.clusterInfo()`
> JAMES-3693 Fixup RedisHealthCheck wrong check when Redis Cluster

- server/mailet/rate-limiter-redis/docker-compose.yml
- server/mailet/rate-limiter-redis/healthcheck.properties
- server/mailet/rate-limiter-redis/src/main/scala/org/apache/james/rate/limiter/redis/RedisRateLimiter.scala
James can not start when running rate-limiter-redis docker-compose: https://github.com/apache/james-project/blob/master/server/mailet/rate-limiter-redis/docker-compose.yml
Error
```
03:32:17.943 [INFO ] o.a.j.u.GuiceGenericLoader - Enabling injects contained in org.apache.james.rate.limiter.redis.RedisRateLimiterModule
2024-05-07T03:32:17.961261846Z 03:32:17.954 [ERROR] o.a.j.GuiceJamesServer - Fatal error while starting James
2024-05-07T03:32:17.961282565Z com.google.inject.ProvisionException: Unable to provision, see the following errors:
2024-05-07T03:32:17.961285240Z 
2024-05-07T03:32:17.961287504Z 1) [Guice/BindingAlreadySet]: Set<HealthCheck> was bound multiple times.
2024-05-07T03:32:17.961290069Z 
2024-05-07T03:32:17.961292093Z Bound at:
2024-05-07T03:32:17.961294147Z 1  : …
```
> JAMES-3693 Fix guice binding Redis Health check in RateLimiter module

- metrics/metrics-api/src/main/java/org/apache/james/metrics/api/TimeMetric.java
- metrics/metrics-dropwizard/src/main/java/org/apache/james/metrics/dropwizard/DropWizardTimeMetric.java
- metrics/metrics-dropwizard/src/test/java/org/apache/james/metrics/dropwizard/DropWizardMetricFactoryTest.java
- metrics/metrics-logger/src/main/java/org/apache/james/metrics/logger/DefaultTimeMetric.java
- metrics/metrics-tests/src/main/java/org/apache/james/metrics/tests/RecordingTimeMetric.java
- server/apps/distributed-app/docs/modules/ROOT/pages/configure/jvm.adoc
- server/apps/scaling-pulsar-smtp/src/main/java/org/apache/james/Main.java
- server/blob/blob-s3/pom.xml
- server/blob/blob-s3/src/main/java/org/apache/james/blob/objectstorage/aws/JamesS3MetricPublisher.java
- server/blob/blob-s3/src/main/java/org/apache/james/blob/objectstorage/aws/S3BlobStoreDAO.java
- server/blob/blob-s3/src/test/java/org/apache/james/blob/objectstorage/aws/S3BlobStoreDAOTest.java
- server/blob/blob-s3/src/test/java/org/apache/james/blob/objectstorage/aws/S3DeDuplicationBlobStoreTest.java
- server/blob/blob-s3/src/test/java/org/apache/james/blob/objectstorage/aws/S3HealthCheckTest.java
- server/blob/blob-s3/src/test/java/org/apache/james/blob/objectstorage/aws/S3MinioTest.java
- server/blob/blob-s3/src/test/java/org/apache/james/blob/objectstorage/aws/S3NamespaceTest.java
- server/blob/blob-s3/src/test/java/org/apache/james/blob/objectstorage/aws/S3PassThroughBlobStoreTest.java
- server/blob/blob-s3/src/test/java/org/apache/james/blob/objectstorage/aws/S3PrefixAndNamespaceTest.java
- server/blob/blob-s3/src/test/java/org/apache/james/blob/objectstorage/aws/S3PrefixTest.java
- server/container/guice/distributed/src/main/java/org/apache/james/modules/blobstore/BlobStoreModulesChooser.java
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/DownloadRoutes.scala
Print some S3 client buillt-in metrics:
```log
17:47:15.719 [INFO ] s.a.a.m.LoggingMetricPublisher - [94c9c81] ApiCall
17:47:15.719 [INFO ] s.a.a.m.LoggingMetricPublisher - [94c9c81] ┌─────────────────────────────────────────┐
17:47:15.719 [INFO ] s.a.a.m.LoggingMetricPublisher - [94c9c81] │ MarshallingDuration=PT0.000082267S      │
17:47:15.719 [INFO ] s.a.a.m.LoggingMetricPublisher - [94c9c81] │ RetryCount=0                            │
17:47:15.719 [INFO ] s.a.a.m.LoggingMetricPublisher - [94c9c81] │ ApiCallSuccessful=true                  │
17:47:15.719 [INFO ] s.a.a.m.LoggingMetricPublisher - [94c9c81] │ OperationName=DeleteBucket              │
17:47:15.719 [INFO ] s.a.a.m.LoggingMetricPublisher - [94c9c81] │ ApiCallDuration=PT0.011391168S          │
17:47:15.719 [INFO ] …
```
> [METRICS] Add some useful S3 connection metrics

- backends-common/redis/src/main/java/org/apache/james/backends/redis/RedisConfiguration.scala
- backends-common/redis/src/main/java/org/apache/james/backends/redis/RedisHealthCheck.scala
- backends-common/redis/src/test/java/org/apache/james/backends/redis/RedisClusterExtension.java
- backends-common/redis/src/test/java/org/apache/james/backends/redis/RedisConfigurationTest.scala
- backends-common/redis/src/test/java/org/apache/james/backends/redis/RedisExtension.java
- backends-common/redis/src/test/java/org/apache/james/backends/redis/RedisMasterReplicaExtension.java
- backends-common/redis/src/test/java/org/apache/james/backends/redis/RedisMasterReplicaHealthCheckTest.scala
- backends-common/redis/src/test/java/org/apache/james/backends/redis/RedisStandaloneHealthCheckTest.scala
- server/apps/distributed-app/docs/modules/ROOT/pages/configure/redis.adoc
- server/mailet/rate-limiter-redis/redis.properties
- server/mailet/rate-limiter-redis/src/main/java/org/apache/james/rate/limiter/redis/RedisMasterReplicaRateLimiterFactory.java
- server/mailet/rate-limiter-redis/src/main/scala/org/apache/james/rate/limiter/redis/RedisRateLimiter.scala
- server/mailet/rate-limiter-redis/src/test/java/org/apache/james/rate/limiter/RedisRateLimiterTest.scala
- server/mailet/rate-limiter-redis/src/test/java/org/apache/james/rate/limiter/RedisRateLimiterWithMasterReplicaTopologyTest.scala
https://github.com/linagora/james-project/issues/5172
RedisRateLimiter is not updated because I see that ratelimit library mostly run redisScriptingReactiveCommands.evalsha which has to work with master node (this method is used to run lua script).
> James 3693 update redis config to support read from replicas

- backends-common/rabbitmq/src/main/java/org/apache/james/backends/rabbitmq/QueueArguments.java
- backends-common/rabbitmq/src/main/java/org/apache/james/backends/rabbitmq/RabbitMQConfiguration.java
- upgrade-instructions.md
Claimed to be better than version 1 cf:
- https://www.rabbitmq.com/blog/2023/05/17/rabbitmq-3.12-performance-improvements#classic-queues-massively-improved-classic-queues-v2-cqv2
- https://www.rabbitmq.com/blog/2023/05/17/rabbitmq-3.12-performance-improvements#312-cqv1-vs-cqv2
Better performance overall (p99 805ms vs 914ms).
SELECT p99 1874ms vs 2049ms
UNSELECT p99 1420ms vs 1755ms
> [ENHANCEMENT] Apply RabbitMQ classic queue version 2

- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/MDNSendMethodContract.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/MDNSendMethod.scala
3% of CPU wall time on CNB JMAP pods. Contributes to 12% of overall blockingCallWrapper thread usage.
Along with 18% of XUser...
This move would help slightly lowering the count of threads and limit context switches.
> [ENHANCEMENT] MDN/send shall be reactive

- protocols/smtp/src/main/java/org/apache/james/protocols/smtp/core/AbstractSenderAuthIdentifyVerificationHook.java
- server/mailet/integration-testing/src/test/java/org/apache/james/smtp/SmtpIdentityVerificationTest.java
- server/protocols/protocols-smtp/src/main/java/org/apache/james/smtpserver/SenderAuthIdentifyVerificationHook.java
Will ease channel pool sizing as well as debugging of RabbitMQ channelPool related errors.
> JAMES-4034 SMTP submission: validate FROM header

- server/apps/distributed-app/docs/modules/ROOT/pages/configure/jvm.adoc
- server/apps/distributed-app/sample-configuration/jvm.properties
- server/container/util/src/main/java/org/apache/james/util/ReactorUtils.java
`boundedElastic` threads as well as AWS response threads spends a lot of time blocking on this, adding a prefertch could smooth things up and help having a lower thread count as well as lower user facing latencies.
Up to 25% wall clock time.
> [ENHANCEMENT] Allow custom prefetch in Flux => InputStream convertions

- mailbox/plugin/deleted-messages-vault-postgres/src/main/java/org/apache/james/vault/metadata/PostgresDeletedMessageVaultDeletionCallback.java
- server/container/guice/mailbox-postgres/src/main/java/org/apache/james/modules/mailbox/PostgresDeletedMessageVaultModule.java
To fix exception: 
`java.lang.ClassCastException: class org.apache.james.vault.metadata.DeletedMessageVaultDeletionCallback cannot be cast to class org.apache.james.mailbox.postgres.DeleteMessageListener$DeletionCallback (org.apache.james.vault.metadata.DeletedMessageVaultDeletionCallback and org.apache.james.mailbox.postgres.DeleteMessageListener$DeletionCallback are in unnamed module of loader 'app')`
because we have 2 classes that have the same name, and same package: `org.apache.james.modules.mailbox.DeletedMessageVaultModule` : one for Cassandra, one for Postgres
> JAMES-2586 - Rename class DeletedMessageVaultDeletionCallback -> PostgresDeletedMessageVaultDeletionCallback

- server/data/data-jmap/src/main/java/org/apache/james/jmap/api/projections/MessageFastViewProjectionHealthCheck.java
We observe some warning from perfectly well running systems. This threshold is hard coded, a bit of liberty can be nice.
> [IMPROVEMENT] Configure fastview projection miss threshold

- server/task/task-distributed/src/main/java/org/apache/james/task/eventsourcing/distributed/RabbitMQWorkQueue.java
- server/task/task-distributed/src/test/java/org/apache/james/task/eventsourcing/distributed/RabbitMQWorkQueueTest.java
This avoids a long task to crash the consumer. Instead the task is aborted and marked as "failed".
> JAMES-3955 Software timeout before consumer timeout

- event-bus/api/src/test/java/org/apache/james/events/EventBusConcurrentTestContract.java
- event-bus/in-vm/src/main/java/org/apache/james/events/InVMEventBus.java
- event-bus/in-vm/src/test/java/org/apache/james/events/InVMEventBusTest.java
It used to throw a `ConcurrentModificationException` when there was a high level of concurrency.
Here's a simple demo that reproduces the issue:
```java
import java.util.Collections;
import java.util.HashMap;
import java.util.concurrent.ConcurrentHashMap;
import java.util.function.Supplier;
import java.util.stream.IntStream;
import com.google.common.collect.HashMultimap;
import com.google.common.collect.Multimap;
import com.google.common.collect.Multimaps;
public class SimpleDemo {
private static final String KEY = "key";
public static void main(String[] args) {
System.out.println("Thread safe demo");
demo(SimpleDemo::threadSafe);
System.out.println("Partially thread safe demo");
demo(SimpleDemo::partiallyThreadSafe);
}
private static Multimap<String, Integer> threadSafe() {
return …
```
> [FIX] registrations multimap made fully thread safe

- mailbox/api/src/main/java/org/apache/james/mailbox/model/MailboxACL.java
The method was buggy as always returning true.
It is not being used anywhere anyway.
> [CLEAN CODE] Remove unused buggy Rfc4314Rights::isSupported

- protocols/imap/src/main/java/org/apache/james/imap/processor/AbstractAuthProcessor.java
With PLAIN auth, flushing before popping `ImapLineHandler` in `AuthenticateProcessor` will result sometimes in this `ImapLineHandler` to also consume the next IMAP command.
It can be reproduced with this simple demo:
```java
for (var i = 0; i < 10_000; i++) {
Session.getInstance(getProperties()).getStore().connect("user", "password");
}
```
Without this patch, the problem occurs on average every 500 authentications in my environment.
With the patch, the demo loop completes every time.
> [FIX] race condition avoided

- backends-common/postgres/src/test/java/org/apache/james/backends/postgres/PostgresExtension.java
- server/blob/blob-postgres/src/test/java/org/apache/james/blob/postgres/PostgresBlobStoreDAOTest.java
After Apache James CI issue with infra recently, the tests are somehow more unstable. 
`PostgresBlobStoreDAOTest.concurrentSaveInputStreamShouldReturnConsistentValues`:
```java
18:39:45.087 [ERROR] o.a.j.b.p.u.PostgresExecutor - Time out executing Postgres query. May need to check either jOOQ reactive issue or Postgres DB performance.
java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 10000ms in 'flatMap' (and no fallback has been configured)
```
Note that the failure rate locally is really low though...
> [BUILD] Increase jOOQ reactive timeout for testing

- core/src/test/java/org/apache/james/core/MailAddressTest.java
- core/src/test/java/org/apache/james/core/UsernameTest.java
- mailbox/event/json/src/test/java/org/apache/james/event/json/dtos/QuotaRootTest.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/quota/DefaultUserQuotaRootResolver.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/quota/DefaultUserQuotaRootResolverTest.java
- server/mailet/integration-testing/src/test/java/org/apache/james/mailets/SieveDelivery.java
- server/mailet/ldap/pom.xml
- server/mailet/ldap/src/main/java/org/apache/james/transport/matchers/HasLDAPAttribute.java
Reported by @samiulsami on gitter chat.
Delivery to this valid mail address and username failed due to quota root limitations that was not pushed to system edge.
We lift this limitation bu reworking the way
DefaultUserQuotaRootResolver is working.
> [FIX] Allow delivering emails to a&b@linagora.com

- server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/ImapRequestFrameDecoder.java
- server/protocols/protocols-imap4/src/test/java/org/apache/james/imapserver/netty/IMAPServerTest.java
Handling several literal within the same network frame was broken when literal size exceeded 16.
Solution was to not rely on Netty cumulation but implement our own.
> JAMES-4043 Improve literal handling

- server/data/data-jmap-postgres/src/main/java/org/apache/james/jmap/postgres/change/PostgresEmailChangeModule.java
- server/data/data-jmap-postgres/src/main/java/org/apache/james/jmap/postgres/change/PostgresMailboxChangeModule.java
As the logic of method [MailboxAndEmailChange.Factory#fromExpunged](https://github.com/apache/james-project/blob/ae536b8dbc8ab2f56d6eea5610c9a0e175a4703e/server/data/data-jmap/src/main/java/org/apache/james/jmap/api/change/MailboxAndEmailChange.java#L151)
We can have 2 records that have the same `accountId` & `state`, but  different `is_share`
> JAMES-2586 - Update primaryKey constraint for Postgres mailbox_change and email_change

- server/protocols/protocols-library/src/main/java/org/apache/james/protocols/lib/netty/AbstractConfigurableAsyncServer.java
Otherwise, the client can not be aware of the actual result of the request because the eventloop can not return the actual result executed by the executor and the client may retry e.g. send 2 identical emails.
A test tries to fire SMTP requests during the shutdown:
```java
@Test
void test() throws Exception {
// Connect 10000 SMTP clients before sending requests
List<Pair<SMTPClient, Integer>> smtpClients = Flux.fromStream(IntStream.rangeClosed(1, 10000).boxed())
.map(Throwing.function(counter -> {
SMTPClient smtpClient = new SMTPClient();
InetSocketAddress bindedAddress = testSystem.getBindedAddress();
smtpClient.connect(bindedAddress.getAddress().getHostAddress(), bindedAddress.getPort());
smtpClient.sendCommand("EHLO whatever.tld");
return Pair.of(smtpClient, counter);
})) …
```
> JAMES-4023 Graceful shutdown: executor should be shutdown before eventloop

- docs/modules/servers/nav.adoc
Mistake I did when rebasing last time the migration work on antora distributed doc, sorry.
The menu item for droplists is creating a mess with the distributed doc menu in configure section. This should fix it :)
> [Antora] Fix droplists item position in navigation menu on the left

- mpt/impl/smtp/cassandra-rabbitmq-object-storage/pom.xml
Fix the 'NotFoundException' error when running the test.
> Fixup - add missing dependencies in apache-james-mpt-smtp-cassandra-rabbitmq-object-storage

- server/protocols/protocols-smtp/src/test/java/org/apache/james/smtpserver/SMTPSTest.java
The consumer argument of the hasOnlyOneElementSatisfying method does not include any assertions, causing the test to pass regardless of the expected string.
> [FIX] shouldAddSSLInformationInReceivedHeaders() test

- docs/modules/servers/nav.adoc
- docs/modules/servers/pages/distributed/run/run-docker.adoc
- docs/modules/servers/pages/postgres/index.adoc
- docs/modules/servers/pages/postgres/run/index.adoc
- docs/modules/servers/pages/postgres/run/run-docker.adoc
- docs/modules/servers/pages/postgres/run/run-java.adoc
I'm basing on a temporary branch `postgres-doc-tmp` that is postgres branch rebased on latest master, temporarily for now, to make it simple, as we dont care much about the build anyways for doc.
@vttranlina feel free to base temporarily your pg doc PRs on this branch as well, should be easier to see the work done.
Also I need to rework the run section. It's working well with partials, but I just realized that it's actually a bit more to it for postgres part, as you can run it without opensearch or s3 for example, compared to distributed where those are mandatory
> [Antora] Run section documentation for postgresql

- server/data/data-jmap-cassandra/src/main/java/org/apache/james/jmap/cassandra/pushsubscription/CassandraPushSubscriptionDAO.java
- server/data/data-jmap/src/main/scala/org/apache/james/jmap/api/change/TypeStateFactory.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/change/JmapEventSerializer.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/core/PushSubscriptionSet.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/json/PushSerializer.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/json/PushSubscriptionSerializer.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/EventSourceRoutes.scala
- server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/change/StateChangeEventSerializerTest.scala
- server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/change/TypeStateFactoryTest.scala
This could help if the operator reverses James to an older version that does not support the recently introduced TypeName.
- `PushSubscription/get` and `PushListener` would not fail when `TypeStateFactory` parsing the unknown type name from DB.
- Deserialize `StateChangeEvent` would not fail leading to resilient handling of `StateChangeEvent`.
Meanwhile, when parsing user input, we need to be strict.
> JAMES-3581 Parsing TypeName should be more lenient when parsing server side data

- protocols/smtp/src/main/java/org/apache/james/protocols/smtp/core/esmtp/AuthCmdHandler.java
`AuthCmdHandler` supports `HookResultHook` in `wireExtensions` and with its `rHooks` field but not in `getMarkerInterfaces` so `rHooks` will always be empty; this PR fixes this to be able to get `AuthHook` results in `HookResultHook` (e.g. getting `UsersRepositoryAuthHook` result).
> [FIX] HookResultHook added to marker interfaces of AuthCmdHandler

- core/src/main/java/org/apache/james/core/MailAddress.java
- core/src/test/java/org/apache/james/core/MailAddressTest.java
In order to fix error
javax.mail.internet.AddressException: Domain contains illegal character
```
javax.mail.internet.AddressException: Domain contains illegal character
at javax.mail.internet.InternetAddress.checkAddress(InternetAddress.java:1432)
at javax.mail.internet.InternetAddress.parse(InternetAddress.java:1215)
at javax.mail.internet.InternetAddress.parse(InternetAddress.java:752)
at javax.mail.internet.InternetAddress.parse(InternetAddress.java:729)
at javax.mail.internet.MimeMessage.setRecipients(MimeMessage.java:666)
at org.apache.james.jmap.method.MDNSendMethod.buildMailAndMimeMessage(MDNSendMethod.scala:197)
at org.apache.james.jmap.method.MDNSendMethod.$anonfun$buildMailAndResponse$2(MDNSendMethod.scala:189)
at scala.util.Either.map(Either.scala:382)
at …
```
> MailAddress should not contain backslash + comma character

- backends-common/rabbitmq/src/main/java/org/apache/james/backends/rabbitmq/ReactorRabbitMQChannelPool.java
```
reactor.core.Exceptions$ErrorCallbackNotImplemented: com.rabbitmq.client.ShutdownSignalException: clean connection shutdown; protocol method: #method<connection.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
Caused by: com.rabbitmq.client.ShutdownSignalException: clean connection shutdown; protocol method: #method<connection.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:66)
Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoRunnable] :
reactor.core.publisher.Mono.fromRunnable(Mono.java:702)
org.apache.james.backends.rabbitmq.ReactorRabbitMQChannelPool.lambda$new$2(ReactorRabbitMQChannelPool.java:694) …
```
> [ENHANCEMENT] Remove benign verbose logs upon shutdown

- backends-common/redis/src/main/java/org/apache/james/backends/redis/RedisConfiguration.scala
- backends-common/redis/src/test/java/org/apache/james/backends/redis/RedisConfigurationTest.scala
- backends-common/redis/src/test/java/org/apache/james/backends/redis/RedisSentinelExtension.java
- server/mailet/rate-limiter-redis/docker-compose-sample/README.md
- server/mailet/rate-limiter-redis/docker-compose-sample/config-template/master/docker-entrypoint-master.sh
- server/mailet/rate-limiter-redis/docker-compose-sample/config-template/master/redis.conf.template
- server/mailet/rate-limiter-redis/docker-compose-sample/config-template/replica/docker-entrypoint-replica.sh
- server/mailet/rate-limiter-redis/docker-compose-sample/config-template/replica/redis.conf.template
- server/mailet/rate-limiter-redis/docker-compose-sample/config-template/sentinel/docker-entrypoint-sentinel.sh
- server/mailet/rate-limiter-redis/docker-compose-sample/config-template/sentinel/sentinel.conf.template
- server/mailet/rate-limiter-redis/docker-compose-sample/docker-compose-with-redis-sentinel.yml
- server/mailet/rate-limiter-redis/docker-compose-sample/redis.properties
Why require commit ? [JAMES-3693 Fixup RedisConfiguration - parsing correct `redisURL` when multiple redis sentinel endpoint](https://github.com/apache/james-project/commit/344a80157059fb18d2830da3c0eaaea6f11ca53c)
The current James configuration uses:
```
config.setListDelimiterHandler(new DefaultListDelimiterHandler(','))
```
Then when give `redisURL` is `redis-sentinel://secret1@redis-sentinel-1:26379,redis-sentinel-2:26379,redis-sentinel-3:26379?sentinelMasterId=mymaster` (multiple sentinel endpoint)
the James configuration parsing is incorrect.
> JAMES-3693 Rate limiting for Apache James on top of Redis sentinel - introduce docker-compose sample

- server/apps/cassandra-app/sample-configuration/mailetcontainer.xml
- server/apps/distributed-app/sample-configuration/mailetcontainer.xml
- server/apps/distributed-pop3-app/sample-configuration/mailetcontainer.xml
- server/apps/jpa-app/sample-configuration/mailetcontainer.xml
- server/apps/jpa-smtp-app/sample-configuration/mailetcontainer.xml
- server/apps/memory-app/sample-configuration/mailetcontainer.xml
MailetContainerModule seems to check that RemoveMimeHeader with the parameter name strictly equal to `bcc` is present. If not, it crashes james startup. 
That would create issues during next release I think and this is the fix.
Why do we do such a strict checkup btw does somebody now? sound absurd to me.
> JAMES-4054 Fix remove X-SMIME-Status header in mailetcontainer.xml

- mailbox/lucene/src/main/java/org/apache/james/mailbox/lucene/search/LuceneMessageSearchIndex.java
- mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/events/DisabledListeningMessageSearchIndex.java
- mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/events/OpenSearchListeningMessageSearchIndex.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/search/LazyMessageSearchIndex.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/search/ListeningMessageSearchIndex.java
- mailbox/tools/indexer/src/main/java/org/apache/mailbox/tools/indexer/ReIndexerPerformer.java
- mailbox/tools/indexer/src/test/java/org/apache/mailbox/tools/indexer/CassandraReIndexerImplTest.java
- mailbox/tools/indexer/src/test/java/org/apache/mailbox/tools/indexer/ReIndexerImplTest.java
- server/container/guice/memory/src/main/java/org/apache/james/FakeMessageSearchIndex.java
- server/container/guice/opensearch/src/main/java/org/apache/james/SearchModuleChooser.java
- server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/routes/MailboxesRoutesTest.java
- server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/routes/UserMailboxesRoutesTest.java
As per mailinglist:
>>    should we finish the operation with the explicit "commit" operation?
> +1
> 
> We could add a `postReindexing()` method for search indexes which commits for Lucene and noop for Opensearch + scanning.
> 
> Then calling it in reindexing task would be a no brainer.
> 
> Do you think you can contribute this?--
> 
> Best regards,
> 
> Benoit TELLIER
> Explicit commit after running reindex

- mailbox/store/src/main/java/org/apache/james/mailbox/store/streaming/InputStreamContent.java
- mpt/impl/imap-mailbox/core/src/main/java/org/apache/james/mpt/imapmailbox/suite/Fetch.java
- mpt/impl/imap-mailbox/core/src/main/resources/org/apache/james/imap/scripts/FetchAllEmptyMailbox.test
- mpt/impl/imap-mailbox/core/src/main/resources/org/apache/james/imap/scripts/Uid.test
- protocols/imap/src/main/java/org/apache/james/imap/api/Tag.java
- protocols/imap/src/main/java/org/apache/james/imap/decode/main/DefaultImapDecoder.java
- protocols/imap/src/main/java/org/apache/james/imap/decode/parser/UidCommandParser.java
- protocols/imap/src/main/java/org/apache/james/imap/message/request/AbstractImapRequest.java
- protocols/imap/src/main/java/org/apache/james/imap/message/response/ImmutableStatusResponse.java
- protocols/imap/src/main/java/org/apache/james/imap/message/response/UnpooledStatusResponseFactory.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/AbstractMailboxProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/StatusProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/fetch/ContentBodyElement.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/fetch/FetchProcessor.java
- server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/ChannelImapResponseWriter.java
- server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/ImapChannelUpstreamHandler.java
(ref: https://issues.apache.org/jira/browse/JAMES-4060, https://www.mail-archive.com/server-dev@james.apache.org/msg74362.html)
(followup to https://github.com/apache/james-project/pull/2385 #2385)
* extending testcase to include `UID FETCH`
* fix the issue by ignoring range retrieval when the inbox is empty
* improvements to debug logs (compacting DefaultImapDecoder logs to single entry; add missing `toString()` and simplify toString in `ImmutableStatusResponse`):
Log afterwards looks nicer/cleaner IMHO (it's not perfect as it's mostly parsed data but gives more information about request-response chatter):
```
17:14:05.268 [DEBUG] o.a.j.m.p.ProtocolSession - C: b1 CREATE box
17:14:05.268 [TRACE] o.a.j.i.d.m.DefaultImapDecoder - Processing b1 CREATE CreateRequest{mailboxName=box} …
```
> JAMES-4060: Fix UID FETCH command failing on empty mailbox

- mailbox/plugin/deleted-messages-vault/src/main/java/org/apache/james/vault/DeletedMessage.java
- mailbox/plugin/deleted-messages-vault/src/test/java/org/apache/james/vault/DeletedMessageTest.java
cf: https://github.com/linagora/james-project/issues/5252
DeletedMessage' size was indeed zero in one of our customer envs.
```
java.lang.IllegalArgumentException: 'size' is required to be a strictly positive number
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143)
at org.apache.james.vault.DeletedMessage.<init>(DeletedMessage.java:175)
at org.apache.james.vault.DeletedMessage$Builder$FinalStage.build(DeletedMessage.java:150)
at org.apache.james.vault.metadata.DeletedMessageVaultDeletionCallback.lambda$forMessage$2(DeletedMessageVaultDeletionCallback.java:89)
at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:132)
at reactor.core.publisher.MonoUsing$MonoUsingSubscriber.onNext(MonoUsing.java:231)
at …
```
> [FIX] DeletedMessage size could be zero

- docs/modules/servers/pages/distributed/configure/jvm.adoc
- server/apps/cassandra-app/sample-configuration/jvm.properties
- server/apps/distributed-app/sample-configuration/jvm.properties
- server/apps/distributed-pop3-app/sample-configuration/jvm.properties
- server/apps/jpa-app/sample-configuration/jvm.properties
- server/apps/jpa-smtp-app/sample-configuration/jvm.properties
- server/apps/memory-app/sample-configuration/jvm.properties
- server/apps/scaling-pulsar-smtp/sample-configuration/jvm.properties
- server/container/guice/mailet/src/main/java/org/apache/james/modules/server/MailetContainerModule.java
- server/container/guice/protocols/jmap/src/test/java/org/apache/james/jmap/MailetPreconditionTest.java
I hesitated adding a test for the jvm property commit as it's a bit tricky for james startup
Maybe in memory-app with some alternative conf files in resources? Or just not necessary?
> JAMES-4059 MailetContainerModule should not do a strict check on RemoveMimeHeader with bcc name param

- protocols/smtp/src/main/java/org/apache/james/protocols/smtp/core/esmtp/EhloCmdHandler.java
- server/protocols/protocols-smtp/src/test/java/org/apache/james/smtpserver/SMTPServerTest.java
Postfix indeed supports alphanumeric hostname
```
hp@hp-quanth:~$ telnet localhost 41055
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
220 incoming.upn.integration-open-paas.org ESMTP Postfix (Ubuntu) EHLO 7kO2OrE
250-incoming.upn.integration-open-paas.org
```
> JAMES-4066 EHLO should accept alphanumeric hostname

- server/apps/cassandra-app/src/main/scripts/james-cli
- server/apps/distributed-app/src/main/scripts/james-cli
- server/apps/distributed-pop3-app/src/main/scripts/james-cli
- server/apps/jpa-app/src/main/scripts/james-cli
- server/apps/jpa-smtp-app/src/main/scripts/james-cli
- server/apps/memory-app/src/main/scripts/james-cli
- server/apps/scaling-pulsar-smtp/src/main/scripts/james-cli
- server/apps/webadmin-cli/james-cli
GIVEN I run james-cli in kubernetes
THEN the pod crashes and reboots
Because the james-cli runs JVM it catches the environment variables set by James. As such it always pretouch 3GB of RAM. When added to memory consumed by James it exceeds the limit and pod get's OOM-killed.
> James: unset JAVA_TOOL_OPTIONS env variable when running james-cli

- server/apps/postgres-app/src/main/scripts/james-cli
GIVEN I run james-cli in kubernetes
THEN the pod crashes and reboots
Because the james-cli runs JVM it catches the environment variables set by James. As such it always pretouch 3GB of RAM. When added to memory consumed by James it exceeds the limit and pod get's OOM-killed.
> Postgres-app: unset JAVA_TOOL_OPTIONS env variable when running james-cli

- docs/modules/servers/pages/distributed/operate/webadmin/admin-mailboxes-extend.adoc
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/task/SolveMailboxFlagInconsistenciesService.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/task/SolveMailboxFlagInconsistenciesTaskAdditionalInformationDTO.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/task/SolveMailboxFlagInconsistenciesTaskDTO.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/task/SolveMailboxFlagInconsistencyTask.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/task/SolveMailboxFlagInconsistenciesServiceTest.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/task/SolveMailboxFlagInconsistencyTaskSerializationTest.java
- server/container/guice/cassandra/src/main/java/org/apache/james/modules/CassandraConsistencyTaskSerializationModule.java
- server/container/guice/cassandra/src/main/java/org/apache/james/modules/webadmin/InconsistencySolvingRoutesModule.java
- server/protocols/webadmin-integration-test/distributed-webadmin-integration-test/src/test/java/org/apache/james/webadmin/integration/rabbitmq/ConsistencyTasksIntegrationTest.java
- server/protocols/webadmin/webadmin-cassandra/src/main/java/org/apache/james/webadmin/routes/SolveMessageDeletedInconsistenciesRequestToTask.java
- server/protocols/webadmin/webadmin-cassandra/src/main/java/org/apache/james/webadmin/routes/SolveMessageRecentInconsistenciesRequestToTask.java
- src/site/markdown/server/manage-webadmin.md
resolve https://github.com/linagora/james-project/issues/5235
Jira: https://issues.apache.org/jira/browse/JAMES-4071
>  JAMES-4071 - Task fix inconsistencies messagedeleted, mailboxRecents

- docs/modules/servers/partials/AmqpForwardAttribute.adoc
- mailet/amqp/src/main/java/org/apache/james/transport/mailets/AmqpForwardAttribute.java
- mailet/amqp/src/test/java/org/apache/james/transport/mailets/AmqpForwardAttributeTest.java
- server/mailet/integration-testing/src/test/java/org/apache/james/transport/mailets/AmqpForwardAttributeWithFanoutExchangeTypeIntegrationTest.java
- server/mailet/integration-testing/src/test/java/org/apache/james/transport/mailets/amqp/AmqpExtension.java
Right now it using direct by default
We can provide the configurable for it by init parameter exchange_type
it optional default to direct to prevent bracking change
> AmqpForwardAttribute mailet supports declaring exchange types

- docs/modules/servers/pages/distributed/objectives.adoc
I am guessing this is a typo? Metadata is stored in Cassandra and Cassandra enables horizontal scalability.
> Fix typo in documentation

- pom.xml
classes annotated unstable at classlevel are properly execucted with  -Punstable
this may not be true for 2 modules that override the surefire plugin definition but i'm not sure what they actually attempt to do : 
- distributed-jmap-rfc-8621-integration-tests
- rabbitmq-webadmin-integration-test
at the very least the situation will be better than it was before this change
> [devscout] fix execution of unstable group

- backends-common/pulsar/pom.xml
- backends-common/pulsar/src/test/java/org/apache/james/backends/pulsar/DockerPulsarExtension.java
- server/queue/queue-activemq/src/test/java/org/apache/james/queue/activemq/ActiveMQMailQueueBlobTest.java
- server/queue/queue-api/src/test/java/org/apache/james/queue/api/DelayedManageableMailQueueContract.java
- server/queue/queue-api/src/test/java/org/apache/james/queue/api/MailQueueContract.java
- server/queue/queue-api/src/test/java/org/apache/james/queue/api/ManageableMailQueueContract.java
- server/queue/queue-pulsar/src/test/java/org/apache/james/queue/pulsar/PulsarMailQueueTest.java
When I tried to start working on the flaky test I ran the `PulsarMailqueueTest` suite and one of the tests failed. Using `git bisect` I was able to trace it back to the introduction of the deadletter policy a while ago and yet all the pipelines were ok on the CI. 
I looked into the `unstable-test` stage and in develocity but couldn't find any trace of the `PulsarMailqueueTest` suite being executed. 
Doing local tests I realized that when the whole class is tagged, for some reason, the suite will not be executed, neither in the normal test stage or in the `unstable-test` stage. This does not only affect `PulsarMailQueueTest`. See my attempt at fixing the underlying problem in https://github.com/apache/james-project/pull/2417
This PR focuses on resolving the flakyness of the pulsar …
> [JAMES-3696] fix broken tests

- server/queue/queue-api/src/main/java/org/apache/james/queue/api/ManageableMailQueue.java
- server/queue/queue-pulsar/README.adoc
This serves to clarify implementation details that can affect the semantics of some operations.
i couldn't really find a better place than the javadoc of the `ManageableMailQueue` to put this in. 
I did write the following in `server/queue/queue-api/README.adoc`
```README.adoc
= Apache James MailQueue projects
The James MailQueue project provies the queue/spool mechanism used in the Apache James project.
The james-server-queue-api defines 2 levels of APIs which can be implemented to provide such spool mechanism
basic and manageable.
== Overview
The main API contracts are:
- MailQueue
- ManageableMailQueue
== MailQueue
This contract includes the most basic semantics for the queue mechanism:
- enqueue
- dequeue
Both operations are exposed in a blocking and a reactive flavor.
== …
```
> [devscout] adds implementation notes on ManageableMailQueue and PulsarMailQueue

- server/queue/queue-pulsar/src/main/scala/org/apache/james/queue/pulsar/PulsarMailQueue.scala
- server/queue/queue-pulsar/src/test/java/org/apache/james/queue/pulsar/PulsarMailQueueTest.java
As discussed in the issue, filter topics need to use unique subscription names to fetch all applicable filters upon restart. 
At the moment we use durable subscriptions which means that these subscriptions accumulate across restarts on the pulsar side, eventually reaching the limit of allowed subscriptions per topic. 
Alternatives
- We could try to be good citizens and delete the subscriptions but there is no guarantee that the process terminates properly and does the cleanup
- We could use another kind of UUID which is strictly incremental and or includes a timestamp, allowing to build a safe cleanup script, but it would be difficult to run automatically in a safe way. 
- We could expose the filter subscription names of the active nodes to make sure the cleanup script doesn't …
> [JAMES-4064] switch pulsarmailqueue filter topics to non durable subscriptions

- mailbox/api/src/test/java/org/apache/james/mailbox/MailboxManagerTest.java
I created new tests in `MailboxManagerTest` to ensure that mailboxes on which i have a `p` right are not listed in the ones i can see.
they seem to pass :)
> ISSUE-5290 check that mailboxes on which i have a p right are not listed in the ones i can see

- server/apps/jpa-app/pom.xml
- server/apps/jpa-app/src/main/java/org/apache/james/JPAJamesServerMain.java
- server/container/guice/lucene/pom.xml
- server/container/guice/lucene/src/main/java/org/apache/james/modules/mailbox/LuceneMemorySearchMailboxModule.java
- server/container/guice/lucene/src/main/java/org/apache/james/modules/mailbox/LuceneSearchMailboxModule.java
- server/container/guice/pom.xml
Currently [LuceneSearchMailboxModule.java](https://github.com/apache/james-project/compare/master...vttranlina:guice_lucene?expand=1#diff-9d43f98c587435fb4cb72d364e81779eb6a9babd234348bf32a1788193526753) was located in mailbox-jpa
To allow for options beyond "jpa," 
I propose  `<artifactId>james-server-guice-lucene</artifactId>`
> JAMES-4077 - Introduce james-server-guice-lucene module & replace it to JPAJamesServerMain

- mailbox/tika/src/test/java/org/apache/james/mailbox/tika/TikaTextExtractorTest.java
- server/container/guice/mailbox/src/main/java/org/apache/james/modules/ACLProbeImpl.java
- server/mailet/integration-testing/src/test/java/org/apache/james/mailets/SubAddressingTest.java
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/SubAddressing.java
this is the very beginning of the implementation of URLEncoding for subaddressing.
right now, i can't manage to write the integration test correctly: even using the probe instead of IMAP commands, the creation of a mailbox with a name containing a space is rejected: `java.lang.RuntimeException: AAAC BAD CREATE failed. Illegal encoding.`...
side note: i was unsure of what to do with the checkstyle issue in TikaTextExtractorTest, i committed it separately.
> URLEncoding for subaddressing

- backends-common/cassandra/pom.xml
- backends-common/opensearch/pom.xml
- event-bus/cassandra/pom.xml
- event-sourcing/event-store-cassandra/pom.xml
- mailbox/cassandra/pom.xml
- mailbox/plugin/deleted-messages-vault-cassandra/pom.xml
- mailbox/plugin/quota-mailing-cassandra/pom.xml
- mpt/impl/imap-mailbox/cassandra/pom.xml
- mpt/impl/managesieve/cassandra/pom.xml
- mpt/impl/smtp/cassandra-rabbitmq-object-storage/pom.xml
- mpt/impl/smtp/cassandra/pom.xml
- server/apps/cassandra-app/pom.xml
- server/apps/distributed-app/pom.xml
- server/apps/distributed-pop3-app/pom.xml
- server/blob/blob-cassandra/pom.xml
- server/data/data-cassandra/pom.xml
- server/data/data-jmap-cassandra/pom.xml
- server/mailrepository/mailrepository-cassandra/pom.xml
- server/protocols/jmap-rfc-8621-integration-tests/distributed-jmap-rfc-8621-integration-tests/pom.xml
- server/queue/queue-rabbitmq/pom.xml
- server/task/task-distributed/pom.xml
Encountered on a customer install...
```
test_james20_pub | Exception in thread "OpenSearch-driver-1" java.lang.NoClassDefFoundError: org/apache/commons/codec/binary/Base64
test_james20_pub |      at org.apache.http.impl.auth.BasicScheme.authenticate(BasicScheme.java:166)
test_james20_pub |      at org.apache.http.impl.auth.HttpAuthenticator.doAuth(HttpAuthenticator.java:233)
test_james20_pub |      at org.apache.http.impl.auth.HttpAuthenticator.generateAuthResponse(HttpAuthenticator.java:213)
test_james20_pub |      at org.apache.http.impl.nio.client.MainClientExec.generateRequest(MainClientExec.java:224)
test_james20_pub |      at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.generateRequest(DefaultClientExchangeHandlerImpl.java:135)
test_james20_pub |      at …
```
> [FIX] Add missing commons codec dependency

- server/blob/blob-common/src/main/java/org/apache/james/blob/api/Store.java
S3 returned some 404 due to content size mismatches
What is weird is that if retried the S3 calles eventually succeeds. Wich means size eventually gets correct.
A missing flush onto the file system is a casual suspect: content isn't there at start but eventually gets there, explaining the observed behaviour...
> [FIX] Store add a missing flush

- backends-common/redis/src/test/java/org/apache/james/backends/redis/RedisClusterExtension.java
- backends-common/redis/src/test/java/org/apache/james/backends/redis/RedisMasterReplicaExtension.java
- backends-common/redis/src/test/java/org/apache/james/backends/redis/RedisSentinelExtension.java
- backends-common/redis/src/test/java/org/apache/james/backends/redis/RedisTLSExtension.java
Somehow testcontainers erase the content of binding files when READ_WRITE mode is used
> Update RedisSentinelExtension to switch BindMode to READ_ONLY

- mailbox/api/src/main/java/org/apache/james/mailbox/MailboxManager.java
- mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/events/OpenSearchListeningMessageSearchIndex.java
- mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/search/OpenSearchSearchHighlighter.java
- server/apps/distributed-app/src/main/java/org/apache/james/CassandraRabbitMQJamesServerMain.java
- server/apps/distributed-pop3-app/src/main/java/org/apache/james/DistributedPOP3JamesServerMain.java
- server/container/guice/opensearch/src/main/java/org/apache/james/OpenSearchHighlightModule.java
- server/container/guice/opensearch/src/main/java/org/apache/james/SearchModuleChooser.java
- server/container/guice/protocols/jmap/src/main/java/org/apache/james/jmap/rfc8621/RFC8621MethodsModule.java
- server/protocols/jmap-rfc-8621-integration-tests/distributed-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/distributed/DistributedSearchSnippetGetMethodTest.java
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/SearchSnippetGetMethodContract.scala
- server/protocols/jmap-rfc-8621/doc/specs/spec/mail/rights.mdown
- server/protocols/jmap-rfc-8621/doc/specs/spec/mail/searchsnippet.mdown
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/highlight/SearchSnippetGetRequest.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/json/EmailQuerySerializer.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/json/SearchSnippetSerializer.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/EmailQuery.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/SearchSnippetGetMethod.scala
- server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/json/SearchSnippetSerializerTest.scala
jira https://issues.apache.org/jira/browse/JAMES-4077
resolve https://github.com/linagora/james-project/issues/5254
> JAMES-4077 JMAP - SearchSnippet/get method

- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/MailboxSetMethodContract.scala
- server/protocols/jmap-rfc-8621/doc/specs/spec/mail/rights.mdown
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/Rights.scala
- server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/mail/RightsTest.scala
i am tackling [the step 4 of this issue](https://issues.apache.org/jira/browse/JAMES-3945), that is, adding JMAP support for subaddressing
in order to allow subaddressing or not for a specific mailbox, there is the need for a `p` (`posting`) right, that can be granted to the identifier `anyone`
> posting right in JMAP for subaddressing

- mailbox/lucene/src/main/java/org/apache/james/mailbox/lucene/search/LuceneSearchHighlighter.java
- server/apps/distributed-app/src/main/java/org/apache/james/CassandraRabbitMQJamesServerMain.java
- server/apps/distributed-pop3-app/src/main/java/org/apache/james/DistributedPOP3JamesServerMain.java
- server/apps/memory-app/pom.xml
- server/apps/memory-app/src/main/java/org/apache/james/MemoryJamesServerMain.java
- server/container/guice/lucene/src/main/java/org/apache/james/modules/mailbox/LuceneSearchMailboxModule.java
- server/container/guice/memory/pom.xml
- server/container/guice/memory/src/main/java/org/apache/james/modules/mailbox/MemoryMailboxModule.java
- server/container/guice/protocols/jmap/src/main/java/org/apache/james/jmap/rfc8621/RFC8621MethodsModule.java
- server/protocols/jmap-rfc-8621-integration-tests/memory-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/memory/MemorySearchSnippetGetMethodTest.java
jira https://issues.apache.org/jira/browse/JAMES-4077
resolve https://github.com/linagora/james-project/issues/5305
> JAMES-4077 Back memory-app with Lucene

- server/mailet/mock-smtp-server/pom.xml
- server/mailet/mock-smtp-server/src/main/java/org/apache/james/mock/smtp/server/HTTPConfigurationServer.java
- server/mailet/mock-smtp-server/src/main/java/org/apache/james/mock/smtp/server/model/Condition.java
- server/mailet/mock-smtp-server/src/main/java/org/apache/james/mock/smtp/server/model/Mail.java
- server/mailet/mock-smtp-server/src/main/java/org/apache/james/mock/smtp/server/model/Mails.java
- server/mailet/mock-smtp-server/src/main/java/org/apache/james/mock/smtp/server/model/MockSMTPBehavior.java
- server/mailet/mock-smtp-server/src/main/java/org/apache/james/mock/smtp/server/model/MockSMTPBehaviorInformation.java
- server/mailet/mock-smtp-server/src/main/java/org/apache/james/mock/smtp/server/model/MockSmtpBehaviors.java
- server/mailet/mock-smtp-server/src/main/java/org/apache/james/mock/smtp/server/model/Response.java
- server/mailet/mock-smtp-server/src/main/java/org/apache/james/mock/smtp/server/model/SMTPExtension.java
- server/mailet/mock-smtp-server/src/main/java/org/apache/james/mock/smtp/server/model/SMTPExtensions.java
- server/mailet/mock-smtp-server/src/main/java/org/apache/james/mock/smtp/server/testing/MockSmtpServerExtension.java
- server/mailet/mock-smtp-server/src/test/java/org/apache/james/mock/smtp/server/MockSMTPServerTest.java
Hello! 
I think the mock-smtp-server needs tweaking to improve the integration testing work, he must accept a specific list of parameters without values. Like for example for a `REQUIRETLS` parameter in a task: 
[JAMES-3823](https://issues.apache.org/jira/projects/JAMES/issues/JAMES-3823?filter=allopenissues)
[#2460](https://github.com/apache/james-project/pull/2460)
> [IMPROVEMENT] mock-smtp-server (parameters without values)

- protocols/imap/src/main/java/org/apache/james/imap/api/process/ImapSession.java
- protocols/imap/src/main/java/org/apache/james/imap/decode/base/AbstractImapCommandParser.java
- protocols/imap/src/main/java/org/apache/james/imap/decode/main/DefaultImapDecoder.java
- server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/HAProxyMessageHandler.java
- server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/IMAPMDCContext.java
- server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/ImapChannelUpstreamHandler.java
- server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/NettyImapSession.java
Design choices:
- For performance reasons do not set up the MDC for each and every parsing attempt. Doing it upon parsing errors is likely enough, and prevent costs associated with MDC management.
- Centralize management of the MDC into the IMAP session. This avoids coupling the parsers to the transport layer by preventing constant duplication.
- And finally this meant also managing user and selected mailbox in a statefull manner. This unsure the MDC from the IMAP session can be used straight away...
> [ENHANCEMENT] MDC for IMAP parsing logs

- server/protocols/protocols-imap4/src/test/java/org/apache/james/imapserver/netty/IMAPServerTest.java
- According to RFC 2177, IDLE is supported in the authenticated state, but it doesn't specify detailed behavior. Currently, James simply returns an idling state without any responding when new messages, similar to other mail services like Cyrus and Gmail.
> IMAP - IDLE Command - Add test cases when authenticated state

- docs/modules/servers/partials/configure/mailetcontainer.adoc
- mailet/base/src/test/java/org/apache/mailet/base/MatcherInverterTest.java
- server/apps/memory-app/src/test/resources/mailetcontainer.xml
- server/mailet/mailetcontainer-impl/src/main/java/org/apache/james/mailetcontainer/lib/AbstractStateMailetProcessor.java
- server/mailet/mailetcontainer-impl/src/test/java/org/apache/james/mailetcontainer/impl/matchers/InvertMatcherWithCompositeMatcherTest.java
```
<matcher name="relay-allowed" match="org.apache.james.mailetcontainer.impl.matchers.Or">
    <matcher match="SMTPAuthSuccessful"/>
    <matcher match="SMTPIsAuthNetwork"/>
    <matcher match="SentByMailet"/>
    <matcher match="org.apache.james.jmap.mailet.SentByJmap"/>
</matcher>
<matcher name="should-check-spam" match="org.apache.james.mailetcontainer.impl.matchers.Not">
    <matcher match="relay-allowed"/>
</matcher>
```
was not possible before.
Loading the matcher from composite matchers collection also, not only using class loader solves the issue.
> [MAILET] Allow chaining composite matcher

- mailbox/api/src/main/java/org/apache/james/mailbox/model/MailboxACL.java
- server/container/guice/mailbox/src/main/java/org/apache/james/modules/ACLProbeImpl.java
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/MailboxGetMethodContract.scala
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/MailboxSetMethodContract.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/json/MailboxSerializer.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/MailboxSet.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/Rights.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/MailboxSetUpdatePerformer.scala
- server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/json/MailboxSerializationTest.scala
- server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/mail/RightsTest.scala
tackling [issue #5314](https://github.com/linagora/james-project/issues/5314)
> refactor and test the use of the `anyone` keyword when sharing with JMAP

- mailbox/api/src/main/java/org/apache/james/mailbox/MailboxCounterCorrector.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/task/CassandraMailboxCounterCorrector.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/AbstractSelectionProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/DefaultProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/ExamineProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/SelectProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/main/DefaultImapProcessorFactory.java
- protocols/imap/src/test/java/org/apache/james/imap/processor/AbstractSelectionProcessorTest.java
- protocols/imap/src/test/java/org/apache/james/imap/processor/SelectProcessorTest.java
- server/container/guice/cassandra/src/main/java/org/apache/james/modules/mailbox/CassandraMailboxModule.java
- server/container/guice/mailbox-jpa/src/main/java/org/apache/james/modules/mailbox/JPAMailboxModule.java
- server/container/guice/memory/src/main/java/org/apache/james/modules/mailbox/MemoryMailboxModule.java
This is critical for Mail User Agent like Apple mail relying on MSN FETCH for resynchronisation. Outdated counters, meant to be expected with Cassandra implementation would lead to terminal errors aborting mail resynchronisation.
Instead, use the content of the just loaded selected mailbox, accurate and piggyback counter asynchronous correction as needed.
> [CNB] JAMES-4088 Ensure IMAP SELECT EXIST response is up to date

- mailet/standard/src/main/java/org/apache/james/transport/mailets/ContactExtractor.java
- mailet/standard/src/test/java/org/apache/james/transport/mailets/ContactExtractorTest.java
In https://github.com/linagora/tmail-backend/pull/1308, calling `ObjectMapper#readValue` and casting the result to ExtractedContacts results in the following error: `com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of org.apache.james.transport.mailets.ContactExtractor$ExtractedContacts`. 
Changing it to a record resolves the issue.
> Convert ExtractedContacts class to a record

- core/src/main/java/org/apache/james/core/Domain.java
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/MailboxSetMethodContract.scala
- server/protocols/webadmin/webadmin-data/src/test/java/org/apache/james/webadmin/routes/DLPConfigurationRoutesTest.java
- server/protocols/webadmin/webadmin-data/src/test/java/org/apache/james/webadmin/routes/MappingRoutesTest.java
- server/protocols/webadmin/webadmin-jmap/src/test/java/org/apache/james/webadmin/data/jmap/RecomputeUserFastViewProjectionItemsRequestToTaskTest.java
- server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/routes/UserMailboxesRoutesTest.java
- server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/service/MailboxesExportRequestToTaskTest.java
- server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/service/SubscribeAllRequestToTaskTest.java
ref: 980d3144e9a0be6258d9570c04b9351231536aaf
- Fix mistake placeholder `%s` vs `{}`
> [FIX] Domain validation should be more informative - Fixup message

- docs/modules/servers/partials/MailToAllUsers.adoc
- docs/modules/servers/partials/SplitMail.adoc
- docs/modules/servers/partials/configure/mailets.adoc
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/MailToAllUsers.java
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/SplitMail.java
- server/mailet/mailets/src/test/java/org/apache/james/transport/mailets/MailToAllUsersTest.java
- server/mailet/mailets/src/test/java/org/apache/james/transport/mailets/SplitMailTest.java
- I suspect James could struggle in distributed version to distribute very large count of recipients To this end, splitting email would help.
- This is a default Postfix behaviour.
The code snippet is extracted from MailToAllUsers mailet.
> [FIX] Ability to split emails with large recipient counts

- mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/mail/dao/PostgresThreadModule.java
The performance test reveals that the query on the `thread` table is take time:
```sql
select
thread_id,
hash_base_subject
from thread
where (
username = $1
and hash_mime_message_id in (
$2, $3
)
)
```
before
After
> JAMES-2586 Add index for thread table

- server/blob/blob-api/src/main/java/org/apache/james/blob/api/BlobStore.java
- server/blob/blob-api/src/main/java/org/apache/james/blob/api/MetricableBlobStore.java
- server/blob/blob-cassandra/src/main/java/org/apache/james/blob/cassandra/cache/CachedBlobStore.java
- server/blob/blob-storage-strategy/src/main/scala/org/apache/james/server/blob/deduplication/DeDuplicationBlobStore.scala
- server/blob/blob-storage-strategy/src/main/scala/org/apache/james/server/blob/deduplication/PassThroughBlobStore.scala
It avoids buffering byte arrays onto temporary files..
Triggering IOs is a MAJOR performance hit in itself but adding this onto a dedicated large pool for IOs when we are compute bound also skyrockets the count of threads. Not to mention that my experience with resource management with reactor let me think that edge cases like cancelation could trigger a ressource leak (been there).
We can beatifully avoid these inneficiencies by making BlobIdProvider a generic.
Disaster that waited to happen...
> JAMES-3763 Generics for BlobIdProvider

- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/CustomMethodContract.scala
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/DisabledCapabilityContract.scala
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EmailSubmissionSetMethodFutureReleaseContract.scala
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/SessionRoutesContract.scala
- server/protocols/jmap-rfc-8621/doc/specs/spec/mail/rights.mdown
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/core/Capability.scala
- server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/json/SessionSerializationTest.scala
- server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/routes/SessionRoutesTest.scala
[jira JAMES-3945 ticket for subaddressing](https://issues.apache.org/jira/browse/JAMES-3945)
subaddressing has now been implemented on the backend side, but not fully deployed. we need to have the frontend automatically detect if the backend supports subaddressing or not.
thus i modified the `urn:apache:james:params:jmap:mail:shares` capability to add a `subaddressingSupported` property (boolean). if this property is not defined, then the frontend should assume it is not supported.
> JAMES-3945 advertize that subaddressing is supported

- mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/mail/dao/PostgresThreadModule.java
This reverts commit 194832f1ba30df2ef260e7f64c9b4fc020709fea.
No argumentation, no analysis whatsoever
mean time is still lower on the second run
APPEND is SIGNIFICANTLY slower.
Please revert and analysis more.
> Revert "JAMES-2586 Add index for thread table"

- protocols/lmtp/src/main/java/org/apache/james/protocols/lmtp/core/ReceivedDataLineFilter.java
- protocols/smtp/src/main/java/org/apache/james/protocols/smtp/core/ReceivedDataLineFilter.java
- protocols/smtp/src/main/java/org/apache/james/protocols/smtp/core/ReceivedHeaderGenerator.java
- Detail LMTP service type
- Expose auth settings through service type
- Extract message generation
CF https://datatracker.ietf.org/doc/html/rfc3848
> [FIX] Support RFC-3848 service types in Received headers

- protocols/imap/src/main/java/org/apache/james/imap/decode/parser/LoginCommandParser.java
Failure to do so:
- closes needlessly the connection
- and polutes log level
> [FIX] IMAP login parsing: handle IllegalArgumentException

- docs/modules/servers/partials/configure/jvm.adoc
- event-bus/api/src/main/java/org/apache/james/events/EventBus.java
- event-bus/api/src/main/java/org/apache/james/events/EventListener.java
- event-bus/api/src/main/java/org/apache/james/events/EventSerializer.java
- event-bus/api/src/main/java/org/apache/james/events/EventSerializersAggregator.java
- event-bus/api/src/test/java/org/apache/james/events/EventBusTestFixture.java
- event-bus/distributed/src/main/java/org/apache/james/events/EventDispatcher.java
- event-bus/distributed/src/main/java/org/apache/james/events/GroupRegistration.java
- event-bus/distributed/src/main/java/org/apache/james/events/GroupRegistrationHandler.java
- event-bus/distributed/src/main/java/org/apache/james/events/ListenerExecutor.java
- event-bus/distributed/src/main/java/org/apache/james/events/RabbitMQEventBus.java
- event-bus/in-vm/src/main/java/org/apache/james/events/InVMEventBus.java
- event-bus/in-vm/src/main/java/org/apache/james/events/delivery/EventDelivery.java
- event-bus/in-vm/src/main/java/org/apache/james/events/delivery/InVmEventDelivery.java
- mailbox/event/json/src/main/scala/org/apache/james/event/json/MailboxEventSerializer.scala
- mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMessageIdManager.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMessageManager.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/quota/ListeningCurrentQuotaUpdater.java
- server/apps/distributed-app/sample-configuration/jvm.properties
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/WebSocketContract.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/change/JmapEventSerializer.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/change/MailboxChangeListener.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailSetUpdatePerformer.scala
Today moving emails triggers 2 JMAP websocket notification: it shall generate a signle one!
Key idea: on the EventBus, I shall be able to publish a list of events.
This will be serialized and transported by rabbit as a list of event. (We can have a configuration parameter to turn on/off this parameter to ease rolling migration). Deserialization will need to handle both list and single events.
It will be executed as a list of events by listeners, with a default implementation to handle the current single event (without breaking change)
MailboxChangeListener will handle the email move in a single pass: process both `Added` and `Expunged` in a single pass and return a single `StateChange`.
See https://github.com/linagora/tmail-flutter/issues/3331
> [PERF] Email move should send only one JMAP push notification

- event-sourcing/event-store-jpa/pom.xml
- event-sourcing/event-store-jpa/src/main/java/org/apache/james/eventsourcing/eventstore/jpa/JPAEventStore.java
- event-sourcing/event-store-jpa/src/main/java/org/apache/james/eventsourcing/eventstore/jpa/model/JPAEvent.java
- event-sourcing/event-store-jpa/src/test/java/org/apache/james/eventsourcing/eventstore/jpa/JPAEventSourcingSystemTest.java
- event-sourcing/event-store-jpa/src/test/java/org/apache/james/eventsourcing/eventstore/jpa/JPAEventStoreExtension.java
- event-sourcing/event-store-jpa/src/test/java/org/apache/james/eventsourcing/eventstore/jpa/JPAEventStoreTest.java
- event-sourcing/event-store-jpa/src/test/java/org/apache/james/eventsourcing/eventstore/jpa/model/JPAEventTest.java
- event-sourcing/event-store-jpa/src/test/resources/persistence.xml
- event-sourcing/pom.xml
This is just a rough draft and not ready to merge yet, but since I have no previous experience with Scala or Reactive Streams or Guice or this event api or its usages, if anyone could help in improving and finalizing this, I think we can get this done :-)
> JAMES-2433 Implement EventStore for a JPA backend

- mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMessageIdManager.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/AbstractMessageIdManagerSideEffectTest.java
This limits downstream chatter:
- RabbitMQ / Redis dispatch overhead
- Websocket resynchs
> [FIX] Email/set destroy should fire one event per impacted mailbox

- docs/modules/servers/partials/operate/logging.adoc
- pom.xml
- protocols/netty/src/main/java/org/apache/james/protocols/netty/ProtocolMDCContextFactory.java
- server/apps/cassandra-app/pom.xml
- server/apps/distributed-app/helm-chart/james/configs/logback.xml
- server/apps/distributed-app/pom.xml
- server/apps/distributed-pop3-app/pom.xml
- server/apps/jpa-app/pom.xml
- server/apps/jpa-smtp-app/pom.xml
- server/apps/memory-app/pom.xml
- server/apps/scaling-pulsar-smtp/pom.xml
- third-party/crowdsec/sample-configuration/logback.xml
- third-party/crowdsec/src/test/java/org/apache/james/crowdsec/CrowdsecExtension.java
- third-party/crowdsec/src/test/resources/crowdsec/parsers/syslog-logs.yaml
- third-party/crowdsec/src/test/resources/logback-test.xml
This commit drops the unmaintained logback-classic dependecy and upgrades logback to the latest version.
Logback-classic has a native JsonEncoder (already in the original version). The latest version allows to have the formatted message and to enable/disable any top level field\ by configuration.
This allows using logback's own JSON encoder and get rid ot logback-contrib which is unmaintained to output json ( the repository is archived and the dependencies are quite outdated)
A side effect was that the format of the Json output changes slightly, I adjusted the samplec configurations for the crowdsec module.
One of the change is a higher resolution for the timestamp, which required raising crowdsec to 1.6.x.
I missed the previous [merge …
> [devscout] upgrade logback and crowdsec

- server/protocols/webadmin/webadmin-core/src/main/java/org/apache/james/webadmin/WebAdminServer.java
Cancellation generated by `curl ... | head` is very
verbose and needlessly noisy.
> [FIX] Silent Eof exception for webadmin

- docs/modules/servers/partials/configure/jvm.adoc
- mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreRightManager.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/StoreRightManagerTest.java
- server/apps/cassandra-app/docker-configuration/jvm.properties
- server/apps/cassandra-app/sample-configuration/jvm.properties
- server/apps/distributed-app/docker-configuration/jvm.properties
- server/apps/distributed-app/sample-configuration/jvm.properties
- server/apps/distributed-pop3-app/docker-configuration/jvm.properties
- server/apps/distributed-pop3-app/sample-configuration/jvm.properties
- server/apps/jpa-app/sample-configuration/jvm.properties
- server/apps/memory-app/sample-configuration/jvm.properties
[James-4097](https://issues.apache.org/jira/browse/JAMES-4097)
Add a configuration switch lifting the same-domain requirement when assigning rights.
This feature is opt-in - the default configuration will still forbid cross-domain access.
> James-4097 Allow disabling same-domain requirement when assigning rights

- protocols/netty/src/main/java/org/apache/james/protocols/netty/BasicChannelInboundHandler.java
Those are annoying, mostly benign (badly configured spammers for the win!) and definitly NOT errors.
> [FIX] Silent verbose SSL logs in SMTP

- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/LocalDelivery.java
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/delivery/MailDispatcher.java
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/delivery/MailboxAppenderImpl.java
- server/mailet/mailets/src/test/java/org/apache/james/transport/mailets/delivery/MailDispatcherTest.java
And log level INFO.
Was:
```
Caused by: jakarta.mail.MessagingException: Could not append due to quota error
at org.apache.james.transport.mailets.delivery.MailboxAppenderImpl.lambda$append$7(MailboxAppenderImpl.java:127)
at reactor.core.publisher.Mono.lambda$onErrorMap$27(Mono.java:3840)
at reactor.core.publisher.Mono.lambda$onErrorResume$29(Mono.java:3930)
at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
... 62 common frames omitted
Caused by: org.apache.james.mailbox.exception.OverQuotaException: You use too much space in #private&akishtoo@govmu.org
at org.apache.james.mailbox.store.quota.QuotaChecker.trySizeAddition(QuotaChecker.java:68)
at org.apache.james.mailbox.store.quota.QuotaChecker.tryAddition(QuotaChecker.java:59)
at …
```
> [ENHANCEMENT] Do not retry storing mails when OverQuotaException

- mpt/impl/imap-mailbox/core/src/main/resources/org/apache/james/imap/scripts/ListWithSharedMailbox.test
- protocols/imap/src/main/java/org/apache/james/imap/processor/ListProcessor.java
The response of list request should not include private mailboxes when query the other users namespace `#user.*`
> JAMES-3754 - Fix IMAP LIST EXTENSION - return incorrect list response when SUBCRIBED in request option with other usersnamespace query

- server/protocols/webadmin/webadmin-jmap/src/main/java/org/apache/james/webadmin/data/jmap/EmailQueryViewPopulator.java
Current task only creates new entry and never remove existing entries which fails at solving some classes of inconsistencies.
> [FIX] Cleanup EmailQueryView when populating it.

- server/apps/jpa-app/README.adoc
- server/apps/jpa-app/docker-compose.yml
- server/apps/jpa-app/pom.xml
- server/apps/jpa-smtp-app/README.adoc
- server/apps/jpa-smtp-app/docker-compose.yml
- server/apps/jpa-smtp-app/pom.xml
Validate from jib 3.1.0 https://github.com/GoogleContainerTools/jib/blob/master/jib-gradle-plugin/CHANGELOG.md#310
> Jib build - update extraClasspath jdbc driver for jpa-app, jpa-smtp-app

- docs/modules/servers/partials/configure/jvm.adoc
- mailbox/api/src/main/java/org/apache/james/mailbox/model/MailboxConstants.java
- mailbox/api/src/main/java/org/apache/james/mailbox/model/MailboxPath.java
- mailbox/api/src/test/java/org/apache/james/mailbox/MailboxSessionUtil.java
- mailbox/api/src/test/java/org/apache/james/mailbox/model/MailboxFolderDelimiterAwareTest.java
- mailbox/api/src/test/java/org/apache/james/mailbox/model/MailboxPathTest.java
- mailbox/api/src/test/java/org/apache/james/mailbox/model/search/PrefixedRegexTest.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/SessionProviderImpl.java
- protocols/imap/src/main/java/org/apache/james/imap/main/PathConverter.java
- protocols/imap/src/main/java/org/apache/james/imap/message/response/ListResponse.java
- protocols/imap/src/test/java/org/apache/james/imap/main/DefaultPathConverterTest.java
- protocols/imap/src/test/java/org/apache/james/imap/main/PathConverterBasicContract.java
- server/apps/cassandra-app/docker-configuration/jvm.properties
- server/apps/cassandra-app/sample-configuration/jvm.properties
- server/apps/distributed-app/docker-configuration/jvm.properties
- server/apps/distributed-app/sample-configuration/jvm.properties
- server/apps/distributed-pop3-app/docker-configuration/jvm.properties
- server/apps/distributed-pop3-app/sample-configuration/jvm.properties
- server/apps/jpa-app/sample-configuration/jvm.properties
- server/apps/jpa-smtp-app/sample-configuration/jvm.properties
- server/apps/memory-app/sample-configuration/jvm.properties
- server/apps/scaling-pulsar-smtp/sample-configuration/jvm.properties
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/jsieve/FileIntoAction.java
[James-4099](https://issues.apache.org/jira/projects/JAMES/issues/JAMES-4099)
Add a configuration switch for adjusting the default mailbox folder delimiter.
Currently allowed (because unit-tested) values are: `dot` (will use '.' as delimiter), `slash` (will use '/' as delimiter), `pipe` ('|'), `comma` (','), `colon` (':'), `semicolon` (';').
Currently explicitly left-out values are: '#' (clashes with namespace prefix character), '\\' (anticipated some problems with the prefixedRegex matching and because it is the escaping character, it can generally be a bit more annoying to deal with in strings).
This feature is opt in - the default configuration will still retain the current default delimiter (dot).
**Notes to reviewer:**
- Unfortunately, git becomes pretty confused when indentation of …
> James 4099 Configurable path delimiter

- mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/search/OpenSearchSearcher.java
Because HTML is extracted prior indexing we need to escape it prior to rendering highlights otherwize
one can inject additional <mark> tags that will get rendered.
> [FIX] Escape HTML before highlights

- docs/modules/servers/partials/operate/webadmin.adoc
- server/mailrepository/mailrepository-api/src/main/java/org/apache/james/mailrepository/api/MailRepository.java
- server/mailrepository/mailrepository-cassandra/src/main/java/org/apache/james/mailrepository/cassandra/CassandraMailRepository.java
- server/mailrepository/mailrepository-cassandra/src/test/java/org/apache/james/mailrepository/cassandra/CassandraMailRepositoryTest.java
- server/protocols/webadmin/webadmin-core/src/main/java/org/apache/james/webadmin/utils/ParametersExtractor.java
- server/protocols/webadmin/webadmin-mailrepository/src/main/java/org/apache/james/webadmin/routes/MailRepositoriesRoutes.java
- server/protocols/webadmin/webadmin-mailrepository/src/main/java/org/apache/james/webadmin/service/MailRepositoryStoreService.java
- server/protocols/webadmin/webadmin-mailrepository/src/test/java/org/apache/james/webadmin/routes/MailRepositoriesRoutesTest.java
- src/site/markdown/server/manage-webadmin.md
> JAMES-4092 Update webadmin to filter content from mail repository

- server/apps/scaling-pulsar-smtp/src/main/java/org/apache/james/Main.java
Without this fix the scaling pulsar smtp assembly doesn't start This is not detected by tests because the  AwsS3BlobStoreExtension injects the awsS3TestRule's module which does inject the default option in scope so it only affects the production code.
cc @vttranlina @quantranhong1999
> [devscout] adds missing binding for S3RequestOption

- protocols/smtp/src/main/java/org/apache/james/protocols/smtp/core/esmtp/AuthCmdHandler.java
- server/protocols/protocols-smtp/src/test/java/org/apache/james/smtpserver/SMTPSaslTest.java
Not doing so prevents follow up commands execution to proceed normally
CF https://github.com/apache/james-project/pull/2617
Thanks to Felix Auringer for the report
> JAMES-4108 Remove OAUTH line handler post authentication

- docs/modules/development/pages/logging.adoc
- testing/base/src/main/resources/logback-test.xml
This sample config can be used when debugging tests by setting the log level to DEBUG.
> Improve documentation for activating debug mode for tests

- docs/modules/servers/pages/distributed/configure/jvm.adoc
- mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/events/OpenSearchListeningMessageSearchIndex.java
- mailbox/opensearch/src/test/java/org/apache/james/mailbox/opensearch/OpenSearchIntegrationTest.java
- mailbox/opensearch/src/test/java/org/apache/james/mailbox/opensearch/OpenSearchNoIndexBodyIntegrationTest.java
- mailbox/opensearch/src/test/java/org/apache/james/mailbox/opensearch/events/OpenSearchListeningMessageSearchIndexTest.java
- mailbox/opensearch/src/test/java/org/apache/james/mailbox/opensearch/search/OpenSearchSearchHighlighterTest.java
- mailbox/opensearch/src/test/java/org/apache/james/mailbox/opensearch/search/OpenSearchSearcherTest.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/search/ListeningMessageSearchIndex.java
- mpt/impl/imap-mailbox/opensearch/src/test/java/org/apache/james/mpt/imapmailbox/elasticsearch/host/OpenSearchHostSystem.java
- server/container/guice/opensearch/src/main/java/org/apache/james/modules/mailbox/OpenSearchMailboxModule.java
- server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/routes/MailboxesRoutesTest.java
- server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/routes/UserMailboxesRoutesTest.java
During the listener process, we need to re-download the all message in order to...
- Index it in search engine
- Pre-compute the JMAP preview
That would cause x2 network traffic and x2 S3 bill.
We can download the message just once doing both the job to optimize the performance and cost.
> [ENHANCEMENT] Allow plug custom indexers into OpenSearchListeningMessageSearchIndex

- mailbox/api/src/test/java/org/apache/james/mailbox/MailboxManagerTest.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMailboxManager.java
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/MailboxSetMethodContract.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/MailboxSetDeletePerformer.scala
Fix assert some delete mailbox method, that still use assert check only owner,
It should be check owner or has `Right.DeleteMailbox`
> JAMES-2182 Fix rights for DELETE - update correct assert for delete mailbox methods

- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/MailboxGetMethodContract.scala
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/MailboxSetMethodContract.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/MailboxFactory.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/Rights.scala
- server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/mail/RightsTest.scala
Currently, `mayDelete` always returns `false`, even when another user has the `DeleteMailbox` right, 
and the `right` property is missing the `x` right in the response.
> JAMES-3171 - JMAP - Mailbox/get - Fix missing MailboxDelete right in response for shared mailbox

- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/CassandraMailboxSessionMapperFactory.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraAttachmentMapper.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/CassandraSubscriptionManagerTest.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/utils/GuiceUtils.java
- mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/PostgresMailboxSessionMapperFactory.java
- mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/mail/PostgresAttachmentMapper.java
- mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/mail/PostgresAttachmentModule.java
- mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/mail/PostgresMessageMapper.java
- mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/mail/dao/PostgresAttachmentDAO.java
- mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/mail/dto/AttachmentsDTO.java
- mailbox/postgres/src/test/java/org/apache/james/mailbox/postgres/DeleteMessageListenerTest.java
- mailbox/postgres/src/test/java/org/apache/james/mailbox/postgres/DeleteMessageListenerWithRLSTest.java
- mailbox/postgres/src/test/java/org/apache/james/mailbox/postgres/PostgresMailboxManagerAttachmentTest.java
- mailbox/postgres/src/test/java/org/apache/james/mailbox/postgres/PostgresMailboxManagerProvider.java
- mailbox/postgres/src/test/java/org/apache/james/mailbox/postgres/PostgresTestSystemFixture.java
- mailbox/postgres/src/test/java/org/apache/james/mailbox/postgres/mail/PostgresAnnotationMapperRowLevelSecurityTest.java
- mailbox/postgres/src/test/java/org/apache/james/mailbox/postgres/mail/PostgresAttachmentBlobReferenceSourceTest.java
- mailbox/postgres/src/test/java/org/apache/james/mailbox/postgres/mail/PostgresAttachmentMapperTest.java
- mailbox/postgres/src/test/java/org/apache/james/mailbox/postgres/mail/PostgresMapperProvider.java
- mailbox/postgres/src/test/java/org/apache/james/mailbox/postgres/mail/PostgresMessageMapperRowLevelSecurityTest.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/AttachmentIdAssignationStrategy.java
- mpt/impl/imap-mailbox/postgres/src/test/java/org/apache/james/mpt/imapmailbox/postgres/host/PostgresHostSystem.java
- server/container/guice/cassandra/src/main/java/org/apache/james/modules/mailbox/CassandraMailboxModule.java
- server/container/guice/mailbox-postgres/src/main/java/org/apache/james/modules/mailbox/PostgresMailboxModule.java
This PR is used for later attachment improvement apply to postgres in tmail backend
> Update postgres attachment to use string as id instead of UUID

- mailbox/memory/src/main/java/org/apache/james/mailbox/inmemory/mail/InMemoryMailboxMapper.java
- mailbox/postgres/src/test/java/org/apache/james/mailbox/postgres/mail/PostgresMailboxMapperACLTest.java
- mailbox/postgres/src/test/java/org/apache/james/mailbox/postgres/mail/RLSSupportPostgresMailboxMapperACLTest.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/MailboxMapperACLTest.java
Using `ConcurrentHashMap.compute` api of ensuring thread-safe, instead of get then set
> [FIX] make `updateACL` thread-safe in InMemoryMailboxMapper

- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/RecipientRewriteTableProcessor.java
Previously, unexpected technical issues (like Cassandra driver error) were interpreted as functional errors, which is misleading and prevent retrying timely the error.
> [FIX] Forward unexpected exceptions upon executing RRT

- mailbox/api/src/test/java/org/apache/james/mailbox/MailboxManagerTest.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMailboxManager.java
- mpt/impl/imap-mailbox/core/src/main/java/org/apache/james/mpt/imapmailbox/suite/Rename.java
- mpt/impl/imap-mailbox/core/src/main/resources/org/apache/james/imap/scripts/RenameSharedMailbox.test
- mpt/impl/imap-mailbox/jpa/src/test/java/org/apache/james/mpt/imapmailbox/jpa/JpaRenameTest.java
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/pom.xml
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/MailboxSetMethodContract.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/MailboxFactory.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/MailboxSetUpdatePerformer.scala
- server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/mail/RightsTest.scala
> JAMES-2182 Implement: Rename mailbox with rights

- event-bus/api/src/main/java/org/apache/james/events/EventBus.java
- event-bus/distributed/src/main/java/org/apache/james/events/EventBusReconnectionHandler.java
- event-bus/distributed/src/main/java/org/apache/james/events/GroupRegistrationHandler.java
- event-bus/distributed/src/main/java/org/apache/james/events/GroupRegistrationHandlerGroup.java
- event-bus/distributed/src/main/java/org/apache/james/events/KeyReconnectionHandler.java
- event-bus/distributed/src/main/java/org/apache/james/events/RabbitEventBusConsumerHealthCheck.java
- event-bus/distributed/src/main/java/org/apache/james/events/RabbitMQEventBus.java
- event-bus/in-vm/src/main/java/org/apache/james/events/InVMEventBus.java
- server/apps/distributed-app/src/main/java/org/apache/james/CassandraRabbitMQJamesServerMain.java
- server/apps/distributed-pop3-app/src/main/java/org/apache/james/DistributedPOP3JamesServerMain.java
- server/apps/postgres-app/src/main/java/org/apache/james/PostgresJamesServerMain.java
- server/container/guice/distributed/src/main/java/org/apache/james/modules/event/MailboxEventBusModule.java
To support new event bus extension in TMail (refer to https://github.com/linagora/tmail-backend/issues/1556)
> Refactor some event bus handlers so that they do not tightly bind to RabbitMQEventBus

- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EmailSetMethodContract.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/json/EmailSetSerializer.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/EmailSet.scala
Currently, the client sends a JSON request with `headers: EmailHeader[]` under the `bodyValues` property, structured as follows:
```json
"bodyValues": {
"a49d": {
"value": "$htmlBody",
"isTruncated": false,
"isEncodingProblem": false,
"header:Specific:asText": "MATCHME"
}
}
```
However, according to [RFC 8621](https://datatracker.ietf.org/doc/html/rfc8621#section-4.1), `EmailBodyValue` does not reference headers property. 
Instead, headers are mentioned in the `EmailBodyPart`.
The example in the RFC is also similar.
To align with the RFC specification, we need to update the mapping. 
This change will also support cases where the email part uses `blobId` instead of `partId`, while still allowing the client to set headers.
> JAMES-3962 JMAP Email/set: move `EmailHeader[]` from `bodyValues` to `htmlBody`/`textBody`

- protocols/netty/src/main/java/org/apache/james/protocols/netty/AllButStartTlsLineBasedChannelHandler.java
- protocols/netty/src/main/java/org/apache/james/protocols/netty/CommandInjectionDetectedException.java
- server/protocols/protocols-smtp/src/main/java/org/apache/james/smtpserver/DataLineJamesMessageHookHandler.java
**WHY** We have this exception arising on a prod environment (low occurence) and we are blind...
Is it a faulty client?
Is it an attack by injection attempt?
Are we too strict?
The analysis of the actual line causing the failure could be very helpful to answer those questions...
**Debug info we can't get**: starttls is the very begining of a connection so BEFORE auth and BEFORE mua details. Those are thus not available to the diagnostic...
> [ENHANCEMENT] CommandInjectionDetectedException: cary over the exception

- server/protocols/webadmin/webadmin-core/src/main/java/org/apache/james/webadmin/jettyserver/JettyHandler.java
- server/protocols/webadmin/webadmin-http-client/pom.xml
- server/protocols/webadmin/webadmin-http-client/src/main/java/org/apache/james/webadmin/httpclient/WebAdminHTTPClientFactory.java
It will fix case `500 org. eclipse. jetty.io.EofException: Closed` when client try re-using existing connection.
I suggestion we set header `Connection: close` in the response to client for fixed it. 
Command: `curl 127.0.0.1:52389/healthcheck 127.0.0.1:52389/healthcheck -v --http1.1` 
Before:
```
*   Trying 127.0.0.1:52330...
* Connected to 127.0.0.1 (127.0.0.1) port 52330
> GET /healthcheck HTTP/1.1
> Host: 127.0.0.1:52330
> User-Agent: curl/8.7.1
> Accept: */*
>
* Request completely sent off
< HTTP/1.1 200 OK
< Server: Jetty(12.0.15)
< Date: Wed, 26 Feb 2025 08:32:17 GMT
< Access-Control-Allow-Origin: *
< Access-Control-Request-Method: DELETE, GET, POST, PUT
< Access-Control-Allow-Headers: Content-Type, Authorization, Accept
< Content-Type: application/json
< Transfer-Encoding: chunked …
```
> JAMES-4104 - Webadmin Spark - Fix Error `500 org. eclipse. jetty.io.EofException: Closed`

- server/container/util/src/main/java/org/apache/james/util/MDCBuilder.java
- server/container/util/src/test/java/org/apache/james/util/MDCBuilderTest.java
Keeping the last value is OK IMO.
This would avoid similar MDC issues as the IMAP ID command issue where `mailUserAgent` was added multiple times to MDC.
> [ENHANCEMENT] MDC should be lenient when duplicate keys

- docs/modules/servers/partials/configure/jmap.adoc
- server/apps/distributed-app/sample-configuration/jvm.properties
- server/data/data-jmap-cassandra/src/main/java/org/apache/james/jmap/cassandra/projections/CassandraMessageFastViewProjection.java
It does take rougthly 10% of the DB space
```
Table: message_fast_view_projection
SSTable count: 11
Space used (live): 11602029036
```
We are also to fallback leniently if unused.
So setting an optional TTL, contolled by an system property, defaulting to none, could be great to improve tiering of this table.
A value of 30 days would also seem relevant...
> [ENHANCEMENT] Allow setting a preview for TTL

- server/apps/migration/core-data-jpa-to-pg/sample-configuration/blob.properties
- server/apps/migration/core-data-jpa-to-pg/sample-configuration/logback.xml
- server/apps/migration/core-data-jpa-to-pg/src/main/java/org/apache/james/MigrationConfiguration.java
I ran the migration tool on my "production" this led me to detect a couple issues 
- a null pointer for the blobstoreConfiguration (not sure how I missed that in my local tests :/)
- the sample config suggested using deduplication for the blobstore which is not supported
With the fixes, my production data was migrated and I was able to use the jooq/postgres backed version of scaling-pulsar-smtp to transfer some emails
> [JAMES-4119] minor fixes

- protocols/smtp/src/main/java/org/apache/james/protocols/smtp/core/HeloCmdHandler.java
- protocols/smtp/src/main/java/org/apache/james/protocols/smtp/core/MailCmdHandler.java
- protocols/smtp/src/main/java/org/apache/james/protocols/smtp/core/QuitCmdHandler.java
- protocols/smtp/src/main/java/org/apache/james/protocols/smtp/core/RcptCmdHandler.java
- protocols/smtp/src/main/java/org/apache/james/protocols/smtp/core/esmtp/EhloCmdHandler.java
- protocols/smtp/src/main/java/org/apache/james/protocols/smtp/core/log/HookResultLogger.java
I had a rought debugging session with a customer and getting detailed actions from any SMTP transaction included turning on debug logs and being flooded with irrelevant logs. My feeling was that we could easily do better.
This changeset proposes to keep:
- Email rejection at INFO level (so that it gets logged on system production)
- Mail SMTP commands at level DEBUG 
- And the noise at level TRACE (detailed hooks & their results)
Care is taken to truncate input to 80 chars...
> [ENHANCEMENT] Improve smtp debug logs

- mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/OpenSearchMailboxConfiguration.java
- mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/query/CriterionConverter.java
- mailbox/opensearch/src/test/java/org/apache/james/mailbox/opensearch/OpenSearchQueryStringTest.java
This allows eg the user that both the terms "avocado" and "banana" are expected when searching the string
"avocado banana"
Amongst overs.
> JAMES-4057 Enable Query String to be used on OpenSearch

- backends-common/redis/src/main/java/org/apache/james/backends/redis/RedisClientFactory.scala
- backends-common/redis/src/main/java/org/apache/james/backends/redis/RedisHealthCheck.scala
- backends-common/redis/src/test/java/org/apache/james/backends/redis/RedisClusterExtension.java
- backends-common/redis/src/test/java/org/apache/james/backends/redis/RedisMasterReplicaExtension.java
- backends-common/redis/src/test/java/org/apache/james/backends/redis/RedisSentinelExtension.java
- backends-common/redis/src/test/java/org/apache/james/backends/redis/RedisTLSExtension.java
Currently, in the `RedisHealthcheck`, we are using Reactor's timeout handling, not the timeout provided by Redis Lettuce.
With this configuration, the timeout will be correctly handled by the Lettuce library
Reference: https://github.com/redis/lettuce/discussions/2614
> JAMES-4072 Enable timeout option in RedisClientFactory

- mailbox/api/src/test/java/org/apache/james/mailbox/MailboxManagerTest.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMailboxManager.java
- mpt/impl/imap-mailbox/core/src/main/resources/org/apache/james/imap/scripts/RenameSharedMailbox.test
- protocols/imap/src/main/java/org/apache/james/imap/api/display/HumanReadableText.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/AbstractMailboxProcessor.java
- server/protocols/protocols-imap4/src/test/java/org/apache/james/imapserver/netty/IMAPServerTest.java
We observed a few `MailboxExistsException` error logs since the change https://github.com/apache/james-project/commit/91f50b031ce2fd1040aa345272ae3f3a76e13b99#diff-51e67dcd44af864286be49fbe7d5474bff07b8fe6cd0536121b4f2898dbbda9e.
Actually, the errors are still caught by the main reactor stream, therefore no impact to users. However, it seems errors emitted by asynchronous operators like `.filterWhen` can be propagated through their own internal asynchronous paths and result in unhandled exceptions being logged (e.g., `onErrorDropped`).
> JAMES-2182 StoreMailboxManager should avoid throwing exception in `.filterWhen`

- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/pushsubscription/WebPushClient.scala
- server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/pushsubscription/WebPushClientContract.scala
It seems that some push gateways, like MSGraph, are using return codes 200 and 202 as well.
> JAMES-3539 WebPushClient should accept more flexible 20x codes from Push server

- server/data/data-jmap-cassandra/src/main/java/org/apache/james/jmap/cassandra/pushsubscription/CassandraPushSubscriptionRepository.java
- server/data/data-jmap-cassandra/src/test/java/org/apache/james/jmap/cassandra/pushsubscription/CassandraPushSubscriptionRepositoryTest.java
- server/data/data-jmap-postgres/src/main/java/org/apache/james/jmap/postgres/pushsubscription/PostgresPushSubscriptionRepository.java
- server/data/data-jmap/src/main/java/org/apache/james/jmap/memory/pushsubscription/MemoryPushSubscriptionRepository.java
- server/data/data-jmap/src/main/scala/org/apache/james/jmap/api/change/TypeStateFactory.scala
- server/data/data-jmap/src/main/scala/org/apache/james/jmap/api/model/PushSubscription.scala
- server/data/data-jmap/src/test/java/org/apache/james/jmap/memory/pushsubscription/MemoryPushSubscriptionRepositoryTest.java
- server/data/data-jmap/src/test/scala/org/apache/james/jmap/api/pushsubscription/PushDeleteUserDataTaskStepTest.scala
- server/data/data-jmap/src/test/scala/org/apache/james/jmap/api/pushsubscription/PushSubscriptionRepositoryContract.scala
- server/protocols/jmap-rfc-8621-integration-tests/distributed-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/distributed/DistributedPushSubscriptionSetMethodTest.java
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/PushSubscriptionSetMethodContract.scala
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/probe/TypeStateProbe.scala
- server/protocols/jmap-rfc-8621-integration-tests/memory-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/memory/MemoryPushSubscriptionSetMethodTest.java
- server/protocols/jmap-rfc-8621-integration-tests/postgres-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/postgres/PostgresPushSubscriptionSetMethodTest.java
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/core/PushSubscriptionSet.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/PushSubscriptionUpdatePerformer.scala
- server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/pushsubscription/PushListenerTest.scala
- server/protocols/webadmin-integration-test/memory-webadmin-integration-test/src/test/java/org/apache/james/webadmin/integration/memory/MemoryUserDeletionIntegrationTest.java
According to the rfc https://datatracker.ietf.org/doc/html/rfc8620#section-7.2 PushSubscription/set should accept a null value for types, and in this case register the push ith all the types available on the server.
We need to fix this to be RFC compliant.
> JAMES-3539 Types field in push subscription should accept null value

- mailbox/opensearch/src/test/java/org/apache/james/mailbox/opensearch/json/IndexableMessageTest.java
- mailbox/opensearch/src/test/resources/eml/alternative.json
- mailbox/opensearch/src/test/resources/eml/attachments-filename-in-content-type.eml
- mailbox/store/src/main/java/org/apache/james/mailbox/store/search/mime/MimePartParser.java
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/resources/eml/attachment-filename-in-content-type.eml
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EmailQueryMethodContract.scala
Make the attachment filename search more resilient.
> [FIX] Attachment filename should be indexed when missing in the `Content-Disposition` header but exists in the `Content-Type` header

- backends-common/redis/pom.xml
- backends-common/redis/src/main/java/org/apache/james/backends/redis/RedisClientFactory.scala
- backends-common/redis/src/main/java/org/apache/james/backends/redis/RedisConfiguration.scala
- backends-common/redis/src/test/java/org/apache/james/backends/redis/RedisClusterExtension.java
- backends-common/redis/src/test/java/org/apache/james/backends/redis/RedisConfigurationTest.scala
- docs/modules/servers/partials/configure/redis.adoc
- server/mailet/rate-limiter-redis/src/main/java/org/apache/james/rate/limiter/redis/RedisClusterRateLimiterFactory.java
- server/mailet/rate-limiter-redis/src/main/scala/org/apache/james/rate/limiter/redis/RedisRateLimiter.scala
A couple of Redis config entries are not applied fully e.g. `ioThreads`, `workerThreads`, `readFrom`.
I take the chance to fix them, clean up the code, and allow Lettuce to use native epoll transport.
> JAMES-3693 Polish Redis client setup code

- third-party/rspamd/docker-compose-distributed.yml
- third-party/rspamd/docker-compose-rspamd-with-kvrocks-sentinel.yml
- third-party/rspamd/docker-compose-rspamd-with-kvrocks-standalone.yml
- third-party/rspamd/docker-compose-rspamd-with-redis-sentinel.yml
- third-party/rspamd/docker-compose.yml
- third-party/rspamd/sample-configuration/kvrocks/sentinel/replica-node/kvrocks.conf
- third-party/rspamd/sample-configuration/rspamd-kvrocks-sentinel.conf
- third-party/rspamd/src/test/java/org/apache/james/rspamd/RspamdExtension.java
This would allow Rspamd to execute EVASHA_RO commands against Kvrocks replicas (instead of EVASHA, which Kvrocks replicas reject ATM).
cf: https://github.com/rspamd/rspamd/pull/5419
Then no workaround is needed anymore for Rspamd + Kvrocks sentinel.
> JAMES-4124 Upgrade Rspamd to 3.12.0

- docs/modules/servers/partials/configure/imap.adoc
- protocols/imap/src/main/java/org/apache/james/imap/processor/DefaultProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/fetch/FetchProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/main/DefaultImapProcessorFactory.java
- server/container/guice/protocols/imap/src/main/java/org/apache/james/modules/protocols/IMAPServerModule.java
- server/protocols/protocols-imap4/src/test/java/org/apache/james/imapserver/netty/IMAPHealthCheckTest.java
- server/protocols/protocols-imap4/src/test/java/org/apache/james/imapserver/netty/IMAPServerTest.java
- src/site/xdoc/server/config-imap4.xml
Some mail user agents relies on *partial body retrieval* in order to simulate "streaming" (and catching back upon transmission errors within a message scope)
This is most notably true for IOS clients which issues commands like:
```
UID FETCH xx FetchData{items=[UID], setSeen=false, bodyElements=[BodyFetchElement{firstOctet=0, numberOfOctets=10024, name=BODY[1.1], sectionType=CONTENT}]
```
(so streaming not the bytes of the message but of it's individual subparts - we simply cannot work offset into S3)
Using chuncks of 10024 bytes means that in order to download a 10MB files ~ 1000 requests needs to be done and thus 1000 S3 reads.
Cache for FETCH of partial body content. (we can bet on locality as a given connection will be used)
If the fetch concerns a single email and if the fetch …
> Improve IMAP partial body fetch

- pom.xml
- server/protocols/jwt/pom.xml
- server/protocols/jwt/src/main/java/org/apache/james/jwt/DefaultPublicKeyProvider.java
- server/protocols/jwt/src/main/java/org/apache/james/jwt/JwksPublicKeyProvider.java
- server/protocols/jwt/src/main/java/org/apache/james/jwt/JwtTokenVerifier.java
- server/protocols/jwt/src/main/java/org/apache/james/jwt/OidcJwtTokenVerifier.java
- server/protocols/jwt/src/main/java/org/apache/james/jwt/PublicKeyProvider.java
- server/protocols/jwt/src/test/java/org/apache/james/jwt/DefaultPublicKeyProviderTest.java
- server/protocols/jwt/src/test/java/org/apache/james/jwt/JwksPublicKeyProviderTest.java
- server/protocols/jwt/src/test/java/org/apache/james/jwt/JwtTokenVerifierTest.java
- server/protocols/jwt/src/test/java/org/apache/james/jwt/OidcJwtTokenVerifierTest.java
- server/protocols/webadmin/webadmin-core/src/main/java/org/apache/james/webadmin/authentication/JwtFilter.java
- src/site/markdown/server/manage-webadmin.md
- src/site/xdoc/server/config-webadmin.xml
- documentation on how to set up JWT for webadmin access
- added token expiration tests (it works, but was not documented/tested)
- added kid lookup support to the DefaultPublicKeyProvider (using JWK thumbprint), changed the PublicKeyProvider interface to have a separate get(kid) method, changed JwksPublicKeyProvider to have separate implementations for the get all and get kid methods (instead of the instance having a kid associated with it and either using it or not in the get all method), and updated JwtTokenVerifier (shared by both) to try the kid lookup if kid header exists or iterate through all keys if the header does not exist. This makes the design more intuitive, consistent and shared among all providers.
- upgrade jwks-rsa
- upgrade jjwt, including migration to the new api - …
> Improved JWT support

- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/DSNBounce.java
An i18n version of dsn bounce may need to override the body message, for example.
> [ENHANCEMENT] Allow to extend DSNBounce

- pom.xml
- server/protocols/protocols-imap4/pom.xml
- server/protocols/protocols-library/pom.xml
- server/protocols/protocols-library/src/main/java/org/apache/james/protocols/lib/LegacyJavaEncryptionFactory.java
The library has been renamed from sslcontext-kickstart to ayza. The latest version is 10.0.0
Sorry for the inconvenience
> Bump and rename sslcontext-kicktart to ayza

- docs/modules/servers/partials/RemoteDelivery.adoc
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/RemoteDelivery.java
- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/remote/delivery/RemoteDeliveryConfiguration.java
CF https://www.mail-archive.com/server-user@james.apache.org/msg17214.html
This attempts to give the option for user to still activate SSL / STARTTLS but to tolerate invalid / expired certs.
(I feel uneasy with the conclusion of just run an unsecure mail server or die by bureaucracy. I believe there's a third way that is allow to relax James' SSL setup.)
> [RemoteDelivery] Add an explicit option to trust all certs

- docs/modules/servers/partials/configure/smtp-hooks.adoc
- server/protocols/protocols-smtp/src/main/java/org/apache/james/smtpserver/ConfigurationAuthHook.java
- server/protocols/protocols-smtp/src/main/java/org/apache/james/smtpserver/NoAuthCmdHandlerLoader.java
- server/protocols/protocols-smtp/src/main/java/org/apache/james/smtpserver/SetMailAttributeMessageHook.java
- server/protocols/protocols-smtp/src/test/java/org/apache/james/smtpserver/ConfiguredAuthTest.java
- server/protocols/protocols-smtp/src/test/resources/smtpserver-configured-auth.xml
My need:
Port 25: authentication is disabled
Port 465: submission, user auth, strict sender validation
Port 26: opened locally with k8s cluster. I want to add auth for it not to be opened. 
I do not want to create user for port 26 because:
- I do not want to have a mailbox assiciated to it
- I want the set up to be declarative to limit to the maximum manual actions
The idea is to deploy to port 26 a specific auth mechanism matching configuration. 
```
<handlerchain coreHandlersPackage="org.apache.james.smtpserver.NoAuthCmdHandlerLoader" enableJmx="false">
<handler class="org.apache.james.protocols.smtp.core.esmtp.AuthCmdHandler" />
<handler class="org.apache.james.smtpserver.SetMailAttributeMessageHook" >
<name>technicaluser</name>
<value>true</value>
</handler>
<handler …
```
> [ENHANCEMENT] Smtp technical accounts

- docs/modules/servers/partials/configure/imap.adoc
- server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/IMAPCommandsThrottler.java
- server/protocols/protocols-imap4/src/test/java/org/apache/james/imapserver/netty/IMAPCommandsThrottlerTest.java
- server/protocols/protocols-imap4/src/test/resources/commandsThrottling.xml
Helps mitigate delays in Outlook upon sending email: a full refresh is needed for the operation to complete
That's the only use cases the throttling is frontally visible to end users.
> JAMES-4140 Allow reseting IMAP command throttling upon specific commands

- server/data/data-jmap-cassandra/src/test/resources/json/event-v4.json
- server/data/data-jmap/src/main/java/org/apache/james/jmap/api/filtering/Rule.java
- server/data/data-jmap/src/test/java/org/apache/james/jmap/api/filtering/RuleFixture.java
- server/protocols/jmap-rfc-8621/src/main/java/org/apache/james/jmap/mailet/filter/ContentMatcher.java
- server/protocols/jmap-rfc-8621/src/test/java/org/apache/james/jmap/mailet/filter/JMAPFilteringTest.java
- server/protocols/webadmin/webadmin-jmap/src/test/java/org/apache/james/webadmin/data/jmap/RunRulesOnMailboxRoutesTest.java
So users can filter mails having an existing header, e.g., a mail from Github notifications with header `X-Github-...`
> JAMES-4148 Implement ANY comparator for custom header
