apache/james-project

README.adoc
=> Updated grammar at top of readme.

protocols/smtp/src/main/java/org/apache/james/protocols/smtp/core/AbstractHookableCmdHandler.java, server/protocols/protocols-library/src/main/java/org/apache/james/protocols/lib/netty/JMXEnabledOrderedMemoryAwareThreadPoolExecutor.java
opened these two jira tickets was asked to do PR for them.
=> randymo-JAMES-2192, JAMES-2193

server/data/data-jdbc/src/test/java/org/apache/james/mailrepository/jdbc/JDBCMailRepositoryTest.java
Just removed disabled test that actually passes.
Please close the [ticket](https://issues.apache.org/jira/browse/JAMES-2304).
=> JAMES-2304 JDBC Mail repository do not allow content update.

mailet/standard/src/main/java/org/apache/james/transport/mailets/RemoveMimeHeader.java, mailet/standard/src/main/java/org/apache/james/transport/mailets/RemoveMimeHeaderByPrefix.java, mailet/standard/src/main/java/org/apache/james/transport/matchers/HasHeader.java, mailet/standard/src/main/java/org/apache/james/transport/matchers/HasHeaderWithPrefix.java, mailet/standard/src/test/java/org/apache/james/transport/mailets/RemoveMimeHeaderByPrefixTest.java, mailet/standard/src/test/java/org/apache/james/transport/mailets/RemoveMimeHeaderTest.java, mailet/standard/src/test/java/org/apache/james/transport/matchers/HasHeaderTest.java, mailet/standard/src/test/java/org/apache/james/transport/matchers/HasHeaderWithPrefixTest.java
=> JAMES-2735 Update mailet and matcher that uses the headers and the per recipients

dockerfiles/run/guice/cassandra-ldap/destination/conf/extensions.properties, dockerfiles/run/guice/cassandra-rabbitmq-ldap/destination/conf/extensions.properties, dockerfiles/run/guice/cassandra-rabbitmq/destination/conf/extensions.properties, dockerfiles/run/guice/cassandra/destination/conf/extensions.properties, dockerfiles/run/guice/jpa-smtp/destination/conf/extensions.properties, dockerfiles/run/guice/jpa/destination/conf/extensions.properties, dockerfiles/run/guice/memory/destination/conf/extensions.properties, mailbox/api/src/main/java/org/apache/james/mailbox/events/Group.java, mailbox/cassandra/README.txt, mailbox/elasticsearch/src/main/java/org/apache/james/mailbox/elasticsearch/json/IndexableMessage.java, mailbox/tools/copier/src/test/java/org/apache/james/mailbox/tools/copier/MailboxCopierTest.java, server/container/guice/guice-common/src/main/java/org/apache/james/modules/server/GuiceMailRepositoryLoader.java, server/container/guice/guice-common/src/main/java/org/apache/james/utils/GuiceProtocolHandlerLoader.java, server/container/guice/guice-utils/src/main/java/org/apache/james/utils/GuiceGenericLoader.java, server/container/guice/mailbox/src/main/java/org/apache/james/modules/mailbox/MailboxListenerFactory.java, server/container/guice/mailbox/src/main/java/org/apache/james/modules/mailbox/PreDeletionHookLoaderImpl.java, server/container/guice/mailet/src/main/java/org/apache/james/utils/GuiceMailetLoader.java, server/container/guice/mailet/src/main/java/org/apache/james/utils/GuiceMatcherLoader.java, server/data/data-jmap/src/test/java/org/apache/james/jmap/api/filtering/FilteringManagementContract.java, server/data/data-library/src/test/java/org/apache/james/rrt/lib/AbstractRecipientRewriteTableTest.java, server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/RabbitMQMailQueueFactory.java, src/site/xdoc/server/dev-extend-mailet.xml
Just a very small typo that I spotted by looking over the shoulder of @chibenwa at OpenTechSummit ;-)
=> Fix typo in cassandra-rabbitmq Dockerfile conf

docs/antora.yml, docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/index.adoc, docs/modules/admin/nav.adoc, docs/modules/admin/pages/index.adoc, docs/modules/dev/nav.adoc, docs/modules/dev/pages/index.adoc, docs/modules/doc/nav.adoc, docs/modules/doc/pages/index.adoc, docs/modules/ops/nav.adoc, docs/modules/ops/pages/index.adoc, docs/modules/user/nav.adoc, docs/modules/user/pages/build.adoc, docs/modules/user/pages/index.adoc, docs/modules/user/pages/learn.adoc, docs/modules/user/pages/try.adoc
Hi!
As a newcomer, I have the advantage of seeing the project with fresh eyes. Everything I know about James comes exclusively from the docs. I am therefore unbiased about how the text is written. If something is difficult to understand, it is easier for me to know than somebody who understands James well.
With that in mind, I wanted to provide my comments on this page, and I plan on doing so for the website in general as well. It is my hope that the people in the community will answer my various questions in order to help me with this task.
I thought it would be easiest to get started directly in this PR, even though this is **not at all ready to be merged**. This is a work in progress, but I need help in order to continue. I thought this would provide a good place for me to ask …
=> Initial updates to top README page

README.adoc
=> simple grammar fixes

docs/modules/servers/nav.adoc, docs/modules/servers/pages/15-minute-demo.adoc, docs/modules/servers/pages/demo.adoc
=> JAMES-3187 Updates to "Demo Server" section of new documentation

server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EmailChangesMethodContract.scala, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/MailboxChangesMethodContract.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/json/EmailGetSerializer.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/json/MailboxSerializer.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/json/package.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/EmailGet.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/MailboxGet.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailChangesMethod.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/MailboxChangesMethod.scala
See https://github.com/apache/james-project/pull/352 for master version
=> JAMES-3481 JMAP: Fix the s/maxChanged/maxChanges/ typo [3.6.0 backport]

server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/resources/eml/mdn_relate_original_message.eml, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/MDNParseMethodContract.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/json/MDNParseSerializer.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/MDNParse.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/MDNParseMethod.scala
Ref: https://github.com/linagora/james-project/issues/4312
=> JAMES-3520 MDN/parse should position forEmailId property

server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/CustomMethodContract.scala, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/SessionRoutesContract.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/core/JmapRfc8621Configuration.scala, server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/core/JmapRfc8621ConfigurationTest.scala, server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/routes/SessionRoutesTest.scala
Contents of pull request #379 to 3.6.x branch
=> JAMES-3556 to 3.6.x branch

server/container/guice/protocols/jmap/src/main/java/org/apache/james/jmap/rfc8621/RFC8621MethodsModule.java, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EmailImportContract.scala, server/protocols/jmap-rfc-8621-integration-tests/memory-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/memory/MemoryEmailImportTest.java, server/protocols/jmap-rfc-8621/doc/specs/spec/mail/message.mdown, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/json/EmailSetSerializer.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/EmailImport.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailImportMethod.scala
Weekend contribution to continue the (long) journey toward JMAP spec compliance...
=> JAMES-3532 Implement Email/import

server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/http/UploadRoutes.java, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/UploadContract.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/UploadRoutes.scala
=> JAMES-3432 to 3.6.x branch

server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EmailSetMethodContract.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/EmailSet.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailSetCreatePerformer.scala
I'm trying to start the process of identifiying bugfixes merged into master branch and creating PR-s with the same content to 3.6.x branch. My goal is to make 3.6.x branch a stable branch that is long lived and an alternative to building on top of latest branch (that could be unstable at times). Eventually we could make releases like 3.6.1 etch from this branch (though it is a time consuming process so this is why it would be done rather rarely).
So as first candidate I picked this Pull request: https://github.com/apache/james-project/pull/362 and now I'm proposing to merge it to 3.6.x branch.
=> JAMES-3537 (Email/set create should allow to attach mails) to 3.6.x branch

protocols/smtp/src/main/java/org/apache/james/protocols/smtp/core/AbstractSenderAuthIdentifyVerificationRcptHook.java, server/container/guice/cassandra/src/main/java/org/apache/james/modules/mailbox/CassandraMailboxModule.java, server/container/guice/memory-guice/src/main/java/org/apache/james/modules/mailbox/MemoryMailboxModule.java, server/data/data-jmap-cassandra/src/main/java/org/apache/james/jmap/cassandra/change/CassandraEmailChangeRepository.java, server/data/data-jmap-cassandra/src/main/java/org/apache/james/jmap/cassandra/change/CassandraMailboxChangeRepository.java, server/data/data-jmap-cassandra/src/test/java/org/apache/james/jmap/cassandra/change/CassandraEmailChangeRepositoryTest.java, server/data/data-jmap-cassandra/src/test/java/org/apache/james/jmap/cassandra/change/CassandraMailboxChangeRepositoryTest.java, server/data/data-jmap/src/main/java/org/apache/james/jmap/api/change/CanNotCalculateChangesException.java, server/data/data-jmap/src/main/java/org/apache/james/jmap/api/change/EmailChanges.java, server/data/data-jmap/src/main/java/org/apache/james/jmap/api/change/MailboxChanges.java, server/data/data-jmap/src/main/java/org/apache/james/jmap/memory/change/MemoryEmailChangeRepository.java, server/data/data-jmap/src/main/java/org/apache/james/jmap/memory/change/MemoryMailboxChangeRepository.java, server/data/data-jmap/src/test/java/org/apache/james/jmap/api/change/EmailChangeRepositoryContract.java, server/data/data-jmap/src/test/java/org/apache/james/jmap/api/change/MailboxChangeRepositoryContract.java, server/data/data-jmap/src/test/java/org/apache/james/jmap/memory/change/MemoryEmailChangeRepositoryTest.java, server/data/data-jmap/src/test/java/org/apache/james/jmap/memory/change/MemoryMailboxChangeRepositoryTest.java, server/mailet/integration-testing/src/test/java/org/apache/james/smtp/SmtpIdentityVerificationTest.java, server/protocols/jmap-rfc-8621-integration-tests/distributed-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/distributed/DistributedEmailChangeMethodTest.java, server/protocols/jmap-rfc-8621-integration-tests/distributed-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/distributed/DistributedMailboxChangeMethodTest.java, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EmailChangesMethodContract.scala, server/protocols/jmap-rfc-8621-integration-tests/memory-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/memory/MemoryEmailChangesMethodTest.java, server/protocols/jmap-rfc-8621-integration-tests/memory-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/memory/MemoryMailboxChangesMethodTest.java, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailChangesMethod.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailSetUpdatePerformer.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailSubmissionSetMethod.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/MailboxChangesMethod.scala, server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/change/MailboxChangeListenerTest.scala, server/testing/src/main/java/org/apache/james/utils/SMTPMessageSender.java
https://github.com/apache/james-project/pull/377
https://github.com/apache/james-project/pull/395
https://github.com/apache/james-project/pull/394
=> [3.6.1] Backport recent changes

dockerfiles/run/guice/cassandra-ldap/Dockerfile, dockerfiles/run/guice/cassandra/Dockerfile, dockerfiles/run/guice/jpa-smtp/Dockerfile, dockerfiles/run/guice/jpa/Dockerfile
This helps discoverability of these folders by
docker users...
=> JAMES-1858 Docker: expose volumes used for persistence with volumes

server/data/data-cassandra/src/test/java/org/apache/james/domainlist/cassandra/CacheDomainListTest.java, server/data/data-library/src/main/java/org/apache/james/domainlist/lib/AbstractDomainList.java, server/mailet/mailetcontainer-camel/src/test/java/org/apache/james/mailetcontainer/impl/JamesMailetContextTest.java
Tonight experimentation and thoughts...
=> JAMES-3467 Polish domainList cache

backends-common/cassandra/src/main/java/org/apache/james/backends/cassandra/migration/Migration.java
Caused errors to be lost, making diagnostic harder
=> JAMES-2813 Add a missing log upon Migration

server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/WebSocketContract.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/WebSocketRoutes.scala
Multiplex emissions with Flux.merge to prevent
on the Sink object. The sink is now only used for the push subscription.
=> JAMES-3491 JMAP webSocket can be used to mix responses and state changes

protocols/pop3/src/main/java/org/apache/james/protocols/pop3/mailbox/ImapMailbox.java, protocols/pop3/src/main/java/org/apache/james/protocols/pop3/mailbox/Mailbox.java, server/container/guice/protocols/pop/src/main/java/org/apache/james/modules/protocols/POP3ServerModule.java, server/protocols/protocols-pop3/src/main/java/org/apache/james/pop3server/core/PassCmdHandler.java, server/protocols/protocols-pop3/src/main/java/org/apache/james/pop3server/mailbox/DefaultMailboxAdapterFactory.java, server/protocols/protocols-pop3/src/main/java/org/apache/james/pop3server/mailbox/MailboxAdapter.java, server/protocols/protocols-pop3/src/main/java/org/apache/james/pop3server/mailbox/MailboxAdapterFactory.java, server/protocols/protocols-pop3/src/main/resources/META-INF/spring/pop3server-context.xml, server/protocols/protocols-pop3/src/test/java/org/apache/james/pop3server/POP3ServerTest.java
Also remove unused methods in POP3 Mailbox API
Modify POP3ServerTests so that it can be reused.
=> JAMES-3585 Allow customizing the POP3 mailbox

mailbox/api/src/main/java/org/apache/james/mailbox/SubscriptionManager.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/user/CassandraSubscriptionMapper.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreSubscriptionManager.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/user/SubscriptionMapper.java, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/MailboxFactory.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailChangesMethod.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailGetMethod.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/MailboxChangesMethod.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/MailboxGetMethod.scala
Benefit IMAP LSUB workloads.
Benefits JMAP RFC-8621 workloads that do list mailboxes.
=> [REFACTORING] CassandraSubscriptionMapper should prepare its statements

docs/modules/servers/pages/distributed/configure/jmap.adoc, server/protocols/jmap-rfc-8621-integration-tests/distributed-jmap-rfc-8621-integration-tests/src/test/resources/jmap.properties, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/CustomMethodContract.scala, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/SessionRoutesContract.scala, server/protocols/jmap-rfc-8621-integration-tests/memory-jmap-rfc-8621-integration-tests/src/test/resources/jmap.properties, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/core/Capabilities.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/core/Capability.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/core/JmapRfc8621Configuration.scala, server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/routes/JMAPApiRoutesTest.scala, server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/routes/SessionRoutesTest.scala, src/site/xdoc/server/config-jmap.xml
Allow for more flexibility in advertising URLs in the session object.
=> JAMES-3491 Configurable websocket URL for JMAP configuration

backends-common/cassandra/src/main/java/org/apache/james/backends/cassandra/init/configuration/CassandraConfiguration.java, docs/modules/servers/pages/distributed/configure/cassandra.adoc, mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageDAOTest.java, mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageDAOV3Test.java, mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/migration/MessageV3MigrationTest.java, mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/utils/GuiceUtils.java, server/blob/blob-cassandra/src/main/java/org/apache/james/blob/cassandra/CassandraBlobStoreDAO.java, server/blob/blob-cassandra/src/main/java/org/apache/james/blob/cassandra/CassandraBlobStoreFactory.java, server/blob/blob-cassandra/src/main/java/org/apache/james/blob/cassandra/CassandraBucketDAO.java, server/blob/blob-cassandra/src/main/java/org/apache/james/blob/cassandra/CassandraDefaultBucketDAO.java, server/blob/blob-cassandra/src/test/java/org/apache/james/blob/cassandra/CassandraBlobStoreClOneTest.java, server/blob/blob-cassandra/src/test/java/org/apache/james/blob/cassandra/CassandraBlobStoreDAOTest.java, server/blob/blob-cassandra/src/test/java/org/apache/james/blob/cassandra/CassandraBlobStoreTest.java, server/blob/blob-cassandra/src/test/java/org/apache/james/blob/cassandra/CassandraPassTroughBlobStoreTest.java, server/blob/blob-cassandra/src/test/java/org/apache/james/blob/cassandra/cache/CachedBlobStoreTest.java, server/container/guice/cassandra-guice/sample-configuration/cassandra.properties, server/container/guice/cassandra-rabbitmq-guice/sample-configuration/cassandra.properties, server/mailrepository/mailrepository-cassandra/pom.xml, server/mailrepository/mailrepository-cassandra/src/test/java/org/apache/james/mailrepository/cassandra/CassandraMailRepositoryTest.java, server/mailrepository/mailrepository-cassandra/src/test/java/org/apache/james/mailrepository/cassandra/CassandraMailRepositoryWithFakeImplementationsTest.java, server/queue/queue-rabbitmq/src/test/java/org/apache/james/queue/rabbitmq/RabbitMQMailQueueConfigurationChangeTest.java, server/queue/queue-rabbitmq/src/test/java/org/apache/james/queue/rabbitmq/RabbitMQMailQueueTest.java, src/site/xdoc/server/config-cassandra.xml
Just a beginning, many things left to do...
=> JAMES-3586 CL one option for the Cassandra blob store

server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/model/Keywords.java, server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/model/message/view/MessageFastView.java, server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/model/message/view/MessageFastViewFactory.java, server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/model/message/view/MessageFullView.java, server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/model/message/view/MessageFullViewFactory.java, server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/model/message/view/MessageHeaderView.java, server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/model/message/view/MessageHeaderViewFactory.java, server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/model/message/view/MessageMetadataView.java, server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/model/message/view/MessageMetadataViewFactory.java, server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/model/message/view/MessageViewFactory.java, server/protocols/jmap-draft/src/test/java/org/apache/james/jmap/draft/model/message/view/MessageFullViewTest.java
These minor enhancements aims at improving the CPU costs of `getMessages`
Gains are marginal yet the fix are simple. And desirable.
=> [PERFORMANCE] Another small enhancement round

core/src/main/java/org/apache/james/core/quota/QuotaCountLimit.java, core/src/main/java/org/apache/james/core/quota/QuotaSizeLimit.java, mailbox/api/src/main/java/org/apache/james/mailbox/model/FetchGroup.java, mailbox/api/src/main/java/org/apache/james/mailbox/model/MailboxACL.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageIdDAO.java, protocols/imap/src/main/java/org/apache/james/imap/decode/parser/SetAnnotationCommandParser.java, protocols/pop3/src/main/java/org/apache/james/protocols/pop3/core/MDCConstants.java, server/container/util/src/main/java/org/apache/james/util/mime/MessageContentExtractor.java, server/container/util/src/main/java/org/apache/james/util/streams/Limit.java, server/container/util/src/main/java/org/apache/james/util/streams/Offset.java, server/data/data-library/src/main/java/org/apache/james/dlp/eventsourcing/aggregates/DLPDomainConfiguration.java, server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/jsieve/VacationReply.java, server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/model/Keyword.java, server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/utils/FilterToCriteria.java, server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/mailet/filter/ContentMatcher.java, server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/IMAPMDCContext.java
Favor orElseGet in such places.
Use constants where it makes sense.
=> [REFACTORING] Avoid Optional::orElse where it looks expensive

mailbox/api/src/main/java/org/apache/james/mailbox/model/ThreadId.java, mailbox/api/src/test/java/org/apache/james/mailbox/model/ThreadIdTest.java, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/Email.scala
Using the MessageResult::getThreadId property at the JMAP level - in Email/get + Email/import
=> JAMES-3516 Using the MessageResult::getThreadId property at the JMAP level

mailbox/api/src/main/java/org/apache/james/mailbox/MailboxPathLocker.java, mailbox/api/src/main/java/org/apache/james/mailbox/MessageManager.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraAttachmentMapper.java, mailbox/maildir/src/main/java/org/apache/james/mailbox/maildir/MaildirStore.java, mailbox/maildir/src/test/java/org/apache/james/mailbox/maildir/MaildirMailboxManagerProvider.java, mailbox/maildir/src/test/java/org/apache/james/mailbox/maildir/MaildirSubscriptionManagerTest.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/JVMMailboxPathLocker.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/MessageStorer.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/NoMailboxPathLocker.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMessageManager.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/AttachmentMapper.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/MessageIdMapper.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/MessageMapper.java, mpt/impl/imap-mailbox/maildir/src/test/java/org/apache/james/mpt/imapmailbox/maildir/host/MaildirHostSystem.java, server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/methods/MessageAppender.java, server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/methods/SetMessagesCreationProcessor.java, server/protocols/jmap-draft/src/test/java/org/apache/james/jmap/draft/methods/SetMessagesCreationProcessorTest.java, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailSetCreatePerformer.scala
I extracted (and fixed) the subpart of apache#455 that do break the build....
https://github.com/linagora/james-project/pull/4322 is the draft version of this (I messed up, I opened it on the wrong repo...)
=> [PERFORMANCE] (further) Reactify setMessages create 

docs/antora.yml
=> JAMES-3187 Remove duplicated SNAPSHOT mention in documentation menu

server/container/guice/configuration/src/main/java/org/apache/james/utils/DelegatedPropertiesConfiguration.java, server/container/guice/configuration/src/main/java/org/apache/james/utils/PropertiesProvider.java, server/container/guice/configuration/src/test/java/org/apache/james/utils/PropertiesProviderTest.java, server/container/guice/configuration/src/test/resources/a.properties, server/container/guice/guice-utils/src/main/java/org/apache/james/utils/ExtensionConfiguration.java, server/container/guice/guice-utils/src/test/java/org/apache/james/utils/ExtensionConfigurationTest.java, server/container/guice/protocols/webadmin/src/main/java/org/apache/james/modules/server/WebAdminServerModule.java, server/container/guice/protocols/webadmin/src/test/java/org/apache/james/modules/server/WebAdminServerModuleTest.java
Proof that we can now lauch 2 custom routes with webAdmin...
https://user-images.githubusercontent.com/6928740/121112398-8f229a00-c83a-11eb-9ecd-7f81ca145775.mp4
I discovered our property loading was actually flowed...
Review @Arsnael  please...
=> JAMES-2886 Fix collection handling for PropertiesProvider

CHANGELOG.md, dockerfiles/run/docker-compose.yml, docs/modules/servers/pages/distributed/run-docker.adoc, docs/modules/servers/pages/distributed/run.adoc, server/container/guice/cassandra-rabbitmq-guice/README.adoc, server/testing/src/main/java/org/apache/james/util/docker/Images.java, src/site/markdown/server/install/guice-cassandra-rabbitmq-s3.md
3.8.16 have some undisclosed vulnerabilities.
=> JAMES-3593 Recommend the upgrade to RabbitMQ 3.8.17

backends-common/elasticsearch-v7/src/main/java/org/apache/james/backends/es/v7/IndexCreationFactory.java
Security plugin turned on, this leads to errors in
environment where the right to create indexes is not
granted.
=> JAMES-3492 Do not create indices if it already exists

mailbox/plugin/deleted-messages-vault/src/main/java/org/apache/james/vault/blob/BlobStoreDeletedMessageVault.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMessageIdManager.java, metrics/metrics-dropwizard/src/main/java/org/apache/james/metrics/dropwizard/DropWizardMetricFactory.java, metrics/metrics-logger/src/main/java/org/apache/james/metrics/logger/DefaultMetricFactory.java, metrics/metrics-tests/src/main/java/org/apache/james/metrics/tests/RecordingMetricFactory.java, server/blob/blob-cassandra/src/main/java/org/apache/james/blob/cassandra/cache/CachedBlobStore.java, server/protocols/jmap-draft/src/test/java/org/apache/james/jmap/http/JWTAuthenticationStrategyTest.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/jwt/JWTAuthenticationStrategy.java, server/protocols/jwt/src/main/java/org/apache/james/jwt/JwtTokenVerifier.java, server/protocols/jwt/src/test/java/org/apache/james/jwt/JwtTokenVerifierTest.java, server/protocols/webadmin/webadmin-core/src/main/java/org/apache/james/webadmin/authentication/JwtFilter.java, server/protocols/webadmin/webadmin-core/src/test/java/org/apache/james/webadmin/authentication/JwtFilterTest.java
-> Avoid parsing and verfying JWT signature twice
-> Simplify reactor logic in `CachedBlobStore`
-> Avoid Flux.from calls that might not be needed
=> [PERFORMANCE] Various little fixes

server/protocols/jmap-draft-integration-testing/jmap-draft-integration-testing-common/src/test/java/org/apache/james/jmap/JMAPAuthenticationTest.java, server/protocols/jmap-draft-integration-testing/jmap-draft-integration-testing-common/src/test/java/org/apache/james/jmap/ProvisioningTest.java, server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/http/AuthenticationRoutes.java, server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/http/DownloadRoutes.java, server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/http/JMAPApiRoutes.java, server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/http/UploadRoutes.java, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/BackReferenceContract.scala, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/SessionRoutesContract.scala, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/UploadContract.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/DownloadRoutes.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/JMAPApiRoutes.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/SessionRoutes.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/UploadRoutes.scala
(to play well with compression)
=> JAMES-3600 All JMAP calls should position Content-Length

server/data/data-jmap/src/main/java/org/apache/james/jmap/api/model/Preview.java
Ref: https://issues.apache.org/jira/browse/JAMES-2993
Change modifier access of some method in `Preview.Factory` to allow more flexibility to James mail processing
=> JAMES-2993 Preview.Factory - change modifier access

server/apps/cassandra-app/pom.xml, server/apps/cli/pom.xml, server/apps/distributed-app/pom.xml, server/apps/jpa-app/pom.xml, server/apps/jpa-smtp-app/pom.xml, server/apps/jpa-smtp-mariadb-app/pom.xml, server/apps/memory-app/pom.xml, server/apps/webadmin-cli/pom.xml
These manifest entries were defined for the MPT
app and I think it do not hurt to generify
their use...
=> JAMES-3261 Add some manifest entries when using maven-jar-plugin

backends-common/rabbitmq/src/main/java/org/apache/james/backends/rabbitmq/Constants.java, backends-common/rabbitmq/src/main/java/org/apache/james/backends/rabbitmq/QueueArguments.java, backends-common/rabbitmq/src/main/java/org/apache/james/backends/rabbitmq/RabbitMQConfiguration.java, backends-common/rabbitmq/src/main/java/org/apache/james/backends/rabbitmq/RabbitMQConnectionFactory.java, backends-common/rabbitmq/src/test/java/org/apache/james/backends/rabbitmq/DockerRabbitMQ.java, backends-common/rabbitmq/src/test/java/org/apache/james/backends/rabbitmq/RabbitMQConfigurationTest.java, backends-common/rabbitmq/src/test/java/org/apache/james/backends/rabbitmq/RabbitMQConnectionFactoryTest.java, docs/modules/servers/pages/distributed/configure/rabbitmq.adoc, event-bus/distributed/src/main/java/org/apache/james/events/EventDispatcher.java, event-bus/distributed/src/main/java/org/apache/james/events/GroupRegistration.java, event-bus/distributed/src/main/java/org/apache/james/events/GroupRegistrationHandler.java, event-bus/distributed/src/main/java/org/apache/james/events/KeyReconnectionHandler.java, event-bus/distributed/src/main/java/org/apache/james/events/KeyRegistrationHandler.java, event-bus/distributed/src/main/java/org/apache/james/events/RabbitMQEventBus.java, event-bus/distributed/src/test/java/org/apache/james/events/NetworkErrorTest.java, event-bus/distributed/src/test/java/org/apache/james/events/RabbitMQEventBusDeadLetterQueueUpgradeTest.java, event-bus/distributed/src/test/java/org/apache/james/events/RabbitMQEventBusTest.java, mpt/impl/imap-mailbox/rabbitmq/src/test/java/org/apache/james/mpt/imapmailbox/rabbitmq/host/RabbitMQEventBusHostSystem.java, server/apps/distributed-app/sample-configuration/rabbitmq.properties, server/container/guice/distributed/src/main/java/org/apache/james/modules/event/JMAPEventBusModule.java, server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/RabbitMQMailQueueFactory.java, server/queue/queue-rabbitmq/src/test/java/org/apache/james/queue/rabbitmq/RabbitMQMailQueueConfigurationChangeTest.java, server/queue/queue-rabbitmq/src/test/java/org/apache/james/queue/rabbitmq/RabbitMQMailQueueTest.java, server/queue/queue-rabbitmq/src/test/java/org/apache/james/queue/rabbitmq/RabbitMqMailQueueFactoryTest.java, src/site/xdoc/server/config-rabbitmq.xml
Reopened because of Spring build issues.
Already approuved, I am just looking for a green build
=> JAMES-3604 Improve RabbitMQ resiliency #508

event-bus/distributed/src/main/java/org/apache/james/events/RoutingKeyConverter.java, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EmailQueryMethodContract.scala, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/MailboxSetMethodContract.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/core/Id.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/http/BasicAuthenticationStrategy.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/Method.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/SessionSupplier.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/vacation/VacationResponse.scala, server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/json/Fixture.scala, server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/json/VacationResponseGetSerializationTest.scala
- Avoid refined with regex, prefer introduce custom validators
- Avoid needlessly generating full session to only validate accoutId
- Also improve messaging handling
=> [PERFORMANCE] Improve JMAP RFC-8621 performances

mailbox/store/src/main/java/org/apache/james/mailbox/store/search/SearchUtil.java, mailbox/store/src/test/java/org/apache/james/mailbox/store/search/SearchUtilTest.java
CF https://github.com/apache/james-project/pull/529
=> JAMES-3611 SearchUtil getBaseSubject do not sanitize empty subject

mailbox/store/src/main/java/org/apache/james/mailbox/store/search/comparator/SentDateComparator.java, mailbox/store/src/test/java/org/apache/james/mailbox/store/search/comparator/SentDateComparatorTest.java, pom.xml, server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/model/message/view/MessageFastViewFactory.java, server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/model/message/view/MessageFullViewFactory.java, server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/model/message/view/MessageHeaderViewFactory.java, server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/model/message/view/MessageViewFactory.java
This allow leveraging the multiple performance enhancements that this release
contributed.
=> [UPGRADE] Upgrade to MIME4J 0.8.5

pom.xml
Fixes CVE-2021-36090 that exposes to denial of services attacks
=> [UPGRADE] Security upgrade: common-compress to 1.21

mailbox/api/src/main/java/org/apache/james/mailbox/model/SearchQuery.java, mailbox/api/src/main/java/org/apache/james/mailbox/model/ThreadId.java, mailbox/elasticsearch-v7/src/main/java/org/apache/james/mailbox/elasticsearch/v7/MailboxMappingFactory.java, mailbox/elasticsearch-v7/src/main/java/org/apache/james/mailbox/elasticsearch/v7/json/IndexableMessage.java, mailbox/elasticsearch-v7/src/main/java/org/apache/james/mailbox/elasticsearch/v7/json/JsonMessageConstants.java, mailbox/elasticsearch-v7/src/main/java/org/apache/james/mailbox/elasticsearch/v7/query/CriterionConverter.java, mailbox/elasticsearch-v7/src/test/java/org/apache/james/mailbox/elasticsearch/v7/ElasticSearchIntegrationTest.java, mailbox/elasticsearch-v7/src/test/java/org/apache/james/mailbox/elasticsearch/v7/json/IndexableMessageTest.java, mailbox/lucene/src/main/java/org/apache/james/mailbox/lucene/search/LuceneMessageSearchIndex.java, mailbox/lucene/src/test/java/org/apache/james/mailbox/lucene/search/LuceneMessageSearchIndexTest.java, mailbox/scanning-search/src/test/java/org/apache/james/mailbox/store/search/SimpleMessageSearchIndexTest.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/search/MessageSearches.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/search/SearchUtil.java, mailbox/store/src/test/java/org/apache/james/mailbox/store/search/AbstractMessageSearchIndexTest.java, mailbox/store/src/test/resources/eml/emailWithNonIndexableAttachmentWithoutAttachment.json, mailbox/store/src/test/resources/eml/htmlMail.json, mailbox/store/src/test/resources/eml/invalidCharset.json, mailbox/store/src/test/resources/eml/mail.json, mailbox/store/src/test/resources/eml/nonTextual.json, mailbox/store/src/test/resources/eml/pgpSignedMail.json, mailbox/store/src/test/resources/eml/recursiveMail.json, mailbox/store/src/test/resources/eml/recursiveMailWithoutAttachments.json, mailbox/store/src/test/resources/eml/spamMail.json
WIP: add threadId to ES document schema
Next: complete ES part, then ScanningSearch and Lucene
=> JAMES-3516 Enable threadId search query for MessageSearchIndex

mailbox/api/src/main/java/org/apache/james/mailbox/MailboxManager.java, mailbox/api/src/main/java/org/apache/james/mailbox/exception/ThreadNotFoundException.java, mailbox/api/src/main/java/org/apache/james/mailbox/model/ThreadId.java, mailbox/scanning-search/src/test/java/org/apache/james/mailbox/store/search/SearchThreadIdGuessingAlgorithmTest.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMailboxManager.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/NaiveThreadIdGuessingAlgorithm.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/SearchThreadIdGuessingAlgorithm.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/ThreadIdGuessingAlgorithm.java, mailbox/store/src/test/java/org/apache/james/mailbox/store/ThreadIdGuessingAlgorithmContract.java, server/container/guice/mailbox/src/main/java/org/apache/james/modules/MailboxProbeImpl.java, server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/mailet/ExtractMDNOriginalJMAPMessageId.java, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/ThreadGetContract.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/json/ThreadSerializer.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/Thread.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/ThreadGetMethod.scala
WIP: Plug getThread API into JMAP Thread/get
=> JAMES-3516 Implement MailboxManager::getThread API and plug it into JMAP Thread/get

pom.xml, server/apps/cassandra-app/pom.xml, server/apps/cassandra-app/src/test/java/org/apache/james/CassandraLdapJamesServerTest.java, server/apps/cassandra-app/src/test/java/org/apache/james/CassandraLdapJmapJamesServerTest.java, server/apps/distributed-app/pom.xml, server/apps/distributed-app/src/test/java/org/apache/james/CassandraRabbitMQLdapJmapJamesServerTest.java, server/apps/jpa-app/pom.xml, server/apps/jpa-app/src/main/java/org/apache/james/JPAJamesConfiguration.java, server/apps/jpa-app/src/main/java/org/apache/james/JPAJamesServerMain.java, server/apps/jpa-app/src/test/java/org/apache/james/JPAJamesServerTest.java, server/apps/jpa-app/src/test/java/org/apache/james/JPAJamesServerWithAuthenticatedDatabaseSqlValidationTest.java, server/apps/jpa-app/src/test/java/org/apache/james/JPAWithLDAPJamesServerTest.java, server/apps/jpa-app/src/test/java/org/apache/james/JamesCapabilitiesServerTest.java, server/apps/jpa-smtp-app/pom.xml, server/apps/jpa-smtp-app/src/main/java/org/apache/james/JPAJamesConfiguration.java, server/apps/jpa-smtp-app/src/main/java/org/apache/james/JPAJamesServerMain.java, server/apps/jpa-smtp-app/src/test/java/org/apache/james/JPAJamesServerTest.java, server/apps/jpa-smtp-app/src/test/java/org/apache/james/mariadb/JPAMariaDBJamesServerTest.java, server/container/guice/data-ldap/pom.xml, server/container/guice/data-ldap/src/test/java/org/apache/james/data/DockerLdapRule.java, server/container/guice/data-ldap/src/test/java/org/apache/james/data/LdapTestExtension.java, server/container/guice/jpa-common/src/main/java/org/apache/james/modules/data/JPADataModule.java, server/container/guice/pom.xml
Includes:
- JPA App
- JPA-SMTP App
=> JAMES-3618 Support LDAP for JPA guice based apps

server/blob/blob-aes/src/main/java/org/apache/james/blob/aes/AESBlobStoreDAO.java, server/blob/blob-aes/src/test/java/org/apache/james/blob/aes/AESBlobStoreDAOTest.java, server/blob/blob-api/src/main/java/org/apache/james/blob/api/BlobStore.java, server/blob/blob-api/src/main/java/org/apache/james/blob/api/BlobStoreDAO.java, server/blob/blob-api/src/main/java/org/apache/james/blob/api/MetricableBlobStore.java, server/blob/blob-api/src/test/java/org/apache/james/blob/api/BucketBlobStoreContract.java, server/blob/blob-api/src/test/java/org/apache/james/blob/api/BucketBlobStoreDAOContract.java, server/blob/blob-cassandra/src/main/java/org/apache/james/blob/cassandra/CassandraBlobStoreDAO.java, server/blob/blob-cassandra/src/main/java/org/apache/james/blob/cassandra/cache/CachedBlobStore.java, server/blob/blob-cassandra/src/test/java/org/apache/james/blob/cassandra/CassandraBlobStoreDAOTest.java, server/blob/blob-memory/src/main/java/org/apache/james/blob/memory/MemoryBlobStoreDAO.java, server/blob/blob-memory/src/test/java/org/apache/james/blob/memory/MemoryBlobStoreDAOTest.java, server/blob/blob-s3/src/main/java/org/apache/james/blob/objectstorage/aws/BucketNameResolver.java, server/blob/blob-s3/src/main/java/org/apache/james/blob/objectstorage/aws/S3BlobStoreDAO.java, server/blob/blob-s3/src/test/java/org/apache/james/blob/objectstorage/aws/BucketNameResolverTest.java, server/blob/blob-storage-strategy/src/main/scala/org/apache/james/server/blob/deduplication/DeDuplicationBlobStore.scala, server/blob/blob-storage-strategy/src/main/scala/org/apache/james/server/blob/deduplication/PassThroughBlobStore.scala
This allow bucket based expiration to be in synchronisation with the underlying data store
=> JAMES-3544 Blob store should allow to list bucket

server/data/data-jmap/pom.xml, server/data/data-jmap/src/main/java/org/apache/james/jmap/api/model/Size.scala, server/data/data-jmap/src/main/java/org/apache/james/jmap/api/model/Upload.scala, server/data/data-jmap/src/main/java/org/apache/james/jmap/api/model/UploadId.java, server/data/data-jmap/src/main/java/org/apache/james/jmap/api/upload/UploadRepository.java, server/data/data-jmap/src/main/java/org/apache/james/jmap/memory/upload/InMemoryUploadRepository.java, server/data/data-jmap/src/test/java/org/apache/james/jmap/api/upload/UploadRepositoryContract.scala, server/data/data-jmap/src/test/java/org/apache/james/jmap/memory/upload/InMemoryUploadRepositoryTest.java, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/CustomMethodContract.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/json/EmailGetSerializer.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/Email.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/EmailBodyPart.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/EmailQuery.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/EmailSet.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailImportMethod.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailSetCreatePerformer.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/DownloadRoutes.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/UploadRoutes.scala
Ref: https://issues.apache.org/jira/browse/JAMES-3544
https://github.com/linagora/james-project/issues/4349
=> [JAMES-3544] UploadRepository contract & InMemory implementationtemp

src/homepage/index.html
- Download page in the top links
- Reference the getting started from downloads guide before the docker hands-on
- We still keep a link to downloads inside the community block
=> JAMES-3614 The homepage should comply with the ASF release policy

mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraThreadDAO.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/modules/CassandraThreadModule.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/table/CassandraThreadTable.java, mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraThreadDAOTest.java, server/container/guice/cassandra/src/main/java/org/apache/james/modules/mailbox/CassandraMailboxModule.java, server/container/guice/cassandra/src/main/java/org/apache/james/modules/mailbox/CassandraThreadIdGuessingModule.java
=> JAMES-3516 Implement Thread Cassandra table

mailbox/elasticsearch-v7/src/main/java/org/apache/james/mailbox/elasticsearch/v7/json/EMailer.java, mailbox/elasticsearch-v7/src/main/java/org/apache/james/mailbox/elasticsearch/v7/json/IndexableMessage.java, mailbox/elasticsearch-v7/src/main/java/org/apache/james/mailbox/elasticsearch/v7/json/MimePartParser.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/MimeDescriptorImpl.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMessageManager.java, mailet/api/src/main/java/org/apache/mailet/AttributeValue.java, server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/methods/MIMEMessageConverter.java
=> [PERFORMANCE] AttributeValue: object mapper can be static

docs/modules/servers/pages/distributed/operate/webadmin.adoc, mailbox/api/src/main/java/org/apache/james/mailbox/model/MailboxCounters.java, mailbox/api/src/test/java/org/apache/james/mailbox/MailboxManagerTest.java, mailbox/api/src/test/java/org/apache/james/mailbox/model/MailboxCountersTest.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMailboxCounterDAO.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageMapper.java, mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMailboxCounterDAOTest.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMailboxManager.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMessageManager.java, server/protocols/jmap-draft/src/test/java/org/apache/james/jmap/draft/model/MailboxFactoryTest.java, server/protocols/webadmin/webadmin-mailbox/src/main/java/org/apache/james/webadmin/routes/UserMailboxesRoutes.java, server/protocols/webadmin/webadmin-mailbox/src/main/java/org/apache/james/webadmin/service/UserMailboxesService.java, server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/routes/UserMailboxesRoutesTest.java, src/site/markdown/server/manage-webadmin.md
Ref: https://issues.apache.org/jira/browse/JAMES-3621
https://github.com/linagora/james-project/issues/4363
=> James 3621 get mail box size

server/container/guice/queue/rabbitmq/src/main/java/org/apache/james/modules/queue/rabbitmq/RabbitMQModule.java
This avoids re-preparing queries
=> JAMES-3601 Bind ContentStartDAO as a singleton

docs/modules/servers/pages/distributed/operate/webadmin.adoc, server/container/guice/protocols/webadmin-mailbox/src/main/java/org/apache/james/modules/server/WebadminMailboxTaskSerializationModule.java, server/protocols/webadmin-integration-test/distributed-webadmin-integration-test/src/test/java/org/apache/james/webadmin/integration/rabbitmq/RabbitMQWebAdminServerTaskSerializationIntegrationTest.java, server/protocols/webadmin/webadmin-mailbox/src/main/java/org/apache/james/webadmin/routes/UserMailboxesRoutes.java, server/protocols/webadmin/webadmin-mailbox/src/main/java/org/apache/james/webadmin/service/ClearMailboxContentTask.java, server/protocols/webadmin/webadmin-mailbox/src/main/java/org/apache/james/webadmin/service/ClearMailboxContentTaskAdditionalInformationDTO.java, server/protocols/webadmin/webadmin-mailbox/src/main/java/org/apache/james/webadmin/service/ClearMailboxContentTaskDTO.java, server/protocols/webadmin/webadmin-mailbox/src/main/java/org/apache/james/webadmin/service/UserMailboxesService.java, server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/routes/UserMailboxesRoutesTest.java, server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/service/ClearMailboxContentTaskAdditionalInformationDTOTest.java, server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/service/ClearMailboxContentTaskSerializationTest.java, server/protocols/webadmin/webadmin-mailbox/src/test/resources/json/clearMailboxContent.additionalInformation.json, server/protocols/webadmin/webadmin-mailbox/src/test/resources/json/clearMailboxContent.task.json, src/site/markdown/server/manage-webadmin.md
Ref: https://issues.apache.org/jira/browse/JAMES-3621
https://github.com/linagora/james-project/issues/4364
WIP: testcase & document
=> JAMES-3621 WebAdmin - Clearing content of given mailbox - Task & Route 

docs/modules/servers/pages/distributed/operate/webadmin.adoc, server/apps/cassandra-app/src/main/java/org/apache/james/CassandraJamesServerMain.java, server/apps/distributed-app/src/main/java/org/apache/james/CassandraRabbitMQJamesServerMain.java, server/blob/blob-memory/src/main/java/org/apache/james/blob/memory/MemoryBlobStoreDAO.java, server/container/guice/protocols/webadmin-jmap/src/main/java/org/apache/james/modules/server/JmapUploadCleanupModule.java, server/protocols/webadmin-integration-test/distributed-webadmin-integration-test/src/test/java/org/apache/james/webadmin/integration/rabbitmq/RabbitMQWebAdminServerTaskSerializationIntegrationTest.java, server/protocols/webadmin/webadmin-jmap/pom.xml, server/protocols/webadmin/webadmin-jmap/src/main/java/org/apache/james/webadmin/data/jmap/JmapUploadRoutes.java, server/protocols/webadmin/webadmin-jmap/src/main/java/org/apache/james/webadmin/data/jmap/UploadCleanupTaskAdditionalInformationDTO.java, server/protocols/webadmin/webadmin-jmap/src/main/java/org/apache/james/webadmin/data/jmap/UploadCleanupTaskDTO.java, server/protocols/webadmin/webadmin-jmap/src/main/java/org/apache/james/webadmin/data/jmap/UploadRepositoryCleanupTask.java, server/protocols/webadmin/webadmin-jmap/src/test/java/org/apache/james/webadmin/data/jmap/JmapUploadRoutesTest.java, server/protocols/webadmin/webadmin-jmap/src/test/java/org/apache/james/webadmin/data/jmap/UploadCleanupTaskAdditionalInformationDTOTest.java, server/protocols/webadmin/webadmin-jmap/src/test/java/org/apache/james/webadmin/data/jmap/UploadCleanupTaskSerializationTest.java, server/protocols/webadmin/webadmin-jmap/src/test/resources/json/cleanUpload.additionalInformation.json, server/protocols/webadmin/webadmin-jmap/src/test/resources/json/cleanUpload.task.json, src/site/markdown/server/manage-webadmin.md
Ref : https://issues.apache.org/jira/browse/JAMES-3544
https://github.com/linagora/james-project/issues/4357
=> James 3544 webadmin upload repository cleanup

src/site/xdoc/server/install.xml
=> [DOCUMENTATION] Install guide needs to refer to JRE 11

server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EmailQueryMethodContract.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailQueryMethod.scala
=> JAMES-3440 JMAP RFC-8621: EmailQueryView position handling was wrong

server/blob/blob-storage-strategy/pom.xml, server/blob/blob-storage-strategy/src/main/java/org/apache/james/server/blob/deduplication/BlobGCTask.java, server/blob/blob-storage-strategy/src/main/java/org/apache/james/server/blob/deduplication/BlobGCTaskAdditionalInformationDTO.java, server/blob/blob-storage-strategy/src/main/java/org/apache/james/server/blob/deduplication/BloomFilterGCAlgorithm.java, server/protocols/webadmin/webadmin-data/pom.xml, server/protocols/webadmin/webadmin-data/src/main/java/org/apache/james/webadmin/routes/BlobRoutes.java, server/protocols/webadmin/webadmin-data/src/test/java/org/apache/james/webadmin/routes/BlobRoutesTest.java
Jira: https://issues.apache.org/jira/browse/JAMES-3150
ref: https://github.com/linagora/james-project/issues/4370
=> JAMES-3150 Expose the webAdmin endpoint to trigger blob deduplicated garbage collection

server/blob/blob-storage-strategy/src/test/java/org/apache/james/server/blob/deduplication/BloomFilterGCAlgorithmContract.java
Before: 80%
After: 1%
This was causing test stability issues
=> JAMES-3150 BloomFilterGCAlgorithmContract: Lower false positive rates

server/container/core/src/main/java/org/apache/james/server/core/filesystem/FileSystemImpl.java, server/container/core/src/main/java/org/apache/james/server/core/filesystem/ResourceFactory.java, server/container/filesystem-api/src/main/java/org/apache/james/filesystem/api/FileSystem.java, server/container/spring/src/main/java/org/apache/james/container/spring/context/JamesServerApplicationContext.java, server/container/spring/src/main/java/org/apache/james/container/spring/context/web/JamesServerWebApplicationContext.java, server/container/spring/src/main/java/org/apache/james/container/spring/filesystem/FileSystemImpl.java, server/container/spring/src/main/java/org/apache/james/container/spring/filesystem/ResourceLoaderFileSystem.java, server/container/spring/src/main/java/org/apache/james/container/spring/resource/DefaultJamesResourceLoader.java, server/container/spring/src/main/java/org/apache/james/container/spring/resource/JamesResourceLoader.java, server/data/data-file/src/main/java/org/apache/james/sieverepository/file/SieveFileRepository.java, server/data/data-file/src/test/java/org/apache/james/mailrepository/FileMailRepositoryTest.java, server/data/data-file/src/test/java/org/apache/james/sieverepository/file/SieveFileRepositoryTest.java, server/data/data-library/src/main/java/org/apache/james/repository/file/AbstractFileRepository.java
Please refer to https://github.com/apache/james-project/pull/636 https://github.com/apache/james-project/pull/637
=> JAMES-3646 Sanitize some File based components [backport]

src/homepage/howTo/imap-server.html
=> JAMES-3644 Link for SPF and DKIM

src/homepage/_posts/2021-09-21-james-joinsapachecon.markdown
=> Blog post for James joining ApacheCON 2021

src/homepage/_posts/2021-09-26-mime4j-0.8.6.markdown, src/site/xdoc/download.xml
- Post for the release
- Update of the download page
=> RELEASE MIME4J 0.8.6

server/container/core/src/main/java/org/apache/james/server/core/MailImpl.java, server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/DSNBounce.java, server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/RecipientRewriteTableProcessor.java, server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/redirect/ProcessRedirectNotify.java
Large mails exceeding 100K would be stored on disk and not reclaimed...
=> JAMES-3477 Mail::duplicate did lead to file leak in various places [BACKPORT 3.6.1]

server/container/util/src/main/java/org/apache/james/util/concurrent/JMXEnabledScheduledThreadPoolExecutor.java, server/container/util/src/main/java/org/apache/james/util/concurrent/JMXEnabledThreadPoolExecutor.java, server/mailet/mailetcontainer-impl/src/main/java/org/apache/james/mailetcontainer/lib/AbstractStateCompositeProcessor.java, server/mailet/mailetcontainer-impl/src/main/java/org/apache/james/mailetcontainer/lib/AbstractStateMailetProcessor.java, server/protocols/protocols-library/src/main/java/org/apache/james/protocols/lib/netty/JMXEnabledOrderedMemoryAwareThreadPoolExecutor.java
=> JAMES-3652 Avoid locking in protocol task execution

docs/modules/servers/pages/distributed/operate/webadmin.adoc, server/container/guice/protocols/webadmin-data/src/main/java/org/apache/james/modules/server/DataRoutesModules.java, server/protocols/webadmin/webadmin-data/src/main/java/org/apache/james/webadmin/routes/AliasRoutes.java, server/protocols/webadmin/webadmin-data/src/main/java/org/apache/james/webadmin/routes/GroupsRoutes.java, server/protocols/webadmin/webadmin-data/src/main/java/org/apache/james/webadmin/routes/UserRoutes.java, server/protocols/webadmin/webadmin-data/src/main/java/org/apache/james/webadmin/service/AggregateUserEntityValidator.java, server/protocols/webadmin/webadmin-data/src/main/java/org/apache/james/webadmin/service/DefaultUserEntityValidator.java, server/protocols/webadmin/webadmin-data/src/main/java/org/apache/james/webadmin/service/RecipientRewriteTableUserEntityValidator.java, server/protocols/webadmin/webadmin-data/src/main/java/org/apache/james/webadmin/service/UserEntityValidator.java, server/protocols/webadmin/webadmin-data/src/main/java/org/apache/james/webadmin/service/UserService.java, server/protocols/webadmin/webadmin-data/src/test/java/org/apache/james/webadmin/routes/AliasRoutesTest.java, server/protocols/webadmin/webadmin-data/src/test/java/org/apache/james/webadmin/routes/GroupsRoutesTest.java, server/protocols/webadmin/webadmin-data/src/test/java/org/apache/james/webadmin/routes/UserRoutesTest.java, src/site/markdown/server/manage-webadmin.md
**Why?**: Adding a new entity requires to modify all the other
entity, which is error prone, and also fastidious...
These entity includes: groups, aliases, users.
**How?**: Write a modular validation system that all types would use.
Adding a new type would just require to add its validator.
=> JAMES-3657 Modular entity validation for webadmin-data

server/container/guice/protocols/jmap/src/main/java/org/apache/james/jmap/rfc8621/RFC8621MethodsModule.java, server/protocols/jmap-rfc-8621-integration-tests/distributed-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/distributed/DistributedCustomNamespaceTest.java, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/CustomNamespaceContract.scala, server/protocols/jmap-rfc-8621-integration-tests/memory-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/memory/MemoryCustomNamespaceTest.java, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/json/MailboxSerializer.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/Mailbox.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/MailboxFactory.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/MailboxNamespace.scala
Ref https://issues.apache.org/jira/browse/JAMES-3659
=> JAMES-3659 Modularize Namespace of mailbox share extension

server/apps/memory-app/src/main/java/org/apache/james/MemoryJamesServerMain.java, server/container/guice/cassandra/src/main/java/org/apache/james/modules/data/CassandraJmapModule.java, server/container/guice/protocols/jmap/src/main/java/org/apache/james/jmap/rfc8621/RFC8621MethodsModule.java, server/data/data-jmap/pom.xml, server/data/data-jmap/src/main/java/org/apache/james/jmap/memory/pushsubscription/MemoryPushSubscriptionModule.java, server/data/data-jmap/src/main/scala/org/apache/james/jmap/api/model/PushSubscription.scala, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/PushSubscriptionSetMethodContract.scala, server/protocols/jmap-rfc-8621-integration-tests/memory-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/memory/MemoryPushSubscriptionSetMethodTest.java, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/core/PushSubscriptionSet.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/json/PushSubscriptionSerializer.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/Method.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/PushSubscriptionSetCreatePerformer.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/PushSubscriptionSetMethod.scala, server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/json/PushSubscriptionSerializerTest.scala
Follow up https://github.com/apache/james-project/pull/717
=> JAMES-3539 PushSubscription/set create

server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/pom.xml, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/PushSubscriptionSetMethodContract.scala, server/protocols/jmap-rfc-8621-integration-tests/memory-jmap-rfc-8621-integration-tests/pom.xml, server/protocols/jmap-rfc-8621-integration-tests/memory-jmap-rfc-8621-integration-tests/src/test/resources/jmap.properties, server/protocols/jmap-rfc-8621-integration-tests/pom.xml, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/json/PushSerializer.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/PushSubscriptionSetCreatePerformer.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/pushsubscription/PushRequest.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/pushsubscription/WebPushClient.scala, server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/json/PushSerializerTest.scala, server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/pushsubscription/PushSubscriptionSetCreateProcessorTest.scala
Jira: https://issues.apache.org/jira/browse/JAMES-3539
=> JAMES-3539 PushSubscriptionSetCreateProcessor - pushVerification

server/container/guice/common/src/test/java/org/apache/james/ClockExtension.java, server/container/guice/distributed/src/main/java/org/apache/james/modules/event/JMAPEventBusModule.java, server/container/guice/protocols/jmap/src/main/java/org/apache/james/jmap/draft/JMAPModule.java, server/protocols/jmap-rfc-8621-integration-tests/distributed-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/distributed/DistributedWebPushTest.java, server/protocols/jmap-rfc-8621-integration-tests/distributed-jmap-rfc-8621-integration-tests/src/test/resources/smtpserver.xml, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/pom.xml, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/WebPushContract.scala, server/protocols/jmap-rfc-8621-integration-tests/memory-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/memory/MemoryWebPushTest.java
ref: https://github.com/linagora/james-project/issues/4419
Jira: https://issues.apache.org/jira/browse/JAMES-3539
=> JAMES-3539 JMAP webpush integration test

Jenkinsfile, server/container/guice/protocols/jmap/src/main/java/org/apache/james/jmap/rfc8621/RFC8621MethodsModule.java, server/data/data-jmap/src/main/scala/org/apache/james/jmap/api/identity/CustomIdentityDAO.scala, server/data/data-jmap/src/main/scala/org/apache/james/jmap/api/model/Identity.scala, server/protocols/jmap-rfc-8621-integration-tests/distributed-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/distributed/DistributedIdentitySetTest.java, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/IdentitySetContract.scala, server/protocols/jmap-rfc-8621-integration-tests/memory-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/memory/MemoryIdentitySetMethodTests.java, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/json/IdentitySerializer.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/IdentitySet.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/IdentitySetCreatePerformer.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/IdentitySetMethod.scala
resolve https://github.com/linagora/james-project/issues/4428
=> JAMES-3534 Implement Identity/set create

server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/IdentitySetContract.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/json/IdentitySerializer.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/IdentitySet.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/IdentitySetCreatePerformer.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/IdentitySetMethod.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/IdentitySetUpdatePerformer.scala
Jira: https://issues.apache.org/jira/browse/JAMES-3534
resolve https://github.com/linagora/james-project/issues/4429
=> JAMES-3534 Implement Identity/set update (custom identities)

server/data/data-jmap-cassandra/src/main/scala/org/apache/james/jmap/cassandra/identity/CassandraCustomIdentityDAO.scala, server/data/data-jmap/src/main/scala/org/apache/james/jmap/api/identity/CustomIdentityDAO.scala, server/data/data-jmap/src/main/scala/org/apache/james/jmap/memory/identity/MemoryCustomIdentityDAO.scala, server/data/data-jmap/src/test/scala/org/apache/james/jmap/api/identity/IdentityRepositoryTest.scala, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/IdentityGetContract.scala, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/IdentitySetContract.scala
Jira https://issues.apache.org/jira/browse/JAMES-3534
resolve https://github.com/linagora/james-project/issues/4427
=> JAMES-3534 Identity/set update should work on existing server-set Identities

server/apps/cassandra-app/sample-configuration/jvm.properties, server/apps/distributed-app/docs/modules/ROOT/pages/configure/index.adoc, server/apps/distributed-app/sample-configuration/jvm.properties, server/apps/distributed-pop3-app/sample-configuration/jvm.properties, server/apps/jpa-app/sample-configuration/jvm.properties, server/apps/jpa-smtp-app/sample-configuration/jvm.properties, server/apps/memory-app/sample-configuration/jvm.properties, server/container/core/src/main/java/org/apache/james/server/core/MimeMessageInputStreamSource.java, server/container/util/src/test/java/org/apache/james/util/SizeFormatTest.java, src/site/xdoc/server/config-system.xml
- Docmentation available
- Added but commented within jvm.properties file (cf #744)
This is a rework of #285 using #744 to improve discoverability
=> JAMES-3487 Java property: MimeMessageInputStreamSource THRESHOLD

server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/ImapChannelUpstreamHandler.java
Very rarely mdc can be called while the session is not yet registered.
```
java.lang.NullPointerException
at org.apache.james.imapserver.netty.ImapChannelUpstreamHandler.mdc(ImapChannelUpstreamHandler.java:112)
at org.apache.james.imapserver.netty.ImapChannelUpstreamHandler.exceptionCaught(ImapChannelUpstreamHandler.java:154)
at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:112)
at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
at org.jboss.netty.handler.codec.frame.FrameDecoder.exceptionCaught(FrameDecoder.java:377)
at …
```
=> JAMES-3613 Avoid a NPE due to IMAP MDC

server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/BackReferenceContract.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/ProcessingContext.scala, server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/json/BackReferenceTest.scala
https://issues.apache.org/jira/browse/JAMES-3677
=> JAMES-3677 BackReference should allow pointing to specific array elements

server/data/data-jmap-cassandra/src/main/scala/org/apache/james/jmap/cassandra/identity/CassandraCustomIdentityDAO.scala, server/data/data-jmap/src/main/scala/org/apache/james/jmap/api/identity/CustomIdentityDAO.scala, server/data/data-jmap/src/main/scala/org/apache/james/jmap/memory/identity/MemoryCustomIdentityDAO.scala, server/data/data-jmap/src/test/scala/org/apache/james/jmap/api/identity/CustomIdentityDAOContract.scala, server/data/data-jmap/src/test/scala/org/apache/james/jmap/api/identity/IdentityRepositoryTest.scala, server/data/data-jmap/src/test/scala/org/apache/james/jmap/memory/identity/MemoryCustomIdentityTest.scala, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/IdentitySetContract.scala
resolve https://github.com/linagora/james-project/issues/4433
=> JAMES-3534 Identity/set update + delete and Identity/get should fail for identities whose alias is deleted

pom.xml
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-44228
Let me know if something else needs to be done!
=> JAMES-3683 log4j 2.14.1 -> 2.15.0 to address CVE-2021-44228

pom.xml
=> JAMES-3683 Upgrade Log4J to 2.15.0 [3.6.x]

protocols/imap/src/main/java/org/apache/james/imap/api/process/ImapSession.java, protocols/imap/src/main/java/org/apache/james/imap/encode/FakeImapSession.java, protocols/imap/src/main/java/org/apache/james/imap/processor/AuthenticateProcessor.java, protocols/imap/src/main/java/org/apache/james/imap/processor/LoginProcessor.java, server/apps/cassandra-app/sample-configuration/imapserver.xml, server/apps/distributed-app/docs/modules/ROOT/pages/configure/imap.adoc, server/apps/distributed-app/sample-configuration/imapserver.xml, server/apps/jpa-app/sample-configuration/imapserver.xml, server/apps/memory-app/sample-configuration/imapserver.xml, server/apps/spring-app/src/main/resources/imapserver.xml, server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/IMAPServer.java, server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/ImapChannelUpstreamHandler.java, server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/NettyImapSession.java, server/protocols/protocols-imap4/src/test/java/org/apache/james/imapserver/netty/IMAPServerTest.java, server/protocols/protocols-imap4/src/test/resources/imapServerPlainAuthDisabled.xml, server/protocols/protocols-imap4/src/test/resources/imapServerPlainAuthEnabledWithoutRequireSSL.xml, server/testing/src/main/java/org/apache/james/utils/TestIMAPClient.java, server/testing/src/test/java/org/apache/james/utils/TestIMAPClientTest.java, src/site/xdoc/server/config-imap4.xml
WIP: modify document and sample config files
=> JAMES-3680 IMAP Allow disable plain authentication

pom.xml, server/protocols/jmap-draft/pom.xml, server/protocols/jwt/pom.xml
Build without Tests succeeded on my local. Let see if this breaks any tests.
=> JAMES-3686 Update JJWT library version

src/site/xdoc/server/install.xml
=> Fixed typo error Java version 1.11 to 11

server/apps/distributed-app/docs/modules/ROOT/pages/configure/imap.adoc, server/protocols/protocols-imap4/pom.xml, server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/IMAPServer.java, server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/ImapChannelUpstreamHandler.java, server/protocols/protocols-imap4/src/test/java/org/apache/james/imapserver/netty/IMAPServerTest.java, server/protocols/protocols-imap4/src/test/resources/imapServerRequireSSLIsFalseAndStartSSLIsFalse.xml, server/protocols/protocols-imap4/src/test/resources/imapServerRequireSSLIsFalseAndStartSSLIsTrue.xml, server/protocols/protocols-imap4/src/test/resources/imapServerRequireSSLIsTrueAndStartSSLIsFalse.xml, server/protocols/protocols-imap4/src/test/resources/imapServerRequireSSLIsTrueAndStartSSLIsTrue.xml, server/protocols/protocols-imap4/src/test/resources/imapServerStartTLS.xml, src/site/xdoc/server/config-imap4.xml
Jira: https://issues.apache.org/jira/browse/JAMES-3680
https://github.com/linagora/james-project/issues/4441
=> JAMES-3680 IMAP config support auth.requireSSL

server/apps/spring-app/src/main/resources/imapserver.xml, server/apps/spring-app/src/main/resources/managesieveserver.xml, server/apps/spring-app/src/main/resources/pop3server.xml, server/apps/spring-app/src/main/resources/smtpserver.xml
CF https://www.mail-archive.com/server-user@james.apache.org/msg16548.html
=> [CONF] Remove misleading comments regarding SSL

pom.xml
Fixes https://cve.report/CVE-2021-42550
=> [UPGRADE] Logback 1.2.5 -> 1.2.9

pom.xml
Fixes https://cve.report/CVE-2021-42550
=> [UPGRADE] Logback 1.2.3 -> 1.2.9

src/site/xdoc/server/config-smtp-lmtp.xml
Hi,
I thought the Sun JCE provider stuff is outdated.
Thanks,
=> [SITE] Remove misleading comments regarding SSL

src/site/xdoc/server/install.xml, src/site/xdoc/server/quick-start.xml
Last I checked
James logs in log/wrapper.log file
Thanks,
=> [SITE] log file reference

src/site/xdoc/download.xml
Should be the one of the targetted file.
Changes already deployed on the website.
=> [DOWNLOAD] Fix Guice artifact links text

server/container/guice/protocols/jmap/src/main/java/org/apache/james/jmap/draft/JMAPModule.java, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/CustomMethodContract.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/core/Capabilities.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/core/Capability.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/core/JmapRfc8621Configuration.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/JmapApi.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/SessionRoutes.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/SessionSupplier.scala, server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/change/StateChangeEventSerializerTest.scala, server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/core/JmapUrlEndpointResolverTest.scala, server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/routes/JMAPApiRoutesTest.scala, server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/routes/SessionRoutesTest.scala, server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/routes/SessionSupplierTest.scala
- Avoids a uggly if
- Allows extension capability to access resolved prefixes.
=> JAMES-3680 Capability should be aware of request URL prefixes

server/queue/queue-activemq/src/test/java/org/apache/james/queue/activemq/ActiveMQMailQueueTest.java, server/queue/queue-api/src/test/java/org/apache/james/queue/api/ManageableMailQueueContract.java, server/queue/queue-jms/src/main/java/org/apache/james/queue/jms/JMSCacheableMailQueue.java
Try triggers CI for https://github.com/apache/james-project/pull/824
Credits to @mbaechler
=> JAMES-2296 JAMES-3689 fix removal by recipient in more cases

pom.xml, protocols/api/src/main/java/org/apache/james/protocols/api/OIDCSASLParser.java, protocols/api/src/main/java/org/apache/james/protocols/api/OidcSASLConfiguration.java, protocols/api/src/test/java/org/apache/james/protocols/api/OIDCSASLHelper.java, protocols/api/src/test/java/org/apache/james/protocols/api/OIDCSASLParserTest.java, protocols/imap/pom.xml, protocols/imap/src/main/java/org/apache/james/imap/api/process/ImapSession.java, protocols/imap/src/main/java/org/apache/james/imap/encode/FakeImapSession.java, protocols/imap/src/main/java/org/apache/james/imap/processor/AbstractAuthProcessor.java, protocols/imap/src/main/java/org/apache/james/imap/processor/AuthenticateProcessor.java, protocols/imap/src/main/java/org/apache/james/imap/processor/DefaultProcessorChain.java, server/protocols/jwt/pom.xml, server/protocols/jwt/src/main/java/org/apache/james/jwt/DefaultPublicKeyProvider.java, server/protocols/jwt/src/main/java/org/apache/james/jwt/JwksPublicKeyProvider.java, server/protocols/jwt/src/main/java/org/apache/james/jwt/JwtTokenHelper.java, server/protocols/jwt/src/main/java/org/apache/james/jwt/JwtTokenVerifier.java, server/protocols/jwt/src/main/java/org/apache/james/jwt/OidcJwksPublicKeyProvider.java, server/protocols/jwt/src/main/java/org/apache/james/jwt/OidcJwtTokenVerifier.java, server/protocols/jwt/src/test/java/org/apache/james/jwt/DefaultPublicKeyProviderTest.java, server/protocols/jwt/src/test/java/org/apache/james/jwt/JwksPublicKeyProviderTest.java, server/protocols/jwt/src/test/java/org/apache/james/jwt/JwtTokenVerifierTest.java, server/protocols/jwt/src/test/java/org/apache/james/jwt/OidcJwksPublicKeyProviderTest.java, server/protocols/jwt/src/test/java/org/apache/james/jwt/OidcJwtTokenVerifierTest.java, server/protocols/jwt/src/test/java/org/apache/james/jwt/OidcTokenFixture.java, server/protocols/protocols-imap4/pom.xml, server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/IMAPServer.java, server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/ImapChannelUpstreamHandler.java, server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/NettyImapSession.java, server/protocols/protocols-imap4/src/test/java/org/apache/james/imapserver/netty/IMAPServerTest.java, server/protocols/protocols-imap4/src/test/resources/oauth.xml
Ref: https://issues.apache.org/jira/browse/JAMES-3680
https://github.com/linagora/james-project/issues/4436
This PR in progress
=> JAMES-3680 OAuth support for IMAP authentication

server/apps/distributed-pop3-app/src/test/java/org/apache/james/Pop3ServerContract.java
=> [boyscout] removes potential flakyness from Pop3ServerContract#deletingAMessageDeletesOnlyOne

server/queue/queue-api/src/test/java/org/apache/james/queue/api/DelayedManageableMailQueueContract.java, server/queue/queue-pulsar/src/main/scala/org/apache/james/queue/pulsar/PulsarMailQueue.scala
- Add an explicit test
- Fix the pulsar implementation
=> JAMES-3687 Clear should remove delayed emails

backends-common/rabbitmq/src/main/java/org/apache/james/backends/rabbitmq/QueueArguments.java, backends-common/rabbitmq/src/main/java/org/apache/james/backends/rabbitmq/RabbitMQConfiguration.java, backends-common/rabbitmq/src/test/java/org/apache/james/backends/rabbitmq/RabbitMQConfigurationTest.java, event-bus/distributed/src/test/java/org/apache/james/events/RabbitMQEventBusTest.java, server/apps/distributed-app/docs/modules/ROOT/pages/configure/rabbitmq.adoc, server/apps/distributed-app/sample-configuration/rabbitmq.properties, src/site/xdoc/server/config-rabbitmq.xml
Jira: https://issues.apache.org/jira/browse/JAMES-3694
=> JAMES-3694 Add a TTL on RabbitMQ queues

server/apps/distributed-app/docs/modules/ROOT/nav.adoc, server/apps/distributed-app/docs/modules/ROOT/pages/operate/security.adoc
This document will present the most threats running James exposes you to, and then will list actions one can take to address those threats. We will rate those from MUST (if not addressed basic security features will not be achieved), SHOULD (easy to set up, not strictly required but still very beneficial) and COULD (for the most stringent environments, but expect advanced configuration to be mobilized...)
This document should enable one to see what to expect for James security-wise.
=> JAMES-3692 Write a security checklist

server/mailet/rate-limiter/pom.xml, server/mailet/rate-limiter/src/main/scala/org/apache/james/rate/limiter/api/RateLimiter.scala, server/mailet/rate-limiter/src/main/scala/org/apache/james/rate/limiter/memory/MemoryRateLimiter.scala, server/mailet/rate-limiter/src/test/scala/org/apache/james/rate/limiter/api/RateLimiterContract.scala, server/mailet/rate-limiter/src/test/scala/org/apache/james/rate/limiter/memory/MemoryRateLimiterTest.scala, server/pom.xml
Implement memory version for it using the RateLimitJ library. Provide
a contract test running against this implementation.
=> JAMES-3693 Provide an API for rate limiting

pom.xml, server/mailet/rate-limiter-redis/pom.xml, server/mailet/rate-limiter-redis/src/main/scala/org/apache/james/rate/limiter/redis/RedisRateLimiter.scala, server/mailet/rate-limiter-redis/src/main/scala/org/apache/james/rate/limiter/redis/RedisRateLimiterConfiguration.scala, server/mailet/rate-limiter-redis/src/test/java/org/apache/james/rate/limiter/DockerRedis.java, server/mailet/rate-limiter-redis/src/test/java/org/apache/james/rate/limiter/RedisExtension.java, server/mailet/rate-limiter-redis/src/test/java/org/apache/james/rate/limiter/RedisRateLimiterTest.scala
Jira: https://issues.apache.org/jira/browse/JAMES-3693
=> JAMES-3693 Redis implementation RateLimiter (with configuration)

examples/oidc/jwt-revoker/main.go
The rpc client from Krakend don't seem to really handle reconnections. It makes more sense as well to open a connection and close it when we finish using it.
=> Jwt-revoker container update for oidc example

CHANGELOG.md, src/homepage/_posts/2021-12-02-james-3.6.1.markdown, src/site/xdoc/server/release-notes.xml
If prefered, I can cut this in 2 PRs...
=> [Documentation] Tackle outdated "release note" server page

event-sourcing/event-sourcing-core/pom.xml, event-sourcing/event-sourcing-pojo/pom.xml, mailbox/event/json/pom.xml, mdn/pom.xml, pom.xml, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/pom.xml, server/protocols/jmap-rfc-8621/pom.xml, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/DownloadRoutes.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/JmapApi.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/SessionSupplier.scala
Ref: 
https://github.com/evis/scalafix-maven-plugin
https://scalacenter.github.io/scalafix/
=> [SCALA_CHECKSTYLE] Upgrade version 0.1.4_0.9.23 -> 0.1.4_0.9.33

server/mailet/integration-testing/src/test/java/org/apache/james/transport/mailets/PerRecipientRateLimitMailetIntegrationTest.java, server/mailet/rate-limiter/src/test/scala/org/apache/james/rate/limiter/api/RateLimiterContract.scala
Jira: https://issues.apache.org/jira/browse/JAMES-3693
Separate from https://github.com/apache/james-project/pull/853 and fixing some comments
=> JAMES-3693 Integration test: Mailet PerRecipientRateLimit

server/mailrepository/mailrepository-cassandra/src/main/java/org/apache/james/mailrepository/cassandra/CassandraMailRepository.java, server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/methods/MessageSender.java, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailSubmissionSetMethod.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/MDNSendMethod.scala, server/protocols/webadmin/webadmin-mailqueue/src/main/java/org/apache/james/webadmin/dto/MailQueueItemDTO.java, server/protocols/webadmin/webadmin-mailrepository/src/main/java/org/apache/james/webadmin/service/MailRepositoryStoreService.java, server/protocols/webadmin/webadmin-mailrepository/src/main/java/org/apache/james/webadmin/service/ReprocessingService.java, server/queue/queue-api/pom.xml, server/queue/queue-api/src/main/java/org/apache/james/queue/api/ManageableMailQueue.java, server/queue/queue-jms/src/main/java/org/apache/james/queue/library/MailQueueManagement.java, server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/EnqueuedItem.java, server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/RabbitMQMailQueue.java, server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/view/cassandra/CassandraMailQueueBrowser.java, server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/view/cassandra/CassandraMailQueueMailDelete.java, server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/view/cassandra/model/EnqueuedItemWithSlicingContext.java
Cherry-Picked the commits for [JAMES-3720](https://issues.apache.org/jira/browse/JAMES-3720) to the 3.7.x branch, since this is an important bug fix which should be a included in an eventual 3.7.1 release.
This is virtually the same as https://github.com/apache/james-project/pull/904 for 3.7.x
=> JAMES-3720  Email reprocessing: temporary file leak (for 3.7.x)

docs/modules/community/pages/release.adoc, server/grafana-reporting/es-datasource/README.md, src/homepage/_posts/2020-07-16-james-3.5.0.markdown, src/homepage/howTo/custom-listeners.html, src/homepage/howTo/deleted-messages-vault.html, src/homepage/howTo/imap-server.html
Fix: Some links have been outdated, not exist.
=> [Document] Update docker-compose, sample configuration links

server/apps/cassandra-app/sample-configuration/jvm.properties, server/apps/distributed-app/docs/modules/ROOT/pages/configure/jvm.adoc, server/apps/distributed-app/sample-configuration/jvm.properties, server/apps/distributed-pop3-app/sample-configuration/jvm.properties, server/apps/jpa-app/sample-configuration/jvm.properties, server/apps/jpa-smtp-app/sample-configuration/jvm.properties, server/apps/memory-app/sample-configuration/jvm.properties, server/blob/mail-store/src/main/java/org/apache/james/blob/mail/MimeMessageStore.java, server/container/core/src/main/java/org/apache/james/server/core/BufferedDeferredFileOutputStream.java, server/container/core/src/main/java/org/apache/james/server/core/MimeMessageInputStreamSource.java, server/container/core/src/main/java/org/apache/james/server/core/MimeMessageSource.java, server/container/core/src/main/java/org/apache/james/server/core/MimeMessageWrapper.java, server/container/core/src/test/java/org/apache/james/server/core/MimeMessageInputStreamSourceTest.java, server/container/core/src/test/java/org/apache/james/server/core/MimeMessageWrapperTest.java, server/container/lifecycle-api/pom.xml, server/container/lifecycle-api/src/main/java/org/apache/james/lifecycle/api/Disposable.java, server/container/lifecycle-api/src/test/java/org/apache/james/lifecycle/api/LeakAwareTest.java, server/data/data-file/src/main/java/org/apache/james/mailrepository/file/MimeMessageStreamRepositorySource.java, server/data/data-jdbc/src/main/java/org/apache/james/mailrepository/jdbc/MimeMessageJDBCSource.java, server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/methods/MessageSender.java, server/protocols/protocols-smtp/src/main/java/org/apache/james/smtpserver/JamesDataCmdHandler.java, server/queue/queue-activemq/src/main/java/org/apache/james/queue/activemq/MimeMessageBlobMessageSource.java, server/queue/queue-jms/src/main/java/org/apache/james/queue/jms/MimeMessageObjectMessageSource.java, src/site/xdoc/server/config-system.xml
Jira: https://issues.apache.org/jira/browse/JAMES-3724
=> JAMES-3724 - Implement LeakAware

server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EmailSetMethodContract.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/core/SetError.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailSetCreatePerformer.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/Method.scala
resolve https://github.com/linagora/james-project/issues/4492
=> JMAP Email/set create should use tooLarge when attempt to create an oversize mail

server/protocols/protocols-imap4/pom.xml, server/protocols/protocols-imap4/src/test/java/org/apache/james/imapserver/netty/IMAPServerTest.java, server/protocols/protocols-imap4/src/test/resources/imapServerSSL.xml
This reliable reproduces the issue in the Netty4 pull request.
=> JAMES-3715 Add IMAP IDLE tests when combined with SSL, COMPRESS

server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/LocalDelivery.java, server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/delivery/MailDispatcher.java, server/mailet/mailets/src/test/java/org/apache/james/transport/mailets/delivery/MailDispatcherTest.java
jira: https://issues.apache.org/jira/browse/JAMES-3729
=> JAMES-3729 LocalDelivery error handling is non-standard

backends-common/cassandra/src/main/java/org/apache/james/backends/cassandra/init/configuration/CassandraConfiguration.java, server/apps/cassandra-app/sample-configuration/cassandra.properties, server/apps/distributed-app/docs/modules/ROOT/pages/configure/cassandra.adoc, server/apps/distributed-app/sample-configuration/cassandra.properties, server/apps/distributed-pop3-app/sample-configuration/cassandra.properties, server/mailrepository/mailrepository-cassandra/src/main/java/org/apache/james/mailrepository/cassandra/CassandraMailRepositoryKeysDAO.java, server/mailrepository/mailrepository-cassandra/src/test/java/org/apache/james/mailrepository/cassandra/CassandraMailRepositoryKeysDAOTest.java, server/mailrepository/mailrepository-cassandra/src/test/java/org/apache/james/mailrepository/cassandra/CassandraMailRepositoryTest.java, server/mailrepository/mailrepository-cassandra/src/test/java/org/apache/james/mailrepository/cassandra/CassandraMailRepositoryWithFakeImplementationsTest.java, src/site/xdoc/server/config-cassandra.xml
Jira https://issues.apache.org/jira/browse/JAMES-3726
=> JAMES-3726 Allow relaxing CassandraMailRepository LWT usage

backends-common/elasticsearch-v7/src/main/java/org/apache/james/backends/es/v7/IndexCreationFactory.java, backends-common/elasticsearch-v7/src/test/java/org/apache/james/backends/es/v7/IndexCreationFactoryTest.java
This could enable setting up specific index' own settings upon specific use cases.
=> JAMES-3739: Allow specific index' own settings

mailbox/api/src/main/java/org/apache/james/mailbox/model/Mailbox.java, mailbox/api/src/main/java/org/apache/james/mailbox/model/UpdatedFlags.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/CassandraMailboxSessionMapperFactory.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraIndexTableHandler.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMailboxDAO.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMailboxPathV3DAO.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMailboxManager.java, protocols/imap/src/main/java/org/apache/james/imap/api/message/FetchData.java, protocols/imap/src/main/java/org/apache/james/imap/api/message/IdRange.java, server/container/util/src/main/java/org/apache/james/util/MDCBuilder.java, server/data/data-jmap-cassandra/src/main/java/org/apache/james/jmap/cassandra/change/EmailChangeRepositoryDAO.java, server/data/data-jmap-cassandra/src/main/java/org/apache/james/jmap/cassandra/change/MailboxChangeRepositoryDAO.java, server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/NettyImapSession.java
It will mostly benefit IMAP LIST and will transfer to JMAP as well. 1-2% less CPU consumption and ~5% less memory allocation for the IMAP workload.
=> [PERF] A collection of flame graph detected IMAP related improvments

mailet/base/src/main/java/org/apache/mailet/base/FlowedMessageUtils.java, mailet/base/src/test/java/org/apache/mailet/base/FlowedMessageUtilsTest.java
Jira: https://issues.apache.org/jira/browse/JAMES-3753
=> JAMES-3753 Fix FlowedMessageUtils.deflow()

backends-common/rabbitmq/pom.xml, backends-common/rabbitmq/src/main/java/org/apache/james/backends/rabbitmq/ReactorRabbitMQChannelPool.java, backends-common/rabbitmq/src/test/java/org/apache/james/backends/rabbitmq/ChannelPoolContract.java, backends-common/rabbitmq/src/test/java/org/apache/james/backends/rabbitmq/RabbitMQExtension.java, backends-common/rabbitmq/src/test/java/org/apache/james/backends/rabbitmq/ReactorRabbitMQChannelPoolTest.java, event-bus/distributed/pom.xml, event-bus/distributed/src/test/java/org/apache/james/events/NetworkErrorTest.java, event-bus/distributed/src/test/java/org/apache/james/events/RabbitMQEventBusTest.java, pom.xml, server/apps/distributed-app/docs/modules/ROOT/pages/configure/rabbitmq.adoc, server/apps/distributed-app/sample-configuration/rabbitmq.properties, server/apps/distributed-app/src/test/java/org/apache/james/modules/DockerRabbitMQRule.java, server/apps/distributed-pop3-app/sample-configuration/rabbitmq.properties, server/queue/queue-jms/src/test/java/org/apache/james/queue/jms/BrokerExtension.java, src/site/xdoc/server/config-rabbitmq.xml
This reverts commit 8564a2ecf72e0a7ef404fe491799fb8140dea1f6.
=> Revert "JAMES-3747 Reactive implementation for RabbitMQ channelPool"

protocols/imap/src/main/java/org/apache/james/imap/api/ImapConfiguration.java, protocols/imap/src/main/java/org/apache/james/imap/processor/IdleProcessor.java, server/apps/distributed-app/docs/modules/ROOT/pages/configure/imap.adoc, server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/IMAPServer.java, server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/ImapChannelUpstreamHandler.java, server/protocols/protocols-imap4/src/main/resources/imapserver.xml, src/site/xdoc/server/config-imap4.xml
Jira: https://issues.apache.org/jira/browse/JAMES-3752
=> JAMES-3752 Allow disabling ImapChannelUpstreamHandler heartbeat handler

server/protocols/jmap/src/main/java/org/apache/james/jmap/UriMatcher.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/FixedUriMatcherTest.java
This allows matching routes with query param.
=> JAMES-3744 Fixed URI matcher should be more flexible

core/src/main/java/org/apache/james/core/MailAddress.java, core/src/main/java/org/apache/james/util/Host.java, mailet/api/src/main/java/org/apache/mailet/DsnParameters.java, mailet/standard/src/main/java/org/apache/james/transport/mailets/MappingArgument.java, mailet/standard/src/main/java/org/apache/james/transport/matchers/HasMimeTypeParameter.java, mailet/standard/src/main/java/org/apache/james/transport/matchers/RecipientDomainIs.java, mailet/standard/src/main/java/org/apache/james/transport/matchers/SenderDomainIs.java, mailet/standard/src/main/java/org/apache/james/transport/matchers/SenderHostIs.java, mailet/standard/src/main/java/org/apache/james/transport/matchers/utils/MailAddressCollectionReader.java, protocols/imap/src/main/java/org/apache/james/imap/decode/parser/CreateCommandParser.java, protocols/netty/src/main/java/org/apache/james/protocols/netty/AllButStartTlsLineBasedChannelHandler.java, protocols/pop3/src/main/java/org/apache/james/protocols/pop3/core/POP3MessageCommandArguments.java, protocols/smtp/src/main/java/org/apache/james/protocols/smtp/core/RcptCmdHandler.java, server/container/guice/utils/src/main/java/org/apache/james/utils/PackageName.java, server/mailet/mock-smtp-server/src/main/java/org/apache/james/mock/smtp/server/model/Mail.java, server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/methods/SetMessagesCreationProcessor.java, server/protocols/webadmin/webadmin-mailrepository/src/main/java/org/apache/james/webadmin/routes/MailRepositoriesRoutes.java, server/queue/queue-jms/src/main/java/org/apache/james/queue/jms/JMSCacheableMailQueue.java, server/testing/src/main/java/org/apache/james/utils/TestIMAPClient.java
Avoids an intermediate collection and a second streaming.
=> [REFACTORING] Use Splitter::splitToStream

server/data/data-file/src/main/java/org/apache/james/mailrepository/file/FileMailRepository.java, server/data/data-jdbc/src/main/java/org/apache/james/mailrepository/jdbc/JDBCMailRepository.java, server/mailrepository/mailrepository-api/src/main/java/org/apache/james/mailrepository/api/MailRepository.java, server/mailrepository/mailrepository-api/src/test/java/org/apache/james/mailrepository/MailRepositoryContract.java, server/mailrepository/mailrepository-cassandra/src/main/java/org/apache/james/mailrepository/cassandra/CassandraMailRepository.java, server/mailrepository/mailrepository-memory/src/main/java/org/apache/james/mailrepository/memory/MemoryMailRepository.java, server/protocols/webadmin/webadmin-mailrepository/src/main/java/org/apache/james/webadmin/service/ReprocessingService.java
Co-Authored-By: Matthieu Baechler <matthieu@apache.org>
=> JAMES-3762 Reworks MailRepository contract to use MailKeys instead of Mails

server/mailrepository/mailrepository-blob/pom.xml, server/mailrepository/mailrepository-blob/src/main/scala/org/apache/james/mailrepository/blob/BlobMailRepository.scala, server/mailrepository/mailrepository-blob/src/main/scala/org/apache/james/mailrepository/blob/MailMetadata.scala, server/mailrepository/mailrepository-blob/src/test/java/org/apache/james/mailrepository/blob/BlobMailRepositoryTest.java, server/pom.xml
This branch includes commits from https://github.com/apache/james-project/pull/985  and https://github.com/apache/james-project/pull/986 and add the blobstore implementation on top.
=> James 3763 BlobStore backed MailRepository

pom.xml, server/blob/blob-s3/pom.xml, server/mailet/rate-limiter-redis/pom.xml
S3 team had been, partly on our reports [1] working
on numerous performance enhancements [2] [3] that
Apache James IMAP workload would definitely benefit
from.
[1] https://github.com/aws/aws-sdk-java-v2/issues/3162
[2] https://github.com/aws/aws-sdk-java-v2/pull/3175
[3] https://github.com/aws/aws-sdk-java-v2/pull/3178
=> [UPGRADE] S3 2.17.170 -> 2.17.189

mailbox/api/src/main/java/org/apache/james/mailbox/SessionProvider.java, mailbox/api/src/main/java/org/apache/james/mailbox/exception/ForbiddenDelegationException.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/FakeAuthorizator.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/SessionProviderImpl.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMailboxManager.java, mailbox/store/src/test/java/org/apache/james/mailbox/store/StoreMailboxManagerTest.java, protocols/api/src/main/java/org/apache/james/protocols/api/OIDCSASLParser.java, protocols/api/src/test/java/org/apache/james/protocols/api/OIDCSASLParserTest.java, protocols/imap/src/main/java/org/apache/james/imap/processor/AbstractAuthProcessor.java, protocols/imap/src/main/java/org/apache/james/imap/processor/AuthenticateProcessor.java, server/apps/jpa-smtp-app/src/main/java/org/apache/james/JPAJamesServerMain.java, server/container/guice/jpa-common/pom.xml, server/container/guice/jpa-common/src/main/java/org/apache/james/modules/data/JPAAuthorizatorModule.java, server/container/guice/jpa-common/src/main/java/org/apache/james/modules/data/JPANoAuthorizatorModule.java, server/protocols/protocols-imap4/src/test/java/org/apache/james/imapserver/netty/IMAPServerTest.java, server/protocols/protocols-smtp/src/main/java/org/apache/james/smtpserver/UsersRepositoryAuthHook.java, server/protocols/protocols-smtp/src/test/java/org/apache/james/smtpserver/AuthAnnounceTest.java, server/protocols/protocols-smtp/src/test/java/org/apache/james/smtpserver/DSNTest.java, server/protocols/protocols-smtp/src/test/java/org/apache/james/smtpserver/SMTPSaslTest.java, server/protocols/protocols-smtp/src/test/java/org/apache/james/smtpserver/SMTPServerTest.java, server/testing/src/main/java/org/apache/james/utils/TestIMAPClient.java
Jira: https://issues.apache.org/jira/browse/JAMES-3757
=> JAMES-3757 IMAP/SMTP OIDC extensions should support impersonation

server/apps/cassandra-app/sample-configuration/elasticsearch.properties, server/apps/distributed-app/sample-configuration/elasticsearch.properties, server/apps/memory-app/sample-configuration/elasticsearch.properties, src/site/markdown/server/manage-guice-distributed-james.md, src/site/xdoc/server/metrics.xml, src/site/xdoc/server/release-notes.xml
=> [SITE] Apply recent mailing list feedback

server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EmailSetMethodContract.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/EmailSet.scala
This enable GMail to pick rich text rendering....
=> JAMES-3783 multipart/alternative should display text/html last

pom.xml, server/apps/cassandra-app/sample-configuration/jvm.properties, server/apps/distributed-app/sample-configuration/jvm.properties, server/apps/distributed-pop3-app/sample-configuration/jvm.properties, server/apps/jpa-app/sample-configuration/jvm.properties, server/apps/jpa-smtp-app/sample-configuration/jvm.properties, server/apps/memory-app/sample-configuration/jvm.properties, server/container/guice/common/src/main/java/org/apache/james/GuiceJamesServer.java
A JVM property allows disabling this behaviour.
=> JAMES-2146 James should exit when startup sequence fails 

server/apps/cassandra-app/sample-configuration/jvm.properties, server/apps/distributed-app/sample-configuration/jvm.properties, server/apps/distributed-pop3-app/sample-configuration/jvm.properties, server/apps/jpa-app/sample-configuration/jvm.properties, server/apps/jpa-smtp-app/sample-configuration/jvm.properties, server/apps/memory-app/sample-configuration/jvm.properties, server/apps/memory-app/src/test/java/org/apache/james/DefaultMemoryJamesServerTest.java, server/container/core/src/main/java/org/apache/james/server/core/configuration/FileConfigurationProvider.java, server/container/guice/configuration/src/main/java/org/apache/james/utils/PropertiesProvider.java
Adds james.fail.on.missing.configuration=true JVM option.
=> JAMES-3781 As a user I want to enforce explicit configuration

server/apps/cassandra-app/sample-configuration/jvm.properties, server/apps/distributed-app/sample-configuration/jvm.properties, server/apps/distributed-pop3-app/sample-configuration/jvm.properties, server/apps/jpa-app/sample-configuration/jvm.properties, server/apps/jpa-smtp-app/sample-configuration/jvm.properties, server/apps/memory-app/sample-configuration/jvm.properties
Suspicious! GC every hour with JMX activated... I'll shoot down the usual suspect.
=> [IMPROVEMENT] Prevent RMI from doing System.gc every hour

backends-common/cassandra/src/test/java/org/apache/james/backends/cassandra/init/CassandraTableManagerTest.java, backends-common/cassandra/src/test/java/org/apache/james/backends/cassandra/init/CassandraTypeProviderTest.java, protocols/imap/src/main/java/org/apache/james/imap/processor/AbstractMailboxProcessor.java, protocols/imap/src/main/java/org/apache/james/imap/processor/AbstractMessageRangeProcessor.java, protocols/imap/src/main/java/org/apache/james/imap/processor/AbstractSelectionProcessor.java, protocols/imap/src/main/java/org/apache/james/imap/processor/CloseProcessor.java, protocols/imap/src/main/java/org/apache/james/imap/processor/CreateProcessor.java, protocols/imap/src/main/java/org/apache/james/imap/processor/DeleteProcessor.java, protocols/imap/src/main/java/org/apache/james/imap/processor/EnableProcessor.java, protocols/imap/src/main/java/org/apache/james/imap/processor/ExpungeProcessor.java, protocols/imap/src/main/java/org/apache/james/imap/processor/GetACLProcessor.java, protocols/imap/src/main/java/org/apache/james/imap/processor/LSubProcessor.java, protocols/imap/src/main/java/org/apache/james/imap/processor/ListProcessor.java, protocols/imap/src/main/java/org/apache/james/imap/processor/ListRightsProcessor.java, protocols/imap/src/main/java/org/apache/james/imap/processor/MyRightsProcessor.java, protocols/imap/src/main/java/org/apache/james/imap/processor/RenameProcessor.java, protocols/imap/src/main/java/org/apache/james/imap/processor/SearchProcessor.java, protocols/imap/src/main/java/org/apache/james/imap/processor/StatusProcessor.java, protocols/imap/src/main/java/org/apache/james/imap/processor/StoreProcessor.java, protocols/imap/src/main/java/org/apache/james/imap/processor/SubscribeProcessor.java, protocols/imap/src/main/java/org/apache/james/imap/processor/base/AbstractProcessor.java, server/blob/blob-cassandra/src/test/java/org/apache/james/blob/cassandra/CassandraBlobStoreClOneTest.java, server/data/data-cassandra/src/test/java/org/apache/james/domainlist/cassandra/CacheDomainListTest.java, server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/ImapChannelUpstreamHandler.java
blob entry and blobpart entry could increment the metrics.
=> FIX CassandraBlobStoreClOneTest was instable

server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/remote/delivery/MailDelivrerToHost.java
Backport of the additional fix from master.
=> JAMES-3791 Remote delivery pooling supports SMTPS (3.7.x)

server/apps/cassandra-app/docker-compose.yml, server/apps/distributed-app/docker-compose.yml, server/apps/distributed-pop3-app/docker-compose.yml
Fix error when starting docker-compose
```
Error: Unable to access jarfile james-server.jar
```
=> [3.7.x] Update docker-compose sample - Remove entrypoint

server/mailet/integration-testing/src/test/java/org/apache/james/mailets/GatewayRemoteDeliveryIntegrationTest.java
Reliably reproduce the issue and would prevent regressions.
=> JAMES-3791 Integration test for RemoteDelivery concurrency

third-party/rspamd/README.md, third-party/rspamd/pom.xml, third-party/rspamd/src/main/java/org/apache/james/rspamd/client/RSpamDHttpClient.java, third-party/rspamd/src/main/java/org/apache/james/rspamd/module/RSpamDModule.java, third-party/rspamd/src/main/java/org/apache/james/rspamd/route/FeedMessageRoute.java, third-party/rspamd/src/main/java/org/apache/james/rspamd/task/FeedSpamToRSpamDTask.java, third-party/rspamd/src/main/java/org/apache/james/rspamd/task/FeedSpamToRSpamDTaskAdditionalInformationDTO.java, third-party/rspamd/src/main/java/org/apache/james/rspamd/task/GetMailboxMessagesService.java, third-party/rspamd/src/test/java/org/apache/james/rspamd/route/FeedMessageRouteTest.java, third-party/rspamd/src/test/java/org/apache/james/rspamd/task/FeedSpamToRSpamDTaskAdditionalInformationDTOTest.java, third-party/rspamd/src/test/java/org/apache/james/rspamd/task/FeedSpamToRSpamDTaskTest.java, third-party/rspamd/src/test/resources/json/feedSpamEmptyPeriod.additionalInformation.json, third-party/rspamd/src/test/resources/json/feedSpamNonEmptyPeriod.additionalInformation.json
TODO task unit tests, webadmin route , webadmin unit tests, and a bit of documentation the route.
=> JAMES-3775 Write a webadmin route to feed spam to RSpamD

third-party/rspamd/pom.xml, third-party/rspamd/src/main/java/org/apache/james/rspamd/RSpamDListener.java, third-party/rspamd/src/test/java/org/apache/james/rspamd/RSpamDListenerTest.java
jira https://issues.apache.org/jira/browse/JAMES-3775
=> JAMES-33775 RSpamDListener

server/mailrepository/mailrepository-api/src/main/java/org/apache/james/mailrepository/api/EmptyErrorMailRepositoryHealthCheck.java
=> JAMES-3784 EmptyErrorMailRepositoryHealthCheck: Wrap blocking calls

pom.xml, server/container/core/pom.xml, server/container/spring/pom.xml, server/protocols/webadmin/webadmin-core/pom.xml
Fixes Jetty dependency management mess
=> [UPGRADE] Spark 2.9.3 -> 2.9.4

backends-common/rabbitmq/src/test/java/org/apache/james/backends/rabbitmq/RabbitMQTest.java, server/queue/queue-api/src/test/java/org/apache/james/queue/api/MailQueueContract.java, server/queue/queue-rabbitmq/src/test/java/org/apache/james/queue/rabbitmq/RabbitMQMailQueueTest.java
CF https://github.com/apache/james-project/pull/1075 follow up.
See https://github.com/reactor/reactor-rabbitmq/issues/176
=> Fix testing queue/queue-rabbitmq - RabbitMQMailQueueTest.deQueueMails - RabbitFluxException 

server/blob/blob-s3/src/main/java/org/apache/james/blob/objectstorage/aws/S3BlobStoreDAO.java
Trivial patch to include blobId in exception message, so it will be logged as well.
=> JAMES-3806 S3BlobStoreDAO logs missing blob id if not found

server/apps/distributed-app/docs/modules/ROOT/pages/configure/jmap.adoc, server/apps/distributed-app/docs/modules/ROOT/pages/configure/webadmin.adoc, server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/http/LoggingHelper.java, server/protocols/webadmin/webadmin-core/src/main/java/org/apache/james/webadmin/mdc/LoggingRequestFilter.java, server/protocols/webadmin/webadmin-core/src/main/java/org/apache/james/webadmin/mdc/LoggingResponseFilter.java, src/site/xdoc/server/config-jmap.xml, src/site/xdoc/server/config-webadmin.xml
This allows for preserving the client IP address for audit purposes.
=> JAMES-3788 JMAP/WebAdmin add X-Real-IP to logging MDC

backends-common/cassandra/src/main/java/org/apache/james/backends/cassandra/init/ClusterFactory.java, backends-common/cassandra/src/main/java/org/apache/james/backends/cassandra/init/KeyspaceFactory.java, mpt/impl/imap-mailbox/cassandra/src/test/java/org/apache/james/mpt/imapmailbox/cassandra/host/CassandraHostSystem.java, mpt/impl/imap-mailbox/cassandra/src/test/java/org/apache/james/mpt/imapmailbox/cassandra/host/CassandraHostSystemExtension.java, mpt/impl/managesieve/cassandra/src/test/java/org/apache/james/mpt/managesieve/cassandra/CassandraManageSieveMPTTest.java, mpt/impl/managesieve/cassandra/src/test/java/org/apache/james/mpt/managesieve/cassandra/host/CassandraHostSystem.java
Gains ~15 minutes of build time, will avoid timeouts.
=> JAMES-3774 Fasten Cassandra MPT tests

server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/Requeue.java, server/protocols/webadmin/webadmin-mail-over-web/src/main/java/org/apache/james/webadmin/routes/TransferEmailRoutes.java, server/protocols/webadmin/webadmin-mailqueue/src/main/java/org/apache/james/webadmin/routes/MailQueueRoutes.java, server/protocols/webadmin/webadmin-rabbitmq/src/main/java/org/apache/james/webadmin/routes/RabbitMQMailQueuesRoutes.java, server/queue/queue-api/src/test/java/org/apache/james/queue/api/MailQueueContract.java, server/queue/queue-memory/pom.xml, server/queue/queue-memory/src/main/java/org/apache/james/queue/memory/MemoryMailQueueFactory.java, server/queue/queue-memory/src/test/java/org/apache/james/queue/memory/MemoryCacheableMailQueueTest.java
Fixes https://ci-builds.apache.org/job/james/job/ApacheJames/job/PR-1098/6/testReport/junit/org.apache.james.queue.memory/MemoryCacheableMailQueueTest/dequeueShouldAllowRetrieveFailItemsNackOutOfOrder/
=> [BUILD] Improve MemoryMailQueue build stability

Jenkinsfile
This provides otherwise missing build isolation
=> [BUILD] Enforce the use of a local m2 repo

protocols/imap/src/main/java/org/apache/james/imap/api/process/SelectedMailbox.java, protocols/imap/src/main/java/org/apache/james/imap/processor/AbstractSelectionProcessor.java, protocols/imap/src/main/java/org/apache/james/imap/processor/IdleProcessor.java, protocols/imap/src/main/java/org/apache/james/imap/processor/base/SelectedMailboxImpl.java, protocols/imap/src/test/java/org/apache/james/imap/processor/base/MailboxEventAnalyserTest.java, protocols/imap/src/test/java/org/apache/james/imap/processor/base/SelectedMailboxImplTest.java
Avoid that nested call to .block
=> JAMES-3773 Prevent deadlock under load in AbstractSelectionProcessor

backends-common/opensearch/src/main/java/org/apache/james/backends/opensearch/OpenSearchHealthCheck.java, server/container/guice/queue/rabbitmq/src/main/java/org/apache/james/modules/queue/rabbitmq/CassandraMailQueueViewModule.java, server/data/data-jpa/src/main/java/org/apache/james/jpa/healthcheck/JPAHealthCheck.java, server/mailrepository/mailrepository-api/src/main/java/org/apache/james/mailrepository/api/EmptyErrorMailRepositoryHealthCheck.java, server/queue/queue-activemq/src/main/java/org/apache/james/queue/activemq/ActiveMQHealthCheck.java, server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/Dequeuer.java, server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/view/cassandra/BrowseStartDAO.java, server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/view/cassandra/BrowseStartHealthCheck.java, server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/view/cassandra/CassandraMailQueueBrowser.java, server/queue/queue-rabbitmq/src/test/java/org/apache/james/queue/rabbitmq/view/cassandra/BrowseStartDAOTest.java, server/queue/queue-rabbitmq/src/test/java/org/apache/james/queue/rabbitmq/view/cassandra/BrowseStartHealthCheckTest.java
Discussed on gitter, will create a nice JIRA with the discussion tomorrow.
=> JAMES-3810 Various fixes related to the RabbitMQ mail queue

backends-common/cassandra/src/main/java/org/apache/james/backends/cassandra/components/CassandraModule.java, backends-common/cassandra/src/main/java/org/apache/james/backends/cassandra/components/CassandraTable.java, backends-common/cassandra/src/main/java/org/apache/james/backends/cassandra/components/CassandraType.java, backends-common/cassandra/src/main/java/org/apache/james/backends/cassandra/init/CassandraTableManager.java, backends-common/cassandra/src/main/java/org/apache/james/backends/cassandra/init/CassandraTypesCreator.java, backends-common/cassandra/src/test/java/org/apache/james/backends/cassandra/components/CassandraTableTest.java, backends-common/cassandra/src/test/java/org/apache/james/backends/cassandra/components/CassandraTypeTest.java
Localy table creation went from 42s to 6s.
=> [BUILD] Provision Cassandra tables in parallel

server/testing/src/main/java/org/apache/james/utils/FakeSmtp.java
With this, I run mailet integration tests in 2 min locally
=> [BUILD] Reuse FakeSMTP container port 25

third-party/rspamd/src/main/java/org/apache/james/rspamd/client/RspamdHttpClient.java, third-party/rspamd/src/main/java/org/apache/james/rspamd/task/FeedHamToRspamdTask.java, third-party/rspamd/src/main/java/org/apache/james/rspamd/task/FeedSpamToRspamdTask.java, third-party/rspamd/src/main/java/org/apache/james/rspamd/task/GetMailboxMessagesService.java, third-party/rspamd/src/test/java/org/apache/james/rspamd/client/RspamdHttpClientTest.java, third-party/rspamd/src/test/java/org/apache/james/rspamd/task/FeedHamToRspamdTaskTest.java, third-party/rspamd/src/test/java/org/apache/james/rspamd/task/FeedSpamToRspamdTaskTest.java
=> JAMES-3775 Refactor GetMailboxMessagesService + Clean code + Fix webadmin task

src/adr/0051-oidc.md, src/adr/0053-email-rate-limiting.md, src/adr/0057-reactive-imap.md, src/adr/0058-upgrade-to-netty-4.md, src/adr/0059-upgrade-to-cassadra-driver-4.md, src/adr/0060-adopt-bounded-elastic.md, src/adr/0061-delegation.md, src/adr/0062-oidc-token-introspection.md, src/adr/0063-temporary-file-leaks.md
I did got some time in the plane...
=> [BOYSCOUT] Write some missing ADRs regarding recent work

mailet/api/src/main/java/org/apache/mailet/DsnParameters.java, mailet/api/src/main/java/org/apache/mailet/Mail.java, mailet/api/src/test/java/org/apache/mailet/DsnParametersTest.java, mailet/base/src/main/java/org/apache/mailet/base/FlowedMessageUtils.java, mailet/base/src/test/java/org/apache/mailet/base/FlowedMessageUtilsTest.java, server/container/core/src/test/java/org/apache/james/server/core/MailImplTest.java, server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/remote/delivery/DeliveryRunnable.java, server/mailet/mailets/src/test/java/org/apache/james/transport/matchers/DSNDelayRequestedTest.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/UriPathTemplate.java
https://github.com/linagora/james-project/commit/c57bf62155843f2577d2c62a205d5e064b2ea5d8 JAMES-3803 RemoteDelivery uses different scheduler for dequeuing (#1121)
https://github.com/linagora/james-project/commit/6003ecb236b4a2cab38ba73056e9babbaac15fc7 JAMES-343 Mail: Fix resetting DSN parameters
https://github.com/linagora/james-project/commit/5ad5cb6a4e07432502350f4ee1dee9a50fae9d01 JAMES-3431 Stricter validation for DSN ENVID (#1002)
JAMES-3753 Fix FlowedMessageUtils.deflow()
https://github.com/linagora/james-project/commit/06260220051a42522ff501e75f689d59f640744d JAMES-3744 remove redundant hashmaps which lead to OOM
=> Some value backports for 3.7.x

backends-common/rabbitmq/src/main/java/org/apache/james/backends/rabbitmq/RabbitMQManagementAPI.java, backends-common/rabbitmq/src/test/java/org/apache/james/backends/rabbitmq/RabbitMQTest.java, event-bus/distributed/src/main/java/org/apache/james/events/NamingStrategy.java, event-bus/distributed/src/main/java/org/apache/james/events/RabbitMQEventBusDeadLetterQueueHealthCheck.java, event-bus/distributed/src/test/java/org/apache/james/events/RabbitMQEventBusDeadLetterQueueHealthCheckTest.java, server/container/guice/distributed/src/main/java/org/apache/james/modules/event/JMAPEventBusModule.java, server/container/guice/distributed/src/main/java/org/apache/james/modules/event/RabbitMQEventBusModule.java, server/container/guice/queue/rabbitmq/src/main/java/org/apache/james/modules/queue/rabbitmq/RabbitMQModule.java, server/protocols/webadmin-integration-test/distributed-webadmin-integration-test/src/test/java/org/apache/james/webadmin/integration/rabbitmq/RabbitMQWebAdminServerIntegrationImmutableTest.java, server/protocols/webadmin-integration-test/memory-webadmin-integration-test/src/test/java/org/apache/james/webadmin/integration/memory/MemoryWebAdminServerIntegrationImmutableTest.java, server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/RabbitMQMailQueueDeadLetterQueueHealthCheck.java, server/queue/queue-rabbitmq/src/test/java/org/apache/james/queue/rabbitmq/RabbitMQMailQueueDeadLetterQueueHealthCheckTest.java
Healthcheck for:
- MailQueue: dead letter queue
- EventBus: MailboxEvent + JmapEvent dead letter queues
=> JAMES-3817 Health Check for RabbitMQ dead letter queues

event-sourcing/event-store-api/src/main/scala/org/apache/james/eventsourcing/eventstore/EventStore.scala, event-sourcing/event-store-api/src/test/scala/org/apache/james/eventsourcing/eventstore/EventStoreContract.scala, event-sourcing/event-store-cassandra/src/main/scala/org/apache/james/eventsourcing/eventstore/cassandra/CassandraEventStore.scala, event-sourcing/event-store-cassandra/src/main/scala/org/apache/james/eventsourcing/eventstore/cassandra/EventStoreDao.scala, event-sourcing/event-store-memory/src/main/scala/org/apache/james/eventsourcing/eventstore/memory/InMemoryEventStore.scala, server/apps/distributed-app/src/main/java/org/apache/james/CassandraRabbitMQJamesServerMain.java, server/apps/distributed-pop3-app/src/main/java/org/apache/james/DistributedPOP3JamesServerMain.java, server/container/guice/cassandra/src/main/java/org/apache/james/modules/TasksCleanupTaskSerializationModule.java, server/container/guice/cassandra/src/main/java/org/apache/james/modules/webadmin/TasksCleanupRoutesModule.java, server/protocols/webadmin-integration-test/distributed-webadmin-integration-test/src/test/java/org/apache/james/webadmin/integration/rabbitmq/RabbitMQWebAdminServerTaskSerializationIntegrationImmutableTest.java, server/protocols/webadmin/webadmin-cassandra/pom.xml, server/protocols/webadmin/webadmin-cassandra/src/main/java/org/apache/james/webadmin/routes/TasksCleanupRoutes.java, server/protocols/webadmin/webadmin-cassandra/src/main/java/org/apache/james/webadmin/services/TasksCleanupService.java, server/protocols/webadmin/webadmin-cassandra/src/main/java/org/apache/james/webadmin/tasks/TasksCleanupTask.java, server/protocols/webadmin/webadmin-cassandra/src/main/java/org/apache/james/webadmin/tasks/TasksCleanupTaskAdditionalInformationDTO.java, server/protocols/webadmin/webadmin-cassandra/src/main/java/org/apache/james/webadmin/tasks/TasksCleanupTaskDTO.java, server/protocols/webadmin/webadmin-cassandra/src/test/java/org/apache/james/webadmin/routes/TasksCleanupRoutesTest.java, server/task/task-api/src/main/java/org/apache/james/task/TaskManager.java, server/task/task-distributed/src/main/scala/org/apache/james/task/eventsourcing/cassandra/CassandraTaskExecutionDetailsProjection.scala, server/task/task-distributed/src/main/scala/org/apache/james/task/eventsourcing/cassandra/CassandraTaskExecutionDetailsProjectionDAO.scala, server/task/task-distributed/src/test/java/org/apache/james/task/eventsourcing/cassandra/CassandraTaskExecutionDetailsProjectionDAOTest.java, server/task/task-memory/src/main/java/org/apache/james/task/MemoryTaskManager.java, server/task/task-memory/src/main/scala/org/apache/james/task/eventsourcing/EventSourcingTaskManager.scala, server/task/task-memory/src/main/scala/org/apache/james/task/eventsourcing/TaskExecutionDetailsProjection.scala
Why: Prevents unwanted infinite data growth
jira: https://issues.apache.org/jira/browse/JAMES-3825
resolve: https://github.com/linagora/james-project/issues/4620
=> JAMES-3825 Task to clean up tasks 

third-party/rspamd/src/main/java/org/apache/james/rspamd/task/GetMailboxMessagesService.java
Attempts to load too much messages at once...
=> JAMES-3775 Decrease slightly Rspamd task concurrency

backends-common/opensearch/pom.xml, pom.xml, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/pom.xml, server/protocols/jmap-rfc-8621/pom.xml, server/protocols/jwt/pom.xml, server/queue/queue-activemq/pom.xml
=> [Upgrade] Maven dependencies for fix CVE vulnerabilities

backends-common/cassandra/pom.xml, mailbox/event/json/pom.xml, mailet/api/pom.xml, pom.xml, server/mailet/mailets/pom.xml, server/queue/queue-pulsar/pom.xml
=> [NO_REVIEW] Draft - for optimize import maven dependencies

server/blob/blob-common/src/main/java/org/apache/james/blob/api/Store.java
Critical to correctly propagate errors.
Replacing by `map` would cause the error not to be catch downstream. No idea why, failed to reproduce with a test.
Impact: unacknowledged messages for RabbitMQ mailQueue that eventually piles up to interruption of service.
=> [FIX] FIx error management for Store

server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/ImapChannelUpstreamHandler.java, server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/ReactiveThrottler.java, server/protocols/protocols-imap4/src/test/java/org/apache/james/imapserver/netty/ReactiveThrottlerTest.java
Previously on rejected IMAP computation the connexion was closed which may be a bit too harsh
=> JAMES-3816 Manage IMAP throttling errors

server/apps/distributed-app/docs/modules/ROOT/pages/configure/ssl.adoc, server/protocols/protocols-library/src/main/java/org/apache/james/protocols/lib/LegacyJavaEncryptionFactory.java, server/protocols/protocols-library/src/main/java/org/apache/james/protocols/lib/SslConfig.java, src/site/xdoc/server/config-ssl-tls.xml
```
<tls socketTLS="false" startTLS="true">
<keystore>file://conf/keystore</keystore>
<keystoreType>JKS</keystoreType>
<secret>yoursecret</secret>
<clientAuth>
<truststore>file://conf/truststore</truststore>
<truststoreType>JKS</truststoreType>
<truststoreSecret>yoursecret</truststoreSecret>
<enableOCSPCRLChecks>true</enableOCSPCRLChecks>
</clientAuth>
</tls>
```
=> JAMES-3833 SSL client auth: verify Certificates Revocation Lists

mailbox/api/src/main/java/org/apache/james/mailbox/probe/QuotaProbe.java, server/container/guice/mailbox/src/main/java/org/apache/james/modules/QuotaProbesImpl.java, server/container/guice/protocols/jmap/src/main/java/org/apache/james/jmap/rfc8621/RFC8621MethodsModule.java, server/protocols/jmap-rfc-8621-integration-tests/distributed-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/distributed/DistributedQuotaGetMethodTest.java, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/QuotaGetMethodContract.scala, server/protocols/jmap-rfc-8621-integration-tests/memory-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/memory/MemoryQuotaGetMethodTest.java, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/json/QuotaSerializer.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/Quotas.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/QuotaGetMethod.scala, server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/json/QuotaSerializerTest.scala
jira: https://issues.apache.org/jira/browse/JAMES-3830
resolve: https://github.com/linagora/james-project/issues/4624
=> JAMES-3830 Implement JMAP Quota/get

server/mailet/mailetcontainer-impl/src/main/java/org/apache/james/mailetcontainer/impl/JamesMailSpooler.java, server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/remote/delivery/DeliveryRunnable.java, server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/send/PostDequeueDecorator.java, server/protocols/jmap-draft/src/test/java/org/apache/james/jmap/draft/send/PostDequeueDecoratorTest.java, server/queue/queue-activemq/src/main/java/org/apache/james/queue/activemq/ActiveMQMailQueueItem.java, server/queue/queue-api/src/main/java/org/apache/james/queue/api/MailQueue.java, server/queue/queue-api/src/main/java/org/apache/james/queue/api/RawMailQueueItem.java, server/queue/queue-api/src/test/java/org/apache/james/queue/api/DelayedPriorityMailQueueContract.java, server/queue/queue-api/src/test/java/org/apache/james/queue/api/MailQueueContract.java, server/queue/queue-api/src/test/java/org/apache/james/queue/api/MailQueueMetricContract.java, server/queue/queue-api/src/test/java/org/apache/james/queue/api/ManageableMailQueueContract.java, server/queue/queue-api/src/test/java/org/apache/james/queue/api/PriorityMailQueueContract.java, server/queue/queue-jms/src/main/java/org/apache/james/queue/jms/JMSMailQueueItem.java, server/queue/queue-memory/src/main/java/org/apache/james/queue/memory/MemoryMailQueueFactory.java, server/queue/queue-pulsar/src/main/scala/org/apache/james/queue/pulsar/PulsarMailQueue.scala, server/queue/queue-pulsar/src/test/java/org/apache/james/queue/pulsar/PulsarMailQueueTest.java, server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/Dequeuer.java, server/queue/queue-rabbitmq/src/test/java/org/apache/james/queue/rabbitmq/RabbitMQMailQueueTest.java, server/task/task-memory/src/main/java/org/apache/james/task/SerialTaskManagerWorker.java
Implement rejection with RabbitMQ mail queue to prevent an infinite loop upon unserializable mail attributes.
=> JAMES-3828 Allow JamesMailSpooler to reject mails

CHANGELOG.md, server/protocols/jmap-rfc-8621/doc/specs/rfc/src/quotas.mdown, server/protocols/jmap-rfc-8621/doc/specs/spec/custom-quotas/quotas.mdown, server/protocols/jmap-rfc-8621/doc/specs/spec/quotas/ianaconsiderations.mdown, server/protocols/jmap-rfc-8621/doc/specs/spec/quotas/intro.mdown, server/protocols/jmap-rfc-8621/doc/specs/spec/quotas/quota.mdown, server/protocols/jmap-rfc-8621/doc/specs/spec/quotas/securityconsiderations.mdown
Should probably wait for the work on quotas to be done before merging it...
=> Quotas documentation

backends-common/pulsar/src/test/java/org/apache/james/backends/pulsar/DockerPulsarExtension.java
adds explicit image construction to avoid deprecation relies on improved default wait strategy to stop waiting for arbitrary log message
=> [JAMES-3805] further improves docker pulsar extension

mailbox/api/src/main/java/org/apache/james/mailbox/quota/UserQuotaRootResolver.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/quota/DefaultUserQuotaRootResolver.java, mailbox/store/src/test/java/org/apache/james/mailbox/store/quota/DefaultUserQuotaRootResolverTest.java, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/QuotaGetMethodContract.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/Quotas.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/QuotaGetMethod.scala
jira https://issues.apache.org/jira/browse/JAMES-3830
resolve: https://github.com/linagora/james-project/issues/4631
=> JAMES-3830 UserQuotaRootResolver support method list all QuotaRoot of delegated mailboxes

mailbox/api/src/main/java/org/apache/james/mailbox/model/ByteContent.java, mailbox/api/src/main/java/org/apache/james/mailbox/model/Content.java, mailbox/api/src/main/java/org/apache/james/mailbox/model/Header.java, mailbox/api/src/main/java/org/apache/james/mailbox/model/HeaderAndBodyByteContent.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/MessageResultImpl.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/MimeDescriptorImpl.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/model/Message.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/model/impl/SimpleMessage.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/streaming/FullByteContent.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/streaming/InputStreamContent.java, protocols/imap/src/main/java/org/apache/james/imap/processor/fetch/EmptyContent.java, third-party/rspamd/src/main/java/org/apache/james/rspamd/RspamdListener.java, third-party/rspamd/src/main/java/org/apache/james/rspamd/client/RspamdHttpClient.java, third-party/rspamd/src/main/java/org/apache/james/rspamd/task/FeedHamToRspamdTask.java, third-party/rspamd/src/main/java/org/apache/james/rspamd/task/FeedSpamToRspamdTask.java, third-party/rspamd/src/test/java/org/apache/james/rspamd/client/RspamdHttpClientTest.java, third-party/rspamd/src/test/java/org/apache/james/rspamd/task/FeedHamToRspamdTaskTest.java, third-party/rspamd/src/test/java/org/apache/james/rspamd/task/FeedSpamToRspamdTaskTest.java
Start using this at least for Rspamd code (listener, task). Other places if wanted need many refactoring efforts IMO.
=> [REACTOR] Reactive content

server/apps/distributed-app/docs/modules/ROOT/pages/operate/webadmin.adoc, server/protocols/webadmin/webadmin-core/src/main/java/org/apache/james/webadmin/dto/ExecutionDetailsDto.java, server/protocols/webadmin/webadmin-core/src/main/java/org/apache/james/webadmin/routes/TasksRoutes.java, server/protocols/webadmin/webadmin-core/src/test/java/org/apache/james/webadmin/routes/TasksRoutesTest.java, src/site/markdown/server/manage-webadmin.md
- Document `status` query parameter
- Add `type` query parameter
- Sort the results (recent goes first)
- Add limit and offsets
=> JAMES-3292 More powerful task listing

third-party/rspamd/src/main/java/org/apache/james/rspamd/task/FeedHamToRspamdTask.java, third-party/rspamd/src/main/java/org/apache/james/rspamd/task/FeedSpamToRspamdTask.java, third-party/rspamd/src/main/java/org/apache/james/rspamd/task/RunningOptions.java, third-party/rspamd/src/test/java/org/apache/james/rspamd/task/FeedHamToRspamdTaskAdditionalInformationDTOTest.java, third-party/rspamd/src/test/java/org/apache/james/rspamd/task/FeedSpamToRspamdTaskAdditionalInformationDTOTest.java, third-party/rspamd/src/test/resources/json/feedHamEmptyRspamdTimeout.additionalInformation.json, third-party/rspamd/src/test/resources/json/feedHamNonEmptyRspamdTimeout.additionalInformation.json, third-party/rspamd/src/test/resources/json/feedSpamEmptyRspamdTimeout.additionalInformation.json, third-party/rspamd/src/test/resources/json/feedSpamNonEmptyRspamdTimeout.additionalInformation.json
Make this field more robust again possible null cases.
=> JAMES-3775 Handle possible empty `rspamdTimeoutInSeconds` when deserializing task additional information

third-party/rspamd/src/main/java/org/apache/james/rspamd/task/GetMailboxMessagesService.java, third-party/rspamd/src/test/java/org/apache/james/rspamd/route/FeedMessageRouteTest.java, third-party/rspamd/src/test/java/org/apache/james/rspamd/task/FeedHamToRspamdTaskTest.java, third-party/rspamd/src/test/java/org/apache/james/rspamd/task/FeedSpamToRspamdTaskTest.java
We always count all spam/ham messages before.
=> JAMES-3775 Task should only count messages in the period

pom.xml
CF https://issues.apache.org/jira/browse/JAMES-3847
=> [UPGRADE] commons-text 1.9 -> 1.10

server/container/guice/protocols/jmap/src/main/java/org/apache/james/jmap/rfc8621/RFC8621MethodsModule.java, server/protocols/jmap-rfc-8621-integration-tests/distributed-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/distributed/DistributedQuotaChangesMethodTest.java, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/QuotaChangesMethodContract.scala, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/QuotaGetMethodContract.scala, server/protocols/jmap-rfc-8621-integration-tests/memory-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/memory/MemoryQuotaChangesMethodTest.java, server/protocols/jmap-rfc-8621/doc/specs/spec/quotas/quota.mdown, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/json/QuotaSerializer.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/json/ResponseSerializer.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/Quotas.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailChangesMethod.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailGetMethod.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailImportMethod.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailQueryMethod.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailSetMethod.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/IdentityGetMethod.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/IdentitySetMethod.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/MDNParseMethod.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/MDNSendMethod.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/MailboxChangesMethod.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/MailboxGetMethod.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/MailboxQueryMethod.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/MailboxSetMethod.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/PushSubscriptionGetMethod.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/PushSubscriptionSetMethod.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/QuotaChangesMethod.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/QuotaGetMethod.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/ThreadChangesMethod.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/ThreadGetMethod.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/VacationResponseGetMethod.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/VacationResponseSetMethod.scala
jira: https://issues.apache.org/jira/browse/JAMES-3830
resolve https://github.com/linagora/james-project/issues/4627
=> JAMES-3830 Implement JMAP Quota/changes

server/container/guice/protocols/jmap/src/main/java/org/apache/james/jmap/rfc8621/RFC8621MethodsModule.java, server/protocols/jmap-rfc-8621-integration-tests/distributed-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/distributed/DistributedQuotaQueryMethodTest.java, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/QuotaQueryMethodContract.scala, server/protocols/jmap-rfc-8621-integration-tests/memory-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/memory/MemoryQuotaQueryMethodTest.java, server/protocols/jmap-rfc-8621/doc/specs/spec/quotas/quota.mdown, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/core/Query.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/json/QuotaSerializer.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/Quotas.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/QuotaQueryMethod.scala, server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/json/QuotaSerializerTest.scala
jira: https://issues.apache.org/jira/browse/JAMES-3830
resolve https://github.com/linagora/james-project/issues/4626
=> JAMES-3830 Jmap Quota/query

mpt/impl/imap-mailbox/core/src/main/resources/org/apache/james/imap/scripts/Status.test, protocols/imap/src/main/java/org/apache/james/imap/api/ImapConstants.java, protocols/imap/src/main/java/org/apache/james/imap/api/message/StatusDataItems.java, protocols/imap/src/main/java/org/apache/james/imap/decode/parser/StatusCommandParser.java, protocols/imap/src/main/java/org/apache/james/imap/encode/AnnotationResponseEncoder.java, protocols/imap/src/main/java/org/apache/james/imap/encode/MailboxStatusResponseEncoder.java, protocols/imap/src/main/java/org/apache/james/imap/message/response/MailboxStatusResponse.java, protocols/imap/src/main/java/org/apache/james/imap/processor/StatusProcessor.java, protocols/imap/src/test/java/org/apache/james/imap/encode/MailboxStatusResponseEncoderTest.java, server/apps/distributed-app/docs/modules/ROOT/pages/architecture/implemented-standards.adoc, src/site/xdoc/protocols/imap4.xml
CF https://datatracker.ietf.org/doc/html/rfc8438.html
=> JAMES-3854 RFC-8438 IMAP STATUS=SIZE

protocols/imap/src/main/java/org/apache/james/imap/api/ImapConfiguration.java, protocols/imap/src/main/java/org/apache/james/imap/api/ImapConstants.java, protocols/imap/src/main/java/org/apache/james/imap/api/message/StatusDataItems.java, protocols/imap/src/main/java/org/apache/james/imap/decode/parser/StatusCommandParser.java, protocols/imap/src/main/java/org/apache/james/imap/encode/MailboxStatusResponseEncoder.java, protocols/imap/src/main/java/org/apache/james/imap/message/response/MailboxStatusResponse.java, protocols/imap/src/main/java/org/apache/james/imap/processor/AppendProcessor.java, protocols/imap/src/main/java/org/apache/james/imap/processor/StatusProcessor.java, protocols/imap/src/test/java/org/apache/james/imap/encode/MailboxStatusResponseEncoderTest.java, server/apps/distributed-app/docs/modules/ROOT/pages/architecture/implemented-standards.adoc, server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/IMAPServer.java, server/protocols/protocols-imap4/src/test/java/org/apache/james/imapserver/netty/IMAPServerTest.java, src/site/xdoc/protocols/imap4.xml
https://www.rfc-editor.org/rfc/rfc7889.html
Allows advertising the size limit for APPEND command.
-> Add the APPENDLIMIT capability
-> Add the APPENDLIMIT status item
=> JAMES-3857 Implement RFC-7889 IMAP APPENDLIMIT

mailbox/api/src/main/java/org/apache/james/mailbox/Authorizator.java, mailbox/api/src/main/java/org/apache/james/mailbox/SessionProvider.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/SessionProviderImpl.java, protocols/imap/src/main/java/org/apache/james/imap/processor/AbstractAuthProcessor.java, protocols/imap/src/main/java/org/apache/james/imap/processor/AuthenticateProcessor.java, server/data/data-api/src/main/java/org/apache/james/user/api/DelegationStore.java, server/protocols/protocols-smtp/src/main/java/org/apache/james/smtpserver/UsersRepositoryAuthHook.java, server/protocols/webadmin/webadmin-data/src/main/java/org/apache/james/webadmin/routes/UserRoutes.java, server/protocols/webadmin/webadmin-data/src/test/java/org/apache/james/webadmin/routes/UserRoutesTest.java
It is very easy to be confused between the two arguments and I believe staged methods makes this way easier to understand and might prevent errors down the road...
=> JAMES-3756 Improve delegation

mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMessageManager.java, mailet/standard/src/main/java/org/apache/james/transport/mailets/StripAttachment.java, server/apps/jpa-app/pom.xml, server/apps/jpa-app/src/main/java/org/apache/james/JPAJamesServerMain.java, server/apps/jpa-smtp-app/src/main/java/org/apache/james/JPAJamesServerMain.java, server/apps/memory-app/src/test/java/org/apache/james/StartSequenceTest.java, server/container/core/src/main/java/org/apache/james/server/core/BufferedDeferredFileOutputStream.java, server/container/core/src/main/java/org/apache/james/server/core/MimeMessageInputStreamSource.java, server/container/core/src/test/java/org/apache/james/server/core/BufferedDeferredFileOutputStreamTest.java, server/container/guice/common/src/main/java/org/apache/james/modules/StartablesModule.java, server/container/guice/common/src/main/java/org/apache/james/utils/InitializationOperations.java, server/container/guice/common/src/main/java/org/apache/james/utils/Startables.java, server/container/guice/common/src/test/java/org/apache/james/modules/InitializationOperationsTest.java, server/container/guice/configuration/src/main/java/org/apache/james/utils/InitializationOperation.java, server/container/guice/configuration/src/main/java/org/apache/james/utils/InitilizationOperationBuilder.java, server/data/data-file/src/main/java/org/apache/james/sieverepository/file/SieveFileRepository.java, server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/ImapRequestFrameDecoder.java
I will backport this to 3.7.x for my customer...
=> JAMES-3859 Wrong starting sequence

mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/CassandraSubscriptionManagerTest.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreSubscriptionManager.java
Prior storage as mailboxName needs to coexist with the mailboxPath format. Tests for this and fixes.
=> JAMES-3852 Test for legacy data cohabitation

server/blob/blob-storage-strategy/src/main/java/org/apache/james/server/blob/deduplication/BlobGCTask.java, server/blob/blob-storage-strategy/src/main/java/org/apache/james/server/blob/deduplication/BlobGCTaskAdditionalInformationDTO.java, server/blob/blob-storage-strategy/src/main/java/org/apache/james/server/blob/deduplication/BlobGCTaskDTO.java, server/blob/blob-storage-strategy/src/main/java/org/apache/james/server/blob/deduplication/BloomFilterGCAlgorithm.java, server/blob/blob-storage-strategy/src/test/java/org/apache/james/server/blob/deduplication/BlobGCTaskAdditionalInformationDTOTest.java, server/blob/blob-storage-strategy/src/test/java/org/apache/james/server/blob/deduplication/BlobGCTaskSerializationTest.java, server/blob/blob-storage-strategy/src/test/java/org/apache/james/server/blob/deduplication/BloomFilterGCAlgorithmContract.java, server/blob/blob-storage-strategy/src/test/resources/json/blobGC-legacy.additionalInformation.json, server/blob/blob-storage-strategy/src/test/resources/json/blobGC-legacy.task.json, server/protocols/webadmin/webadmin-data/src/main/java/org/apache/james/webadmin/routes/BlobRoutes.java, server/protocols/webadmin/webadmin-data/src/test/java/org/apache/james/webadmin/routes/BlobRoutesTest.java
I encountered timeouts for big deletion batches... Processing smaller batches fixes the issue.
=> JAMES-3150 Configuration for blob deletion window size

examples/custom-listeners/src/test/java/org/apache/james/examples/custom/listeners/SetCustomFlagOnBigMessagesTest.java, mailbox/api/src/main/java/org/apache/james/mailbox/MessageManager.java, mailbox/api/src/main/java/org/apache/james/mailbox/events/MailboxEvents.java, mailbox/api/src/test/java/org/apache/james/mailbox/EventTest.java, mailbox/api/src/test/java/org/apache/james/mailbox/MailboxListenerTest.java, mailbox/event/json/src/main/scala/org/apache/james/event/json/DTOs.scala, mailbox/event/json/src/main/scala/org/apache/james/event/json/MailboxEventSerializer.scala, mailbox/event/json/src/test/java/org/apache/james/event/json/AddedSerializationTest.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMessageIdManager.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMessageManager.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/event/EventFactory.java, mailbox/store/src/test/java/org/apache/james/mailbox/store/MessageIdManagerTestSystem.java, mailbox/store/src/test/java/org/apache/james/mailbox/store/ThreadIdGuessingAlgorithmContract.java, mailbox/store/src/test/java/org/apache/james/mailbox/store/search/AbstractMessageSearchIndexTest.java, protocols/imap/src/test/java/org/apache/james/imap/processor/base/MailboxEventAnalyserTest.java, protocols/imap/src/test/java/org/apache/james/imap/processor/base/SelectedMailboxImplTest.java, server/data/data-jmap/src/main/java/org/apache/james/jmap/api/change/EmailChange.java, server/data/data-jmap/src/main/java/org/apache/james/jmap/api/change/MailboxAndEmailChange.java, server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/delivery/MailboxAppenderImpl.java, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EventSourceContract.scala, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/WebPushContract.scala, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/WebSocketContract.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/change/MailboxChangeListener.scala, third-party/rspamd/src/test/java/org/apache/james/rspamd/RspamdListenerTest.java, third-party/spamassassin/src/test/java/org/apache/james/spamassassin/SpamAssassinListenerTest.java
Only push `EmailDelivery` for receiving emails (local delivery).
=> JAMES-3861 EmailDelivery push is used too much

mpt/impl/imap-mailbox/core/src/main/java/org/apache/james/mpt/imapmailbox/suite/AuthenticatedState.java, mpt/impl/imap-mailbox/core/src/main/java/org/apache/james/mpt/imapmailbox/suite/SelectedInbox.java, mpt/impl/imap-mailbox/core/src/main/resources/org/apache/james/imap/scripts/ListSubscribed.test, protocols/imap/src/main/java/org/apache/james/imap/api/ImapConstants.java, protocols/imap/src/main/java/org/apache/james/imap/decode/parser/ListCommandParser.java, protocols/imap/src/main/java/org/apache/james/imap/encode/ListingEncodingUtils.java, protocols/imap/src/main/java/org/apache/james/imap/message/request/ListRequest.java, protocols/imap/src/main/java/org/apache/james/imap/message/request/XListRequest.java, protocols/imap/src/main/java/org/apache/james/imap/message/response/ListResponse.java, protocols/imap/src/main/java/org/apache/james/imap/processor/DefaultProcessor.java, protocols/imap/src/main/java/org/apache/james/imap/processor/ListProcessor.java, protocols/imap/src/main/java/org/apache/james/imap/processor/XListProcessor.java, protocols/imap/src/test/java/org/apache/james/imap/encode/ListResponseEncoderTest.java, protocols/imap/src/test/java/org/apache/james/imap/encode/ListingEncodingUtilsTest.java
resolve: https://github.com/linagora/james-project/issues/4675
=> JAMES-3754 - IMAP support List command extension RFC-5258

mailbox/api/src/main/java/org/apache/james/mailbox/events/MailboxEvents.java, mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/CassandraMailboxManagerTest.java, mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/CassandraSubscriptionManagerTest.java, mailbox/event/json/src/main/scala/org/apache/james/event/json/MailboxEventSerializer.scala, mailbox/jpa/src/main/resources/META-INF/spring/mailbox-jpa.xml, mailbox/jpa/src/test/java/org/apache/james/mailbox/jpa/JPAMailboxManagerTest.java, mailbox/jpa/src/test/java/org/apache/james/mailbox/jpa/JPASubscriptionManagerTest.java, mailbox/memory/src/main/resources/META-INF/spring/mailbox-memory.xml, mailbox/memory/src/test/java/org/apache/james/mailbox/inmemory/MemoryMailboxManagerTest.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreSubscriptionManager.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/event/EventFactory.java, mpt/impl/imap-mailbox/cassandra/src/test/java/org/apache/james/mpt/imapmailbox/cassandra/host/CassandraHostSystem.java, mpt/impl/imap-mailbox/core/src/main/resources/org/apache/james/imap/scripts/Subscribe.test, mpt/impl/imap-mailbox/inmemory/src/test/java/org/apache/james/mpt/imapmailbox/inmemory/host/InMemoryHostSystem.java, mpt/impl/imap-mailbox/jpa/src/test/java/org/apache/james/mpt/imapmailbox/jpa/host/JPAHostSystem.java, mpt/impl/imap-mailbox/lucenesearch/src/test/java/org/apache/james/mpt/imapmailbox/lucenesearch/host/LuceneSearchHostSystem.java, mpt/impl/imap-mailbox/opensearch/src/test/java/org/apache/james/mpt/imapmailbox/elasticsearch/host/OpenSearchHostSystem.java, mpt/impl/imap-mailbox/rabbitmq/src/test/java/org/apache/james/mpt/imapmailbox/rabbitmq/host/RabbitMQEventBusHostSystem.java, server/data/data-jmap/src/main/java/org/apache/james/jmap/api/change/MailboxChange.java, server/protocols/jmap-draft/src/test/java/org/apache/james/jmap/draft/methods/GetMailboxesMethodTest.java, server/protocols/jmap-draft/src/test/java/org/apache/james/jmap/http/DefaultMailboxesProvisionerTest.java, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/JmapRequests.scala, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/MailboxChangesMethodContract.scala, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/MailboxSetMethodContract.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/change/MailboxChangeListener.scala, server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/change/MailboxChangeListenerTest.scala, server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/http/MailboxesProvisionerTest.scala, server/protocols/protocols-imap4/src/test/java/org/apache/james/imapserver/netty/IMAPServerTest.java, server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/service/SubscribeAllRequestToTaskTest.java
resolve https://github.com/linagora/james-project/issues/4147
=> JAMES-3461 - Fix Mailbox/changes do not take isSubscribe changes into account

protocols/api/src/main/java/org/apache/james/protocols/api/OidcSASLConfiguration.java, protocols/imap/src/main/java/org/apache/james/imap/processor/AuthenticateProcessor.java, server/apps/distributed-app/docs/modules/ROOT/pages/configure/smtp.adoc, server/protocols/jwt/src/main/java/org/apache/james/jwt/CheckTokenClient.java, server/protocols/jwt/src/main/java/org/apache/james/jwt/DefaultCheckTokenClient.java, server/protocols/jwt/src/main/java/org/apache/james/jwt/OidcJwtTokenVerifier.java, server/protocols/jwt/src/main/java/org/apache/james/jwt/introspection/TokenIntrospectionResponse.java, server/protocols/jwt/src/main/java/org/apache/james/jwt/userinfo/UserInfoCheckException.java, server/protocols/jwt/src/main/java/org/apache/james/jwt/userinfo/UserinfoResponse.java, server/protocols/jwt/src/test/java/org/apache/james/jwt/OidcJwtTokenVerifierTest.java, server/protocols/jwt/src/test/java/org/apache/james/jwt/OidcTokenFixture.java, server/protocols/jwt/src/test/java/org/apache/james/jwt/introspection/DefaultCheckTokenClientTest.java, server/protocols/protocols-imap4/src/test/java/org/apache/james/imapserver/netty/IMAPServerTest.java, server/protocols/protocols-smtp/src/main/java/org/apache/james/smtpserver/UsersRepositoryAuthHook.java, server/protocols/protocols-smtp/src/test/java/org/apache/james/smtpserver/SMTPSaslTest.java, src/site/xdoc/server/config-smtp-lmtp.xml
resolve https://github.com/linagora/james-project/issues/4686
=> James 3755 OIDC check token by user info

mailbox/api/src/main/java/org/apache/james/mailbox/model/SearchQuery.java, mailbox/lucene/src/main/java/org/apache/james/mailbox/lucene/search/LuceneMessageSearchIndex.java, mailbox/lucene/src/test/java/org/apache/james/mailbox/lucene/search/LuceneMessageSearchIndexTest.java, mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/MailboxMappingFactory.java, mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/json/IndexableMessage.java, mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/json/JsonMessageConstants.java, mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/query/CriterionConverter.java, mailbox/opensearch/src/test/java/org/apache/james/mailbox/opensearch/json/IndexableMessageTest.java, mailbox/opensearch/src/test/java/org/apache/james/mailbox/opensearch/json/MessageToOpenSearchJsonTest.java, mailbox/opensearch/src/test/resources/eml/inlined-mixed.json, mailbox/scanning-search/src/test/java/org/apache/james/mailbox/store/search/SimpleMessageSearchIndexTest.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/search/MessageSearches.java, mailbox/store/src/test/java/org/apache/james/mailbox/store/search/AbstractMessageSearchIndexTest.java, mailbox/store/src/test/resources/eml/emailWithNonIndexableAttachmentWithoutAttachment.json, mailbox/store/src/test/resources/eml/htmlMail.json, mailbox/store/src/test/resources/eml/invalidCharset.json, mailbox/store/src/test/resources/eml/mail.json, mailbox/store/src/test/resources/eml/nonTextual.json, mailbox/store/src/test/resources/eml/pgpSignedMail.json, mailbox/store/src/test/resources/eml/recursiveMail.json, mailbox/store/src/test/resources/eml/recursiveMailWithoutAttachments.json, mailbox/store/src/test/resources/eml/spamMail.json, upgrade-instructions.md
=> JAMES-3754 Searching support IMAP savedate extension

server/data/data-api/src/main/java/org/apache/james/user/api/DelegationStore.java, server/data/data-api/src/test/java/org/apache/james/user/api/DelegationStoreContract.java, server/data/data-cassandra/src/main/java/org/apache/james/user/cassandra/CassandraDelegationStore.java, server/data/data-cassandra/src/main/java/org/apache/james/user/cassandra/CassandraUsersDAO.java, server/data/data-cassandra/src/main/java/org/apache/james/user/cassandra/CassandraUsersRepositoryModule.java, server/data/data-cassandra/src/main/java/org/apache/james/user/cassandra/tables/CassandraUserTable.java, server/data/data-cassandra/src/test/java/org/apache/james/user/cassandra/CassandraDelegationStoreTest.java, server/data/data-memory/src/main/java/org/apache/james/user/memory/MemoryDelegationStore.java, server/data/data-memory/src/main/java/org/apache/james/user/memory/NaiveDelegationStore.java, upgrade-instructions.md
resolve https://github.com/linagora/james-project/issues/4673
=> JAMES-3756 Delegation store should allow listing accounts delegated to me

server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/QuotaGetMethod.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/VacationResponseGetMethod.scala
- method `handleRequestValidationErrors` is already in the abstract class (JmapAPI & Method)
=> [CLEAN CODE] JMAP QuotaGet, VacationResponseGet - remove dangling method

server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/DownloadContract.scala, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/UploadContract.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/DownloadRoutes.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/UploadRoutes.scala
resolve https://github.com/linagora/james-project/issues/4679
=> JAMES-3756 JMAP endpoint (upload/download) should support being called with accountIds of delegated accounts

examples/README.md, examples/custom-imap/src/main/java/org/apache/james/examples/imap/PingProcessor.java, examples/custom-imap/src/main/resources/imapserver.xml, examples/custom-imap/src/test/java/org/apache/james/examples/imap/ImapCustomPackagesTest.java, protocols/imap/src/main/java/org/apache/james/imap/api/ImapConfiguration.java, server/apps/distributed-app/docs/modules/ROOT/nav.adoc, server/apps/distributed-app/docs/modules/ROOT/pages/configure/imap.adoc, server/apps/distributed-app/docs/modules/ROOT/pages/extending/imap.adoc, server/apps/distributed-app/docs/modules/ROOT/pages/extending/index.adoc, server/container/guice/protocols/imap/src/main/java/org/apache/james/modules/protocols/IMAPServerModule.java, server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/IMAPServer.java, server/protocols/protocols-imap4/src/test/java/org/apache/james/imapserver/netty/IMAPServerConfigurationTest.java, src/site/xdoc/server/config-imap4.xml
One can define custom, per-IMAP server
configuration values.
=> JAMES-3867 Allow IMAP extensions configuration

Jenkinsfile, examples/custom-healthcheck/pom.xml, examples/custom-imap/pom.xml, examples/custom-listeners/pom.xml, examples/custom-mailets/pom.xml, examples/custom-smtp-command/pom.xml, examples/custom-smtp-hooks/pom.xml, examples/custom-webadmin-route/pom.xml, examples/metrics-graphite/pom.xml, third-party/clamav/pom.xml, third-party/elasticsearch/pom.xml, third-party/rspamd/pom.xml, third-party/spamassassin/pom.xml
This reduces size of the extension.
=> [ENHANCEMENT] Use provided scope for James dependencies in extensions

mailbox/api/pom.xml, mailbox/api/src/main/java/org/apache/james/mailbox/model/MailboxAnnotationKey.java, pom.xml, server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/model/Keyword.java, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/Keyword.scala
Remove icu4j dependency and replace required functionality with other dependencies
https://issues.apache.org/jira/projects/JAMES/issues/JAMES-3878
=> JAMES-3878 - Remove icu4j dependency

examples/custom-james-assembly/src/main/java/org/apache/james/examples/CustomJamesServerMain.java
Considering whole custom James server example is heavily based on memory based James I assume it's ok to re-use memory based UserRepository as well.
=> Fix exaception about missing UserRepository implementation.

server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/utils/JsoupHtmlTextExtractor.java, server/protocols/jmap-draft/src/test/java/org/apache/james/jmap/draft/utils/JsoupHtmlTextExtractorTest.java
User specified input could generate stackoverflow
=> [PERF] JsoupHtmlTextExtractor without recursion

server/data/data-jdbc/src/main/java/org/apache/james/mailrepository/jdbc/JDBCMailRepository.java
=> JAMES-3875 for 3.7.4

mailet/icalendar/pom.xml, mailet/icalendar/src/main/java/org/apache/james/transport/mailets/ICalendarParser.java, mailet/icalendar/src/test/java/org/apache/james/transport/mailets/ICalendarParserTest.java
Allows better parsing resilience
CF https://github.com/linagora/james-project/issues/3774
CF https://github.com/ical4j/ical4j/issues/454
CF https://github.com/linagora/james-project/issues/4703
=> [UPGRADE] ical4j 3.2.8 -> 3.2.9

server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EmailGetMethodContract.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/json/EmailGetSerializer.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/Email.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/EmailBodyPart.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/EmailGet.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailGetMethod.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/DownloadRoutes.scala
CF https://github.com/linagora/james-project/issues/3707
=> JAMES-3419 JMAP EmailBodyPart individual headers

core/src/main/java/org/apache/james/util/Host.java
=> [FIX] Misleeading error log in Host class

server/apps/cassandra-app/sample-configuration/jvm.properties, server/apps/cli-integration-tests/src/test/java/org/apache/james/cli/JmxSecurityServerIntegrationTest.java, server/apps/cli/src/main/java/org/apache/james/cli/ServerCmd.java, server/apps/cli/src/main/java/org/apache/james/cli/probe/impl/JmxConnection.java, server/apps/cli/src/test/java/org/apache/james/cli/ServerCmdTest.java, server/apps/distributed-app/docs/modules/ROOT/pages/configure/jmx.adoc, server/apps/distributed-app/sample-configuration/jvm.properties, server/apps/distributed-pop3-app/sample-configuration/jvm.properties, server/apps/jpa-app/pom.xml, server/apps/jpa-app/sample-configuration/jvm.properties, server/apps/jpa-smtp-app/pom.xml, server/apps/jpa-smtp-app/sample-configuration/jvm.properties, server/apps/memory-app/pom.xml, server/apps/memory-app/sample-configuration/jvm.properties, server/apps/spring-app/src/main/java/org/apache/james/app/spring/JamesAppSpringMain.java, server/container/guice/common/src/main/java/org/apache/james/TemporaryJamesServer.java, server/container/guice/jmx/src/main/java/org/apache/james/modules/server/JMXServer.java, server/container/guice/jmx/src/main/java/org/apache/james/modules/server/JmxConfiguration.java, src/site/xdoc/server/config-system.xml
jira https://issues.apache.org/jira/browse/JAMES-3881
=> JAMES-3881 Set a JMX password

server/apps/distributed-app/docs/modules/ROOT/pages/operate/webadmin.adoc, server/container/guice/common/src/main/java/org/apache/james/CoreDataModule.java, server/container/guice/protocols/webadmin-data/src/main/java/org/apache/james/modules/server/DataRoutesModules.java, server/data/data-api/src/main/java/org/apache/james/rrt/ForwardUsernameChangeTaskStep.java, server/data/data-api/src/main/java/org/apache/james/user/api/UsernameChangeTaskStep.java, server/data/data-memory/src/test/java/org/apache/james/rrt/memory/ForwardUsernameChangeTaskStepTest.java, server/protocols/webadmin-integration-test/memory-webadmin-integration-test/src/test/java/org/apache/james/webadmin/integration/memory/MemoryUsernameChangeIntegrationTest.java, server/protocols/webadmin/webadmin-data/pom.xml, server/protocols/webadmin/webadmin-data/src/main/java/org/apache/james/webadmin/routes/UsernameChangeRoutes.java, server/protocols/webadmin/webadmin-data/src/main/java/org/apache/james/webadmin/service/UsernameChangeService.java, server/protocols/webadmin/webadmin-data/src/main/java/org/apache/james/webadmin/service/UsernameChangeTask.java, server/protocols/webadmin/webadmin-data/src/main/java/org/apache/james/webadmin/service/UsernameChangeTaskAdditionalInformationDTO.java, server/protocols/webadmin/webadmin-data/src/main/java/org/apache/james/webadmin/service/UsernameChangeTaskDTO.java, server/protocols/webadmin/webadmin-data/src/test/java/org/apache/james/webadmin/routes/UsernameChangeRoutesTest.java, server/protocols/webadmin/webadmin-data/src/test/java/org/apache/james/webadmin/service/UsernameChangeTaskSerializationTest.java, src/site/markdown/server/manage-webadmin.md
This is a POC on defining a pluggable mecanism to change of username (divorce, wedding)
=> JAMES-3885 Changing username

protocols/pop3/src/main/java/org/apache/james/protocols/pop3/core/DeleCmdHandler.java, protocols/pop3/src/main/java/org/apache/james/protocols/pop3/core/QuitCmdHandler.java
A minor extensibility refactoring of POP3 handlers, seems I overlooked these back when I was doing JAMES-3705.
=> JAMES-3889 Refactoring POP3 delete handlers to be more extensible

server/apps/spring-app/pom.xml, server/apps/spring-app/src/main/java/org/apache/james/app/spring/JamesAppSpringMain.java
As they might allow arbitrary file read/writes
=> JAMES-3881 Unregister LOG4J MBeans [BACKPORT]

pom.xml, server/blob/blob-export-file/pom.xml, server/container/guice/configuration/pom.xml, server/protocols/webadmin/webadmin-mail-over-web/pom.xml, server/protocols/webadmin/webadmin-mailqueue/pom.xml
CF https://github.com/frohoff/ysoserial
This was possible through the commons-logging 1.2 transitive dependency.
=> JAMES-3881 Prevent CommonsBeanutils1 deserialization exploit [BACKPORT]

server/apps/spring-app/pom.xml, server/apps/spring-app/src/main/java/org/apache/james/app/spring/JamesAppSpringMain.java
As they might allow arbitrary file read/writes
=> JAMES-3881 Unregister LOG4J MBeans

server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/ImapChannelUpstreamHandler.java, server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/Linearalizer.java, server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/NettyConstants.java, server/protocols/protocols-imap4/src/test/java/org/apache/james/imapserver/netty/IMAPServerTest.java, server/protocols/protocols-imap4/src/test/java/org/apache/james/imapserver/netty/LinearalizerTest.java
I do not think a locless approach for linearizing IMAP request execution is actually doable...
=> JAMES-3888 Sequential execution for IMAP

server/apps/memory-app/src/test/java/org/apache/james/GuiceLifecycleHeathCheckTest.java, server/mailet/mailetcontainer-impl/src/main/java/org/apache/james/mailetcontainer/impl/JamesMailSpooler.java, server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/RemoteDelivery.java, server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/remote/delivery/DeliveryRunnable.java
-> Trash the mail queue last
-> Add a grace period for finishing pending processings upon shutdown.
=> JAMES-3891 Graceful shutdown for queue consumers

server/data/data-jpa/src/main/java/org/apache/james/rrt/jpa/JPARecipientRewriteTable.java, server/data/data-jpa/src/main/java/org/apache/james/rrt/jpa/model/JPARecipientRewrite.java
Fixes https://issues.apache.org/jira/browse/JAMES-2643
=> JAMES-2643 Optimize listing mapping by destination on top of JPA

mailbox/opensearch/src/test/java/org/apache/james/mailbox/opensearch/events/OpenSearchListeningMessageSearchIndexTest.java, server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/event/PopulateEmailQueryViewListener.java, server/protocols/jmap-draft/src/test/java/org/apache/james/jmap/event/PopulateEmailQueryViewListenerTest.java
We spotted a possible data race issue when populating the query email view, giving potentially false results when fetching emails ids via the email query view with Email/query jmap method
For example, for a user
```json
{
"using": [
"urn:ietf:params:jmap:core",
"urn:ietf:params:jmap:mail"
],
"methodCalls": [
[
"Email/query",
{
"accountId": "59ecb678c68f69e90d50b580d14512b6c2ec520afe5a3c522113b100235df799",
"filter": {
"inMailbox": "bb6b69d0-32cf-11eb-995c-a3ae66e9f96a"
},
"sort": [
{
"isAscending": false,
"property": "receivedAt"
}
],
"limit": 20
},
"c2"
],
[
"Email/get",
{
"accountId": "59ecb678c68f69e90d50b580d14512b6c2ec520afe5a3c522113b100235df799",
"#ids": {
"resultOf": "c2",
"name": "Email/query",
"path": "ids/*"
}
},
"c3"
]
]
}
```
Then the response 
```json
{
"sessionState": …
```
=> JAMES-3440 Fixbug: Data race issue with JMAP email query view

server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/http/DownloadRoutes.java, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/DownloadRoutes.scala
```
java.lang.IllegalArgumentException: a header value contains prohibited character 0x20 at index 0.
at io.netty.handler.codec.http.DefaultHttpHeaders$HeaderValueValidator.validate(DefaultHttpHeaders.java:395)
at io.netty.handler.codec.http.DefaultHttpHeaders$HeaderValueValidator.validate(DefaultHttpHeaders.java:387)
at io.netty.handler.codec.DefaultHeaders.validateValue(DefaultHeaders.java:1016)
at io.netty.handler.codec.DefaultHeaders.set(DefaultHeaders.java:468)
at io.netty.handler.codec.DefaultHeaders.setObject(DefaultHeaders.java:520)
at io.netty.handler.codec.http.DefaultHttpHeaders.set(DefaultHttpHeaders.java:169)
at reactor.netty.http.server.HttpServerOperations.header(HttpServerOperations.java:293)
at org.apache.james.jmap.http.DownloadRoutes.downloadBlob(DownloadRoutes.java:231) …
```
=> [FIX] Prevent sending invalid content type upon downloads

mailbox/api/src/main/java/org/apache/james/mailbox/AttachmentContentLoader.java, mailbox/api/src/main/java/org/apache/james/mailbox/AttachmentManager.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraAttachmentMapper.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreAttachmentManager.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/AttachmentMapper.java, protocols/imap/src/main/java/org/apache/james/imap/processor/ListProcessor.java, server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/methods/BlobManagerImpl.java, server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/model/Blob.java, server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/http/DownloadRoutes.java, server/protocols/jmap-draft/src/test/java/org/apache/james/jmap/draft/methods/BlobManagerImplTest.java, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/DownloadRoutes.scala
- Some blocking calls done upon attachment downloads on the Cassandra driver event loop (BAD)
- Concurrency issues for the list commands
CF:
- https://github.com/linagora/james-project/issues/4742
- https://github.com/linagora/james-project/issues/4743
=> [FIX] Fixes issues discovered on TMail 0.6.5-rc6

server/data/data-memory/src/test/java/org/apache/james/user/memory/DelegationUsernameChangeTaskStepTest.java
I am unsure if we deleted all the data during migration for delegation, thus the unit test.
It is good it is passed.
=> JAMES-3885 Harden delegation migration tests

server/apps/distributed-app/docs/modules/ROOT/pages/configure/cassandra.adoc, server/apps/distributed-app/docs/modules/ROOT/pages/configure/mailrepositorystore.adoc, server/apps/distributed-app/docs/modules/ROOT/pages/operate/webadmin.adoc, server/apps/distributed-app/docs/modules/ROOT/partials/MetricsMailet.adoc
Fix not found  error when build html
```
docs git:(master) antora antora-playbook-local.yml
[15:20:23.604] ERROR (asciidoctor): target of xref not found: ../architecture/consistency-model.html#_about_multi_data_center_setups
file: /home/tungtv/workplace/2_JAMES/1james-project/server/apps/distributed-app/docs/modules/ROOT/pages/configure/cassandra.adoc
source: /home/tungtv/workplace/2_JAMES/1james-project (branch: master <worktree> | start path: server/apps/distributed-app/docs)
[15:20:23.787] ERROR (asciidoctor): target of xref not found: distributed/operate/metrics.adoc
file: /home/tungtv/workplace/2_JAMES/1james-project/server/apps/distributed-app/docs/modules/ROOT/pages/configure/mailets.adoc
source: /home/tungtv/workplace/2_JAMES/1james-project (branch: master <worktree> | start path: …
```
=> JAMES-3894 Antora - update xref, fix not found error

mpt/impl/imap-mailbox/external-james/src/test/resources/org/apache/james/imap/scripts/ValidateDeployment.test
Necessary after adding default mailboxes provisioning via imap
=> [FIX] Fix DeploymentValidation test script

server/apps/distributed-app/docs/modules/ROOT/pages/configure/jmx.adoc, src/site/xdoc/server/config-system.xml
rf: https://docs.oracle.com/javadb/10.10.1.2/adminguide/radminjmxenablesimpleauth.html
=> JAMES-3881 [DOC] readWrite -> readwrite

server/blob/blob-cassandra/src/main/java/org/apache/james/blob/cassandra/CassandraBlobStoreDAO.java, server/blob/blob-s3/src/main/java/org/apache/james/blob/objectstorage/aws/S3BlobStoreDAO.java, server/container/util/src/main/java/org/apache/james/util/DataChunker.java, server/container/util/src/test/java/org/apache/james/util/DataChunkerTest.java
Code is exactly the same thus the helper class can be mutualized
=> [REFACTORING] Merge ReactorUtils::toChunks and DataChunker::chunkStream

event-sourcing/event-store-cassandra/src/main/scala/org/apache/james/eventsourcing/eventstore/cassandra/CassandraEventStore.scala, event-sourcing/event-store-cassandra/src/main/scala/org/apache/james/eventsourcing/eventstore/cassandra/CassandraEventStoreModule.scala, event-sourcing/event-store-cassandra/src/main/scala/org/apache/james/eventsourcing/eventstore/cassandra/CassandraEventStoreTable.scala, event-sourcing/event-store-cassandra/src/main/scala/org/apache/james/eventsourcing/eventstore/cassandra/EventStoreDao.scala, event-sourcing/event-store-cassandra/src/test/scala/org/apache/james/eventsourcing/eventstore/cassandra/CassandraEventStoreExtensionForTestEvents.scala, event-sourcing/event-store-cassandra/src/test/scala/org/apache/james/eventsourcing/eventstore/cassandra/CassandraEventStoreTest.scala, event-sourcing/event-store-cassandra/src/test/scala/org/apache/james/eventsourcing/eventstore/cassandra/dto/SnapshotEvent.scala, event-sourcing/event-store-cassandra/src/test/scala/org/apache/james/eventsourcing/eventstore/cassandra/dto/SnapshotEventDTO.scala, event-sourcing/event-store-cassandra/src/test/scala/org/apache/james/eventsourcing/eventstore/cassandra/dto/TestEventDTOModules.scala, server/apps/cassandra-app/sample-configuration/jvm.properties, server/apps/distributed-app/sample-configuration/jvm.properties, server/data/data-jmap/src/main/java/org/apache/james/jmap/api/filtering/impl/FilteringAggregate.java, server/data/data-jmap/src/main/java/org/apache/james/jmap/api/filtering/impl/RuleSetDefined.java, upgrade-instructions.md
The snapshots allows to easily improve insertions.
Before above benchmark for 5000 rules: `31 min 42` with last rue creation taking `954 ms`.
After `6 min 18` with last rule creation taking `124 ms`
=> JAMES-3777 Snapshots for eventSourcing JMAP filters

server/task/task-distributed/src/test/java/org/apache/james/task/eventsourcing/distributed/DistributedTaskManagerTest.java, server/task/task-memory/src/main/scala/org/apache/james/task/eventsourcing/DecisionProjection.scala
- Avoid sleeps and use count down latches/awaits
=> [FIX] Improve DistributedTaskManagerTest stability

mpt/impl/imap-mailbox/core/src/main/resources/org/apache/james/imap/scripts/SearchOptionAggregations.test, protocols/imap/src/main/java/org/apache/james/imap/encode/ESearchResponseEncoder.java, protocols/imap/src/main/java/org/apache/james/imap/message/response/ESearchResponse.java, protocols/imap/src/main/java/org/apache/james/imap/processor/SearchProcessor.java
Low code coverage...
And this took a significant amount of CPU! (5% on a production workload...)
Apparently linked to some slow queries in IMAP SEARCH:
=> [PERF + FIX] Improve IMAP ESEARCH

protocols/smtp/src/main/java/org/apache/james/protocols/smtp/core/esmtp/EhloCmdHandler.java, server/apps/distributed-app/docs/modules/ROOT/pages/configure/smtp-hooks.adoc, server/protocols/protocols-smtp/src/main/java/org/apache/james/smtpserver/SendMailHandler.java, server/protocols/protocols-smtp/src/main/java/org/apache/james/smtpserver/dsn/DSNEhloHook.java, server/protocols/protocols-smtp/src/main/java/org/apache/james/smtpserver/futurerelease/FutureReleaseEHLOHook.java, server/protocols/protocols-smtp/src/main/java/org/apache/james/smtpserver/futurerelease/FutureReleaseMailParameterHook.java, server/protocols/protocols-smtp/src/main/java/org/apache/james/smtpserver/futurerelease/FutureReleaseParameters.java, server/protocols/protocols-smtp/src/test/java/org/apache/james/smtpserver/FutureReleaseTest.java, server/protocols/protocols-smtp/src/test/java/org/apache/james/smtpserver/futurerelease/FutureReleaseParametersTest.java, server/protocols/protocols-smtp/src/test/resources/smtpserver-futurerelease.xml, server/queue/queue-memory/src/main/java/org/apache/james/queue/memory/MemoryMailQueueFactory.java, server/queue/queue-memory/src/test/java/org/apache/james/queue/memory/MemoryCacheableMailQueueTest.java
=> JAMES-3822 Add FutureRelease Extension

server/apps/distributed-app/docs/modules/ROOT/pages/operate/webadmin.adoc, server/container/guice/common/src/main/java/org/apache/james/CoreDataModule.java, server/container/guice/protocols/webadmin-data/src/main/java/org/apache/james/modules/server/DataRoutesModules.java, server/data/data-api/src/main/java/org/apache/james/user/api/DeleteUserDataTaskStep.java, server/protocols/webadmin/webadmin-data/src/main/java/org/apache/james/webadmin/routes/DeleteUserDataRoutes.java, server/protocols/webadmin/webadmin-data/src/main/java/org/apache/james/webadmin/service/DeleteUserDataService.java, server/protocols/webadmin/webadmin-data/src/main/java/org/apache/james/webadmin/service/DeleteUserDataTask.java, server/protocols/webadmin/webadmin-data/src/main/java/org/apache/james/webadmin/service/DeleteUserDataTaskAdditionalInformationDTO.java, server/protocols/webadmin/webadmin-data/src/main/java/org/apache/james/webadmin/service/DeleteUserDataTaskDTO.java, server/protocols/webadmin/webadmin-data/src/test/java/org/apache/james/webadmin/routes/DeleteUserDataRoutesTest.java, server/protocols/webadmin/webadmin-data/src/test/java/org/apache/james/webadmin/service/DeleteUserDataTaskSerializationTest.java, src/site/markdown/server/manage-webadmin.md
Scope: Task + Service + Webadmin
TODO: docs, guice binding
=> JAMES-3909 Skeleton code for user data deletion

backends-common/jpa/pom.xml, examples/custom-listeners/src/main/java/org/apache/james/examples/custom/listeners/SetCustomFlagOnBigMessages.java, mailbox/backup/src/main/java/org/apache/james/mailbox/backup/DefaultMailboxBackup.java, mailbox/backup/src/main/java/org/apache/james/mailbox/backup/ZipMailArchiveRestorer.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/CassandraMailboxSessionMapperFactory.java, mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/task/CassandraRecomputeCurrentQuotasServiceTest.java, mailbox/jpa/src/test/java/org/apache/james/mailbox/jpa/mail/task/JPARecomputeCurrentQuotasServiceTest.java, mailbox/memory/src/test/java/org/apache/james/mailbox/inmemory/mail/task/MemoryRecomputeCurrentQuotasServiceTest.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/SystemMailboxesProviderImpl.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/event/MailboxAnnotationListener.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/quota/DefaultUserQuotaRootResolver.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/search/ListeningMessageSearchIndex.java, mailbox/store/src/test/java/org/apache/james/mailbox/store/event/MailboxAnnotationListenerTest.java, mailbox/tools/indexer/src/main/java/org/apache/mailbox/tools/indexer/ReIndexerImpl.java, mailbox/tools/indexer/src/main/java/org/apache/mailbox/tools/indexer/ReIndexerPerformer.java, mailbox/tools/quota-recompute/src/main/java/org/apache/james/mailbox/quota/task/RecomputeCurrentQuotasService.java, server/container/feature-checks/src/main/java/org/apache/james/healthcheck/MailReceptionCheck.java, server/container/mailbox-adapter/src/main/java/org/apache/james/adapter/mailbox/ACLUsernameChangeTaskStep.java, server/container/mailbox-adapter/src/main/java/org/apache/james/adapter/mailbox/MailboxUserDeletionTaskStep.java, server/container/mailbox-adapter/src/main/java/org/apache/james/adapter/mailbox/MailboxUsernameChangeTaskStep.java, server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/RandomStoring.java, server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/send/PostDequeueDecorator.java, server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/mailet/filter/ActionApplier.java, server/protocols/webadmin/webadmin-mailbox-deleted-message-vault/src/main/java/org/apache/james/webadmin/vault/routes/RestoreService.java, server/protocols/webadmin/webadmin-mailbox/src/main/java/org/apache/james/webadmin/service/CreateMissingParentsTask.java, server/protocols/webadmin/webadmin-mailbox/src/main/java/org/apache/james/webadmin/service/ExpireMailboxService.java, server/protocols/webadmin/webadmin-mailbox/src/main/java/org/apache/james/webadmin/service/UserMailboxesService.java, third-party/rspamd/src/main/java/org/apache/james/rspamd/RspamdListener.java, third-party/rspamd/src/main/java/org/apache/james/rspamd/task/GetMailboxMessagesService.java, third-party/spamassassin/src/main/java/org/apache/james/spamassassin/SpamAssassinListener.java
CF https://github.com/apache/james-project/pull/1579
=> JPA connection reuse + avoid leaks

mailbox/jpa/src/main/java/org/apache/james/mailbox/jpa/mail/JPAMessageMapper.java, mailbox/jpa/src/main/java/org/apache/james/mailbox/jpa/mail/model/openjpa/AbstractJPAMailboxMessage.java
Avoids loading all mail metadata
=> JAMES-3911 JPA: Propose a dedicated query for UID listing

mailbox/jpa/src/main/java/org/apache/james/mailbox/jpa/mail/JPAMessageMapper.java
=> JAMES-3911 JPA: optimize applicable flags with a native query

mailbox/jpa/src/main/java/org/apache/james/mailbox/jpa/mail/model/openjpa/JPAMailboxMessage.java, mailbox/jpa/src/test/java/org/apache/james/mailbox/jpa/mail/model/openjpa/JPAMailboxMessageTest.java
=> Add simple null-check in JPAMailboxMessage #JAMES-3915 

mailbox/lucene/src/main/java/org/apache/james/mailbox/lucene/search/LuceneMessageSearchIndex.java, mailbox/lucene/src/test/java/org/apache/james/mailbox/lucene/search/LuceneMailboxMessageSearchIndexTest.java
Avoid date double parsing.
Also Lucene Date tools already converts dates to GMT so our code do not need to worry about timezones.
CF https://github.com/apache/james-project/pull/1618
=> JAMES-3921 Fix Lucene indexing issues

mailbox/lucene/src/main/java/org/apache/james/mailbox/lucene/search/LuceneMessageSearchIndex.java, mailbox/lucene/src/test/java/org/apache/james/mailbox/lucene/search/LuceneMailboxMessageSearchIndexTest.java
=> JAMES-3921 Fix Lucene indexing issues [BACKPORT 3.8.x]

server/apps/distributed-app/docs/modules/ROOT/pages/configure/jvm.adoc, server/blob/blob-api/src/main/java/org/apache/james/blob/api/HashBlobId.java, server/blob/blob-api/src/test/java/org/apache/james/blob/api/HashBlobIdTest.java, server/blob/blob-s3/pom.xml, server/blob/blob-s3/src/test/java/org/apache/james/blob/objectstorage/aws/S3MinioTest.java, src/site/xdoc/server/config-system.xml
- The base64 encoding has the `/` slash character that is unsupported in some S3 platform
=> JAMES-2287 HashBlobId.Factory support encoding type

server/container/spring/src/main/resources/META-INF/org/apache/james/spring-server.xml
This fixes DKIM verification using the spring wiring.
=> Register the DNSPublicKeyRecordRetriever bean

server/mailet/integration-testing/src/test/java/org/apache/james/mailets/SPFIntegrationTests.java, server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/SPF.java, server/mailet/mailets/src/test/java/org/apache/james/transport/mailets/SPFTest.java
CF https://github.com/apache/james-project/pull/1627
=> JAMES-3920 backport on 3.8.x

third-party/rspamd/README.md, third-party/rspamd/docker-compose-distributed.yml, third-party/rspamd/docker-compose.yml, third-party/rspamd/sample-configuration/healthcheck.properties, third-party/rspamd/src/main/java/org/apache/james/rspamd/client/RspamdHttpClient.java, third-party/rspamd/src/main/java/org/apache/james/rspamd/healthcheck/RspamdHealthCheck.java, third-party/rspamd/src/test/java/org/apache/james/rspamd/DockerClamAV.java, third-party/rspamd/src/test/java/org/apache/james/rspamd/DockerRspamd.java, third-party/rspamd/src/test/java/org/apache/james/rspamd/client/RspamdHttpClientTest.java, third-party/rspamd/src/test/java/org/apache/james/rspamd/healthcheck/RspamdHealthcheckTest.java
resolve https://github.com/linagora/james-project/issues/4807
=> JAMES-3755 Healthcheck for Rspamd

server/apps/distributed-app/docs/modules/ROOT/pages/configure/usersrepository.adoc, server/apps/distributed-app/sample-configuration/usersrepository.xml, server/container/guice/data-ldap/src/test/java/org/apache/james/data/DockerLdapRule.java, server/data/data-ldap/src/main/java/org/apache/james/user/ldap/LdapRepositoryConfiguration.java, server/data/data-ldap/src/main/java/org/apache/james/user/ldap/ReadOnlyLDAPUsersDAO.java, server/data/data-ldap/src/test/java/org/apache/james/user/ldap/LdapGenericContainer.java, server/data/data-ldap/src/test/java/org/apache/james/user/ldap/ReadOnlyUsersLDAPRepositoryWithLDAPFailoverTest.java, src/site/xdoc/server/config-users.xml
TODO:
- See if the LDAP supports different SSL settings for distinct URI, otherwise, we would need to assume the setting are the same.
- Other tests?
- Additional work upon review
- Docs & sample configuration
=> JAMES-3928 ReadOnlyUsersRepository: Master slave set up

server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/VacationMailet.java, server/mailet/mailets/src/test/java/org/apache/james/transport/mailets/VacationMailetTest.java
resolve https://github.com/linagora/james-project/issues/4823
=> JAMES-3932 VacationMailet should not respond to sender-self

backends-common/opensearch/pom.xml, backends-common/opensearch/src/main/java/org/apache/james/backends/opensearch/OpenSearchIndexer.java, server/testing/src/main/java/org/apache/james/util/docker/Images.java
A simple lib and image upgrades for OpenSearch without refactoring the transport layer like in https://github.com/apache/james-project/pull/1648
Would need a perf test as well to make sure it's fine
=> JAMES-3929 Opensearch deps upgrades

backends-common/opensearch/src/test/java/org/apache/james/backends/opensearch/DockerOpenSearch.java
Let's try with this, idea taken from there: https://github.com/opensearch-project/opensearch-testcontainers/blob/main/src/main/java/org/opensearch/testcontainers/OpensearchContainer.java#L104
=> [BUILD] Changing OpenSearch waiting strategy

server/mailet/integration-testing/src/test/java/org/apache/james/mailets/DKIMIntegrationTest.java
Add a failure DKIM verification test case.
resolve https://github.com/linagora/james-project/issues/4812
=> JAMES-1975 Enhance DKIM integration tests

server/mailet/integration-testing/src/test/java/org/apache/james/mailets/WithStorageDirectiveIntegrationTest.java
- ImapTestClient got an error "failed. Command not valid in this state."
=> JAMES-3899 - Fix test case unstable

server/container/guice/protocols/jmap/src/main/java/org/apache/james/jmap/rfc8621/RFC8621MethodsModule.java, server/data/data-jmap-cassandra/src/main/java/org/apache/james/jmap/cassandra/upload/CassandraUploadRepository.java, server/data/data-jmap-cassandra/src/main/java/org/apache/james/jmap/cassandra/upload/UploadDAO.java, server/data/data-jmap-cassandra/src/main/java/org/apache/james/jmap/cassandra/upload/UploadModule.java, server/data/data-jmap-cassandra/src/test/java/org/apache/james/jmap/cassandra/upload/CassandraUploadRepositoryTest.java, server/data/data-jmap/src/main/java/org/apache/james/jmap/api/model/Upload.scala, server/data/data-jmap/src/main/java/org/apache/james/jmap/api/upload/UploadService.java, server/data/data-jmap/src/main/java/org/apache/james/jmap/api/upload/UploadServiceDefaultImpl.java, server/data/data-jmap/src/main/java/org/apache/james/jmap/memory/upload/InMemoryUploadRepository.java, server/data/data-jmap/src/test/java/org/apache/james/jmap/api/upload/UploadRepositoryContract.scala, server/data/data-jmap/src/test/java/org/apache/james/jmap/memory/upload/InMemoryUploadRepositoryTest.java, server/protocols/jmap-draft/src/test/java/org/apache/james/jmap/draft/methods/BlobManagerImplTest.java, server/protocols/jmap-draft/src/test/java/org/apache/james/jmap/draft/model/message/view/MessageFastViewFactoryTest.java, server/protocols/jmap-draft/src/test/java/org/apache/james/jmap/draft/model/message/view/MessageFullViewFactoryTest.java, server/protocols/jmap-draft/src/test/java/org/apache/james/jmap/draft/model/message/view/MessageHeaderViewFactoryTest.java, server/protocols/jmap-draft/src/test/java/org/apache/james/jmap/draft/model/message/view/MessageMetadataViewFactoryTest.java, server/protocols/jmap-draft/src/test/java/org/apache/james/jmap/event/ComputeMessageFastViewProjectionListenerTest.java, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/DownloadRoutes.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/UploadRoutes.scala, server/protocols/webadmin/webadmin-jmap/src/test/java/org/apache/james/webadmin/data/jmap/JmapUploadRoutesTest.java, upgrade-instructions.md
jira https://issues.apache.org/jira/browse/JAMES-3925
=> JAMES-3925 Rework JMAP upload APIs

backends-common/cassandra/src/test/java/org/apache/james/backends/cassandra/StatementRecorder.java, backends-common/cassandra/src/test/java/org/apache/james/backends/cassandra/TestingSession.java, server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/Dequeuer.java, server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/view/cassandra/CassandraMailQueueBrowser.java, server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/view/cassandra/CassandraMailQueueMailDelete.java, server/queue/queue-rabbitmq/src/test/java/org/apache/james/queue/rabbitmq/RabbitMQMailQueueTest.java
Goal: help https://github.com/apache/james-project/pull/1623 moves on (no branch push permission).
=> [DUPLICATED] JAMES-3924 RabbitMQ mail queue updates: not performed

server/apps/distributed-app/docs/modules/ROOT/pages/configure/usersrepository.adoc, server/data/data-ldap/src/main/java/org/apache/james/user/ldap/LdapRepositoryConfiguration.java, server/data/data-ldap/src/main/java/org/apache/james/user/ldap/ReadOnlyLDAPUsersDAO.java, server/data/data-ldap/src/test/java/org/apache/james/user/ldap/ReadOnlyUsersLDAPRepositoryTest.java, src/site/xdoc/server/config-users.xml
- Allows to block users
- Allows in conjunction with resolveLocalPartAttribute to set up virtual accounts
=> JAMES-3930 Different DN for listing user and authenticating users

backends-common/cassandra/src/main/java/org/apache/james/backends/cassandra/utils/CassandraAsyncExecutor.java, backends-common/cassandra/src/test/java/org/apache/james/backends/cassandra/TestingSession.java, backends-common/cassandra/src/test/java/org/apache/james/backends/cassandra/TestingSessionTest.java
As Cassandra execution is async it is sometime hard
Cc @quantranhong1999
=> [IMPROVMENT] Add Cassandra statements to the logs

mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/CassandraThreadIdGuessingAlgorithm.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraThreadDAO.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraThreadLookupDAO.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/ThreadTablePartitionKey.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/modules/CassandraThreadModule.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/table/CassandraThreadLookupTable.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/table/CassandraThreadTable.java, mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/CassandraMailboxManagerTest.java, mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/CassandraThreadIdGuessingAlgorithmTest.java, mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraThreadDAOTest.java, mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraThreadLookupDAOTest.java, upgrade-instructions.md
resolve https://github.com/linagora/james-project/issues/4862
polish of https://github.com/apache/james-project/pull/1711
=> JAMES-3937 Use hash for CassandraThreadIdGuessingAlgorithm

mailbox/tools/quota-recompute/src/main/java/org/apache/james/mailbox/quota/task/RecomputeSieveUploadCurrentQuotasService.java, server/apps/memory-app/src/main/java/org/apache/james/MemoryJamesServerMain.java, server/container/guice/protocols/webadmin-data/pom.xml, server/container/guice/protocols/webadmin-data/src/main/java/org/apache/james/modules/server/SieveRoutesModule.java, server/data/data-api/src/main/java/org/apache/james/sieverepository/api/ScriptSummary.java, server/data/data-api/src/main/java/org/apache/james/sieverepository/api/SieveCurrentUploadUsageCalculator.java, server/data/data-api/src/main/java/org/apache/james/sieverepository/api/SieveRepository.java, server/data/data-api/src/test/java/org/apache/james/sieverepository/api/SieveCurrentUploadUsageCalculatorContract.java, server/data/data-cassandra/src/main/java/org/apache/james/sieve/cassandra/CassandraSieveDAO.java, server/data/data-cassandra/src/main/java/org/apache/james/sieve/cassandra/CassandraSieveQuotaDAOV1.java, server/data/data-cassandra/src/main/java/org/apache/james/sieve/cassandra/CassandraSieveQuotaDAOV2.java, server/data/data-cassandra/src/main/java/org/apache/james/sieve/cassandra/CassandraSieveRepository.java, server/data/data-cassandra/src/main/java/org/apache/james/sieve/cassandra/FakeSieveQuotaDAO.java, server/data/data-cassandra/src/main/java/org/apache/james/sieve/cassandra/model/Script.java, server/data/data-cassandra/src/test/java/org/apache/james/sieve/cassandra/CassandraSieveCurrentUploadUsageCalculatorTest.java, server/data/data-cassandra/src/test/java/org/apache/james/sieve/cassandra/CassandraSieveQuotaDAOContract.java, server/data/data-cassandra/src/test/java/org/apache/james/sieve/cassandra/model/ScriptTest.java, server/data/data-file/src/main/java/org/apache/james/sieverepository/file/SieveFileRepository.java, server/data/data-jpa/src/main/java/org/apache/james/sieve/jpa/JPASieveRepository.java, server/data/data-jpa/src/main/java/org/apache/james/sieve/jpa/model/JPASieveScript.java, server/data/data-library/src/test/java/org/apache/james/sieverepository/lib/SieveRepositoryContract.java, server/mailet/mailets/src/test/java/org/apache/james/transport/mailets/managesieve/ManageSieveMailetTestCase.java, server/protocols/webadmin-integration-test/webadmin-integration-test-common/src/main/java/org/apache/james/webadmin/integration/WebAdminServerIntegrationTest.java
this PR is based on https://github.com/apache/james-project/pull/1707
=> JAMES-3926 quota current value recomputation for sieve

examples/custom-listeners/src/test/java/org/apache/james/examples/custom/listeners/SetCustomFlagOnBigMessagesTest.java, mailbox/api/src/main/java/org/apache/james/mailbox/events/MailboxEvents.java, mailbox/api/src/test/java/org/apache/james/mailbox/EventTest.java, mailbox/api/src/test/java/org/apache/james/mailbox/MailboxListenerTest.java, mailbox/event/json/src/main/scala/org/apache/james/event/json/DTOs.scala, mailbox/event/json/src/main/scala/org/apache/james/event/json/MailboxEventSerializer.scala, mailbox/event/json/src/test/java/org/apache/james/event/json/AddedSerializationTest.java, mailbox/opensearch/src/test/java/org/apache/james/mailbox/opensearch/events/OpenSearchListeningMessageSearchIndexTest.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMessageIdManager.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMessageManager.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/event/EventFactory.java, mailbox/store/src/test/java/org/apache/james/mailbox/store/MessageIdManagerTestSystem.java, mailbox/store/src/test/java/org/apache/james/mailbox/store/ThreadIdGuessingAlgorithmContract.java, mailbox/store/src/test/java/org/apache/james/mailbox/store/search/AbstractMessageSearchIndexTest.java, protocols/imap/src/test/java/org/apache/james/imap/processor/base/MailboxEventAnalyserTest.java, protocols/imap/src/test/java/org/apache/james/imap/processor/base/SelectedMailboxImplTest.java, server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/event/ComputeMessageFastViewProjectionListener.java, server/protocols/jmap-draft/src/test/java/org/apache/james/jmap/event/ComputeMessageFastViewProjectionListenerTest.java, server/protocols/jmap-draft/src/test/java/org/apache/james/jmap/event/PopulateEmailQueryViewListenerTest.java, third-party/rspamd/src/test/java/org/apache/james/rspamd/RspamdListenerTest.java, third-party/spamassassin/src/test/java/org/apache/james/spamassassin/SpamAssassinListenerTest.java
resolve https://github.com/linagora/james-project/issues/4869
=> JAMES-2991 Avoid duplicate store again its messageFastView projection

server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/event/ComputeMessageFastViewProjectionListener.java, server/protocols/jmap-draft/src/test/java/org/apache/james/jmap/event/ComputeMessageFastViewProjectionListenerTest.java
resolve https://github.com/linagora/james-project/issues/4867
=> JAMES-2991 Manage deletion in ComputeMessageFastViewProjectionListener

server/apps/memory-app/src/test/java/org/apache/james/RCPTCaseSensitivityTest.java, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EmailSubmissionSetMethodContract.scala
resolve https://github.com/linagora/james-project/issues/4873
=> [TEST] Reinforce recipient case insensitivity tests

mailbox/api/src/main/java/org/apache/james/mailbox/events/MailboxEvents.java, mailbox/api/src/test/java/org/apache/james/mailbox/EventTest.java, mailbox/api/src/test/java/org/apache/james/mailbox/MailboxListenerTest.java, mailbox/event/json/src/main/scala/org/apache/james/event/json/MailboxEventSerializer.scala, mailbox/event/json/src/test/java/org/apache/james/event/json/AddedSerializationTest.java, mailbox/event/json/src/test/java/org/apache/james/event/json/ExpungedSerializationTest.java, mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/OpenSearchMailboxConfiguration.java, mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/events/OpenSearchListeningMessageSearchIndex.java, mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/json/IndexableMessage.java, mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/json/MessageToOpenSearchJson.java, mailbox/opensearch/src/test/java/org/apache/james/mailbox/opensearch/OpenSearchIntegrationTest.java, mailbox/opensearch/src/test/java/org/apache/james/mailbox/opensearch/OpenSearchOptimizeMoveIntegrationTest.java, mailbox/opensearch/src/test/java/org/apache/james/mailbox/opensearch/events/OpenSearchListeningMessageSearchIndexTest.java, mailbox/opensearch/src/test/java/org/apache/james/mailbox/opensearch/search/OpenSearchSearcherTest.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMessageIdManager.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMessageManager.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/event/EventFactory.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/search/ListeningMessageSearchIndex.java, mailbox/store/src/test/java/org/apache/james/mailbox/store/search/AbstractMessageSearchIndexTest.java, mpt/impl/imap-mailbox/opensearch/src/test/java/org/apache/james/mpt/imapmailbox/elasticsearch/host/OpenSearchHostSystem.java, server/apps/distributed-app/docs/modules/ROOT/pages/configure/opensearch.adoc, server/apps/distributed-app/sample-configuration/opensearch.properties, server/protocols/jmap-draft/src/test/java/org/apache/james/jmap/event/PopulateEmailQueryViewListenerTest.java, server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/routes/MailboxesRoutesTest.java, server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/routes/UserMailboxesRoutesTest.java, src/site/xdoc/server/config-opensearch.xml
resolve https://github.com/linagora/james-project/issues/4872
=> OpenSearch search index: upon move, GET then INDEX

mailet/icalendar/src/main/java/org/apache/james/transport/mailets/model/ICALAttributeDTO.java, mailet/icalendar/src/test/java/org/apache/james/transport/mailets/ICALToJsonAttributeTest.java, mailet/icalendar/src/test/java/org/apache/james/transport/mailets/model/ICALAttributeDTOTest.java
resolve https://github.com/linagora/james-project/issues/4880
=> JAMES-3828 ICALAttributeDTO: support missing uid, method and dtstamp fields

src/adr/0067-quota-for-jmap-uploads.md, src/adr/0068-mutualize-cassandra-storge-for-quota.md, src/adr/0070-postgresql-adoption.md
resolve https://github.com/linagora/james-project/issues/4905
=> JAMES-2586 ADR: Native PostgreSQL adoption

pom.xml, server/apps/cassandra-app/src/main/java/org/apache/james/CassandraJamesServerMain.java, server/apps/distributed-app/docs/modules/ROOT/pages/configure/blobstore.adoc, server/apps/scaling-pulsar-smtp/src/main/java/org/apache/james/Main.java, server/blob/blob-api/src/test/java/org/apache/james/blob/api/ReadSaveBlobStoreDAOContract.java, server/blob/blob-file/pom.xml, server/blob/blob-file/src/main/java/org/apache/james/blob/file/FileBlobStoreDAO.java, server/blob/blob-file/src/main/java/org/apache/james/blob/file/FileBlobStoreFactory.java, server/blob/blob-file/src/test/java/org/apache/james/blob/file/FileBlobStoreDAOTest.java, server/blob/blob-file/src/test/java/org/apache/james/blob/file/FileBlobStoreGCAlgorithmTest.java, server/blob/blob-file/src/test/java/org/apache/james/blob/file/FileBlobStorePassThroughTest.java, server/blob/blob-file/src/test/java/org/apache/james/blob/file/FileBlobStoreTest.java, server/blob/pom.xml, server/container/guice/blob/s3/src/main/java/org/apache/james/modules/objectstorage/S3BucketModule.java, server/container/guice/cassandra/src/main/java/org/apache/james/modules/mailbox/DefaultBucketModule.java, server/container/guice/distributed/pom.xml, server/container/guice/distributed/src/main/java/org/apache/james/modules/blobstore/BlobStoreConfiguration.java, server/container/guice/distributed/src/main/java/org/apache/james/modules/blobstore/BlobStoreModulesChooser.java, server/container/guice/distributed/src/test/java/org/apache/james/modules/blobstore/BlobStoreConfigurationTest.java, src/site/xdoc/server/config-blobstore.xml
See the ticket for details but in short having such a card in the James game would ease integrating James into legacy storage systems, not cloud / s3 ready. Think ISCI, SAN, NAS and distributed systems like CEPH...
=> JAMES-3953 Provide a file based blob store

Jenkinsfile, backends-common/postgres/pom.xml, backends-common/postgres/src/main/java/org/apache/james/backends/postgres/PostgresIndex.java, backends-common/postgres/src/main/java/org/apache/james/backends/postgres/PostgresModule.java, backends-common/postgres/src/main/java/org/apache/james/backends/postgres/PostgresTable.java, backends-common/postgres/src/main/java/org/apache/james/backends/postgres/PostgresTableManager.java, backends-common/postgres/src/main/java/org/apache/james/backends/postgres/utils/PostgresExecutor.java, backends-common/postgres/src/test/java/org/apache/james/backends/postgres/PostgresFixture.java, backends-common/postgres/src/test/java/org/apache/james/backends/postgres/PostgresTableManagerTest.java
jira Jira https://issues.apache.org/jira/browse/JAMES-2586
=> JAMES-2586 - Implement PostgresTableManager

backends-common/postgres/pom.xml, backends-common/postgres/src/main/java/org/apache/james/backends/postgres/PostgresTableManager.java, backends-common/postgres/src/test/java/org/apache/james/backends/postgres/DockerPostgresSingleton.java, backends-common/postgres/src/test/java/org/apache/james/backends/postgres/PostgresExtension.java, backends-common/postgres/src/test/java/org/apache/james/backends/postgres/PostgresFixture.java, backends-common/postgres/src/test/java/org/apache/james/backends/postgres/SimpleJamesPostgresConnectionFactoryTest.java, backends-common/postgres/src/test/resources/postgres-rowlevelsecurity-init.sql, mailbox/postgres/src/test/java/org/apache/james/mailbox/postgres/user/PostgresSubscriptionMapperRowLevelSecurityTest.java, mailbox/postgres/src/test/java/org/apache/james/mailbox/postgres/user/PostgresSubscriptionMapperTest.java
jira https://issues.apache.org/jira/browse/JAMES-2586
resolve https://github.com/linagora/james-project/issues/4930
=> JAMES-2586 Fix row-level security implementation

backends-common/cassandra/src/main/java/org/apache/james/backends/cassandra/components/CassandraQuotaLimitDao.java, backends-common/cassandra/src/test/java/org/apache/james/backends/cassandra/quota/CassandraQuotaLimitDaoTest.java
resolve https://github.com/linagora/james-project/issues/4933
=> JAMES-3926 Handle insert null quota limit

backends-common/pom.xml, backends-common/redis/pom.xml, backends-common/redis/src/main/java/org/apache/james/backends/redis/RedisConfiguration.scala, backends-common/redis/src/main/java/org/apache/james/backends/redis/RedisHealthCheck.scala, backends-common/redis/src/test/java/org/apache/james/backends/redis/DockerRedis.java, backends-common/redis/src/test/java/org/apache/james/backends/redis/RedisConfigurationTest.scala, backends-common/redis/src/test/java/org/apache/james/backends/redis/RedisExtension.java, backends-common/redis/src/test/java/org/apache/james/backends/redis/RedisExtensionTest.java, backends-common/redis/src/test/java/org/apache/james/backends/redis/RedisHealthCheckTest.scala, code-coverage-report/pom.xml, pom.xml, server/mailet/rate-limiter-redis/pom.xml, server/mailet/rate-limiter-redis/src/main/scala/org/apache/james/rate/limiter/redis/RedisRateLimiter.scala, server/mailet/rate-limiter-redis/src/test/java/org/apache/james/rate/limiter/RedisRateLimiterTest.scala, src/site/xdoc/server/config-redis.xml
https://issues.apache.org/jira/browse/JAMES-3956
- Created redis module in backends-common
- moved redis configuration from rate-limiter-redis
- added RedisConfigurationTest
=> JAMES-3956 Redis module

server/container/guice/common/src/test/java/org/apache/james/JamesServerExtension.java, server/protocols/webadmin/webadmin-core/src/main/java/org/apache/james/webadmin/WebAdminServer.java, server/protocols/webadmin/webadmin-core/src/test/java/org/apache/james/webadmin/WebAdminUtils.java, server/protocols/webadmin/webadmin-core/src/test/java/org/apache/james/webadmin/WebAdminUtilsTest.java
resolve https://github.com/linagora/tmail-backend/issues/742
=> JAMES-3046 [BUILD] Some improvement regarding webadmin port conflict

backends-common/rabbitmq/src/main/java/org/apache/james/backends/rabbitmq/QueueArguments.java, backends-common/rabbitmq/src/main/java/org/apache/james/backends/rabbitmq/RabbitMQConfiguration.java, backends-common/rabbitmq/src/test/java/org/apache/james/backends/rabbitmq/RabbitMQConfigurationTest.java, server/apps/distributed-app/docs/modules/ROOT/pages/configure/rabbitmq.adoc, server/apps/distributed-app/docs/modules/ROOT/pages/operate/performanceChecklist.adoc, server/apps/distributed-app/helm-chart/james/configs/blob.properties, server/apps/distributed-app/sample-configuration/blob.properties, server/apps/distributed-app/sample-configuration/rabbitmq.properties, server/apps/distributed-pop3-app/sample-configuration/blob.properties, server/apps/scaling-pulsar-smtp/sample-configuration/blob.properties, server/blob/blob-cassandra/src/main/java/org/apache/james/blob/cassandra/cache/CassandraCacheConfiguration.java, server/task/task-distributed/src/main/java/org/apache/james/task/eventsourcing/distributed/RabbitMQWorkQueue.java, server/task/task-distributed/src/test/java/org/apache/james/task/eventsourcing/distributed/RabbitMQWorkQueueTest.java, src/site/xdoc/server/config-rabbitmq.xml, upgrade-instructions.md
resolve https://github.com/linagora/james-project/issues/4917
=> JAMES-3955 Increase consumer timeout for TaskManagerWorkQueue

backends-common/cassandra/pom.xml, pom.xml, server/blob/blob-s3/pom.xml
CF https://github.com/linagora/james-project/issues/4943
=> Vulnerability related updates

backends-common/postgres/pom.xml, backends-common/postgres/src/main/java/org/apache/james/backends/postgres/PostgresTableManager.java, backends-common/postgres/src/test/java/org/apache/james/backends/postgres/PostgresExtension.java, mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/mail/PostgresMailboxMapper.java, mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/mail/PostgresMailboxModule.java, mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/mail/dao/PostgresMailboxDAO.java, mailbox/postgres/src/test/java/org/apache/james/mailbox/postgres/mail/PostgresMailboxMapperACLTest.java, server/container/guice/postgres-common/src/main/java/org/apache/james/modules/data/PostgresCommonModule.java
resolve https://github.com/linagora/james-project/issues/4939
=> JAMES-2586 Implement MailboxACL support for PostgresMailboxMapper

mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/MailboxMappingFactory.java, mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/query/SortConverter.java, mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/search/OpenSearchSearcher.java, mailbox/store/src/test/java/org/apache/james/mailbox/store/search/AbstractMessageSearchIndexTest.java
=> JAMES-3963 Sort From To Cc on display name first

mailbox/lucene/src/test/java/org/apache/james/mailbox/lucene/search/LuceneMessageSearchIndexTest.java, mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/query/CriterionConverter.java, mailbox/scanning-search/src/test/java/org/apache/james/mailbox/store/search/SimpleMessageSearchIndexTest.java, mailbox/store/src/test/java/org/apache/james/mailbox/store/search/AbstractMessageSearchIndexTest.java
OR default behaviour includes many not - so - related terms.
=> JAMES-3963 Full text search: AND for combining phrase terms

backends-common/cassandra/src/main/java/org/apache/james/backends/cassandra/components/CassandraQuotaCurrentValueDao.java, backends-common/cassandra/src/test/java/org/apache/james/backends/cassandra/quota/CassandraQuotaCurrentValueDaoTest.java, backends-common/postgres/src/main/java/org/apache/james/backends/postgres/quota/PostgresQuotaCurrentValueDAO.java, backends-common/postgres/src/main/java/org/apache/james/backends/postgres/quota/PostgresQuotaModule.java, backends-common/postgres/src/test/java/org/apache/james/backends/postgres/quota/PostgresQuotaCurrentValueDAOTest.java, core/src/main/java/org/apache/james/core/quota/QuotaCurrentValue.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/quota/CassandraCurrentQuotaManagerV2.java, server/data/data-cassandra/src/main/java/org/apache/james/sieve/cassandra/CassandraSieveQuotaDAOV2.java, server/data/data-jmap-cassandra/src/main/java/org/apache/james/jmap/cassandra/upload/CassandraUploadUsageRepository.java
resolve https://github.com/linagora/james-project/issues/4938
=> JAMES-2586 Implement PostgresQuotaCurrentValueDAO

mailbox/opensearch/src/test/java/org/apache/james/mailbox/opensearch/search/OpenSearchSearcherTest.java
Review isolation strategy and make it reactive
=> [BUILD] OpenSearchSearcherTest was unstable

mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/model/impl/MessageParser.java, mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/impl/MessageParserTest.java, server/protocols/jmap-draft-integration-testing/jmap-draft-integration-testing-common/src/test/java/org/apache/james/jmap/draft/methods/integration/SendMDNMethodTest.java, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EmailGetMethodContract.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/EmailBodyPart.scala
CF https://github.com/linagora/tmail-flutter/issues/2331#issuecomment-1822230696
=> [ENHANCEMENT] Improve MDN display for JMAP mail RFC-8621

mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/PostgresAttachmentContentLoader.java, mailbox/postgres/src/test/java/org/apache/james/mailbox/postgres/PostgresMailboxManagerProvider.java, server/container/guice/mailbox-postgres/src/main/java/org/apache/james/modules/mailbox/PostgresMailboxModule.java
Just a small quick refactoring, to remove the last JPA mention in pg-mailbox module :)
=> JAMES-2586 Rename JPAAttachmentContentLoader to PostgresAttachmentContentLoader

backends-common/postgres/src/main/java/org/apache/james/backends/postgres/utils/PostgresExecutor.java, backends-common/postgres/src/test/java/org/apache/james/backends/postgres/PostgresTableManagerTest.java
resolve https://github.com/linagora/james-project/issues/4974
=> JAMES-2586 Add a unit test for recreated RLS column should not fail

server/apps/distributed-app/docs/modules/ROOT/pages/configure/blobstore.adoc, server/blob/blob-s3/src/main/java/org/apache/james/blob/objectstorage/aws/AwsS3AuthConfiguration.java, server/blob/blob-s3/src/main/java/org/apache/james/blob/objectstorage/aws/S3BlobStoreDAO.java, server/container/guice/blob/s3/src/main/java/org/apache/james/modules/objectstorage/aws/s3/AwsS3ConfigurationReader.java, server/container/guice/blob/s3/src/test/java/org/apache/james/modules/objectstorage/aws/s3/AwsS3ConfigurationReaderTest.java, src/site/xdoc/server/config-blobstore.xml
This eases POC validations in some situations
=> [ENHANCEMENT] Allow to trust all certificates with S3 blobstore

server/apps/postgres-app/sample-configuration/mailetcontainer.xml
=> JAMES-3967 Store mails when relay is exceeded

server/data/data-postgres/src/main/java/org/apache/james/mailrepository/postgres/PostgresMailRepositoryModule.java, server/data/data-postgres/src/main/java/org/apache/james/sieve/postgres/PostgresSieveModule.java
Merge a few PRs parallel led to this.
=> JAMES-2586 Fix compilation errors on Postgres branch

server/data/data-postgres/src/main/java/org/apache/james/sieve/postgres/PostgresSieveModule.java, server/data/data-postgres/src/main/java/org/apache/james/sieve/postgres/PostgresSieveRepository.java, server/data/data-postgres/src/main/java/org/apache/james/sieve/postgres/PostgresSieveScriptDAO.java, server/data/data-postgres/src/main/java/org/apache/james/sieve/postgres/model/PostgresSieveScript.java, server/data/data-postgres/src/main/java/org/apache/james/sieve/postgres/model/PostgresSieveScriptId.java
While not needed now this extra field would
significantly ease a future JMAP Sieve
implementation and avoid a migration.
=> JAMES-2586 Add an Id for SieveScript

server/apps/postgres-app/README.adoc, server/apps/postgres-app/docker-compose-distributed.yml, server/apps/postgres-app/pom.xml, server/apps/postgres-app/sample-configuration-distributed/blob.properties, server/apps/postgres-app/src/main/java/org/apache/james/PostgresJamesConfiguration.java, server/apps/postgres-app/src/main/java/org/apache/james/PostgresJamesServerMain.java, server/apps/postgres-app/src/test/java/org/apache/james/DistributedPostgresJamesServerTest.java, server/apps/postgres-app/src/test/java/org/apache/james/JamesCapabilitiesServerTest.java, server/container/guice/distributed/src/main/java/org/apache/james/modules/blobstore/BlobStoreCacheModulesChooser.java, server/container/guice/distributed/src/main/java/org/apache/james/modules/blobstore/BlobStoreConfiguration.java, server/container/guice/mailbox-postgres/src/main/java/org/apache/james/modules/mailbox/PostgresMailboxModule.java, server/container/guice/postgres-common/pom.xml
resolve [[PGSQL] Module chooser: S3, file blobStore](https://github.com/linagora/james-project/issues/4984)
I tested the normal docker-compose and distributed one, they work normally too.
=> JAMES-2586 Module chooser: S3, file blobStore

mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/mail/PostgresMessageMapper.java, mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/mail/PostgresMessageModule.java, mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/mail/dao/PostgresMailboxMessageDAO.java, mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/mail/dao/PostgresMailboxMessageFetchStrategy.java, mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/mail/dao/PostgresMessageDAO.java, server/apps/postgres-app/src/test/java/org/apache/james/BodyDeduplicationIntegrationTest.java, server/apps/postgres-app/src/test/resources/mailetcontainer.xml
resolve https://github.com/linagora/james-project/issues/4990
=> JAMES-2586 Message body deduplication

Jenkinsfile, event-bus/pom.xml, event-bus/postgres/pom.xml, event-bus/postgres/src/main/java/org/apache/james/events/PostgresEventDeadLetters.java, event-bus/postgres/src/main/java/org/apache/james/events/PostgresEventDeadLettersModule.java, event-bus/postgres/src/test/java/org/apache/james/events/PostgresEventDeadLettersTest.java, pom.xml, server/apps/postgres-app/src/main/java/org/apache/james/PostgresJamesServerMain.java, server/apps/postgres-app/src/test/java/org/apache/james/DistributedPostgresJamesServerTest.java, server/container/guice/postgres-common/pom.xml, server/container/guice/postgres-common/src/main/java/org/apache/james/modules/events/PostgresDeadLetterModule.java
resolve https://github.com/linagora/james-project/issues/4985
=> JAMES-2586 Implement PostgresEventDeadLetters

server/blob/blob-postgres/pom.xml, server/blob/blob-postgres/src/main/java/org/apache/james/blob/postgres/PostgresBlobStorageModule.java, server/blob/blob-postgres/src/main/java/org/apache/james/blob/postgres/PostgresBlobStoreDAO.java, server/blob/blob-postgres/src/test/java/org/apache/james/blob/postgres/PostgresBlobStoreDAOTest.java, server/blob/pom.xml
The smaller split of https://github.com/apache/james-project/pull/1883
It only the implementation of `PostgresBlobStoreDAO`
without PoolPostgresExecutor
=> JAMES-2586 Implement only PostgresBlobStoreDAO

backends-common/postgres/src/test/java/org/apache/james/backends/postgres/PostgresFixture.java, server/apps/postgres-app/docker-compose-distributed.yml, server/apps/postgres-app/docker-compose.yml
=> JAMES-2586 Adopt Postgres 16.1

mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/DeleteMessageListener.java, mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/mail/dao/PostgresMailboxMessageDAO.java, mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/mail/dao/PostgresMessageDAO.java, mailbox/postgres/src/test/java/org/apache/james/mailbox/postgres/DeleteMessageListenerContract.java, mailbox/postgres/src/test/java/org/apache/james/mailbox/postgres/DeleteMessageListenerTest.java, mailbox/postgres/src/test/java/org/apache/james/mailbox/postgres/DeleteMessageListenerWithRLSTest.java, mailbox/postgres/src/test/java/org/apache/james/mailbox/postgres/PostgresMailboxManagerProvider.java, server/container/guice/mailbox-postgres/src/main/java/org/apache/james/modules/mailbox/PostgresMailboxModule.java
resolve https://github.com/linagora/james-project/issues/5019
=> JAMES-2586 - Fix BUG - DeleteMessageListener - not work correctly when enabling RLS

third-party/crowdsec/pom.xml, third-party/crowdsec/src/test/java/org/apache/james/CrowdsecExtension.java, third-party/crowdsec/src/test/java/org/apache/james/CrowdsecHttpClientTest.java, third-party/crowdsec/src/test/java/org/apache/james/CrowdsecIntegrationTest.java, third-party/crowdsec/src/test/java/org/apache/james/HAProxyExtension.java, third-party/crowdsec/src/test/resources/crowdsec/acquis.yaml, third-party/crowdsec/src/test/resources/crowdsec/collections/james.yaml, third-party/crowdsec/src/test/resources/crowdsec/parsers/james-auth.yaml, third-party/crowdsec/src/test/resources/crowdsec/parsers/james-dictionary-attack.yaml, third-party/crowdsec/src/test/resources/crowdsec/parsers/syslog-logs.yaml, third-party/crowdsec/src/test/resources/crowdsec/scenarios/james-bf-auth.yaml, third-party/crowdsec/src/test/resources/crowdsec/scenarios/james-dictionary-attack.yaml, third-party/crowdsec/src/test/resources/imapserver.xml, third-party/crowdsec/src/test/resources/listeners.xml, third-party/crowdsec/src/test/resources/logback-test.xml, third-party/crowdsec/src/test/resources/mailetcontainer.xml, third-party/crowdsec/src/test/resources/pop3server.xml, third-party/crowdsec/src/test/resources/smtpserver.xml, third-party/crowdsec/src/test/resources/usersrepository.xml
resolve https://github.com/linagora/james-project/issues/5003
SMTP proxy support with CrowdSec should already be the case.
=> JAMES-3897 CrowdSec integration test for SMTP

server/apps/postgres-app/docker-compose.yml, server/apps/postgres-app/sample-configuration/blob.properties, server/apps/postgres-app/src/main/java/org/apache/james/PostgresJamesConfiguration.java, server/apps/postgres-app/src/test/java/org/apache/james/BodyDeduplicationIntegrationTest.java
The `postgres` has a better performance than `file`
- postgres: https://vttranlina.github.io/gatling_20240109/postgres/index.html
- file: https://vttranlina.github.io/gatling_20240109/file/index.html
=> JAMES-2586 - Set blobStorage implementation is postgres by default

server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/Enqueuer.java
One-liner to correctly propagate the exception up the chain.
=> JAMES-3968 Fix mail loss due to RabbitMQ ack failure

Jenkinsfile, mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/DeleteMessageListener.java, server/data/data-jmap-postgres/pom.xml, server/pom.xml
The module where we can implement the Postgres storage layer for JMAP.
resolve https://github.com/linagora/james-project/issues/5015
=> JAMES-2586 Introduce data-jmap-postgres module

server/apps/postgres-app/src/main/java/org/apache/james/PostgresJamesServerMain.java, server/container/guice/postgres-common/src/main/java/org/apache/james/modules/data/PostgresDelegationStoreModule.java, server/container/guice/postgres-common/src/main/java/org/apache/james/modules/data/PostgresUsersRepositoryModule.java, server/data/data-postgres/src/main/java/org/apache/james/user/postgres/PostgresDelegationStore.java
- Making it easier to install the binding when a user chooses this option.
=> JAMES-2586 - CLEAN CODE -  Guice binding for Postgres User Repository modules

server/data/data-jmap-postgres/pom.xml, server/data/data-jmap-postgres/src/main/java/org/apache/james/jmap/postgres/projections/PostgresMessageFastViewProjection.java, server/data/data-jmap-postgres/src/main/java/org/apache/james/jmap/postgres/projections/PostgresMessageFastViewProjectionModule.java, server/data/data-jmap-postgres/src/test/java/org/apache/james/jmap/postgres/projections/PostgresMessageFastViewProjectionTest.java, server/data/data-jmap/src/main/java/org/apache/james/jmap/api/projections/MessageFastViewProjection.java
resolve https://github.com/linagora/james-project/issues/5009
=> JAMES-2586 Implement PostgresMessageFastViewProjection

server/blob/blob-file/src/main/java/org/apache/james/blob/file/FileBlobStoreDAO.java
Avoid partial reads and array concatenations.
CF: https://github.com/linagora/james-project/pull/5032
=> JAMES-3953 Performance enhancements

backends-common/postgres/src/main/java/org/apache/james/backends/postgres/utils/PostgresExecutor.java, mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/mail/dao/PostgresMailboxMessageDAO.java, mailbox/postgres/src/test/java/org/apache/james/mailbox/postgres/DeleteMessageListenerContract.java, server/apps/postgres-app/src/main/java/org/apache/james/PostgresJmapModule.java
resolve https://github.com/linagora/james-project/issues/5044
=> JAMES-2586 - Fixbug - Delete Message Listener - Fix hanging issue  @vttranlina

backends-common/postgres/src/main/java/org/apache/james/backends/postgres/PostgresCommons.java, backends-common/postgres/src/test/java/org/apache/james/backends/postgres/PostgresExtension.java, server/apps/postgres-app/src/main/java/org/apache/james/PostgresJamesServerMain.java, server/apps/postgres-app/src/main/java/org/apache/james/PostgresJmapModule.java, server/container/guice/postgres-common/pom.xml, server/container/guice/postgres-common/src/main/java/org/apache/james/modules/data/PostgresDataJmapModule.java, server/container/guice/protocols/webadmin-jmap/src/main/java/org/apache/james/modules/server/JmapUploadCleanupModule.java, server/data/data-jmap-cassandra/src/main/java/org/apache/james/jmap/cassandra/upload/CassandraUploadRepository.java, server/data/data-jmap-cassandra/src/test/java/org/apache/james/jmap/cassandra/upload/CassandraUploadRepositoryTest.java, server/data/data-jmap-postgres/src/main/java/org/apache/james/jmap/postgres/PostgresDataJMapAggregateModule.java, server/data/data-jmap-postgres/src/main/java/org/apache/james/jmap/postgres/upload/PostgresUploadDAO.java, server/data/data-jmap-postgres/src/main/java/org/apache/james/jmap/postgres/upload/PostgresUploadModule.java, server/data/data-jmap-postgres/src/main/java/org/apache/james/jmap/postgres/upload/PostgresUploadRepository.java, server/data/data-jmap-postgres/src/main/java/org/apache/james/jmap/postgres/upload/PostgresUploadUsageRepository.java, server/data/data-jmap-postgres/src/test/java/org/apache/james/jmap/postgres/upload/PostgresUploadRepositoryTest.java, server/data/data-jmap-postgres/src/test/java/org/apache/james/jmap/postgres/upload/PostgresUploadServiceTest.java, server/data/data-jmap/src/main/java/org/apache/james/jmap/api/upload/UploadRepository.java, server/data/data-jmap/src/main/java/org/apache/james/jmap/memory/upload/InMemoryUploadRepository.java, server/data/data-jmap/src/test/java/org/apache/james/jmap/api/upload/UploadRepositoryContract.scala, server/data/data-jmap/src/test/java/org/apache/james/jmap/memory/upload/InMemoryUploadRepositoryTest.java, server/protocols/webadmin-integration-test/postgres-webadmin-integration-test/src/test/java/org/apache/james/webadmin/integration/postgres/PostgresWebAdminServerIntegrationTest.java, server/protocols/webadmin/webadmin-jmap/src/main/java/org/apache/james/webadmin/data/jmap/JmapUploadRoutes.java, server/protocols/webadmin/webadmin-jmap/src/main/java/org/apache/james/webadmin/data/jmap/UploadCleanupTaskDTO.java, server/protocols/webadmin/webadmin-jmap/src/main/java/org/apache/james/webadmin/data/jmap/UploadRepositoryCleanupTask.java
resolve  https://github.com/linagora/james-project/issues/5015
=> JAMES-2586 Implement Postgres upload repository

backends-common/postgres/src/main/java/org/apache/james/backends/postgres/PostgresCommons.java, server/apps/postgres-app/src/main/java/org/apache/james/PostgresJamesServerMain.java, server/apps/postgres-app/src/main/java/org/apache/james/PostgresJmapModule.java, server/data/data-jmap-postgres/src/main/java/org/apache/james/jmap/postgres/PostgresDataJMapAggregateModule.java, server/data/data-jmap-postgres/src/main/java/org/apache/james/jmap/postgres/pushsubscription/PostgresPushSubscriptionDAO.java, server/data/data-jmap-postgres/src/main/java/org/apache/james/jmap/postgres/pushsubscription/PostgresPushSubscriptionModule.java, server/data/data-jmap-postgres/src/main/java/org/apache/james/jmap/postgres/pushsubscription/PostgresPushSubscriptionRepository.java, server/data/data-jmap-postgres/src/test/java/org/apache/james/jmap/postgres/pushsubscription/PostgresPushSubscriptionRepositoryTest.java
resolve https://github.com/linagora/james-project/issues/5018
=> JAMES-2586 Implement Postgres Push subscription 

server/apps/postgres-app/README.adoc, server/apps/postgres-app/clean_up.sql
resolve https://github.com/linagora/james-project/issues/5040
=> JAMES-2586 Introduce sql script to clean up PGSL data

mailet/crypto/pom.xml, pom.xml, server/container/core/pom.xml, server/container/filesystem-api/pom.xml, server/container/guice/configuration/pom.xml, server/container/spring/pom.xml, server/mailet/dkim/pom.xml, server/protocols/jwt/pom.xml, server/protocols/webadmin/webadmin-core/pom.xml, server/protocols/webadmin/webadmin-dropwizard-metrics/src/main/java/org/apache/james/webadmin/dropwizard/MetricsRoutes.java, server/protocols/webadmin/webadmin-mailrepository/src/main/java/org/apache/james/webadmin/routes/MailRepositoriesRoutes.java
This reverts commit 69e45e4ddf164cff38764bcc4860b47b1274abb1.
```
org.apache.james.webadmin.routes.UserMailboxesRoutesTest$NormalBehaviour.putShouldReturnNotFoundWhenNoMailboxName
Request method:	PUT
Request URI:	http://localhost:40949/users/username/mailboxes
Proxy:			<none>
Request params:	<none>
Query params:	<none>
Form params:	<none>
Path params:	<none>
Headers:		Accept=application/json, application/javascript, text/javascript, text/json
Content-Type=application/json; charset=UTF-8
Cookies:		<none>
Multiparts:		<none>
Body:			<none>
HTTP/1.1 405 Method Not Allowed
Date: Fri, 26 Jan 2024 11:28:59 GMT
Access-Control-Allow-Origin: *
Access-Control-Request-Method: DELETE, GET, POST, PUT
Access-Control-Allow-Headers: Content-Type, Authorization, Accept
Content-Type: application/json …
```
=> Revert "[UPDATE] Update spark version: Jetty update"

server/container/util/src/main/java/org/apache/james/util/AuditTrail.java, server/container/util/src/test/java/org/apache/james/util/AuditTrailTest.java, server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/delivery/MailDispatcher.java
- Remove unspecified empty values (makes audit harder)
- Flatten parameters
=> [IMPROVMENT] MDC audit trail format

mailet/crypto/pom.xml, pom.xml, server/container/guice/configuration/pom.xml, server/mailet/dkim/pom.xml, server/mailet/integration-testing/pom.xml, server/protocols/jwt/pom.xml
Getting back on this: https://github.com/apache/james-project/pull/1957
=> [UPDATE] BouncyCastle 1.70 -> 1.77 (fixes multiple minor CVEs)

server/container/feature-checks/src/main/java/org/apache/james/healthcheck/MailReceptionCheck.java
By pre-filtering events to the one that interest us we avoid data race.
=> [FIX] MailReceptionCheck should not call sink concurrently

server/apps/spring-app/src/main/resources/fetchmail.xml, server/protocols/fetchmail/pom.xml, server/protocols/fetchmail/src/main/java/org/apache/james/fetchmail/FetchMail.java, server/protocols/fetchmail/src/test/java/org/apache/james/fetchmail/FetchMailTest.java
This PR aims to fix https://issues.apache.org/jira/browse/JAMES-2372.
There was a bug with the increment of one variable but also with getting the configuration for each account.
I did a test but I'm not certain about the correct use and configuration of users with different types for accounts.
=> JAMES-2372 Fixing multiple accounts with Fetchmail

server/apps/postgres-app/README.adoc, server/apps/postgres-app/clean_up.sql, server/container/guice/postgres-common/src/main/java/org/apache/james/modules/data/PostgresVacationModule.java, server/data/data-api/src/test/java/org/apache/james/vacation/api/NotificationRegistryContract.java, server/data/data-cassandra/src/main/java/org/apache/james/vacation/cassandra/CassandraNotificationRegistry.java, server/data/data-memory/src/main/java/org/apache/james/vacation/memory/MemoryNotificationRegistry.java, server/data/data-postgres/src/main/java/org/apache/james/vacation/postgres/PostgresNotificationRegistry.java, server/data/data-postgres/src/main/java/org/apache/james/vacation/postgres/PostgresNotificationRegistryDAO.java, server/data/data-postgres/src/main/java/org/apache/james/vacation/postgres/PostgresVacationModule.java, server/data/data-postgres/src/test/java/org/apache/james/vacation/postgres/PostgresNotificationRegistryTest.java
resolve https://github.com/linagora/james-project/issues/5023
=> JAMES-2586 Implement PostgresNotificationRegistry

server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/NettyImapSession.java
SelectedMailbox subscription was not well cleaned up
=> [FIX] IMAP LEAK: CLOSE, UNSELECT

mailbox/jpa/src/main/java/org/apache/james/mailbox/jpa/mail/JPAAttachmentMapper.java, mailbox/memory/src/main/java/org/apache/james/mailbox/inmemory/mail/InMemoryAttachmentMapper.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/model/impl/FileBufferedBodyFactory.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/model/impl/MessageParser.java
This significantly reduces memory pressure on APPEND. And was surprisingly easy to achieve!
=> File buffering for message storer

server/apps/distributed-app/docs/modules/ROOT/pages/configure/jmap.adoc, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EmailGetMethodContract.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/core/Capability.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/core/JmapRfc8621Configuration.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/Email.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/EmailGet.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailGetMethod.scala, src/site/xdoc/server/config-jmap.xml
Continue of pr https://github.com/apache/james-project/pull/2014
=> JAMES-3995 Add a max number of items for EmailGet full reads

server/apps/distributed-app/docs/modules/ROOT/pages/configure/blobstore.adoc, server/blob/blob-s3/src/main/java/org/apache/james/blob/objectstorage/aws/S3BlobStoreConfiguration.java, server/blob/blob-s3/src/main/java/org/apache/james/blob/objectstorage/aws/S3BlobStoreDAO.java, server/blob/blob-s3/src/test/java/org/apache/james/blob/objectstorage/aws/S3BlobStoreDAOTest.java, server/blob/blob-s3/src/test/java/org/apache/james/blob/objectstorage/aws/S3MinioTest.java, server/container/guice/blob/s3/src/main/java/org/apache/james/modules/objectstorage/S3BlobStoreConfigurationReader.java, src/site/xdoc/server/config-blobstore.xml
Continue of https://github.com/apache/james-project/pull/2017
=> JAMES-4004 [FIX] Allow retries for S3 saves

server/data/data-ldap/src/main/java/org/apache/james/user/ldap/ReadOnlyLDAPUser.java
jira https://issues.apache.org/jira/browse/JAMES-3998
=> JAMES-3998 Empty password should not lead to worrying error

mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMessageIdManager.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMessageManager.java, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/EmailBodyPart.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/EmailImport.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailImportMethod.scala
For 20MB + files this takes time.
This approach avoids over-switching by doing it
only after fetching items...
CF https://github.com/apache/james-project/pull/2015
=> [FIX] Mime parsing on parallel scheduler

mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/IndexBody.java, mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/OpenSearchMailboxConfiguration.java, mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/events/OpenSearchListeningMessageSearchIndex.java, mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/json/IndexableMessage.java, mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/json/MessageToOpenSearchJson.java, mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/json/MimePartParser.java, mailbox/opensearch/src/test/java/org/apache/james/mailbox/opensearch/OpenSearchMailboxConfigurationTest.java, mailbox/opensearch/src/test/java/org/apache/james/mailbox/opensearch/OpenSearchNoIndexBodyIntegrationTest.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/search/ListeningMessageSearchIndex.java, server/apps/distributed-app/docs/modules/ROOT/pages/configure/opensearch.adoc, src/site/xdoc/server/config-opensearch.xml
This relax pressure on the AES blob store and APPEND
Also this is helpfull upon mass data ingestion.
TODO make this configurable
=> Do not index body

mailet/standard/src/main/java/org/apache/james/transport/mailets/StripAttachment.java, mailet/standard/src/test/java/org/apache/james/transport/mailets/StripAttachmentTest.java
- Add a test
- Explicit handling with an INFO level log
=> JAMES-4009 StripAttachment should explicitly handle duplicates

server/data/data-jmap/src/main/java/org/apache/james/jmap/api/model/Preview.java, server/data/data-jmap/src/main/java/org/apache/james/jmap/mime4j/AvoidBinaryBodyBufferingBodyFactory.java, server/data/data-jmap/src/main/java/org/apache/james/jmap/mime4j/FakeBinaryBody.java, server/data/data-jmap/src/main/java/org/apache/james/jmap/mime4j/SizeUtils.java, server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/event/ComputeMessageFastViewProjectionListener.java, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/resources/eml/nested2.eml, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EmailGetMethodContract.scala, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EmailParseMethodContract.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/Email.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/EmailBodyPart.scala
On many very large message we might consume excessive memory.
Avoid buffering of the binary parts in order to save memory.
@Arsnael help wanted to help polish this.
Apparently I did broke some stuff in bodySTructure
=> JAMES-3995 Optimize Email/get

server/apps/distributed-app/docs/modules/ROOT/pages/configure/blobstore.adoc, server/apps/distributed-app/sample-configuration/jvm.properties, server/blob/blob-aes/pom.xml, server/blob/blob-aes/src/main/java/org/apache/james/blob/aes/AESBlobStoreDAO.java, server/blob/blob-api/src/main/java/org/apache/james/blob/api/BlobStoreDAO.java, server/blob/blob-s3/src/main/java/org/apache/james/blob/objectstorage/aws/S3BlobStoreDAO.java
=> JAMES-4002 AES blob store tuning to reduce memory pressure

server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/ImapChannelUpstreamHandler.java, server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/ImapRequestFrameDecoder.java
- Avoid not clearing IMAP litteral in sonme specific cases
- Avoid clearing IMAP litteral while IMAP APPEND is in progress
=> JAMES-4007 Improve IMAP literal lifecycle

mailet/standard/src/main/java/org/apache/james/transport/mailets/StripAttachment.java, mailet/standard/src/test/java/org/apache/james/transport/mailets/StripAttachmentTest.java, mailet/standard/src/test/resources/mime/space.eml
=> JAMES-4011 Use MIME4J to decode filename

server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/remote/delivery/Bouncer.java, server/mailet/mailets/src/test/java/org/apache/james/transport/mailets/remote/delivery/BouncerTest.java
Cherrypick from master.
This fixes an inconsistent behavior, so it should be on the stable branch as well.
=> JAMES-4006 Bouncer should pass DSN to bounce processor (3.8.x)

mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMailboxManager.java
Nested manager calls in listener would cause
deadlock, and event bus remote call would
cause severe performance hit.
Encountered while working on https://github.com/linagora/tmail-backend/pull/946
=> [FIX] Notify eventbus outside of the lock

server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EmailSubmissionSetMethodContract.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailSubmissionSetMethod.scala
=> JAMES-4008 Fix EmailSubmissionSetMethod with named address

server/data/data-jmap-cassandra/src/main/scala/org/apache/james/jmap/cassandra/identity/CassandraCustomIdentityDAO.scala, server/data/data-jmap/src/main/scala/org/apache/james/jmap/api/identity/CustomIdentityDAO.scala, server/data/data-jmap/src/main/scala/org/apache/james/jmap/memory/identity/MemoryCustomIdentityDAO.scala, server/data/data-jmap/src/test/scala/org/apache/james/jmap/api/identity/CustomIdentityDAOContract.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/DelegateSetDeletePerformer.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/IdentitySetDeletePerformer.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/MailboxSetDeletePerformer.scala
Idea from https://github.com/apache/james-project/pull/2071
but for other methods
=> JMAP - Delete/destroy should take a set as an input

server/data/data-jmap/src/main/scala/org/apache/james/jmap/api/identity/CustomIdentityDAO.scala, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/IdentityGetContract.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/json/IdentitySerializer.scala
Fix bug:
GIVEN I modified my default identity in the webmain
WHEN I try to delete it by JMAP
THEN it fails
=> JAMES-3534 Fixbug - Identity response alway return mayDelete=false when server set identity

server/apps/jpa-app/pom.xml, server/apps/jpa-app/src/main/java/org/apache/james/JPAJamesServerMain.java, server/apps/jpa-smtp-app/pom.xml, server/apps/jpa-smtp-app/src/main/java/org/apache/james/JPAJamesServerMain.java, server/apps/memory-app/pom.xml, server/apps/memory-app/src/main/java/org/apache/james/MemoryJamesServerMain.java, server/apps/scaling-pulsar-smtp/pom.xml, server/apps/scaling-pulsar-smtp/src/main/java/org/apache/james/Main.java
Reported from the matric channel by البهي
@muhammadbahey_twitter:gitter.im
> I tried to james:jpa-3.8.0 and tried to call curl -XPOST /mail-transfer-service but it gives 404 NOT found
=> [FIX] Ship mail over web webadmin routes into more apps

protocols/smtp/src/main/java/org/apache/james/protocols/smtp/core/esmtp/AuthCmdHandler.java
Avoids those logs:
TBH I hesited to completly rework the error handling not
=> [ENHANCEMENT] Refactor and improve SMTP AuthCmdHandler

server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/ImapRequestFrameDecoder.java
This exception:
```
java.util.NoSuchElementException: framer
```
Was unmanaged (reactor subscriber in the stacktrace)
Followed immediatly by:
```
org.apache.james.lifecycle.api.Disposable$LeakAwareFinalizer
"message":"Leak detected!
Resource org.apache.james.imapserver.netty.ImapRequestFrameDecoder$FileHolderInner@3d635737 was not released before its referent was garbage-collected.
Resource management needs to be reviewed: ensure to always call dispose() for disposable objects you work with.
Consider enabling advanced leak detection to further identify the problem.
```
In such case catching and propagating the exception as well as releasing the file seems like a good idea.
=> [FIX] IMAP APPEND file leak

server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/Email.scala
If requesting 30 message fast view, and fast view fails, all messages were loaded at once in memory which could be catastrophic with large messages.
Avoid this by lowering concurrency, and splitting the calls
=> [ENHANCEMENT] JMAP: limit parallel read in case of fastView miss

server/protocols/protocols-imap4/src/test/java/org/apache/james/imapserver/netty/IMAPServerTest.java
- Rely on mock to enforce that backpressure is applied
- Ensure that when read FETCH command proceed
=> JAMES-3977 Test for backpressure

server/protocols/jmap-rfc-8621-integration-tests/distributed-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/distributed/DistributedBase.java, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/IdentityGetContract.scala
When I did https://github.com/apache/james-project/pull/2087
I missed verification on the distributed test
=> JAMES-3534 Update IdentityGetContract - fix failing when running with Distributed test

server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/MailboxSetMethodContract.scala, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/package.scala
resolve https://github.com/linagora/james-project/issues/5133
=> JAMES-2586 Fix MailboxSetMethodContract

server/blob/blob-s3/src/main/java/org/apache/james/blob/objectstorage/aws/S3BlobStoreDAO.java
=> [FIX] S3BlobStoreDAO::readReactive is blocking on the driver thread

backends-common/postgres/pom.xml, backends-common/postgres/src/main/java/org/apache/james/backends/postgres/utils/PostgresExecutor.java, server/blob/blob-postgres/pom.xml, server/data/data-postgres/src/main/java/org/apache/james/sieve/postgres/PostgresSieveRepository.java, server/data/data-postgres/src/main/java/org/apache/james/sieve/postgres/PostgresSieveScriptDAO.java, server/data/data-postgres/src/test/java/org/apache/james/rrt/postgres/RewriteTablesTest.java
It looks easier than we thought so far...
=> JAMES-2586 Bump jOOQ to 3.19.6

server/container/guice/protocols/jmap/src/main/java/org/apache/james/jmap/rfc8621/RFC8621MethodsModule.java
Unbind unused AttachmentBlobResolver
=> JAMES-2586 Unbind AttachmentBlobResolver

backends-common/cassandra/pom.xml, pom.xml, protocols/netty/pom.xml, protocols/netty/src/main/java/org/apache/james/protocols/netty/AbstractAsyncServer.java, server/apps/distributed-app/docs/modules/ROOT/pages/configure/imap.adoc, server/apps/distributed-app/docs/modules/ROOT/pages/configure/pop3.adoc, server/apps/distributed-app/docs/modules/ROOT/pages/configure/smtp.adoc, server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/IMAPServer.java, server/protocols/protocols-library/src/main/java/org/apache/james/protocols/lib/netty/AbstractConfigurableAsyncServer.java, src/site/xdoc/server/config-imap4.xml, src/site/xdoc/server/config-pop3.xml, src/site/xdoc/server/config-smtp-lmtp.xml
- Epoll transport
- High / low watermarks for the write buffer
=> [ENHANCEMENT] More Netty tunning options

mailbox/api/src/test/java/org/apache/james/mailbox/MailboxManagerTest.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageMetadata.java, mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/CassandraMailboxManagerTest.java, mailbox/memory/src/test/java/org/apache/james/mailbox/inmemory/mail/InMemoryMapperProvider.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMessageIdManager.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMessageManager.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/model/DelegatingMailboxMessage.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/model/impl/SimpleMessage.java, mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/MapperProvider.java, mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/MessageMapperTest.java, protocols/imap/src/main/java/org/apache/james/imap/processor/fetch/FetchProcessor.java, server/apps/cassandra-app/src/test/java/org/apache/james/WithCassandraBlobStoreTest.java, server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/ImapChannelUpstreamHandler.java
This was not preserved for the Cassandra mailbox, leading to innacurrate backpressure and down the line to OutOfMemoryExceptions
=> JAMES-3977 Add bytes preservation in manager and mapper contracts

server/blob/blob-aes/src/main/java/org/apache/james/blob/aes/AESBlobStoreDAO.java
Was blocking on the S3 driver Netty EventLoop and on the parrallel scheduler
(verified with printing thread names)
=> [Fix] AESBlobStore threading

mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/DeleteMessageListener.java, mailbox/plugin/deleted-messages-vault-cassandra/src/main/java/org/apache/james/vault/metadata/DeletedMessageVaultDeletionCallback.java, mailbox/plugin/deleted-messages-vault/src/main/java/org/apache/james/vault/VaultConfiguration.java, mailbox/plugin/deleted-messages-vault/src/test/java/org/apache/james/vault/VaultConfigurationTest.java, server/apps/distributed-app/src/main/java/org/apache/james/CassandraRabbitMQJamesServerMain.java, server/apps/distributed-pop3-app/src/main/java/org/apache/james/DistributedPOP3JamesServerMain.java, server/container/guice/distributed/src/main/java/org/apache/james/modules/mailbox/DistributedDeletedMessageVaultDeletionCallback.java, server/container/guice/distributed/src/main/java/org/apache/james/modules/mailbox/DistributedDeletedMessageVaultModule.java, server/protocols/webadmin-integration-test/distributed-webadmin-integration-test/src/test/java/org/apache/james/webadmin/integration/rabbitmq/vault/WorkQueueEnabledDeletedMessageVaultIntegrationTest.java
Deleted message vault copy can be long, doing it
asynchronously would make the feature more reliable.
=> [ENHANCEMENT] Workqueue for the deleted message vault

examples/pom.xml, pom.xml, server/data/data-api/src/main/java/org/apache/james/droplists/api/DeniedEntityType.java, server/data/data-api/src/main/java/org/apache/james/droplists/api/DropList.java, server/data/data-api/src/main/java/org/apache/james/droplists/api/DropListEntry.java, server/data/data-api/src/main/java/org/apache/james/droplists/api/OwnerScope.java, server/data/data-api/src/test/java/org/apache/james/droplists/api/DropListEntryTest.java
[https://issues.apache.org/jira/projects/JAMES/issues/JAMES-3946](https://issues.apache.org/jira/projects/JAMES/issues/JAMES-3946?filter=allopenissues)
=> JAMES-3946 DropLists

server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EmailQueryMethodContract.scala, server/protocols/jmap-rfc-8621-integration-tests/postgres-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/postgres/PostgresEmailQueryMethodTest.java
pr for master https://github.com/apache/james-project/pull/2184
=> JAMES-2586 Fix flaky tests in postgres email query method test

server/protocols/webadmin-integration-test/distributed-webadmin-integration-test/src/test/java/org/apache/james/webadmin/integration/rabbitmq/FixingGhostMailboxTest.java, server/protocols/webadmin-integration-test/distributed-webadmin-integration-test/src/test/java/org/apache/james/webadmin/integration/rabbitmq/RabbitMQReindexingWithEventDeadLettersTest.java, server/protocols/webadmin-integration-test/webadmin-integration-test-common/src/main/java/org/apache/james/webadmin/integration/FastViewProjectionHealthCheckIntegrationContract.java, server/protocols/webadmin-integration-test/webadmin-integration-test-common/src/main/java/org/apache/james/webadmin/integration/ForwardIntegrationTest.java, server/protocols/webadmin-integration-test/webadmin-integration-test-common/src/main/java/org/apache/james/webadmin/integration/TestFixture.java, server/protocols/webadmin-integration-test/webadmin-integration-test-common/src/main/java/org/apache/james/webadmin/integration/vault/DeletedMessageVaultIntegrationTest.java, server/protocols/webadmin-integration-test/webadmin-integration-test-common/src/main/java/org/apache/james/webadmin/integration/vault/LinshareBlobExportMechanismIntegrationTest.java, server/testing/src/main/java/org/apache/james/jmap/JmapRFCCommonRequests.java, third-party/spamassassin/src/test/java/org/apache/james/spamassassin/SpamAssassinContract.java, third-party/spamassassin/src/test/java/org/apache/james/spamassassin/module/SpamAssassinTestModule.java
jira https://issues.apache.org/jira/browse/JAMES-4025
=> JAMES-4025 Rewrite some tests of JMAP draft on top of JMAP RFC-8621 (module: webadmin-integration-test)

server/protocols/jmap-rfc-8621-integration-tests/distributed-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/distributed/DistributedCorsHeaderAPITest.java, server/protocols/jmap-rfc-8621-integration-tests/distributed-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/distributed/DistributedIMAPSetMessagesCompatibilityTest.java, server/protocols/jmap-rfc-8621-integration-tests/distributed-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/distributed/DistributedQuotaMailingTest.java, server/protocols/jmap-rfc-8621-integration-tests/distributed-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/distributed/DistributedVacationIntegrationTest.java, server/protocols/jmap-rfc-8621-integration-tests/distributed-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/distributed/DistributedVacationRelayIntegrationTest.java, server/protocols/jmap-rfc-8621-integration-tests/distributed-jmap-rfc-8621-integration-tests/src/test/resources/imapserver.xml, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/pom.xml, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/CorsHeaderAPITest.scala, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/ImapKeywordsConsistencyContract.scala, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/ImapSetMessagesMailboxesUpdatesCompatibilityContract.scala, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/QuotaMailingTest.scala, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/VacationIntegrationTest.scala, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/VacationRelayIntegrationTest.scala, server/protocols/jmap-rfc-8621-integration-tests/memory-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/memory/MemoryCorsHeaderAPITest.java, server/protocols/jmap-rfc-8621-integration-tests/memory-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/memory/MemoryIMAPKeywordsInconsistenciesTest.java, server/protocols/jmap-rfc-8621-integration-tests/memory-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/memory/MemoryIMAPSetMessagesCompatibilityTest.java, server/protocols/jmap-rfc-8621-integration-tests/memory-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/memory/MemoryQuotaMailingTest.java, server/protocols/jmap-rfc-8621-integration-tests/memory-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/memory/MemoryVacationIntegrationTest.java, server/protocols/jmap-rfc-8621-integration-tests/memory-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/memory/MemoryVacationRelayIntegrationTest.java, server/protocols/jmap-rfc-8621-integration-tests/memory-jmap-rfc-8621-integration-tests/src/test/resources/imapserver.xml, server/protocols/jmap-rfc-8621-integration-tests/memory-jmap-rfc-8621-integration-tests/src/test/resources/listeners.xml
=> JAMES-4025 Rewrite some tests of JMAP draft on top of JMAP RFC-8621

mailbox/opensearch/src/test/java/org/apache/james/mailbox/opensearch/OpenSearchIntegrationTest.java
On a production system we encountered a JMAP query for which the clause count of OpenSearch (- 1024) was exceeded. This commit makes sure that it is not linked to the overall right filtering strategy pushing the mailboxes to search in onto the search query.
=> [FIX] Multi-mailbox search should not fail when user has many mailboxes

server/data/data-api/src/main/java/org/apache/james/droplists/api/DropListEntry.java, server/data/data-api/src/test/java/org/apache/james/droplists/api/DropListContract.java, server/data/data-api/src/test/java/org/apache/james/droplists/api/DropListEntryTest.java, server/data/data-memory/src/main/java/org/apache/james/droplists/memory/MemoryDropList.java, server/data/data-memory/src/test/java/org/apache/james/droplists/memory/MemoryDropListTest.java
[https://issues.apache.org/jira/projects/JAMES/issues/JAMES-3946](https://issues.apache.org/jira/projects/JAMES/issues/JAMES-3946?filter=allopenissues)
=> JAMES-3946 add a memory implementation of the DropList

event-bus/cassandra/src/main/java/org/apache/james/events/CassandraEventDeadLetters.java, event-bus/cassandra/src/main/java/org/apache/james/events/CassandraEventDeadLettersDAO.java
Make it public for easy create manually by the constructor via Guice
=> JAMES-3498 Modify the access for CassandraEventDeadLetters, CassandraEventDeadLettersDAO

backends-common/rabbitmq/src/test/java/org/apache/james/backends/rabbitmq/RabbitMQConfigurationTest.java
Actually, we supported the case with the `hosts` configuration.
=> JAMES-4031 Add configuration tests for RabbitMQ cluster usage

server/mailet/mailetcontainer-impl/src/main/java/org/apache/james/mailetcontainer/impl/JamesMailetContext.java, server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/RecipientRewriteTableProcessor.java, server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/remote/delivery/Bouncer.java, server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/remote/delivery/DeliveryRunnable.java, server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/remote/delivery/MailDelivrer.java
This results on a nack of the underlying mailqueue, thus not loosing the email
=> JAMES-4030 Carry over Bouncer exceptions

event-bus/distributed/src/main/java/org/apache/james/events/GroupRegistrationHandler.java
And be initialized in the constructor.
Given the `RabbitMQEventBus` beans are limited and the group use case is soon or late being used, we do not need lazy initialization for the scheduler IMO.
Otherwise, James could restart the `GroupRegistrationHandler` while it is not started yet (e.g. a RabbitMQ node is down before any group listener is registered) which leads to `java.lang.NullPointerException: scheduler` and fail the `RabbitEventBusConsumerHealthCheck`.
=> [FIX] GroupRegistrationHandler's scheduler should be final

backends-common/rabbitmq/src/main/java/org/apache/james/backends/rabbitmq/SimpleConnectionPool.java
Subscribe directly `SimpleConnectionPool::getOpenConnection` on(ReactorUtils.BLOCKING_CALL_WRAPPER) to better avoid blocking calls in other places.
=> JAMES-3117 SimpleConnectionPool::getOpenConnection was blocking on RabbitMQHealthCheck parallel thread

backends-common/rabbitmq/src/main/java/org/apache/james/backends/rabbitmq/Constants.java, backends-common/rabbitmq/src/main/java/org/apache/james/backends/rabbitmq/QueueArguments.java, backends-common/rabbitmq/src/main/java/org/apache/james/backends/rabbitmq/RabbitMQConfiguration.java, backends-common/rabbitmq/src/test/java/org/apache/james/backends/rabbitmq/ConstantsTest.java, backends-common/rabbitmq/src/test/java/org/apache/james/backends/rabbitmq/DockerClusterRabbitMQExtension.java, backends-common/rabbitmq/src/test/java/org/apache/james/backends/rabbitmq/DockerRabbitMQ.java, backends-common/rabbitmq/src/test/java/org/apache/james/backends/rabbitmq/RabbitMQClusterTest.java, backends-common/rabbitmq/src/test/java/org/apache/james/backends/rabbitmq/RabbitMQTest.java, event-bus/distributed/src/main/java/org/apache/james/events/EventDispatcher.java, event-bus/distributed/src/main/java/org/apache/james/events/GroupConsumerRetry.java, event-bus/distributed/src/main/java/org/apache/james/events/GroupRegistration.java, event-bus/distributed/src/main/java/org/apache/james/events/GroupRegistrationHandler.java, event-bus/distributed/src/main/java/org/apache/james/events/KeyReconnectionHandler.java, event-bus/distributed/src/main/java/org/apache/james/events/KeyRegistrationHandler.java, event-bus/distributed/src/test/java/org/apache/james/events/RabbitMQEventBusUsingQuorumQueueTest.java, server/apps/distributed-app/docs/modules/ROOT/pages/configure/rabbitmq.adoc, server/apps/distributed-app/sample-configuration/rabbitmq.properties, server/apps/distributed-pop3-app/sample-configuration/rabbitmq.properties, server/container/guice/distributed/src/main/java/org/apache/james/modules/mailbox/DistributedDeletedMessageVaultDeletionCallback.java, server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/RabbitMQMailQueueFactory.java, server/task/task-distributed/src/main/java/org/apache/james/task/eventsourcing/distributed/RabbitMQTerminationSubscriber.java, server/task/task-distributed/src/main/java/org/apache/james/task/eventsourcing/distributed/RabbitMQWorkQueue.java, server/task/task-distributed/src/main/java/org/apache/james/task/eventsourcing/distributed/TerminationReconnectionHandler.java, server/task/task-distributed/src/test/java/org/apache/james/task/eventsourcing/distributed/DistributedTaskManagerWithQuorumQueueTest.java, src/site/xdoc/server/config-rabbitmq.xml, upgrade-instructions.md
continuation of https://github.com/apache/james-project/pull/2065
=> JAMES-4027 Make all queues on Rabbitmq quorum queue when option enabled

server/data/data-api/src/test/java/org/apache/james/droplists/api/DropListContract.java, server/data/data-cassandra/src/main/java/org/apache/james/droplists/cassandra/CassandraDropListDAO.java, server/data/data-memory/src/main/java/org/apache/james/droplists/memory/MemoryDropList.java, server/mailet/mailets/src/main/java/org/apache/james/transport/matchers/IsInDropList.java, server/mailet/mailets/src/test/java/org/apache/james/transport/matchers/IsInDropListTest.java
[https://issues.apache.org/jira/projects/JAMES/issues/JAMES-3946](https://issues.apache.org/jira/projects/JAMES/issues/JAMES-3946?filter=allopenissues)
=> JAMES-3946 add the IsInDropList matcher

server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/Method.scala
IMO we should not log user input errors.
Or @chibenwa do you want to keep the `RequestTooLargeException` log for example?
=> [FIX] JMAP: Only log ERROR for `serverFail` errors

server/protocols/webadmin/webadmin-mailrepository/src/main/java/org/apache/james/webadmin/routes/MailRepositoriesRoutes.java, server/protocols/webadmin/webadmin-mailrepository/src/main/java/org/apache/james/webadmin/service/ReprocessingAllMailsTaskAdditionalInformationDTO.java, server/protocols/webadmin/webadmin-mailrepository/src/main/java/org/apache/james/webadmin/service/ReprocessingAllMailsTaskDTO.java, server/protocols/webadmin/webadmin-mailrepository/src/main/java/org/apache/james/webadmin/service/ReprocessingOneMailTaskAdditionalInformationDTO.java, server/protocols/webadmin/webadmin-mailrepository/src/main/java/org/apache/james/webadmin/service/ReprocessingOneMailTaskDTO.java, server/protocols/webadmin/webadmin-mailrepository/src/main/java/org/apache/james/webadmin/service/ReprocessingService.java, server/protocols/webadmin/webadmin-mailrepository/src/test/java/org/apache/james/webadmin/routes/MailRepositoriesRoutesTest.java
Why: A user went overquota, and his mail were stored in overquota mail repository.
I am asked to reprocess mails for this user but would ideally like not to touch the 20.000 overquota mails belonging to other people.
=> [ENHANCEMENT] Reprocess for a specific recipient

backends-common/rabbitmq/src/main/java/org/apache/james/backends/rabbitmq/ReactorRabbitMQChannelPool.java, backends-common/rabbitmq/src/test/java/org/apache/james/backends/rabbitmq/RabbitMQExtension.java, backends-common/rabbitmq/src/test/java/org/apache/james/backends/rabbitmq/ReactorRabbitMQChannelPoolTest.java, mailet/amqp/src/main/java/org/apache/james/transport/mailets/AmqpForwardAttribute.java, mpt/impl/imap-mailbox/rabbitmq/src/test/java/org/apache/james/mpt/imapmailbox/rabbitmq/host/RabbitMQEventBusHostSystem.java, server/container/guice/queue/rabbitmq/src/main/java/org/apache/james/modules/queue/rabbitmq/RabbitMQModule.java
Will ease channel pool sizing as well as debugging of RabbitMQ channelPool related errors.
=> [ENHANCEMENT] Metrics for rabbitmq channel pool

protocols/netty/src/main/java/org/apache/james/protocols/netty/AbstractChannelPipelineFactory.java
Would benefit SMTP heavy and POP3 heavy workloads.
=> JAMES-4023 Avoid blocking the SMTP Netty event loop

backends-common/redis/src/main/java/org/apache/james/backends/redis/RedisConfiguration.scala, backends-common/redis/src/main/java/org/apache/james/backends/redis/RedisHealthCheck.scala, backends-common/redis/src/test/java/org/apache/james/backends/redis/RedisConfigurationTest.scala, backends-common/redis/src/test/java/org/apache/james/backends/redis/RedisExtension.java, backends-common/redis/src/test/java/org/apache/james/backends/redis/RedisMasterReplicaExtension.java, backends-common/redis/src/test/java/org/apache/james/backends/redis/RedisMasterReplicaHealthCheckTest.scala, backends-common/redis/src/test/java/org/apache/james/backends/redis/RedisStandaloneHealthCheckTest.scala, server/apps/distributed-app/docs/modules/ROOT/pages/configure/redis.adoc, server/mailet/rate-limiter-redis/README.adoc, server/mailet/rate-limiter-redis/redis.properties, server/mailet/rate-limiter-redis/src/main/java/org/apache/james/rate/limiter/redis/RedisMasterReplicaRateLimiterFactory.java, server/mailet/rate-limiter-redis/src/main/scala/org/apache/james/rate/limiter/redis/RedisRateLimiter.scala, server/mailet/rate-limiter-redis/src/test/java/org/apache/james/rate/limiter/RedisRateLimiterTest.scala, server/mailet/rate-limiter-redis/src/test/java/org/apache/james/rate/limiter/RedisRateLimiterWithMasterReplicaTopologyTest.scala, upgrade-instructions.md
https://github.com/linagora/james-project/issues/5171
=> JAMES-3693 Update redis config to support master-replica topology

backends-common/rabbitmq/src/main/java/org/apache/james/backends/rabbitmq/QueueArguments.java, backends-common/rabbitmq/src/main/java/org/apache/james/backends/rabbitmq/RabbitMQConfiguration.java, backends-common/rabbitmq/src/main/java/org/apache/james/backends/rabbitmq/ReactorRabbitMQChannelPool.java, backends-common/rabbitmq/src/test/java/org/apache/james/backends/rabbitmq/RabbitMQConfigurationTest.java, event-bus/api/src/main/java/org/apache/james/events/EventBus.java, event-bus/distributed/src/main/java/org/apache/james/events/GroupRegistrationHandler.java, event-bus/distributed/src/main/java/org/apache/james/events/ListenerExecutor.java, event-bus/distributed/src/main/java/org/apache/james/events/NamingStrategy.java, event-bus/distributed/src/main/java/org/apache/james/events/RabbitEventBusConsumerHealthCheck.java, event-bus/distributed/src/main/java/org/apache/james/events/RabbitMQEventBus.java, event-bus/in-vm/src/main/java/org/apache/james/events/InVMEventBus.java, server/apps/distributed-app/docs/modules/ROOT/pages/configure/rabbitmq.adoc, server/apps/distributed-app/sample-configuration/rabbitmq.properties, server/container/guice/distributed/src/main/java/org/apache/james/modules/DistributedTaskManagerModule.java, server/container/guice/distributed/src/main/java/org/apache/james/modules/event/JMAPEventBusModule.java, server/container/guice/distributed/src/main/java/org/apache/james/modules/event/RabbitMQEventBusModule.java, server/container/guice/queue/rabbitmq/src/main/java/org/apache/james/modules/queue/rabbitmq/RabbitMQModule.java, server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/Dequeuer.java, server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/RabbitMQMailQueueConsumerHealthCheck.java, server/task/task-distributed/src/main/java/org/apache/james/task/eventsourcing/distributed/DistributedTaskManagerHealthCheck.java, server/task/task-distributed/src/main/java/org/apache/james/task/eventsourcing/distributed/RabbitMQWorkQueue.java, server/task/task-distributed/src/main/java/org/apache/james/task/eventsourcing/distributed/RabbitMQWorkQueueReconnectionHandler.java, server/task/task-distributed/src/test/java/org/apache/james/task/eventsourcing/distributed/RabbitMQWorkQueueTest.java, server/testing/src/main/java/org/apache/james/util/docker/Images.java, src/site/xdoc/server/config-rabbitmq.xml, upgrade-instructions.md
Just https://github.com/apache/james-project/pull/1778 for now (was busy on other things in parallel)
Need as well to backport:
- https://github.com/apache/james-project/pull/1789
- https://github.com/apache/james-project/pull/1802
At least I want to see the CI and if tests are green on what I've been doing, as I had to adapt the code on some parts to fit the backport
=> JAMES-3955 RabbitMQ works Backports [3.7.x]

backends-common/rabbitmq/src/main/java/org/apache/james/backends/rabbitmq/RabbitMQConfiguration.java, backends-common/rabbitmq/src/test/java/org/apache/james/backends/rabbitmq/DockerRabbitMQ.java, backends-common/rabbitmq/src/test/java/org/apache/james/backends/rabbitmq/RabbitMQConfigurationTest.java, event-bus/distributed/src/main/java/org/apache/james/events/EventDispatcher.java, event-bus/distributed/src/test/java/org/apache/james/events/NetworkErrorTest.java, server/apps/distributed-app/docs/modules/ROOT/pages/configure/rabbitmq.adoc, src/site/xdoc/server/config-rabbitmq.xml
Allowing for example IMAP APPEND command not to fail when RabbitMQ has issues.
=> JAMES-4033 Option to propagate event bus dispatch error

backends-common/postgres/src/main/java/org/apache/james/backends/postgres/utils/PoolBackedPostgresConnectionFactory.java, backends-common/postgres/src/test/java/org/apache/james/backends/postgres/JamesPostgresConnectionFactoryTest.java
…g set-domain command in case of empty domain
=> JAMES-2586 Update PoolBackedPostgresConnectionFactory to avoid running set-domain command in case of empty domain

src/site/xdoc/server/config-redis.xml
following the topology and `readFrom` configuration changes
=> JAMES-3693 Update config-redis.xml

server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/DownloadRoutes.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/UploadRoutes.scala
This could allow to track an error for a specific user or down to a specific blob: this could be useful for me!
=> [IMPROVMENT] JMAP upload/download with more context

server/apps/distributed-app/docs/modules/ROOT/nav.adoc, server/apps/distributed-app/docs/modules/ROOT/pages/configure/droplists.adoc, server/apps/distributed-app/docs/modules/ROOT/pages/configure/index.adoc, server/apps/distributed-app/sample-configuration/droplists.properties, server/apps/distributed-app/src/main/java/org/apache/james/CassandraRabbitMQJamesConfiguration.java, server/apps/distributed-app/src/main/java/org/apache/james/CassandraRabbitMQJamesServerMain.java, server/apps/memory-app/sample-configuration/droplists.properties, server/apps/memory-app/src/main/java/org/apache/james/MemoryJamesConfiguration.java, server/apps/memory-app/src/main/java/org/apache/james/MemoryJamesServerMain.java, server/container/guice/cassandra/src/main/java/org/apache/james/modules/data/CassandraDropListsModule.java, server/container/guice/memory/src/main/java/org/apache/james/modules/data/MemoryDropListsModule.java, server/container/guice/protocols/webadmin-data/src/main/java/org/apache/james/modules/server/DropListsRoutesModule.java
[https://issues.apache.org/jira/projects/JAMES/issues/JAMES-3946](https://issues.apache.org/jira/projects/JAMES/issues/JAMES-3946?filter=allopenissues)
=> JAMES-3946 DropList Cassandra and Memory app

mailbox/jpa/src/main/java/org/apache/james/mailbox/jpa/mail/model/JPAMailbox.java, mailbox/jpa/src/main/java/org/apache/james/mailbox/jpa/mail/model/JPAMailboxAnnotation.java, mailbox/jpa/src/main/java/org/apache/james/mailbox/jpa/user/model/JPASubscription.java, server/data/data-jpa/src/main/java/org/apache/james/domainlist/jpa/model/JPADomain.java, server/data/data-jpa/src/main/java/org/apache/james/mailrepository/jpa/model/JPAMail.java, server/data/data-jpa/src/main/java/org/apache/james/mailrepository/jpa/model/JPAUrl.java, server/data/data-jpa/src/main/java/org/apache/james/rrt/jpa/model/JPARecipientRewrite.java, server/data/data-jpa/src/main/java/org/apache/james/sieve/jpa/model/JPASieveQuota.java, server/data/data-jpa/src/main/java/org/apache/james/sieve/jpa/model/JPASieveScript.java, server/data/data-jpa/src/main/java/org/apache/james/user/jpa/model/JPAUser.java
@NamedQueries has been removed.
[Repeating Annotations](https://docs.oracle.com/javase/tutorial/java/annotations/repeating.html)
=> [CLEAN CODE] Annotation repetitions should not be wrapped

server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/DownloadRoutes.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/SessionRoutes.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/UploadRoutes.scala
=> [REFACTORING] JMAP: Problem details already entails the status code

third-party/rspamd/src/test/java/org/apache/james/rspamd/DockerRspamdExtensionTest.java, third-party/rspamd/src/test/resources/mail/spam/phishing.eml
Phishing is enabled by default.
=> JAMES-3775 Phishing test for Rspamd

backends-common/rabbitmq/src/main/java/org/apache/james/backends/rabbitmq/RabbitMQManagementAPI.java
Recently when startup james, 
I got an error
```
{
"timestamp": "2024-07-15T03:48:27.465Z",
"level": "ERROR",
"thread": "main",
"logger": "org.apache.james.GuiceJamesServer",
"message": "Fatal error while starting James",
"context": "default",
"exception": "com.google.inject.ProvisionException: Unable to provision, see the following errors:\n\n1) [Guice/ErrorInjectingConstructor]: RuntimeException: Non recoverable exception status: 404\n  at TransferEmailRoutes.<init>(TransferEmailRoutes.java:50)\n  while locating TransferEmailRoutes\n  while locating Routes annotated with @Element(setName=,uniqueId=408, type=MULTIBINDER, keyType=)\n  at WebAdminServerModule.provideRoutes(WebAdminServerModule.java:112)\n      \\_ for 3rd parameter routesList\n  at …
```
=> RabbitMQManagementAPI - log detail response from rabbitMQ when error

server/container/guice/data-ldap/src/main/java/org/apache/james/data/LdapUsersRepositoryModule.java, server/data/data-ldap/src/main/java/org/apache/james/user/ldap/ReadOnlyLDAPUsersDAO.java, server/data/data-ldap/src/main/java/org/apache/james/user/ldap/ReadOnlyUsersLDAPRepository.java, server/data/data-ldap/src/test/java/org/apache/james/user/ldap/LdapHealthCheckTest.java, server/data/data-ldap/src/test/java/org/apache/james/user/ldap/ReadOnlyUsersLDAPRepositoryEmptyListTest.java, server/data/data-ldap/src/test/java/org/apache/james/user/ldap/ReadOnlyUsersLDAPRepositoryInvalidDnTest.java, server/data/data-ldap/src/test/java/org/apache/james/user/ldap/ReadOnlyUsersLDAPRepositoryTest.java, server/data/data-ldap/src/test/java/org/apache/james/user/ldap/ReadOnlyUsersLDAPRepositoryWithLDAPFailoverTest.java, server/data/data-ldap/src/test/java/org/apache/james/user/ldap/ReadOnlyUsersLDAPRepositoryWithLocalPartAsLoginNameTest.java, server/mailet/ldap/src/main/java/org/apache/james/transport/matchers/SenderHasLDAPAttribute.java, server/mailet/ldap/src/main/java/org/apache/james/transport/matchers/SenderIsInLDAPGroup.java
- Static initialization
- It allows operating on a signle LDAP pool when using LDAP matchers,...
=> [IMPROVEMENT] Use a single LDAP pool accross James

event-bus/distributed/src/test/java/org/apache/james/events/RabbitMQEventBusTest.java
- `eventBus.register(listener, KEY_1)` is a publisher, we need to subscribe it
- resolve deprecated method
=> JAMES-3747 Fixup RabbitMQEventBusTest

docs/modules/servers/partials/LDAPMatchers.adoc, server/mailet/ldap/src/main/java/org/apache/james/transport/matchers/CacheSettings.java, server/mailet/ldap/src/main/java/org/apache/james/transport/matchers/HasLDAPAttribute.java, server/mailet/ldap/src/main/java/org/apache/james/transport/matchers/SenderHasLDAPAttribute.java, server/mailet/ldap/src/test/java/org/apache/james/transport/matchers/CacheSettingsTest.java, server/mailet/ldap/src/test/java/org/apache/james/transport/matchers/HasLDAPAttributeTest.java, server/mailet/ldap/src/test/java/org/apache/james/transport/matchers/SenderHasLDAPAttributeTest.java
(help welcome to address review comments if needed)
=> JAMES-4044 Add a cache for LDAP attribute matchers

docs/modules/servers/pages/distributed/architecture/implemented-standards.adoc, docs/modules/servers/pages/distributed/configure/smtp-hooks.adoc, docs/modules/servers/partials/RemoteDelivery.adoc, protocols/smtp/src/main/java/org/apache/james/protocols/smtp/SMTPSession.java, protocols/smtp/src/main/java/org/apache/james/protocols/smtp/core/ReceivedDataLineFilter.java, server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/RemoteDelivery.java, server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/remote/delivery/DeliveryRunnable.java, server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/remote/delivery/MailDelivrerToHost.java, server/mailet/mailets/src/test/java/org/apache/james/transport/mailets/remote/delivery/DeliveryRunnableTest.java, server/mailet/mailets/src/test/java/org/apache/james/transport/mailets/remote/delivery/RemoteDeliveryTest.java, server/mailet/mock-smtp-server/src/test/java/org/apache/james/mock/smtp/server/MockSMTPServerTest.java, server/mailet/remote-delivery-integration-testing/src/test/java/org/apache/james/smtp/priority/SmtpMtPriorityRelayTest.java, server/protocols/protocols-smtp/src/main/java/org/apache/james/smtpserver/priority/SmtpMtPriorityEhloHook.java, server/protocols/protocols-smtp/src/main/java/org/apache/james/smtpserver/priority/SmtpMtPriorityMessageHook.java, server/protocols/protocols-smtp/src/main/java/org/apache/james/smtpserver/priority/SmtpMtPriorityParameterHook.java, server/protocols/protocols-smtp/src/main/java/org/apache/james/smtpserver/priority/SmtpMtPriorityParameters.java, server/protocols/protocols-smtp/src/test/java/org/apache/james/smtpserver/SmtpMtPriorityMessageHookTest.java, server/protocols/protocols-smtp/src/test/java/org/apache/james/smtpserver/priority/SmtpMtPriorityParametersTest.java, server/protocols/protocols-smtp/src/test/resources/smtpserver-mtPriority.xml, src/site/resources/server/rfclist/smtp/rfc6710.txt, src/site/xdoc/server/rfcs.xml
[JAMES-3824](https://issues.apache.org/jira/projects/JAMES/issues/JAMES-3824?filter=allopenissues)
=> JAMES-3824 SMTP Extension for Message Transfer Priorities

protocols/netty/pom.xml, protocols/netty/src/main/java/org/apache/james/protocols/netty/AbstractAsyncServer.java, server/container/guice/common/src/main/java/org/apache/james/GuiceJamesServer.java, server/container/guice/onami/pom.xml, server/container/guice/onami/src/main/java/org/apache/james/onami/lifecycle/DefaultStager.java, server/container/guice/onami/src/main/java/org/apache/james/onami/lifecycle/StageableMethod.java, server/protocols/protocols-library/src/main/java/org/apache/james/protocols/lib/ProtocolHandlerChainImpl.java, server/protocols/protocols-library/src/main/java/org/apache/james/protocols/lib/netty/AbstractServerFactory.java
(followup to: https://github.com/apache/james-project/pull/2373#issuecomment-2295396500) 
Initial work on making shutdown speed little better, main changes:
* make shutdown parallel
* decrease netty grace period (either to be reversed or made configurable)
(added "cosmetics" with information bout startup and shutdown time)
=> Improving James shutdown speed

mailet/crypto/pom.xml, mailet/crypto/src/main/java/org/apache/james/transport/KeyStoreHolderConfiguration.java, mailet/crypto/src/main/java/org/apache/james/transport/KeyStoreHolderFactory.java, mailet/crypto/src/main/java/org/apache/james/transport/PemReader.java, mailet/crypto/src/main/java/org/apache/james/transport/mailets/SMIMECheckSignature.java, server/mailet/integration-testing/src/main/java/org/apache/james/mailets/TemporaryJamesServer.java, server/mailet/integration-testing/src/test/java/org/apache/james/mailets/crypto/SMIMECheckSignatureWithKeyStoreFileIntegrationTest.java, server/mailet/integration-testing/src/test/java/org/apache/james/mailets/crypto/SMIMECheckSignatureWithPemFileIntegrationTest.java
=> JAMES-4063 Update SMIMECheckSignature to use Filesystem to load crypto materials

docs/modules/servers/pages/distributed/configure/vault.adoc, server/apps/cassandra-app/sample-configuration/deletedMessageVault.properties, server/apps/distributed-app/sample-configuration/deletedMessageVault.properties, server/apps/distributed-pop3-app/sample-configuration/deletedMessageVault.properties, src/site/xdoc/server/config-vault.xml
Feel like was missing. If somebody wants to suggest more details...
=> Add missing doc and options for the deleted message vault

server/mailet/integration-testing/src/test/java/org/apache/james/smtp/SmtpIdentityVerificationTest.java, server/protocols/protocols-smtp/src/main/java/org/apache/james/smtpserver/SenderAuthIdentifyVerificationHook.java
Dropping some production messages because of this.
Be strict about what we send but relaxed about what we receive.
Would fix this regression:
=> JAMES-4034 Fix receival of external badly formated From message

docs/modules/servers/partials/operate/webadmin.adoc, src/site/markdown/server/manage-webadmin.md
- Change HTTP code: 500 ->  503
=> JAMES-4070 Implement query param to return 503 code if degraded - fixup document

core/src/main/java/org/apache/james/core/MailAddress.java, core/src/main/java/org/apache/james/core/Username.java, core/src/test/java/org/apache/james/core/MailAddressTest.java, docs/modules/servers/partials/SubAddressing.adoc, docs/modules/servers/partials/configure/mailets.adoc, mailbox/api/src/main/java/org/apache/james/mailbox/acl/MailboxACLResolver.java, mailbox/api/src/main/java/org/apache/james/mailbox/acl/UnionMailboxACLResolver.java, mailbox/api/src/main/java/org/apache/james/mailbox/model/MailboxACL.java, mailbox/api/src/test/java/org/apache/james/mailbox/acl/UnionMailboxACLResolverTest.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreRightManager.java, server/container/guice/mailbox/src/main/java/org/apache/james/modules/ACLProbeImpl.java, server/data/data-api/src/main/java/org/apache/james/user/api/UsersRepository.java, server/data/data-library/src/main/java/org/apache/james/user/lib/UsersRepositoryImpl.java, server/data/data-library/src/test/java/org/apache/james/user/lib/UsersRepositoryContract.java, server/mailet/integration-testing/src/test/java/org/apache/james/mailets/SubAddressingTest.java, server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/SubAddressing.java, server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/redirect/SpecialAddress.java, server/mailet/mailets/src/test/java/org/apache/james/transport/mailets/SubAddressingTest.java, server/mailet/mailets/src/test/java/org/apache/james/transport/mailets/WithStorageDirectiveTest.java, server/protocols/protocols-smtp/src/test/java/org/apache/james/smtpserver/ValidRcptHandlerTest.java
i am working on implementing sub-addressing for apache james.
for now it works but WITHOUT any right management.
this is still work in progress.
any comment is welcome :)
=> James 3945

mailbox/api/src/main/java/org/apache/james/mailbox/acl/UnionMailboxACLResolver.java, mailbox/api/src/main/java/org/apache/james/mailbox/model/MailboxACL.java, mailbox/api/src/test/java/org/apache/james/mailbox/acl/UnionMailboxACLResolverTest.java, mailbox/api/src/test/java/org/apache/james/mailbox/model/MailboxACLEntryKeyTest.java, mpt/impl/imap-mailbox/core/src/main/resources/org/apache/james/imap/scripts/Rights.test, mpt/impl/imap-mailbox/jpa/src/test/java/org/apache/james/mpt/imapmailbox/jpa/JpaAuthenticatedStateTest.java, server/mailet/integration-testing/src/main/java/org/apache/james/mailets/configuration/Constants.java, server/mailet/integration-testing/src/test/java/org/apache/james/mailets/SubAddressingTest.java, server/mailet/mailets/src/test/java/org/apache/james/transport/mailets/SubAddressingTest.java
i am working on implementing sub-addressing for apache james.
for now, i am trying to make right positioning work with IMAP.
the final goal is to make it work for JMAP !
this is still work in progress.
any comment is welcome :)
=> James 3945 rights positioning for subaddressing

server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/WebSocketContract.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/WebSocketRoutes.scala
JMAP Websocket server should return the header following specs:
```
The reply from the server MUST also contain a corresponding "Sec-WebSocket-Protocol" header field with a value of "jmap" in order for a JMAP subprotocol connection to be established.
````
cf: https://www.rfc-editor.org/rfc/rfc8887.html
Otherwise, Postman and browsers would complain.
=> [FIX] WebSocket should return `Sec-WebSocket-Protocol: jmap` response header

docs/modules/servers/partials/configure/tika.adoc, mailbox/opensearch/src/test/java/org/apache/james/mailbox/opensearch/json/MessageToOpenSearchJsonTest.java, mailbox/store/src/test/resources/eml/nonTextualWithoutAttachmentTextContent.json, mailbox/tika/src/main/java/org/apache/james/mailbox/tika/TikaHttpClientImpl.java, mailbox/tika/src/test/java/org/apache/james/mailbox/tika/TikaContainer.java, mailbox/tika/src/test/java/org/apache/james/mailbox/tika/TikaTextExtractorTest.java
A few improvements for Tika implementation.
=> JAMES-2456 Add a reactor timeout for Tika requests

mailbox/tika/src/test/java/org/apache/james/mailbox/tika/TikaTextExtractorTest.java
=> JAMES-2456 TikaTextExtractorTest: fix checkstyle

mailbox/api/src/main/java/org/apache/james/mailbox/searchhighligt/SearchHighlighter.java, mailbox/api/src/main/java/org/apache/james/mailbox/searchhighligt/SearchHighlighterConfiguration.java, mailbox/api/src/main/java/org/apache/james/mailbox/searchhighligt/SearchSnippet.java, mailbox/lucene/pom.xml, mailbox/lucene/src/main/java/org/apache/james/mailbox/lucene/search/LuceneMemorySearchHighlighter.java, mailbox/lucene/src/main/java/org/apache/james/mailbox/lucene/search/LuceneMessageSearchIndex.java, mailbox/lucene/src/test/java/org/apache/james/mailbox/lucene/search/LuceneMemorySearchHighLightTest.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMailboxManager.java
jira https://issues.apache.org/jira/browse/JAMES-4077
=> JAMES-4077 [SearchSnippet] Search Highlight - Lucene memory implementation

mailbox/api/src/test/java/org/apache/james/mailbox/searchhighligt/SearchHighLighterContract.java, mailbox/lucene/src/main/java/org/apache/james/mailbox/lucene/search/LuceneSearchHighlighter.java, mailbox/lucene/src/test/java/org/apache/james/mailbox/lucene/search/LuceneFSSearchHighLighterTest.java, mailbox/lucene/src/test/java/org/apache/james/mailbox/lucene/search/LuceneMemorySearchHighLighterTest.java
The `LuceneMemorySearchHighlighter` only use lucene highlight api, it's nothing special just for memory.
=> JAMES-4077 Renaming LuceneMemorySearchHighlighter -> LuceneSearchHighlighter & add new Lucene File system test

backends-common/opensearch/src/main/java/org/apache/james/backends/opensearch/search/ScrolledSearch.java, mailbox/api/src/test/java/org/apache/james/mailbox/searchhighligt/SearchHighLighterContract.java, mailbox/lucene/src/main/java/org/apache/james/mailbox/lucene/search/LuceneSearchHighlighter.java, mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/events/OpenSearchListeningMessageSearchIndex.java, mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/json/JsonMessageConstants.java, mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/search/OpenSearchSearchHighlighter.java, mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/search/OpenSearchSearcher.java, mailbox/opensearch/src/test/java/org/apache/james/mailbox/opensearch/search/OpenSearchSearchHighlighterTest.java
jira https://issues.apache.org/jira/browse/JAMES-4077
resolve https://github.com/linagora/james-project/issues/5253
=> JAMES-4077 [SearchSnippet] Highlight OpenSearch implementation

server/data/data-cassandra/src/main/java/org/apache/james/rrt/cassandra/CassandraRecipientRewriteTable.java, server/data/data-file/src/main/java/org/apache/james/rrt/file/XMLRecipientRewriteTable.java, server/data/data-file/src/test/java/org/apache/james/rrt/file/XMLRecipientRewriteTableTest.java, server/data/data-jpa/src/main/java/org/apache/james/rrt/jpa/JPARecipientRewriteTable.java, server/data/data-library/src/main/java/org/apache/james/rrt/lib/AbstractRecipientRewriteTable.java, server/data/data-library/src/test/java/org/apache/james/rrt/lib/RecipientRewriteTableContract.java, server/data/data-memory/src/main/java/org/apache/james/rrt/memory/MemoryRecipientRewriteTable.java
Plus two rafactorings to simplify things.
=> JAMES-4079 RecipientRewriteTable adds duplicate mapping

protocols/smtp/src/main/java/org/apache/james/protocols/smtp/core/fastfail/MaxRcptHandler.java, server/apps/memory-app/src/test/java/org/apache/james/DKIMHookIntegrationTest.java, server/mailet/integration-testing/src/main/java/org/apache/james/mailets/configuration/SmtpConfiguration.java, server/mailet/integration-testing/src/main/resources/smtpserver.xml, server/mailet/integration-testing/src/test/java/org/apache/james/mailets/configuration/SmtpConfigurationTest.java, server/mailet/integration-testing/src/test/java/org/apache/james/smtp/SmtpMaxRcptHandlerTest.java, server/protocols/protocols-smtp/src/main/java/org/apache/james/smtpserver/fastfail/MaxRcptHandler.java
i am tackling [this issue](https://github.com/linagora/james-project/issues/5286)
=> [ISSUE-5286]  Integration tests for MaxRcptHandler

docs/modules/servers/partials/configure/jmap.adoc, examples/oidc/apisix/conf/apisix.yaml, examples/oidc/docker-compose.yml, examples/oidc/james/jmap.properties, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/custom/authentication/strategy/ModularizeJmapRFC8621AuthenticationStrategyContract.java, server/protocols/jmap/pom.xml, server/protocols/jmap/src/main/java/org/apache/james/jmap/http/XUserAuthenticationStrategy.java, src/site/xdoc/server/config-jmap.xml
resolve https://github.com/linagora/james-project/issues/5267
=> JAMES-3680 XUserAuthenticationStrategy support secret checking (safer)

docs/modules/servers/partials/configure/droplists.adoc, docs/modules/servers/partials/operate/cli.adoc, docs/modules/servers/partials/operate/webadmin.adoc, server/apps/cli-integration-tests/pom.xml, server/apps/cli-integration-tests/src/test/java/org/apache/james/cli/DropListCommandsIntegrationTest.java, server/apps/cli/src/main/java/org/apache/james/cli/ServerCmd.java, server/apps/cli/src/main/java/org/apache/james/cli/probe/impl/JmxDataProbe.java, server/apps/cli/src/main/java/org/apache/james/cli/probe/impl/JmxDropListProbe.java, server/apps/cli/src/main/java/org/apache/james/cli/type/CmdType.java, server/apps/cli/src/test/java/org/apache/james/cli/ServerCmdTest.java, server/apps/cli/src/test/java/org/apache/james/cli/type/CmdTypeTest.java, server/container/guice/cassandra/src/main/java/org/apache/james/modules/data/CassandraDropListsModule.java, server/container/guice/common/src/main/java/org/apache/james/utils/DropListProbeImpl.java, server/container/guice/jmx/src/main/java/org/apache/james/modules/server/JMXServerModule.java, server/container/guice/jpa-common/src/main/java/org/apache/james/modules/data/JPADropListsModule.java, server/container/guice/memory/src/main/java/org/apache/james/modules/data/MemoryDropListsModule.java, server/data/data-api/src/main/java/org/apache/james/droplists/api/DropListEntry.java, server/data/data-api/src/main/java/org/apache/james/droplists/api/DropListManagementMBean.java, server/data/data-api/src/main/java/org/apache/james/probe/DropListProbe.java, server/data/data-library/src/main/java/org/apache/james/droplist/lib/DropListManagement.java, src/site/markdown/server/manage-cli.md, src/site/markdown/server/manage-webadmin.md
Hi everyone! I decided to add additional functionality for managing Droplists using the CLI. Also minor refactoring and documentation additions.
=> [IMPROVEMENT] Managing DropLists via CLI

server/blob/blob-s3/src/test/java/org/apache/james/blob/objectstorage/aws/S3MinioTest.java
continue of pr https://github.com/apache/james-project/pull/1981/files
=> JAMES-3982 Upgrade MinIO image tag for tests

server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/Dequeuer.java
Create a bad payload and post it to the spool mail queue directly via rabbit
Then it would trigger an exception, propagated onto rabbitmq driver
The message is then unhandled and unacked
Until the timeout is reach to which point customers dies
unacked message are put back to the queue and delivered again
And message get delivered in loop
=> [FIX] Prevent queue poisoning for spool

backends-common/postgres/pom.xml
Hopefully, we can remove the `.collectList() + flatMapIterables` workaround.
Let's see the build.
=> [PGSQL] Update R2DBC + JOOQ driver

server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/change/JmapEventSerializer.scala
It will help easier to read in the first time
We don't need match pattern for event class here
It already resolve in [org.apache.james.json.DTOConverter#toDTO](https://github.com/apache/james-project/blob/master/json/src/main/java/org/apache/james/json/DTOConverter.java#L53)
=> JAMES-3491 Clean code JmapEventSerializer

pom.xml
=> Bump commons-io to 2.17.0

metrics/metrics-api/src/main/java/org/apache/james/metrics/api/Metric.java, metrics/metrics-dropwizard/src/main/java/org/apache/james/metrics/dropwizard/DropWizardMetric.java, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/WebSocketRoutes.scala
- Opening connections count
- Requests throughput
=> [Metrics] Add a few Websocket metrics

mpt/impl/imap-mailbox/external-james/src/test/resources/org/apache/james/imap/scripts/ValidateDeployment.test
Fix missing update namespace test script
Ref https://github.com/apache/james-project/pull/2445/files#diff-c7df107f1d9d0b4c4080a6a883fd0bb325415eb3c7a0eb87c195ac1943dbb7b3
=> JAMES-2182 Sharing for IMAP - Fix script ValidateDeployment.test

docs/modules/servers/partials/configure/imap.adoc, mpt/impl/imap-mailbox/core/src/main/resources/org/apache/james/imap/scripts/Id.test, protocols/imap/src/main/java/org/apache/james/imap/api/ImapConfiguration.java, protocols/imap/src/main/java/org/apache/james/imap/encode/IdResponseEncoder.java, protocols/imap/src/main/java/org/apache/james/imap/message/response/IdResponse.java, protocols/imap/src/main/java/org/apache/james/imap/processor/IdProcessor.java, server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/IMAPServer.java, server/protocols/protocols-imap4/src/test/java/org/apache/james/imapserver/netty/IMAPServerTest.java, server/protocols/protocols-imap4/src/test/resources/imapServerIdCommandResponseFields.xml, src/site/xdoc/server/config-imap4.xml
ref https://www.rfc-editor.org/rfc/rfc2971.html
=> JAMES-3754 Update IMAP ID Extension - support return id fields response when configured

docs/modules/servers/partials/configure/jvm.adoc, pom.xml, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/metrics/HttpClientMetrics.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/SessionRoutes.scala, server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/routes/SessionRoutesTest.scala, server/protocols/jmap/pom.xml, server/protocols/jmap/src/main/java/org/apache/james/jmap/JMAPServer.java
- jmap.reactor.netty.http.server.connections.active
- jmap.reactor.netty.http.server.connections.total
- jmap.reactor.netty.http.server.data.received
- jmap.reactor.netty.http.server.data.sent
cf https://projectreactor.io/docs/netty/1.1.19/reference/index.html#_metrics_4
=> [Metrics] Expose a few useful Reactor Netty metrics

server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/Rights.scala
We supply right away an In VM implementation.
We can then later supply a rabbitMQ based implementation in order to support broadcast.
=> [FIX] Remove un-relevant log

core/pom.xml, core/src/main/java/org/apache/james/core/Disconnector.java, docs/modules/servers/partials/operate/webadmin.adoc, server/container/guice/protocols/imap/src/main/java/org/apache/james/modules/protocols/IMAPServerModule.java, server/container/guice/protocols/jmap/src/main/java/org/apache/james/jmap/rfc8621/RFC8621MethodsModule.java, server/container/guice/protocols/smtp/src/main/java/org/apache/james/modules/protocols/SMTPServerModule.java, server/container/guice/protocols/webadmin/src/main/java/org/apache/james/modules/server/ServerRouteModule.java, server/data/data-api/src/main/java/org/apache/james/DisconnectorNotifier.java, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/EventSourceRoutes.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/WebSocketRoutes.scala, server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/IMAPServer.java, server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/IMAPServerFactory.java, server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/ImapChannelUpstreamHandler.java, server/protocols/protocols-imap4/src/test/java/org/apache/james/imapserver/netty/IMAPServerTest.java, server/protocols/protocols-library/src/main/java/org/apache/james/protocols/lib/netty/CertificateReloadable.java, server/protocols/protocols-lmtp/src/main/java/org/apache/james/lmtpserver/netty/LMTPServer.java, server/protocols/protocols-smtp/src/main/java/org/apache/james/smtpserver/netty/SMTPChannelInboundHandler.java, server/protocols/protocols-smtp/src/main/java/org/apache/james/smtpserver/netty/SMTPServer.java, server/protocols/protocols-smtp/src/main/java/org/apache/james/smtpserver/netty/SMTPServerFactory.java, server/protocols/webadmin/webadmin-protocols/pom.xml, server/protocols/webadmin/webadmin-protocols/src/main/java/org/apache/james/protocols/webadmin/ProtocolServerRoutes.java, src/site/markdown/server/manage-webadmin.md
As an admin I want to force user deconection.
Eg in case of compromission: close all active channels (IMAP, SMTP)
=> JAMES-4090 Forced disconnection

protocols/smtp/src/main/java/org/apache/james/protocols/smtp/core/AbstractSenderAuthIdentifyVerificationHook.java, server/protocols/protocols-smtp/src/main/java/org/apache/james/smtpserver/SenderAuthIdentifyVerificationHook.java
Invaluable for debugging admin / user configuration issues. A MUST HAVE.
=> [ENHANCEMENT] Logs for sender identity verification

server/mailet/mailetcontainer-impl/src/main/java/org/apache/james/mailetcontainer/impl/CompositeProcessorImpl.java, server/mailet/mailetcontainer-impl/src/main/java/org/apache/james/mailetcontainer/impl/JamesMailSpooler.java, server/mailet/mailetcontainer-impl/src/main/java/org/apache/james/mailetcontainer/impl/MailetProcessorImpl.java, server/mailet/mailetcontainer-impl/src/main/java/org/apache/james/mailetcontainer/impl/ProcessorImpl.java, server/mailet/mailetcontainer-impl/src/test/java/org/apache/james/mailetcontainer/impl/MailetProcessorImplTest.java
I do need to investigate on production why a mail ends up in error state but I lacks logs to do so.
=> [IMPROVEMENT] Improve debug log for allowing tracing mailet container execution

docs/modules/servers/partials/RecipientCountExceeds.adoc, docs/modules/servers/partials/configure/matchers.adoc, mailet/standard/src/main/java/org/apache/james/transport/matchers/RecipientCountExceeds.java, mailet/standard/src/test/java/org/apache/james/transport/matchers/RecipientCountExceedsTest.java
Reopened to trigger CI
Already approuved twice in https://github.com/apache/james-project/pull/2529
=> [ENHANCEMENT] Provide a core RecipientCountExceeds matcher

docs/modules/servers/partials/PartHasContentType.adoc, docs/modules/servers/partials/configure/matchers.adoc, mailet/standard/src/main/java/org/apache/james/transport/matchers/AttachmentFileNameIs.java, mailet/standard/src/main/java/org/apache/james/transport/matchers/PartHasContentType.java, mailet/standard/src/main/java/org/apache/james/transport/matchers/utils/MimeWalk.java, mailet/standard/src/test/java/org/apache/james/transport/matchers/AttachmentFileNameIsTest.java, mailet/standard/src/test/java/org/apache/james/transport/matchers/PartHasContentTypeTest.java, mailet/standard/src/test/java/org/apache/james/transport/matchers/utils/MimeWalkTest.java
https://github.com/apache/james-project/pull/2530 reopened to trigger CI
Approuved by @Arsnael
=> [ENHANCEMENT] Add a PartHasContentType

server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailSubmissionSetMethod.scala, server/protocols/protocols-smtp/src/main/java/org/apache/james/smtpserver/SendMailHandler.java
This could be useful for audit purposes
as well as extracting trends / finding
offenders.
=> [ENHANCEMENT] Log size in the AuditTrail when sending an email

server/blob/blob-storage-strategy/src/main/scala/org/apache/james/server/blob/deduplication/DeDuplicationBlobStore.scala
Potentially long operations...
To be validated by performance tests.
Cf https://github.com/apache/james-project/pull/2540
Cc @vttranlina
=> [FIX] Run blobIdProvider out of driver threads

server/container/guice/distributed/src/main/java/org/apache/james/modules/mailbox/DeletedMessageVaultWorkQueueReconnectionHandler.java, server/container/guice/distributed/src/main/java/org/apache/james/modules/mailbox/DistributedDeletedMessageVaultDeletionCallback.java, server/container/guice/distributed/src/main/java/org/apache/james/modules/mailbox/DistributedDeletedMessageVaultModule.java, server/task/task-distributed/src/main/java/org/apache/james/task/eventsourcing/distributed/TerminationReconnectionHandler.java
So the consumer for deleted message vault work queue could reconnect if needed.
=> JAMES-3605 Implement DeletedMessageVaultWorkQueueReconnectionHandler

server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/change/StateChangeListener.scala, server/task/task-distributed/src/main/java/org/apache/james/task/eventsourcing/distributed/RabbitMQTerminationSubscriber.java
Otherwize:
```
{
"timestamp": "2024-12-06T07:45:29.803Z",
"level": "ERROR",
"thread": "s1-io-3",
"mdc": {
"eventId": "ac688927-c5f7-47d3-832b-6805caf147ea",
"eventClass": "org.apache.james.jmap.change.StateChangeEvent",
"user": "hakurreemun@govmu.org",
"registrationKeys": "[AccountIdRegistrationKey(org.apache.james.jmap.api.model.AccountId@9171bb2e)]"
},
"logger": "org.apache.james.events.TMailEventDispatcher",
"message": "Exception happens when dispatching event",
"context": "default",
"exception": "reactor.core.publisher.Sinks$EmissionException: Spec. Rule 1.3 - onSubscribe, onNext, onError and onComplete signaled to a Subscriber MUST be signaled serially.\n\tat reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:56)\n\tat …
```
=> [FIX] Prevent WebSocket data race

docs/modules/servers/partials/configure/jvm.adoc, server/apps/distributed-app/sample-configuration/jvm.properties, server/blob/blob-storage-strategy/src/main/scala/org/apache/james/server/blob/deduplication/DeDuplicationBlobStore.scala
=> [FIX] Run hashing on separated thread only if relevant 

third-party/rspamd/src/main/java/org/apache/james/rspamd/RspamdListener.java
In dead letter
And then 
Looking at the code we freaking load all mailbox messages at once then send them to RspamD in a single API call...
Apparently too much data to handle for RSpamd, the process got pkilled...
Maybe we can iterate over mailbox messages load their content and report it individually?
=> [FIX] RspamD for large moves

server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/WebSocketRoutes.scala
Count of connection was incremented and decremented as part of the initial HTTP exchange.
This is wrong, it needs to be managed in the socket phase.
=> [FIX] Correct websocket metrics

protocols/imap/src/main/java/org/apache/james/imap/processor/IdProcessor.java
My alternative to https://github.com/apache/james-project/pull/2554
=> [FIX] Do not record mail user agent in MDC twice

server/mailet/integration-testing/src/test/java/org/apache/james/smtp/SmtpIdentityVerificationTest.java, server/protocols/protocols-smtp/src/main/java/org/apache/james/smtpserver/SenderAuthIdentifyVerificationHook.java
=> [FIX] Improve and test SenderAuthIdentifyVerificationHook resiliency (weird inputs)

docs/modules/servers/partials/configure/jmap.adoc, server/container/guice/protocols/jmap/src/test/java/org/apache/james/modules/TestJMAPServerModule.java, server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/WebSocketWithPingIntervalContract.scala, server/protocols/jmap-rfc-8621-integration-tests/memory-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/memory/MemoryWebSocketWithPingIntervalTest.java, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/core/JmapRfc8621Configuration.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/WebSocketRoutes.scala, src/site/xdoc/server/config-jmap.xml
=> JAMES-3491 - JMAP WebSockets - support ping interval

pom.xml
Fixes:
- https://www.cve.org/CVERecord?id=CVE-2024-12798
- https://www.cve.org/CVERecord?id=CVE-2024-12801
=> [UPGRADE] Logback 1.5.12 -> 1.5.15

server/container/util/src/main/java/org/apache/james/util/ReactorUtils.java, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/DelegateSetCreatePerformer.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/DelegateSetDeletePerformer.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/DelegatedAccountDeletePerformer.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailSetDeletePerformer.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailSubmissionSetMethod.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/MailboxSetUpdatePerformer.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/JMAPApiRoutes.scala
Duplicate of https://github.com/apache/james-project/pull/2547
I noticed all builds are timeouts, with even sometimes some java heap space oom issues, but all the builds were continuously being built on the same worker (builds26). So maybe that worker has some issues.
Trying to force the build on an other worker here...
=> [ENHANCEMENT] ip and x-forwarded-for im JMAP logging context

server/mailet/mailets/src/test/java/org/apache/james/transport/mailets/SPFTest.java
In `Run Your Own Mail Server` the DOS with SPF is mentionned and I wanted to know if we are safe. It's untested but we are safe as we have a limit in the count of DNS requests per SPF lookup.
=> [ENHANCEMENT] Test SPF inifinite loops

protocols/netty/src/main/java/org/apache/james/protocols/netty/NettyProtocolTransport.java
Turn off auto-read and run it on the event loop like we do in IMAP
=> JAMES-4101 Wrap SMTp startTLS into a NETTY transaction

server/data/data-api/src/main/java/org/apache/james/DisconnectorNotifier.java, server/protocols/webadmin/webadmin-protocols/src/main/java/org/apache/james/protocols/webadmin/ProtocolServerRoutes.java
Simpler to serialize/deserialize request for implementation class
=> JAMES-4090 Refactoring the interface DisconnectorNotifier

server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/DownloadContract.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/DownloadRoutes.scala
Recommended by JMAP RFC: https://jmap.io/spec-core.html#downloading-binary-data
=> [PERF] Allow browsers to cache download blobs

server/container/guice/protocols/jmap/src/main/java/org/apache/james/jmap/rfc8621/RFC8621MethodsModule.java
Some customer relied on this feature.
=> JAMES-2586 Bind AttachmentBlobResolver

server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/UploadRoutes.scala
(Because I looked ridiculous on error management in an interoperability testing session)
=> [AERC] Interoperability: explicitly log when

pom.xml, server/container/core/pom.xml, server/container/filesystem-api/pom.xml, server/container/spring/pom.xml, server/protocols/webadmin/webadmin-core/pom.xml, server/protocols/webadmin/webadmin-core/src/main/java/org/apache/james/webadmin/WebAdminServer.java, server/protocols/webadmin/webadmin-core/src/main/java/org/apache/james/webadmin/jettyserver/EmbeddedJettyFactory.java, server/protocols/webadmin/webadmin-core/src/main/java/org/apache/james/webadmin/jettyserver/EmbeddedJettyServer.java, server/protocols/webadmin/webadmin-core/src/main/java/org/apache/james/webadmin/jettyserver/JettyHandler.java, server/protocols/webadmin/webadmin-core/src/main/java/org/apache/james/webadmin/jettyserver/JettyServer.java, server/protocols/webadmin/webadmin-core/src/main/java/org/apache/james/webadmin/jettyserver/SocketConnectorFactory.java, server/protocols/webadmin/webadmin-core/src/main/java/org/apache/james/webadmin/mdc/MDCFilter.java, server/protocols/webadmin/webadmin-data/src/main/java/org/apache/james/webadmin/routes/UserCreationRequestLogger.java, server/protocols/webadmin/webadmin-dropwizard-metrics/src/main/java/org/apache/james/webadmin/dropwizard/MetricsRoutes.java, server/protocols/webadmin/webadmin-http-client/pom.xml, server/protocols/webadmin/webadmin-http-client/src/main/java/org/apache/james/webadmin/httpclient/FeignHelper.java, server/protocols/webadmin/webadmin-http-client/src/main/java/org/apache/james/webadmin/httpclient/WebAdminHTTPClientFactory.java, server/protocols/webadmin/webadmin-mailrepository/src/main/java/org/apache/james/webadmin/routes/MailRepositoriesRoutes.java
jira: https://issues.apache.org/jira/browse/JAMES-4104
com.sparkjava:spark-core => org.zoomba-lang:spark-core
https://github.com/nmondal/spark-11
=> JAMES-4104 Migrate from unmaintained SparkJava to active fork

server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/MailboxSetMethodContract.scala, server/protocols/jmap-rfc-8621/src/main/java/org/apache/james/jmap/event/PropagateLookupRightListener.java
I encountered an issue related to applying rights.  
Given: Bob has lookup right for `mailbox1`.  
When: Bob creates `mailbox1.child1`, the 
`PropagateLookupRightListener` attempts to append the lookup right to its parent mailbox (`mailbox1`).  
This is unnecessary and even causes an error:  
**InsufficientRightsException**: *"Setting ACL is only permitted to the owner and admins of the mailbox."*  
This occurs in `org.apache.james.mailbox.store.StoreRightManager#assertHaveAccessTo` because Bob is neither the owner nor an admin of `mailbox1`.
=> [FIX] PropagateLookupRightListener: skip apply Lookup right if already applied

mailbox/store/src/main/java/org/apache/james/mailbox/store/quota/DefaultQuotaChangeNotifier.java
Update to fix the issue https://github.com/linagora/tmail-backend/pull/1526#issuecomment-2661982192 in tmail backend
=> Update DefaultQuotaChangeNotifier to use UserQuotaRootResolver instead of DefaultUserQuotaRootResolver

server/apps/postgres-app/docker-compose-distributed.yml, server/apps/postgres-app/sample-configuration/mailetcontainer.xml, server/apps/postgres-app/src/main/java/org/apache/james/PostgresJamesServerMain.java
Bunch of issues i found out and their fixes when checking community reported issues on postgres app and when I ran both single postgres docker compose and distributed one.
=> Postgres docker example fix

mailbox/postgres/src/test/java/org/apache/james/mailbox/postgres/DeleteMessageListenerTest.java, mailbox/postgres/src/test/java/org/apache/james/mailbox/postgres/DeleteMessageListenerWithRLSTest.java, mailbox/postgres/src/test/java/org/apache/james/mailbox/postgres/PostgresMailboxManagerAttachmentTest.java, mailbox/postgres/src/test/java/org/apache/james/mailbox/postgres/PostgresMailboxManagerProvider.java, mailbox/postgres/src/test/java/org/apache/james/mailbox/postgres/PostgresTestSystemFixture.java, mailbox/postgres/src/test/java/org/apache/james/mailbox/postgres/mail/PostgresAnnotationMapperRowLevelSecurityTest.java, mailbox/postgres/src/test/java/org/apache/james/mailbox/postgres/mail/PostgresMessageMapperRowLevelSecurityTest.java, mpt/impl/imap-mailbox/postgres/src/test/java/org/apache/james/mpt/imapmailbox/postgres/host/PostgresHostSystem.java
I'm not too sure, but I think some of those changes make more sense and might help making the tests more stable. Let's see with the CI
=> [Postgres] More coherence in some tests

server/container/guice/postgres-common/src/main/java/org/apache/james/modules/data/PostgresDataJmapModule.java, server/data/data-jmap-postgres/src/main/java/org/apache/james/jmap/postgres/projections/PostgresMessageFastViewProjectionDeletionCallback.java, server/protocols/jmap-rfc-8621-integration-tests/postgres-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/postgres/PostgresBase.java, server/protocols/jmap-rfc-8621-integration-tests/postgres-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/postgres/PostgresJmapPreviewTest.java
backport of https://github.com/apache/james-project/pull/2635 for postgres-app
=> [BACKPORT] PostgresMessageFastViewProjection should remove entries when delete mailbox

server/container/guice/distributed/src/main/java/org/apache/james/modules/mailbox/DistributedDeletedMessageVaultDeletionCallback.java
Otherwise, blobstore errors for example could crash the DTM consumer (while it should not!).
=> [FIX] Better error management for DeletedMessageVault consumer

server/data/data-file/src/main/java/org/apache/james/mailrepository/file/FileMailRepository.java, server/data/data-file/src/test/java/org/apache/james/mailrepository/FileMailRepositoryTest.java
CF https://issues.apache.org/jira/projects/JAMES/issues/JAMES-4115
=> JAMES-4115 FileMailRepository: drop cacheKey & refactor

.mvn/.gradle-enterprise/gradle-enterprise-workspace-id, .mvn/extensions.xml
Just making sure it there are no red flags before merging,
=> [chore] upgrades develocity extension

.mvn/.gradle-enterprise/gradle-enterprise-workspace-id, .mvn/extensions.xml
Investigating if the upgrade caused the out of heap errors on the CI
=> Revert [chore] upgrades develocity extension

pom.xml, server/dns-service/dnsservice-dnsjava/src/test/java/org/apache/james/dnsservice/dnsjava/DNSJavaServiceTest.java
fixup of https://github.com/apache/james-project/pull/2687
=> [UPGRADE] dnsjava 3.5.2 -> 3.6.0

mailet/base/src/main/java/org/apache/mailet/base/GenericMailet.java, server/container/guice/mailet/src/main/java/org/apache/james/utils/GuiceMailetLoader.java, server/container/guice/mailet/src/test/java/org/apache/james/transport/mailets/sub/ConstructorBoundTestMailet.java, server/container/guice/mailet/src/test/java/org/apache/james/utils/GuiceMailetLoaderTest.java
- allows constructor injection of the MailetConfig for mailets
- allows pre-binding of configuration in GenericMailet
=> [JAMES-4126] improve GuiceMailetLoader

mailet/api/src/main/java/org/apache/mailet/Mailet.java, mailet/base/src/main/java/org/apache/mailet/base/GenericMailet.java, server/container/guice/mailet/src/test/java/org/apache/james/transport/mailets/sub/ConstructorBoundTestMailet.java
PR stacked on https://github.com/apache/james-project/pull/2694, please review only JAMES-4127 commits
=> [JAMES-4127] add default behaviours on Mailet

server/mailet/rate-limiter-redis/src/test/java/org/apache/james/rate/limiter/KvrocksRateLimiterTest.scala, server/mailet/rate-limiter-redis/src/test/java/org/apache/james/rate/limiter/KvrocksSentinelRateLimiterTest.scala
Fix the broken master build (result of merging concurrently 2 PRs).
=> JAMES-3693 Adapt Redis configuration change for Kvrocks tests

docs/modules/servers/pages/distributed/configure/mat-sts.adoc, docs/modules/servers/pages/postgres/configure/mat-sts.adoc, docs/modules/servers/partials/architecture/implemented-standards.adoc, docs/modules/servers/partials/configure/forExtensionsPartial.adoc, docs/modules/servers/partials/configure/mta-sts.adoc, server/protocols/protocols-smtp/src/main/java/org/apache/james/smtpserver/tls/EnforceMtaSts.java, server/protocols/protocols-smtp/src/main/java/org/apache/james/smtpserver/tls/TestMtaSts.java
(Needed for one of my customer projects and I think this can be relevant for the community as well)
That's for the inbound part that outbound part of mta-sts is obviously missing...
=> JAMES-3819 Give tools to enforce RFC-8461 MTA-STS

server/blob/blob-s3/src/test/java/org/apache/james/blob/objectstorage/aws/S3WithMinIOGenerationAwareBlobIdTest.java, server/blob/blob-storage-strategy/src/main/java/org/apache/james/server/blob/deduplication/MinIOGenerationAwareBlobId.java, server/blob/blob-storage-strategy/src/test/java/org/apache/james/server/blob/deduplication/MinIOGenerationAwareBlobIdTest.java
This PR is a duplication of https://github.com/apache/james-project/pull/2710.
The goal is to make the build run on another node than CI node 31 (I observed we had 2 consecutive timeout builds on the node 31, on the other PR).
=> Limit MinIO folder depth to 2

docs/modules/servers/partials/SanitizeMimeMessageId.adoc, docs/modules/servers/partials/configure/mailets.adoc, mailet/standard/src/main/java/org/apache/james/transport/mailets/SanitizeMimeMessageId.java, mailet/standard/src/test/java/org/apache/james/transport/mailets/SanitizeMimeMessageIdTest.java
closes https://github.com/linagora/james-project/issues/5431
=> JAMES-5431 add SanitizeMimeMessageId mailet 

server/container/guice/common/src/main/java/org/apache/james/modules/PeriodicalHealthChecksModule.java, server/container/guice/common/src/main/java/org/apache/james/modules/server/TaskSerializationModule.java, server/container/guice/common/src/main/java/org/apache/james/utils/GuiceProtocolHandlerLoader.java, server/container/guice/mailbox/src/main/java/org/apache/james/modules/mailbox/MailboxListenerFactory.java, server/container/guice/mailbox/src/main/java/org/apache/james/modules/mailbox/PreDeletionHookLoaderImpl.java, server/container/guice/mailet/src/main/java/org/apache/james/utils/GuiceMailetLoader.java, server/container/guice/mailet/src/main/java/org/apache/james/utils/GuiceMatcherLoader.java, server/container/guice/mailrepository-loaders/src/main/java/org/apache/james/modules/mailrepository/guice/GuiceMailRepositoryLoader.java, server/container/guice/opensearch/src/main/java/org/apache/james/modules/mailbox/OpenSearchMailboxConfigurationModule.java, server/container/guice/protocols/imap/src/main/java/org/apache/james/modules/protocols/ConnectionCheckFactoryImpl.java, server/container/guice/protocols/imap/src/main/java/org/apache/james/modules/protocols/IMAPServerModule.java, server/container/guice/protocols/jmap/src/main/java/org/apache/james/jmap/rfc8621/RFC8621MethodsModule.java, server/container/guice/protocols/webadmin/src/main/java/org/apache/james/modules/server/WebAdminServerModule.java, server/container/guice/utils/src/main/java/org/apache/james/utils/ExtensionModule.java, server/container/guice/utils/src/main/java/org/apache/james/utils/GuiceGenericLoader.java, server/container/guice/utils/src/main/java/org/apache/james/utils/GuiceLoader.java, server/container/guice/utils/src/main/java/org/apache/james/utils/UserStartables.java
This PR improves how the James extension mechanism works.
Fixes #1733
=> Update james extension mecanism Fixes 

docs/modules/servers/partials/configure/smtp-hooks.adoc, docs/modules/servers/partials/configure/smtp-limitation-hoot.adoc, server/protocols/protocols-smtp/src/main/java/org/apache/james/smtpserver/EnforceHeaderLimitationsMessageHook.java, server/protocols/protocols-smtp/src/test/java/org/apache/james/smtpserver/EnforcedHeaderLimitationHookIntegrationTest.java, server/protocols/protocols-smtp/src/test/resources/smtpserver-EnforceHeader.xml
=> JAMES-4132 HeaderLimitations

protocols/imap/src/main/java/org/apache/james/imap/processor/DeleteProcessor.java
```java
{"timestamp":"2025-05-30T07:02:53.647Z","level":"WARN","thread":"lettuce-epollEventLoop-4-4","logger":"org.apache.james.util.AuditTrail","message":"Exception while providing AuditTrail parameters","context":"default","exception":"java.lang.NullPointerException: Cannot invoke \"org.apache.james.imap.api.process.SelectedMailbox.getMailboxId()\" because \"selected\" is null
at org.apache.james.imap.processor.DeleteProcessor.lambda$auditTrail$11(DeleteProcessor.java:117)
at org.apache.james.util.AuditTrail$Entry.parameters(AuditTrail.java:101)
at org.apache.james.imap.processor.DeleteProcessor.auditTrail(DeleteProcessor.java:116)
at org.apache.james.imap.processor.DeleteProcessor.lambda$processRequestReactive$1(DeleteProcessor.java:75)
at …
```
=> [FIX] Fix possible NPE when audit trail in DeleteProcessor

docs/modules/servers/partials/operate/webadmin.adoc, server/protocols/webadmin/webadmin-data/src/main/java/org/apache/james/webadmin/routes/GroupsRoutes.java, server/protocols/webadmin/webadmin-data/src/main/java/org/apache/james/webadmin/routes/MappingRoutes.java, server/protocols/webadmin/webadmin-data/src/test/java/org/apache/james/webadmin/routes/GroupsRoutesTest.java, server/protocols/webadmin/webadmin-data/src/test/java/org/apache/james/webadmin/routes/MappingRoutesTest.java, src/site/markdown/server/manage-webadmin.md
Allow:
- To see all groups a user belong to
- Remove a user from all groups
- Delete all groups
=> JAMES-4316 Improve groups management

server/mailet/dkim/src/main/java/org/apache/james/jdkim/mailets/DKIMVerify.java
- Allows admin review of the DKIM verifications
- Also eases writing logic atop the DKIM validation results
Why? On a production deployment I wishes to easily audit and validate DKIM james side, and doing so is needlessly hard.
=> [ENHANCEMENT] DKIMVerify outputs logs and machine readable attributes

CHANGELOG.md
This will ease changelog work...
=> [CHANGELOG] Update as of 22/07/2025

Jenkinsfile
it is expected to fix the CI timeout
=> [INFRA-26647] use james specific develocity access key

server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EmailSubmissionSetMethodContract.scala
I was expecting this test to be failing as we observed on our side the following issue:
- send a mail with attachment
- mail moved in `Sent` mailbox does have the property `hasAttachment` set to false when doing a jmap email/get request on it
But somehow in this integration test it's true...
EDIT: likely more a problem on our side with tmail, dont mind... the test still makes sense though to have
=> Add test with attachment regarding EmailSubmission/set

pom.xml, server/blob/blob-s3/pom.xml
https://www.cve.org/CVERecord?id=CVE-2025-58056
https://www.cve.org/CVERecord?id=CVE-2025-58057
=> Netty upgrade 10 09 2025

docs/modules/servers/partials/operate/webadmin.adoc, server/protocols/webadmin/webadmin-mailbox/src/main/java/org/apache/james/webadmin/routes/MessagesRoutes.java, server/protocols/webadmin/webadmin-mailbox/src/main/java/org/apache/james/webadmin/service/ExpireMailboxService.java, server/protocols/webadmin/webadmin-mailbox/src/main/java/org/apache/james/webadmin/service/ExpireMailboxTask.java, server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/routes/MessageRoutesExpireTest.java, server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/routes/MessageRoutesTest.java, server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/service/ExpireMailboxServiceTest.java, server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/service/ExpireMailboxTaskAdditionalInformationDTOTest.java, server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/service/ExpireMailboxTaskSerializationTest.java, server/protocols/webadmin/webadmin-mailbox/src/test/resources/json/expireMailbox.additionalInformation.v2.1.json, server/protocols/webadmin/webadmin-mailbox/src/test/resources/json/expireMailbox.additionalInformation.v2.json, server/protocols/webadmin/webadmin-mailbox/src/test/resources/json/expireMailbox.age.task.v2.json, server/protocols/webadmin/webadmin-mailbox/src/test/resources/json/expireMailbox.header.task.v2.json
Refactor the class to choose between the different message listing strategies. We did also review the reactive chain to make it more readable.
=> JAMES-3758 Expiration: specific user and possibility to use saved date

mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/query/DefaultCriterionConverter.java, mailbox/opensearch/src/main/java/org/apache/james/mailbox/opensearch/search/OpenSearchSearcher.java
=> JAMES-4057 Align subject search with other implementations

docs/modules/servers/partials/SaveMailNameInHeaders .adoc, mailet/standard/src/main/java/org/apache/james/transport/mailets/SaveMailNameInHeaders.java, mailet/standard/src/test/java/org/apache/james/transport/mailets/SaveMailNameInHeadersTest.java
Could have been convenient for finding a mail based on processing logs in OpenSearch...
=> JAMES-4147 SaveMailNameInHeaders Mailet

docs/modules/servers/partials/operate/webadmin.adoc, server/container/guice/protocols/webadmin-jmap/src/main/java/org/apache/james/modules/server/JmapTaskSerializationModule.java, server/container/guice/protocols/webadmin-jmap/src/main/java/org/apache/james/modules/server/JmapTasksModule.java, server/protocols/jmap-rfc-8621/src/main/java/org/apache/james/jmap/mailet/filter/FilteringHeaders.java, server/protocols/jmap-rfc-8621/src/main/java/org/apache/james/jmap/mailet/filter/HeaderExtractor.java, server/protocols/jmap-rfc-8621/src/main/java/org/apache/james/jmap/mailet/filter/MailMatcher.java, server/protocols/jmap-rfc-8621/src/main/java/org/apache/james/jmap/mailet/filter/RuleMatcher.java, server/protocols/webadmin-integration-test/distributed-webadmin-integration-test/src/test/java/org/apache/james/webadmin/integration/rabbitmq/RabbitMQWebAdminServerTaskSerializationIntegrationTest.java, server/protocols/webadmin/webadmin-jmap/pom.xml, server/protocols/webadmin/webadmin-jmap/src/main/java/org/apache/james/webadmin/data/jmap/RunRulesOnMailboxRoutes.java, server/protocols/webadmin/webadmin-jmap/src/main/java/org/apache/james/webadmin/data/jmap/RunRulesOnMailboxService.java, server/protocols/webadmin/webadmin-jmap/src/main/java/org/apache/james/webadmin/data/jmap/RunRulesOnMailboxTask.java, server/protocols/webadmin/webadmin-jmap/src/main/java/org/apache/james/webadmin/data/jmap/RunRulesOnMailboxTaskAdditionalInformationDTO.java, server/protocols/webadmin/webadmin-jmap/src/main/java/org/apache/james/webadmin/data/jmap/RunRulesOnMailboxTaskDTO.java, server/protocols/webadmin/webadmin-jmap/src/test/java/org/apache/james/webadmin/data/jmap/RunRulesOnMailboxRoutesTest.java, server/protocols/webadmin/webadmin-jmap/src/test/java/org/apache/james/webadmin/data/jmap/RunRulesOnMailboxTaskAdditionalInformationDTOTest.java, server/protocols/webadmin/webadmin-jmap/src/test/java/org/apache/james/webadmin/data/jmap/RunRulesOnMailboxTaskSerializationTest.java, server/protocols/webadmin/webadmin-jmap/src/test/resources/json/runRulesOnMailbox.additionalInformation.json, server/protocols/webadmin/webadmin-jmap/src/test/resources/json/runRulesOnMailbox.task.json, server/protocols/webadmin/webadmin-mailbox/src/main/java/org/apache/james/webadmin/service/UserMailboxesService.java, server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/routes/UserMailboxesRoutesNoIndexationTest.java, server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/routes/UserRoutesWithMailboxParamTest.java, src/site/markdown/server/manage-webadmin.md
=> Webadmin route: Ability to run rules on folders for a specific user
